import crypto from 'node:crypto';
import { GameError } from './gameStore.mjs';

const uid = () => crypto.randomUUID();
const fail = (condition, message, status = 400, code = 'invalid_admin_action') => { if (!condition) throw new GameError(message, status, code); };
const text = (value, max = 500) => typeof value === 'string' ? value.trim().slice(0, max) : '';
export const ADMIN_ROLES = Object.freeze({
  superadmin: ['overview','residents','moderation','payments','finance','roles','settings','audit'],
  operator: ['overview','residents','payments','finance','audit'],
  moderator: ['overview','residents','moderation'],
});
const encodeCursor = value => Buffer.from(JSON.stringify(value)).toString('base64url');
function decodeCursor(value) { if (!value) return null; try { const parsed = JSON.parse(Buffer.from(value,'base64url').toString()); fail(Array.isArray(parsed) && parsed.length === 2 && parsed.every(v => typeof v === 'string' || Number.isSafeInteger(v)), 'Invalid page cursor'); return parsed; } catch { throw new GameError('Invalid page cursor'); } }
const pageLimit = value => Math.max(1, Math.min(100, Number.isSafeInteger(Number(value)) ? Number(value) : 30));

/** Administrative state shares the game SQLite transaction boundary. Initial
 * access binds an existing resident ID once, never a future username claimant. */
export class AdminStore {
  constructor({store, bootstrapUsername = process.env.ABUJALIFE_ADMIN_USERNAME || ''} = {}) {
    fail(store?.db, 'The game store is required', 500); this.store = store; this.clock = () => store.clock();
    store.db.exec(`CREATE TABLE IF NOT EXISTS admin_roles(resident_id TEXT PRIMARY KEY REFERENCES residents(id),role TEXT NOT NULL,assigned_by TEXT,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS admin_suspensions(resident_id TEXT PRIMARY KEY REFERENCES residents(id),reason TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS admin_audit(id TEXT PRIMARY KEY,actor_id TEXT NOT NULL,action TEXT NOT NULL,target_id TEXT,details TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS admin_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS admin_report_reviews(report_id TEXT PRIMARY KEY REFERENCES reports(id),status TEXT NOT NULL,note TEXT NOT NULL,actor_id TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS admin_wallet_operations(actor_id TEXT NOT NULL,operation_key TEXT NOT NULL,fingerprint TEXT NOT NULL,result TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(actor_id,operation_key));
      CREATE INDEX IF NOT EXISTS admin_audit_page ON admin_audit(created_at DESC,id DESC);
      CREATE INDEX IF NOT EXISTS reports_page ON reports(created_at DESC,id DESC);
      CREATE INDEX IF NOT EXISTS residents_username_page ON residents(username,id);`);
    if (bootstrapUsername && !store.get('SELECT resident_id FROM admin_roles LIMIT 1')) {
      const existing = store.get('SELECT id FROM residents WHERE username=?', text(bootstrapUsername,24).toLowerCase());
      if (existing) store.transaction(() => { store.run('INSERT INTO admin_roles VALUES(?,?,?,?)', existing.id, 'superadmin', null, this.clock()); this.record(existing.id,'bootstrap-admin',existing.id,{source:'server environment; existing resident ID'}); });
    }
  }
  record(actorId, action, targetId = null, details = {}) { this.store.run('INSERT INTO admin_audit VALUES(?,?,?,?,?,?)',uid(),actorId,action,targetId,JSON.stringify(details),this.clock()); }
  isSuspended(id) { return Boolean(id && this.store.get('SELECT resident_id FROM admin_suspensions WHERE resident_id=?',id)); }
  status(id) { const role = id && !this.isSuspended(id) ? this.store.get('SELECT role FROM admin_roles WHERE resident_id=?',id)?.role || null : null; return {ok:true,role,permissions:role ? [...ADMIN_ROLES[role]] : [],bootstrapConfigured:Boolean(this.store.get('SELECT resident_id FROM admin_roles LIMIT 1'))}; }
  requirePermission(id, permission) { fail(typeof id === 'string' && id, 'Sign in to your resident account',401,'authentication_required'); const status = this.status(id); fail(status.role && status.permissions.includes(permission),'This action requires administrator access',403,'admin_forbidden'); return status; }
  overview(id) { this.requirePermission(id,'overview'); const s=this.store; return {ok:true,stats:{residents:s.get('SELECT COUNT(*) total FROM residents').total,suspended:s.get('SELECT COUNT(*) total FROM admin_suspensions').total,openReports:s.get("SELECT COUNT(*) total FROM reports r LEFT JOIN admin_report_reviews v ON v.report_id=r.id WHERE v.status IS NULL OR v.status='open'").total,admins:s.get('SELECT COUNT(*) total FROM admin_roles').total},role:this.status(id).role}; }
  residents(id,{query='',cursor,limit}={}) { this.requirePermission(id,'residents'); const prefix=text(query,24).toLowerCase(); fail(!prefix || /^[a-z0-9_]+$/.test(prefix),'Search a username prefix'); const page=decodeCursor(cursor),size=pageLimit(limit),args=[]; let where='WHERE 1=1'; if(prefix){where+=' AND r.username>=? AND r.username<?';args.push(prefix,prefix+'\uffff');} if(page){where+=' AND (r.username>? OR (r.username=? AND r.id>?))';args.push(page[0],page[0],page[1]);} const rows=this.store.all(`SELECT r.id,r.username,r.profile,r.created_at,a.role,sp.reason suspension FROM residents r LEFT JOIN admin_roles a ON a.resident_id=r.id LEFT JOIN admin_suspensions sp ON sp.resident_id=r.id ${where} ORDER BY r.username,r.id LIMIT ?`,...args,size+1);const more=rows.length>size;rows.length=Math.min(rows.length,size);const items=rows.map(row=>{const p=JSON.parse(row.profile);return{id:row.id,username:row.username,displayName:p.displayName,district:p.district,wallet:p.wallet,createdAt:row.created_at,role:row.role||null,suspended:Boolean(row.suspension)};}); return {ok:true,residents:items,nextCursor:more?encodeCursor([rows.at(-1).username,rows.at(-1).id]):null}; }
  resident(id,residentId) { this.requirePermission(id,'residents'); const p=this.store.profile(residentId); return {ok:true,resident:p,role:this.store.get('SELECT role FROM admin_roles WHERE resident_id=?',residentId)?.role||null,suspension:this.store.get('SELECT reason,actor_id,created_at FROM admin_suspensions WHERE resident_id=?',residentId)||null,transactions:this.store.transactions(residentId)}; }
  protectLastSuperadmin(residentId) { const role=this.store.get('SELECT role FROM admin_roles WHERE resident_id=?',residentId)?.role; if(role==='superadmin')fail(this.store.get("SELECT COUNT(*) total FROM admin_roles a LEFT JOIN admin_suspensions s ON s.resident_id=a.resident_id WHERE a.role='superadmin' AND s.resident_id IS NULL").total>1,'Keep at least one active super administrator',409,'last_superadmin'); }
  assignRole(id,{residentId,role}) { this.requirePermission(id,'roles'); this.store.profile(residentId); fail(role===null || Object.hasOwn(ADMIN_ROLES,role),'Choose a supported administrator role'); this.store.transaction(()=>{const old=this.store.get('SELECT role FROM admin_roles WHERE resident_id=?',residentId)?.role||null;if(old==='superadmin'&&role!=='superadmin')this.protectLastSuperadmin(residentId); if(role)this.store.run('INSERT INTO admin_roles VALUES(?,?,?,?) ON CONFLICT(resident_id) DO UPDATE SET role=excluded.role,assigned_by=excluded.assigned_by,created_at=excluded.created_at',residentId,role,id,this.clock());else this.store.run('DELETE FROM admin_roles WHERE resident_id=?',residentId);this.record(id,'assign-role',residentId,{before:old,after:role});});return{ok:true,role}; }
  setSuspension(id,{residentId,suspended,reason}) { this.requirePermission(id,'moderation'); this.store.profile(residentId);if(this.store.get('SELECT role FROM admin_roles WHERE resident_id=?',residentId))fail(this.status(id).role==='superadmin','Only a super administrator may suspend an administrator',403,'admin_forbidden'); fail(typeof suspended==='boolean','Choose a suspension state'); reason=text(reason);fail(reason.length>=8,'Explain this moderation decision in at least eight characters');this.store.transaction(()=>{if(suspended){this.protectLastSuperadmin(residentId);this.store.run('INSERT INTO admin_suspensions VALUES(?,?,?,?) ON CONFLICT(resident_id) DO UPDATE SET reason=excluded.reason,actor_id=excluded.actor_id,created_at=excluded.created_at',residentId,reason,id,this.clock());this.store.run('DELETE FROM sessions WHERE resident_id=?',residentId);}else this.store.run('DELETE FROM admin_suspensions WHERE resident_id=?',residentId);this.record(id,suspended?'suspend-resident':'restore-resident',residentId,{reason});});this.store.emitUser(residentId,'suspension',{suspended});return{ok:true,suspended}; }
  adjustWallet(id,{residentId,amount,reason,idempotencyKey}) { this.requirePermission(id,'finance');fail(Number.isSafeInteger(amount)&&amount!==0,'Enter a nonzero whole Naira adjustment');reason=text(reason,160);fail(reason.length>=8,'Explain this wallet adjustment in at least eight characters');fail(typeof idempotencyKey==='string'&&/^[A-Za-z0-9_-]{8,100}$/.test(idempotencyKey),'Use a valid request key');const fingerprint=JSON.stringify({residentId,amount,reason});let replayed=false;const result=this.store.transaction(()=>{const old=this.store.get('SELECT * FROM admin_wallet_operations WHERE actor_id=? AND operation_key=?',id,idempotencyKey);if(old){fail(old.fingerprint===fingerprint,'Request key was already used for another adjustment',409,'idempotency_conflict');replayed=true;return{...JSON.parse(old.result),profile:this.store.profile(residentId)};}const p=this.store.profile(residentId),before=p.wallet;fail(Number.isSafeInteger(before+amount)&&before+amount>=0,'The resulting balance must be a safe, nonnegative Naira amount',409,'wallet_limit');p.wallet+=amount;this.store.save(p);this.store.appendLedger(residentId,amount,`Administrator adjustment · ${reason}`,this.clock(),`admin:${id}:${idempotencyKey}`,'ADMIN_ADJUSTMENT',p.wallet);this.record(id,'adjust-wallet',residentId,{amount,reason,before,after:p.wallet});const value={ok:true,profile:p,amount};this.store.run('INSERT INTO admin_wallet_operations VALUES(?,?,?,?,?)',id,idempotencyKey,fingerprint,JSON.stringify(value),this.clock());return value;});if(!replayed)this.store.emitUser(residentId,'profile',{profile:result.profile});return{...result,replayed}; }
  reports(id,{cursor,limit}={}) { this.requirePermission(id,'moderation');const page=decodeCursor(cursor),size=pageLimit(limit),args=page?[page[0],page[0],page[1]]:[];const rows=this.store.all(`SELECT r.*,v.status,v.note review_note FROM reports r LEFT JOIN admin_report_reviews v ON v.report_id=r.id ${page?'WHERE r.created_at<? OR (r.created_at=? AND r.id<?)':''} ORDER BY r.created_at DESC,r.id DESC LIMIT ?`,...args,size+1);const more=rows.length>size;rows.length=Math.min(rows.length,size);return{ok:true,reports:rows.map(row=>({...row,status:row.status||'open'})),nextCursor:more?encodeCursor([rows.at(-1).created_at,rows.at(-1).id]):null}; }
  reviewReport(id,{reportId,status,note}) { this.requirePermission(id,'moderation');fail(this.store.get('SELECT id FROM reports WHERE id=?',reportId),'Report not found',404);fail(['open','resolved','dismissed'].includes(status),'Choose a report status');note=text(note);fail(note.length>=8,'Explain the report decision');this.store.transaction(()=>{this.store.run('INSERT INTO admin_report_reviews VALUES(?,?,?,?,?) ON CONFLICT(report_id) DO UPDATE SET status=excluded.status,note=excluded.note,actor_id=excluded.actor_id,created_at=excluded.created_at',reportId,status,note,id,this.clock());this.record(id,'review-report',reportId,{status,note});});return{ok:true,status}; }
  audit(id,{cursor,limit}={}) { this.requirePermission(id,'audit');const page=decodeCursor(cursor),size=pageLimit(limit),args=page?[page[0],page[0],page[1]]:[];const rows=this.store.all(`SELECT * FROM admin_audit ${page?'WHERE created_at<? OR (created_at=? AND id<?)':''} ORDER BY created_at DESC,id DESC LIMIT ?`,...args,size+1);const more=rows.length>size;rows.length=Math.min(rows.length,size);return{ok:true,audit:rows.map(row=>({...row,details:JSON.parse(row.details)})),nextCursor:more?encodeCursor([rows.at(-1).created_at,rows.at(-1).id]):null}; }
  publicSettings() { const row=this.store.get("SELECT value FROM admin_settings WHERE key='game'");return{registrationOpen:true,gameTopupsEnabled:false,maintenance:false,...(row?JSON.parse(row.value):{})}; }
  settings(id) { this.requirePermission(id,'settings');return{ok:true,settings:this.publicSettings()}; }
  saveSettings(id,body) { this.requirePermission(id,'settings');const allowed=['registrationOpen','gameTopupsEnabled','maintenance'];fail(Object.keys(body).every(key=>allowed.includes(key)),'Choose supported game settings');for(const value of Object.values(body))fail(typeof value==='boolean','Use boolean game settings');const settings={...this.publicSettings(),...body};this.store.transaction(()=>{this.store.run("INSERT INTO admin_settings VALUES('game',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at",JSON.stringify(settings),this.clock());this.record(id,'update-game-settings',null,settings);});return{ok:true,settings}; }
}
