import crypto from 'node:crypto';
import { GameError } from './errors.mjs';
import { CIVIC_META,CIVIC_PARTIES,CIVIC_CAMPAIGN_ACTIONS,CIVIC_GOVERNMENT_ACTIONS,CIVIC_STORY_THRESHOLDS,civicCycle,civicParty,civicAction,civicGovernmentAction } from '../shared/civic-life.mjs';

const TOKEN_COOKIE='abujalife_session=';
const HEADERS={'x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','cache-control':'no-store'};
const clean=(v,n=280)=>String(v??'').trim().slice(0,n);
const fail=(ok,message,status=400,code='invalid_civic_action')=>{if(!ok)throw new GameError(message,status,code);};
const keyOK=v=>typeof v==='string'&&/^[A-Za-z0-9_-]{8,100}$/.test(v);
const tokenFor=req=>/^Bearer ([A-Za-z0-9_-]{32,200})$/.exec(req.headers.authorization||'')?.[1]||(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(TOKEN_COOKIE))?.slice(TOKEN_COOKIE.length)||null;
const json=(res,status,body,extra={})=>{if(!res.writableEnded){res.writeHead(status,{'content-type':'application/json; charset=utf-8',...HEADERS,...extra});res.end(JSON.stringify(body));}};
async function readJSON(req){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;fail(size<=65536,'Request body is too large',413,'body_too_large');chunks.push(chunk);}try{const value=JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}');fail(value&&typeof value==='object'&&!Array.isArray(value),'Send a JSON object');return value;}catch(error){if(error instanceof GameError)throw error;throw new GameError('Send valid JSON');}}
const candidateView=r=>r?{residentId:r.residentId,displayName:r.displayName,username:r.username,partyId:r.partyId,manifesto:r.manifesto,support:Number(r.support||0),heat:Number(r.heat||0),status:r.status||'active',enforcement:r.enforcement||'none',votes:Number(r.votes||0),createdAt:Number(r.createdAt||0),updatedAt:Number(r.updatedAt||0)}:null;
const governmentView=r=>r?{cycleId:r.cycleId,winnerId:r.winnerId||null,winnerName:r.winnerName||null,partyId:r.partyId||null,budget:Number(r.budget||0),integrity:Number(r.integrity??100),heat:Number(r.heat||0),electedAt:Number(r.electedAt||0),activeStory:r.activeStory||null,activeStoryEndsAt:Number(r.activeStoryEndsAt||0)}:null;

export class CivicIntegrationV2{
  constructor({store,admin,publicWebUrl,corsOrigins=[],log=()=>{}}={}){fail(store?.db&&typeof store.profile==='function','Civic runtime requires the game store',500,'civic_configuration');this.store=store;this.db=store.db;this.admin=admin;this.mongo=typeof store.collection==='function';this.allowedOrigins=new Set([publicWebUrl,...corsOrigins].filter(Boolean));this.log=log;this.limits=new Map();}
  c(name){return this.store.collection(name);}
  now(){return Number(this.store.clock?.()??Date.now());}
  async init(){if(this.mongo){await Promise.all([this.c('civic_candidates').createIndex({cycleId:1,residentId:1},{unique:true}),this.c('civic_candidates').createIndex({cycleId:1,status:1,support:-1}),this.c('civic_votes').createIndex({cycleId:1,voterId:1},{unique:true}),this.c('civic_votes').createIndex({cycleId:1,candidateId:1}),this.c('civic_events').createIndex({cycleId:1,createdAt:-1}),this.c('civic_governments').createIndex({cycleId:1},{unique:true}),this.c('civic_actions').createIndex({cycleId:1,residentId:1,operationKey:1},{unique:true})]);}else this.db.exec(`CREATE TABLE IF NOT EXISTS civic_candidates(cycle_id TEXT NOT NULL,resident_id TEXT NOT NULL,display_name TEXT NOT NULL,username TEXT NOT NULL,party_id TEXT NOT NULL,manifesto TEXT NOT NULL,support INTEGER NOT NULL DEFAULT 0,heat INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',enforcement TEXT NOT NULL DEFAULT 'none',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,resident_id));CREATE TABLE IF NOT EXISTS civic_votes(cycle_id TEXT NOT NULL,voter_id TEXT NOT NULL,candidate_id TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,voter_id));CREATE INDEX IF NOT EXISTS civic_votes_candidate ON civic_votes(cycle_id,candidate_id);CREATE TABLE IF NOT EXISTS civic_events(id TEXT PRIMARY KEY,cycle_id TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,actor_id TEXT,district TEXT,created_at INTEGER NOT NULL,expires_at INTEGER);CREATE INDEX IF NOT EXISTS civic_events_cycle ON civic_events(cycle_id,created_at DESC);CREATE TABLE IF NOT EXISTS civic_governments(cycle_id TEXT PRIMARY KEY,winner_id TEXT,winner_name TEXT,party_id TEXT,budget INTEGER NOT NULL,integrity INTEGER NOT NULL,heat INTEGER NOT NULL,elected_at INTEGER NOT NULL,active_story TEXT,active_story_ends_at INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS civic_actions(cycle_id TEXT NOT NULL,resident_id TEXT NOT NULL,operation_key TEXT NOT NULL,kind TEXT NOT NULL,result TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,resident_id,operation_key));`);return this;}
  cors(req,res){const origin=req.headers.origin;if(!origin)return;fail(this.allowedOrigins.has(origin),'This origin is not permitted',403,'cross_origin');res.setHeader('access-control-allow-origin',origin);res.setHeader('access-control-allow-credentials','true');res.setHeader('vary','Origin');}
  rate(id,path,limit){const now=Date.now(),k=`${id}:${path}`,prev=this.limits.get(k),b=prev&&now-prev.at<60000?prev:{at:now,count:0};b.count++;this.limits.set(k,b);fail(b.count<=limit,'Please wait before trying again',429,'rate_limited');}
  actionOrigin(req){fail(/^application\/json(?:\s*;|$)/i.test(req.headers['content-type']||''),'Send JSON for this action',415);if(req.headers['sec-fetch-site']==='cross-site'||(req.headers.cookie&&!req.headers.authorization))fail(!req.headers.origin||this.allowedOrigins.has(req.headers.origin),'Open AbujaLife to perform this action',403,'cross_origin');}
  async resident(req){const token=tokenFor(req),id=token?await this.store.session(token):null;fail(id,'Sign in to use AbujaLife civic life',401,'authentication_required');if(this.admin?.isSuspended)fail(!await this.admin.isSuspended(id),'This account is suspended',403,'account_suspended');return id;}
  async profile(id,session){return this.mongo?this.store.profile(id,{session}):this.store.profile(id);}
  venue(profile,id){return profile?.location?.kind==='venue'&&(profile.location.venue===id||profile.location.venueId===id);}
  polling(profile){return !profile?.activeTrip&&profile?.location?.kind==='public'&&profile?.district===profile?.home?.district;}
  sqlCandidate(r){return r?{cycleId:r.cycle_id,residentId:r.resident_id,displayName:r.display_name,username:r.username,partyId:r.party_id,manifesto:r.manifesto,support:r.support,heat:r.heat,status:r.status,enforcement:r.enforcement,createdAt:r.created_at,updatedAt:r.updated_at}:null;}
  sqlGovernment(r){return r?{cycleId:r.cycle_id,winnerId:r.winner_id,winnerName:r.winner_name,partyId:r.party_id,budget:r.budget,integrity:r.integrity,heat:r.heat,electedAt:r.elected_at,activeStory:r.active_story,activeStoryEndsAt:r.active_story_ends_at}:null;}
  async candidate(cycleId,residentId,session){return this.mongo?this.c('civic_candidates').findOne({cycleId,residentId},session?{session}:{}):this.sqlCandidate(this.store.get('SELECT * FROM civic_candidates WHERE cycle_id=? AND resident_id=?',cycleId,residentId));}
  async voted(cycleId,voterId,session){return this.mongo?(await this.c('civic_votes').findOne({cycleId,voterId},session?{session}:{}))?.candidateId||null:this.store.get('SELECT candidate_id FROM civic_votes WHERE cycle_id=? AND voter_id=?',cycleId,voterId)?.candidate_id||null;}
  async counts(cycleId,session){if(this.mongo){const rows=await this.c('civic_votes').aggregate([{$match:{cycleId}},{$group:{_id:'$candidateId',votes:{$sum:1}}}],session?{session}:{}).toArray();return new Map(rows.map(r=>[r._id,r.votes]));}return new Map(this.store.all('SELECT candidate_id,count(*) votes FROM civic_votes WHERE cycle_id=? GROUP BY candidate_id',cycleId).map(r=>[r.candidate_id,Number(r.votes)]));}
  async candidates(cycleId,session){const counts=await this.counts(cycleId,session);let rows=this.mongo?await this.c('civic_candidates').find({cycleId},session?{session}:{}).sort({support:-1,createdAt:1}).limit(200).toArray():this.store.all('SELECT * FROM civic_candidates WHERE cycle_id=? ORDER BY support DESC,created_at ASC LIMIT 200',cycleId).map(r=>this.sqlCandidate(r));return rows.map(r=>candidateView({...r,votes:counts.get(r.residentId)||0})).sort((a,b)=>b.votes-a.votes||b.support-a.support||a.createdAt-b.createdAt);}
  async story(cycleId,{id=crypto.randomUUID(),kind='story',title,body,actorId=null,district=null,createdAt=this.now(),expiresAt=null},session){const row={id,cycleId,kind,title:clean(title,100),body:clean(body,360),actorId,district,createdAt,expiresAt};if(this.mongo)await this.c('civic_events').updateOne({_id:id},{$setOnInsert:{_id:id,...row}},{upsert:true,...(session?{session}:{})});else this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',id,cycleId,kind,row.title,row.body,actorId,district,createdAt,expiresAt);return row;}
  async stories(cycleId){return this.mongo?(await this.c('civic_events').find({cycleId}).sort({createdAt:-1}).limit(30).toArray()).map(({_id,...r})=>r):this.store.all('SELECT * FROM civic_events WHERE cycle_id=? ORDER BY created_at DESC LIMIT 30',cycleId).map(r=>({id:r.id,cycleId:r.cycle_id,kind:r.kind,title:r.title,body:r.body,actorId:r.actor_id,district:r.district,createdAt:r.created_at,expiresAt:r.expires_at}));}
  async government(cycleId,session){return this.mongo?this.c('civic_governments').findOne({cycleId},session?{session}:{}):this.sqlGovernment(this.store.get('SELECT * FROM civic_governments WHERE cycle_id=?',cycleId));}
  async ensureGovernment(cycle){if(cycle.phase.id!=='results')return this.government(cycle.id);const prior=await this.government(cycle.id);if(prior)return prior;const list=(await this.candidates(cycle.id)).filter(c=>!['detained','disqualified'].includes(c.status)),winner=list[0]||null,now=this.now();const row={cycleId:cycle.id,winnerId:winner?.residentId||null,winnerName:winner?.displayName||null,partyId:winner?.partyId||null,budget:CIVIC_META.governmentBudget,integrity:100,heat:0,electedAt:now,activeStory:null,activeStoryEndsAt:0};if(this.mongo){try{await this.c('civic_governments').insertOne({_id:cycle.id,...row});}catch(error){if(error.code!==11000)throw error;}}else this.store.run('INSERT OR IGNORE INTO civic_governments VALUES(?,?,?,?,?,?,?,?,?,?)',cycle.id,row.winnerId,row.winnerName,row.partyId,row.budget,100,0,now,null,0);await this.story(cycle.id,{id:`result:${cycle.id}`,kind:'result',title:winner?`${winner.displayName} wins the AbujaLife presidency`:'No presidential result this cycle',body:winner?`${winner.votes.toLocaleString()} vote${winner.votes===1?'':'s'} · ${civicParty(winner.partyId)?.short||winner.partyId}. The fictional city administration is active.`:'No eligible fictional candidate remained on the ballot.',actorId:winner?.residentId||null,createdAt:now});return this.government(cycle.id);}
  enforcement(heat){if(heat>=CIVIC_STORY_THRESHOLDS.disqualify)return{status:'disqualified',enforcement:'court-disqualification'};if(heat>=CIVIC_STORY_THRESHOLDS.detention)return{status:'detained',enforcement:'detained-pending-hearing'};if(heat>=CIVIC_STORY_THRESHOLDS.raid)return{status:'under-review',enforcement:'efcc-raid'};if(heat>=CIVIC_STORY_THRESHOLDS.review)return{status:'under-review',enforcement:'efcc-review'};return{status:'active',enforcement:'none'};}
  async state(id){const cycle=civicCycle(this.now());await this.ensureGovernment(cycle);const p=await this.profile(id),candidate=await this.candidate(cycle.id,id),government=await this.government(cycle.id),votedFor=await this.voted(cycle.id,id);return{ok:true,meta:CIVIC_META,parties:CIVIC_PARTIES,cycle,candidate:candidateView(candidate),candidates:await this.candidates(cycle.id),government:governmentView(government),events:await this.stories(cycle.id),votedFor,resident:{reputation:Number(p.reputation||0),wallet:Number(p.wallet||0),district:p.district,homeDistrict:p.home?.district||null,location:p.location,atInec:this.venue(p,'inec-hq'),atEfcc:this.venue(p,'efcc-hq'),atCourt:this.venue(p,'federal-high-court-hub'),atHomePoll:this.polling(p),isPresident:government?.winnerId===id},campaignActions:CIVIC_CAMPAIGN_ACTIONS,governmentActions:CIVIC_GOVERNMENT_ACTIONS,eligibility:{nominationOpen:cycle.nominationOpen&&!candidate,reputationReady:Number(p.reputation||0)>=CIVIC_META.nominationReputation,fundsReady:Number(p.wallet||0)>=CIVIC_META.nominationFee,atInec:this.venue(p,'inec-hq'),canVote:cycle.phase.id==='voting'&&!votedFor&&this.polling(p)}};}
  async nominate(id,body){const cycle=civicCycle(this.now()),party=civicParty(clean(body.partyId,40)),manifesto=clean(body.manifesto,260);fail(cycle.nominationOpen,'Candidate nominations are closed for this cycle',409,'nominations_closed');fail(party,'Choose a fictional AbujaLife party');fail(manifesto.length>=20,'Write a manifesto of at least 20 characters');fail(keyOK(body.idempotencyKey),'Use a valid nomination request key',400,'idempotency_required');fail(!await this.candidate(cycle.id,id),'You are already a candidate this cycle',409,'already_candidate');const normalized={cycleId:cycle.id,partyId:party.id,manifesto};
    if(this.mongo){const result=await this.store.economyOperation(id,'civic-nomination',body,normalized,async(p,timestamp,session)=>{fail(this.venue(p,'inec-hq'),'Visit the fictional INEC HQ experience before buying a nomination ticket',409,'wrong_venue');fail(Number(p.reputation||0)>=CIVIC_META.nominationReputation,`Build at least ${CIVIC_META.nominationReputation} reputation before running`,409,'reputation_required');fail(p.wallet>=CIVIC_META.nominationFee,'You need more Game Naira for the nomination ticket',409,'insufficient_balance');p.wallet-=CIVIC_META.nominationFee;const row={cycleId:cycle.id,residentId:id,displayName:p.displayName,username:p.username,partyId:party.id,manifesto,support:0,heat:0,status:'active',enforcement:'none',createdAt:timestamp,updatedAt:timestamp};await this.c('civic_candidates').insertOne({_id:`${cycle.id}:${id}`,...row},{session});await this.story(cycle.id,{kind:'nomination',title:`${p.displayName} enters the presidential race`,body:`${party.short} · ${manifesto}`,actorId:id,createdAt:timestamp},session);return{candidate:candidateView(row),ledgerReason:'AbujaLife presidential nomination ticket'};});return{...result,civic:await this.state(id)};}
    const result=this.store.economyOperation(id,'civic-nomination',body,normalized,(p,timestamp)=>{fail(this.venue(p,'inec-hq'),'Visit the fictional INEC HQ experience before buying a nomination ticket',409,'wrong_venue');fail(Number(p.reputation||0)>=CIVIC_META.nominationReputation,`Build at least ${CIVIC_META.nominationReputation} reputation before running`,409,'reputation_required');fail(p.wallet>=CIVIC_META.nominationFee,'You need more Game Naira for the nomination ticket',409,'insufficient_balance');p.wallet-=CIVIC_META.nominationFee;const row={cycleId:cycle.id,residentId:id,displayName:p.displayName,username:p.username,partyId:party.id,manifesto,support:0,heat:0,status:'active',enforcement:'none',createdAt:timestamp,updatedAt:timestamp};this.store.run('INSERT INTO civic_candidates VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',cycle.id,id,p.displayName,p.username,party.id,manifesto,0,0,'active','none',timestamp,timestamp);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'nomination',`${p.displayName} enters the presidential race`,`${party.short} · ${manifesto}`,id,null,timestamp,null);return{candidate:candidateView(row),ledgerReason:'AbujaLife presidential nomination ticket'};});return{...result,civic:await this.state(id)};}
  async campaign(id,body){const cycle=civicCycle(this.now()),action=civicAction(clean(body.actionId,60)),existing=await this.candidate(cycle.id,id);fail(['nominations','campaign','debates'].includes(cycle.phase.id),'Campaign activities are closed right now',409,'campaign_closed');fail(action,'Choose a listed campaign activity');fail(!action.phase||action.phase===cycle.phase.id,`${action.name} is not available in this phase`,409,'wrong_phase');fail(existing,'Enter the presidential race first',409,'not_candidate');fail(existing.status!=='disqualified','This candidate is no longer on the ballot',409,'candidate_disqualified');fail(keyOK(body.idempotencyKey),'Use a valid campaign request key',400,'idempotency_required');const normalized={cycleId:cycle.id,actionId:action.id};
    const change=(p,timestamp)=>{fail(!action.venueId||this.venue(p,action.venueId),`Go to ${action.venueId.replace(/-/g,' ')} before this activity`,409,'wrong_venue');fail(!action.requiresPublic||p.location?.kind==='public','Head outside before canvassing residents',409,'wrong_location');fail(!action.requiresCase||existing.enforcement!=='none','There is no active case requiring a hearing',409,'no_active_case');if(action.cost){fail(p.wallet>=action.cost,'You need more Game Naira for this campaign activity',409,'insufficient_balance');p.wallet-=action.cost;}const support=Math.max(0,Number(existing.support||0)+Number(action.score||0)),heat=Math.max(0,Number(existing.heat||0)+Number(action.heat||0)),e=this.enforcement(heat);return{row:{...existing,support,heat,status:e.status,enforcement:e.enforcement,updatedAt:timestamp},ledgerReason:action.cost?`Campaign activity · ${action.name}`:undefined};};
    if(this.mongo){const result=await this.store.economyOperation(id,'civic-campaign',body,normalized,async(p,timestamp,session)=>{const{row,ledgerReason}=change(p,timestamp);await this.c('civic_candidates').updateOne({cycleId:cycle.id,residentId:id},{$set:{support:row.support,heat:row.heat,status:row.status,enforcement:row.enforcement,updatedAt:timestamp}},{session});await this.story(cycle.id,{kind:'campaign',title:`${p.displayName}: ${action.name}`,body:action.description,actorId:id,district:p.district,createdAt:timestamp},session);if(row.enforcement!==existing.enforcement)await this.investigationStory(cycle.id,p,row,timestamp,session);return{candidate:candidateView(row),activity:action,ledgerReason};});return{...result,civic:await this.state(id)};}
    const result=this.store.economyOperation(id,'civic-campaign',body,normalized,(p,timestamp)=>{const{row,ledgerReason}=change(p,timestamp);this.store.run('UPDATE civic_candidates SET support=?,heat=?,status=?,enforcement=?,updated_at=? WHERE cycle_id=? AND resident_id=?',row.support,row.heat,row.status,row.enforcement,timestamp,cycle.id,id);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'campaign',`${p.displayName}: ${action.name}`,action.description,id,p.district,timestamp,null);if(row.enforcement!==existing.enforcement)this.investigationStorySql(cycle.id,p,row,timestamp);return{candidate:candidateView(row),activity:action,ledgerReason};});return{...result,civic:await this.state(id)};}
  async investigationStory(cycleId,p,row,timestamp,session){const title=row.enforcement==='efcc-raid'?`EFCC storyline raid opened for ${p.displayName}`:row.enforcement==='detained-pending-hearing'?`${p.displayName} detained pending fictional court hearing`:row.status==='disqualified'?`${p.displayName} removed from the fictional ballot`:`Financial scrutiny opened for ${p.displayName}`;return this.story(cycleId,{kind:'investigation',title,body:'Fictional integrity storyline involving fictional candidates only. No real-world allegation is made.',actorId:p.id,district:p.district,createdAt:timestamp},session);}
  investigationStorySql(cycleId,p,row,timestamp){const title=row.enforcement==='efcc-raid'?`EFCC storyline raid opened for ${p.displayName}`:row.enforcement==='detained-pending-hearing'?`${p.displayName} detained pending fictional court hearing`:row.status==='disqualified'?`${p.displayName} removed from the fictional ballot`:`Financial scrutiny opened for ${p.displayName}`;this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycleId,'investigation',title,'Fictional integrity storyline involving fictional candidates only. No real-world allegation is made.',p.id,p.district,timestamp,null);}
  async vote(id,body){const cycle=civicCycle(this.now()),candidateId=clean(body.candidateId,80),candidate=await this.candidate(cycle.id,candidateId);fail(cycle.phase.id==='voting','Voting is not open right now',409,'voting_closed');fail(candidate&&!['detained','disqualified'].includes(candidate.status),'Choose an eligible candidate');const p=await this.profile(id);fail(this.polling(p),'Return to your home district and head outside to vote',409,'polling_location_required');fail(!await this.voted(cycle.id,id),'You have already voted this cycle',409,'already_voted');const now=this.now();if(this.mongo)await this.c('civic_votes').insertOne({_id:`${cycle.id}:${id}`,cycleId:cycle.id,voterId:id,candidateId,createdAt:now});else this.store.run('INSERT INTO civic_votes VALUES(?,?,?,?)',cycle.id,id,candidateId,now);return{ok:true,receipt:{cycleId:cycle.id,candidateId,castAt:now},civic:await this.state(id)};}
  async governmentAction(id,body){const cycle=civicCycle(this.now()),action=civicGovernmentAction(clean(body.actionId,60));fail(cycle.phase.id==='results','The new administration is not active yet',409,'government_inactive');fail(action,'Choose a listed city decision');fail(keyOK(body.idempotencyKey),'Use a valid city-action request key',400,'idempotency_required');const gov=await this.ensureGovernment(cycle);fail(gov?.winnerId===id,'Only the elected AbujaLife President can make this decision',403,'not_president');const p=await this.profile(id);fail(this.venue(p,action.venueId),`Go to ${action.venueId.replace(/-/g,' ')} to announce this decision`,409,'wrong_venue');const now=this.now(),endsAt=now+action.durationHours*3600000;
    const make=(current)=>{fail(current.budget>=action.cost,'The city budget is too low for this decision',409,'city_budget_low');const budget=current.budget-action.cost,integrity=Math.max(0,Math.min(100,current.integrity+Number(action.integrity||0))),heat=Math.max(0,Number(current.heat||0)+Number(action.heat||0));return{actionId:action.id,title:action.name,startedAt:now,endsAt,budget,integrity,heat};};
    if(this.mongo){const result=await this.store.transaction(async session=>{const prior=await this.c('civic_actions').findOne({cycleId:cycle.id,residentId:id,operationKey:body.idempotencyKey},{session});if(prior)return prior.result;const current=await this.c('civic_governments').findOne({cycleId:cycle.id},{session});fail(current?.winnerId===id,'Administration changed; refresh',409,'government_changed');const out=make(current);await this.c('civic_governments').updateOne({cycleId:cycle.id,winnerId:id},{$set:{budget:out.budget,integrity:out.integrity,heat:out.heat,activeStory:action.name,activeStoryEndsAt:endsAt}},{session});await this.c('civic_actions').insertOne({_id:`${cycle.id}:${id}:${body.idempotencyKey}`,cycleId:cycle.id,residentId:id,operationKey:body.idempotencyKey,kind:action.id,result:out,createdAt:now},{session});await this.story(cycle.id,{kind:'government',title:action.name,body:action.description,actorId:id,district:p.district,createdAt:now,expiresAt:endsAt},session);if(out.heat>=CIVIC_STORY_THRESHOLDS.review&&action.heat)await this.story(cycle.id,{kind:'investigation',title:'EFCC storyline opens a presidential integrity review',body:'A fictional anti-corruption storyline has opened around the unreviewed city decision. No real person or allegation is represented.',actorId:id,district:p.district,createdAt:now},session);return out;});return{ok:true,result,civic:await this.state(id)};}
    let result;this.store.transaction(()=>{const prior=this.store.get('SELECT result FROM civic_actions WHERE cycle_id=? AND resident_id=? AND operation_key=?',cycle.id,id,body.idempotencyKey);if(prior){result=JSON.parse(prior.result);return;}const current=this.sqlGovernment(this.store.get('SELECT * FROM civic_governments WHERE cycle_id=?',cycle.id));fail(current?.winnerId===id,'Administration changed; refresh',409,'government_changed');result=make(current);this.store.run('UPDATE civic_governments SET budget=?,integrity=?,heat=?,active_story=?,active_story_ends_at=? WHERE cycle_id=?',result.budget,result.integrity,result.heat,action.name,endsAt,cycle.id);this.store.run('INSERT INTO civic_actions VALUES(?,?,?,?,?,?)',cycle.id,id,body.idempotencyKey,action.id,JSON.stringify(result),now);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'government',action.name,action.description,id,p.district,now,endsAt);if(result.heat>=CIVIC_STORY_THRESHOLDS.review&&action.heat)this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'investigation','EFCC storyline opens a presidential integrity review','A fictional anti-corruption storyline has opened around the unreviewed city decision. No real person or allegation is represented.',id,p.district,now,null);});return{ok:true,result,civic:await this.state(id)};}
  async handle(req,res){try{this.cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization',...HEADERS});res.end();return;}const id=await this.resident(req),url=new URL(req.url,'https://api.abujacity.life'),path=url.pathname;this.rate(id,path,req.method==='GET'?120:35);if(path==='/api/civic/state'&&req.method==='GET')return json(res,200,await this.state(id));if(path==='/api/civic/candidates'&&req.method==='GET'){const cycle=civicCycle(this.now());return json(res,200,{ok:true,cycle,candidates:await this.candidates(cycle.id)});}if(req.method==='POST')this.actionOrigin(req);const body=req.method==='POST'?await readJSON(req):{};if(path==='/api/civic/nominate'&&req.method==='POST')return json(res,200,await this.nominate(id,body));if(path==='/api/civic/campaign'&&req.method==='POST')return json(res,200,await this.campaign(id,body));if(path==='/api/civic/vote'&&req.method==='POST')return json(res,200,await this.vote(id,body));if(path==='/api/civic/government/action'&&req.method==='POST')return json(res,200,await this.governmentAction(id,body));return json(res,404,{ok:false,error:'Not found',code:'not_found'});}catch(error){const status=error instanceof GameError?error.status:500;this.log('civic_request_error',{status,code:error instanceof GameError?error.code:'internal_error'});return json(res,status,{ok:false,error:error instanceof GameError?error.message:'Something went wrong. Please try again.',code:error instanceof GameError?error.code:'server_error'});}}
}
