import crypto from 'node:crypto';
import { GameError } from './errors.mjs';
import { CIVIC_META,CIVIC_PARTIES,CIVIC_CAMPAIGN_ACTIONS,CIVIC_GOVERNMENT_ACTIONS,CIVIC_STORY_THRESHOLDS,civicCycle,civicParty,civicAction,civicGovernmentAction } from '../shared/civic-life.mjs';

const SECURITY_HEADERS=Object.freeze({'x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','cache-control':'no-store'});
const TOKEN_COOKIE='abujalife_session=';
const clean=(value,max=240)=>String(value??'').trim().slice(0,max);
const fail=(condition,message,status=400,code='invalid_civic_action')=>{if(!condition)throw new GameError(message,status,code);};
const keyOK=value=>typeof value==='string'&&/^[A-Za-z0-9_-]{8,100}$/.test(value);
const publicCandidate=row=>row?{residentId:row.residentId,displayName:row.displayName,username:row.username,partyId:row.partyId,manifesto:row.manifesto,support:Number(row.support||0),heat:Number(row.heat||0),status:row.status||'active',enforcement:row.enforcement||'none',createdAt:Number(row.createdAt||0),updatedAt:Number(row.updatedAt||0),votes:Number(row.votes||0)}:null;
const publicGovernment=row=>row?{cycleId:row.cycleId,winnerId:row.winnerId||null,winnerName:row.winnerName||null,partyId:row.partyId||null,budget:Number(row.budget||0),integrity:Number(row.integrity??100),heat:Number(row.heat||0),electedAt:Number(row.electedAt||0),activeStory:row.activeStory||null,activeStoryEndsAt:Number(row.activeStoryEndsAt||0)}:null;

function tokenFor(req){const bearer=/^Bearer ([A-Za-z0-9_-]{32,200})$/.exec(req.headers.authorization||'');if(bearer)return bearer[1];return(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(TOKEN_COOKIE))?.slice(TOKEN_COOKIE.length)||null;}
function json(res,status,body,extra={}){if(res.writableEnded)return;res.writeHead(status,{'content-type':'application/json; charset=utf-8',...SECURITY_HEADERS,...extra});res.end(JSON.stringify(body));}
async function rawBody(req,maxBytes=65536){let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;fail(size<=maxBytes,'Request body is too large',413,'body_too_large');chunks.push(chunk);}return Buffer.concat(chunks);}
async function readJSON(req){try{const body=JSON.parse((await rawBody(req)).toString('utf8')||'{}');fail(body&&typeof body==='object'&&!Array.isArray(body),'Send a JSON object');return body;}catch(error){if(error instanceof GameError)throw error;throw new GameError('Send valid JSON');}}

export class CivicIntegration{
  constructor({store,admin,publicWebUrl,corsOrigins=[],log=()=>{}}={}){
    fail(store&&store.db&&typeof store.profile==='function','Civic runtime requires the AbujaLife game store',500,'civic_configuration');
    this.store=store;this.db=store.db;this.admin=admin;this.log=log;this.mongo=typeof store.collection==='function';this.allowedOrigins=new Set([publicWebUrl,...corsOrigins].filter(Boolean));this.limits=new Map();
  }
  collection(name){return this.store.collection(name);}
  now(){return Number(this.store.clock?.()??Date.now());}
  async init(){
    if(this.mongo){
      await Promise.all([
        this.collection('civic_candidates').createIndex({cycleId:1,residentId:1},{unique:true}),
        this.collection('civic_candidates').createIndex({cycleId:1,status:1,support:-1,createdAt:1}),
        this.collection('civic_votes').createIndex({cycleId:1,voterId:1},{unique:true}),
        this.collection('civic_votes').createIndex({cycleId:1,candidateId:1}),
        this.collection('civic_events').createIndex({cycleId:1,createdAt:-1}),
        this.collection('civic_governments').createIndex({cycleId:1},{unique:true}),
        this.collection('civic_actions').createIndex({cycleId:1,residentId:1,operationKey:1},{unique:true}),
      ]);
    }else{
      this.db.exec(`
        CREATE TABLE IF NOT EXISTS civic_candidates(cycle_id TEXT NOT NULL,resident_id TEXT NOT NULL,display_name TEXT NOT NULL,username TEXT NOT NULL,party_id TEXT NOT NULL,manifesto TEXT NOT NULL,support INTEGER NOT NULL DEFAULT 0,heat INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',enforcement TEXT NOT NULL DEFAULT 'none',created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,resident_id));
        CREATE TABLE IF NOT EXISTS civic_votes(cycle_id TEXT NOT NULL,voter_id TEXT NOT NULL,candidate_id TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,voter_id));
        CREATE INDEX IF NOT EXISTS civic_votes_candidate ON civic_votes(cycle_id,candidate_id);
        CREATE TABLE IF NOT EXISTS civic_events(id TEXT PRIMARY KEY,cycle_id TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,actor_id TEXT,district TEXT,created_at INTEGER NOT NULL,expires_at INTEGER);
        CREATE INDEX IF NOT EXISTS civic_events_cycle ON civic_events(cycle_id,created_at DESC);
        CREATE TABLE IF NOT EXISTS civic_governments(cycle_id TEXT PRIMARY KEY,winner_id TEXT,winner_name TEXT,party_id TEXT,budget INTEGER NOT NULL,integrity INTEGER NOT NULL,heat INTEGER NOT NULL,elected_at INTEGER NOT NULL,active_story TEXT,active_story_ends_at INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE IF NOT EXISTS civic_actions(cycle_id TEXT NOT NULL,resident_id TEXT NOT NULL,operation_key TEXT NOT NULL,kind TEXT NOT NULL,result TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(cycle_id,resident_id,operation_key));
      `);
    }
    return this;
  }
  rateLimit(principal,kind,limit=50){const now=Date.now(),k=`${principal}:${kind}`,old=this.limits.get(k),bucket=old&&now-old.at<60000?old:{at:now,count:0};bucket.count++;this.limits.set(k,bucket);fail(bucket.count<=limit,'Please wait before trying that again',429,'rate_limited');if(this.limits.size>5000)for(const[k,v]of this.limits)if(now-v.at>60000)this.limits.delete(k);}
  cors(req,res){const origin=req.headers.origin;if(!origin)return;fail(this.allowedOrigins.has(origin),'This origin is not permitted',403,'cross_origin');res.setHeader('access-control-allow-origin',origin);res.setHeader('access-control-allow-credentials','true');res.setHeader('vary','Origin');}
  requireActionOrigin(req){fail(/^application\/json(?:\s*;|$)/i.test(req.headers['content-type']||''),'Send JSON for this action',415);if(req.headers['sec-fetch-site']==='cross-site'||(req.headers.cookie&&!req.headers.authorization))fail(!req.headers.origin||this.allowedOrigins.has(req.headers.origin),'Open AbujaLife to perform this action',403,'cross_origin');}
  async requireResident(req){const token=tokenFor(req),id=token?await this.store.session(token):null;fail(id,'Sign in to use AbujaLife civic life',401,'authentication_required');if(this.admin?.isSuspended)fail(!await this.admin.isSuspended(id),'This account is suspended',403,'account_suspended');return id;}
  async profile(id,session=null){return this.mongo?this.store.profile(id,{session}):this.store.profile(id);}
  locationMatches(profile,venueId){return profile?.location?.kind==='venue'&&(profile.location.venue===venueId||profile.location.venueId===venueId);}
  atHomePoll(profile){return !profile?.activeTrip&&profile?.location?.kind==='public'&&profile?.district===profile?.home?.district;}
  candidateFromSql(row){return row?{cycleId:row.cycle_id,residentId:row.resident_id,displayName:row.display_name,username:row.username,partyId:row.party_id,manifesto:row.manifesto,support:row.support,heat:row.heat,status:row.status,enforcement:row.enforcement,createdAt:row.created_at,updatedAt:row.updated_at}:null;}
  async candidate(cycleId,residentId,{session=null}={}){if(this.mongo)return this.collection('civic_candidates').findOne({cycleId,residentId},session?{session}:{});return this.candidateFromSql(this.store.get('SELECT * FROM civic_candidates WHERE cycle_id=? AND resident_id=?',cycleId,residentId));}
  async voteFor(cycleId,voterId,{session=null}={}){if(this.mongo)return(await this.collection('civic_votes').findOne({cycleId,voterId},session?{session}:{}))?.candidateId||null;return this.store.get('SELECT candidate_id FROM civic_votes WHERE cycle_id=? AND voter_id=?',cycleId,voterId)?.candidate_id||null;}
  async voteCounts(cycleId,{session=null}={}){
    if(this.mongo){const rows=await this.collection('civic_votes').aggregate([{$match:{cycleId}},{$group:{_id:'$candidateId',votes:{$sum:1}}}],session?{session}:{}).toArray();return new Map(rows.map(r=>[r._id,r.votes]));}
    return new Map(this.store.all('SELECT candidate_id,count(*) AS votes FROM civic_votes WHERE cycle_id=? GROUP BY candidate_id',cycleId).map(r=>[r.candidate_id,Number(r.votes)]));
  }
  async candidates(cycleId,{session=null}={}){
    const votes=await this.voteCounts(cycleId,{session});let rows;
    if(this.mongo)rows=await this.collection('civic_candidates').find({cycleId},session?{session}:{}).sort({support:-1,createdAt:1}).limit(200).toArray();
    else rows=this.store.all('SELECT * FROM civic_candidates WHERE cycle_id=? ORDER BY support DESC,created_at ASC LIMIT 200',cycleId).map(r=>this.candidateFromSql(r));
    return rows.map(row=>publicCandidate({...row,votes:votes.get(row.residentId)||0})).sort((a,b)=>b.votes-a.votes||b.support-a.support||a.createdAt-b.createdAt);
  }
  async event(cycleId,{id=crypto.randomUUID(),kind='story',title,body,actorId=null,district=null,createdAt=this.now(),expiresAt=null}={},session=null){const row={id,cycleId,kind,title:clean(title,100),body:clean(body,360),actorId,district,createdAt,expiresAt};if(this.mongo){await this.collection('civic_events').updateOne({_id:id},{$setOnInsert:{_id:id,...row}},{upsert:true,...(session?{session}:{})});}else this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',id,cycleId,kind,row.title,row.body,actorId,district,createdAt,expiresAt);return row;}
  async events(cycleId){if(this.mongo)return(await this.collection('civic_events').find({cycleId}).sort({createdAt:-1}).limit(30).toArray()).map(({_id,...r})=>r);return this.store.all('SELECT * FROM civic_events WHERE cycle_id=? ORDER BY created_at DESC LIMIT 30',cycleId).map(r=>({id:r.id,cycleId:r.cycle_id,kind:r.kind,title:r.title,body:r.body,actorId:r.actor_id,district:r.district,createdAt:r.created_at,expiresAt:r.expires_at}));}
  governmentFromSql(r){return r?{cycleId:r.cycle_id,winnerId:r.winner_id,winnerName:r.winner_name,partyId:r.party_id,budget:r.budget,integrity:r.integrity,heat:r.heat,electedAt:r.elected_at,activeStory:r.active_story,activeStoryEndsAt:r.active_story_ends_at}:null;}
  async government(cycleId,{session=null}={}){if(this.mongo)return this.collection('civic_governments').findOne({cycleId},session?{session}:{});return this.governmentFromSql(this.store.get('SELECT * FROM civic_governments WHERE cycle_id=?',cycleId));}
  async ensureGovernment(cycle){
    if(cycle.phase.id!=='results')return this.government(cycle.id);
    const existing=await this.government(cycle.id);if(existing)return existing;
    const candidates=(await this.candidates(cycle.id)).filter(c=>!['disqualified'].includes(c.status));const winner=candidates[0]||null,now=this.now();
    const row={cycleId:cycle.id,winnerId:winner?.residentId||null,winnerName:winner?.displayName||null,partyId:winner?.partyId||null,budget:CIVIC_META.governmentBudget,integrity:100,heat:0,electedAt:now,activeStory:null,activeStoryEndsAt:0};
    if(this.mongo){try{await this.collection('civic_governments').insertOne({_id:cycle.id,...row});}catch(error){if(error.code!==11000)throw error;}}
    else this.store.run('INSERT OR IGNORE INTO civic_governments VALUES(?,?,?,?,?,?,?,?,?,?)',cycle.id,row.winnerId,row.winnerName,row.partyId,row.budget,row.integrity,row.heat,row.electedAt,null,0);
    if(winner)await this.event(cycle.id,{id:`result:${cycle.id}`,kind:'result',title:`${winner.displayName} wins the AbujaLife presidency`,body:`${winner.votes.toLocaleString()} vote${winner.votes===1?'':'s'} · ${civicParty(winner.partyId)?.short||winner.partyId}. The fictional city administration is now active.`,actorId:winner.residentId,createdAt:now});
    else await this.event(cycle.id,{id:`result:${cycle.id}`,kind:'result',title:'No presidential result this cycle',body:'No eligible fictional candidate remained on the ballot.',createdAt:now});
    return this.government(cycle.id);
  }
  enforcementFor(heat){if(heat>=CIVIC_STORY_THRESHOLDS.disqualify)return{status:'disqualified',enforcement:'court-disqualification'};if(heat>=CIVIC_STORY_THRESHOLDS.detention)return{status:'detained',enforcement:'detained-pending-hearing'};if(heat>=CIVIC_STORY_THRESHOLDS.raid)return{status:'under-review',enforcement:'efcc-raid'};if(heat>=CIVIC_STORY_THRESHOLDS.review)return{status:'under-review',enforcement:'efcc-review'};return{status:'active',enforcement:'none'};}
  async state(id){const now=this.now(),cycle=civicCycle(now);await this.ensureGovernment(cycle);const profile=await this.profile(id),candidate=await this.candidate(cycle.id,id),government=await this.government(cycle.id),votedFor=await this.voteFor(cycle.id,id),candidates=await this.candidates(cycle.id),events=await this.events(cycle.id);const atInec=this.locationMatches(profile,'inec-hq'),atEfcc=this.locationMatches(profile,'efcc-hq'),atCourt=this.locationMatches(profile,'federal-high-court-hub');return{ok:true,meta:CIVIC_META,parties:CIVIC_PARTIES,cycle,candidate:publicCandidate(candidate),candidates,government:publicGovernment(government),events,votedFor,resident:{reputation:Number(profile.reputation||0),wallet:Number(profile.wallet||0),district:profile.district,homeDistrict:profile.home?.district||null,location:profile.location,atInec,atEfcc,atCourt,atHomePoll:this.atHomePoll(profile),isPresident:government?.winnerId===id},campaignActions:CIVIC_CAMPAIGN_ACTIONS,governmentActions:CIVIC_GOVERNMENT_ACTIONS,eligibility:{nominationOpen:cycle.nominationOpen&&!candidate,reputationReady:Number(profile.reputation||0)>=CIVIC_META.nominationReputation,fundsReady:Number(profile.wallet||0)>=CIVIC_META.nominationFee,atInec,canVote:cycle.phase.id==='voting'&&!votedFor&&this.atHomePoll(profile)}};}
  async nominate(id,body){const cycle=civicCycle(this.now()),party=civicParty(clean(body.partyId,40)),manifesto=clean(body.manifesto,260);fail(cycle.nominationOpen,'Candidate nominations are closed for this cycle',409,'nominations_closed');fail(party,'Choose a fictional AbujaLife party');fail(manifesto.length>=20,'Write a manifesto of at least 20 characters');fail(keyOK(body.idempotencyKey),'Use a valid nomination request key',400,'idempotency_required');const existing=await this.candidate(cycle.id,id);fail(!existing,'You are already a candidate this cycle',409,'already_candidate');const normalized={cycleId:cycle.id,partyId:party.id,manifesto};
    const mutate=async(p,timestamp,session)=>{fail(this.locationMatches(p,'inec-hq'),'Visit the fictional INEC HQ experience before buying a nomination ticket',409,'wrong_venue');fail(Number(p.reputation||0)>=CIVIC_META.nominationReputation,`Build at least ${CIVIC_META.nominationReputation} reputation before running`,409,'reputation_required');fail(p.wallet>=CIVIC_META.nominationFee,'You need more Game Naira for the nomination ticket',409,'insufficient_balance');p.wallet-=CIVIC_META.nominationFee;const row={cycleId:cycle.id,residentId:id,displayName:p.displayName,username:p.username,partyId:party.id,manifesto,support:0,heat:0,status:'active',enforcement:'none',createdAt:timestamp,updatedAt:timestamp};if(this.mongo){await this.collection('civic_candidates').insertOne({_id:`${cycle.id}:${id}`,...row},{session});await this.event(cycle.id,{kind:'nomination',title:`${p.displayName} enters the presidential race`,body:`${party.short} · ${manifesto}`,actorId:id,createdAt:timestamp},session);}else{this.store.run('INSERT INTO civic_candidates VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',cycle.id,id,p.displayName,p.username,party.id,manifesto,0,0,'active','none',timestamp,timestamp);await this.event(cycle.id,{kind:'nomination',title:`${p.displayName} enters the presidential race`,body:`${party.short} · ${manifesto}`,actorId:id,createdAt:timestamp});}return{candidate:publicCandidate(row),ledgerReason:'AbujaLife presidential nomination ticket'};};
    const result=this.mongo?await this.store.economyOperation(id,'civic-nomination',body,normalized,mutate):await this.store.economyOperation(id,'civic-nomination',body,normalized,(p,timestamp)=>{let output;mutate(p,timestamp,null).then(v=>output=v);if(!output){fail(this.locationMatches(p,'inec-hq'),'Visit the fictional INEC HQ experience before buying a nomination ticket',409,'wrong_venue');fail(Number(p.reputation||0)>=CIVIC_META.nominationReputation,`Build at least ${CIVIC_META.nominationReputation} reputation before running`,409,'reputation_required');fail(p.wallet>=CIVIC_META.nominationFee,'You need more Game Naira for the nomination ticket',409,'insufficient_balance');p.wallet-=CIVIC_META.nominationFee;const row={cycleId:cycle.id,residentId:id,displayName:p.displayName,username:p.username,partyId:party.id,manifesto,support:0,heat:0,status:'active',enforcement:'none',createdAt:timestamp,updatedAt:timestamp};this.store.run('INSERT INTO civic_candidates VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',cycle.id,id,p.displayName,p.username,party.id,manifesto,0,0,'active','none',timestamp,timestamp);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'nomination',`${p.displayName} enters the presidential race`,`${party.short} · ${manifesto}`,id,null,timestamp,null);return{candidate:publicCandidate(row),ledgerReason:'AbujaLife presidential nomination ticket'};}return output;});return{...result,civic:await this.state(id)};}
  async campaign(id,body){const cycle=civicCycle(this.now()),action=civicAction(clean(body.actionId,60));fail(['nominations','campaign','debates'].includes(cycle.phase.id),'Campaign activities are closed right now',409,'campaign_closed');fail(action,'Choose a listed campaign activity');if(action.phase)fail(cycle.phase.id===action.phase,`${action.name} is not available in this phase`,409,'wrong_phase');fail(keyOK(body.idempotencyKey),'Use a valid campaign request key',400,'idempotency_required');const existing=await this.candidate(cycle.id,id);fail(existing,'Enter the presidential race first',409,'not_candidate');fail(existing.status!=='disqualified','This candidate is no longer on the ballot',409,'candidate_disqualified');const normalized={cycleId:cycle.id,actionId:action.id};
    const apply=(p,timestamp,session)=>{fail(!action.venueId||this.locationMatches(p,action.venueId),`Go to ${action.venueId.replace(/-/g,' ')} before doing this activity`,409,'wrong_venue');fail(!action.requiresPublic||p.location?.kind==='public','Head outside before canvassing residents',409,'wrong_location');fail(!action.requiresCase||existing.enforcement!=='none','There is no active case requiring a hearing',409,'no_active_case');if(action.cost){fail(p.wallet>=action.cost,'You need more Game Naira for this campaign activity',409,'insufficient_balance');p.wallet-=action.cost;}const support=Math.max(0,Number(existing.support||0)+Number(action.score||0)),heat=Math.max(0,Number(existing.heat||0)+Number(action.heat||0)),enforcement=this.enforcementFor(heat),row={...existing,support,heat,status:enforcement.status,enforcement:enforcement.enforcement,updatedAt:timestamp};return{row,ledgerReason:action.cost?`Campaign activity · ${action.name}`:undefined};};
    const persistMongo=async(p,timestamp,session)=>{const{row,ledgerReason}=apply(p,timestamp,session);await this.collection('civic_candidates').updateOne({cycleId:cycle.id,residentId:id},{$set:{support:row.support,heat:row.heat,status:row.status,enforcement:row.enforcement,updatedAt:timestamp}},{session});await this.event(cycle.id,{kind:'campaign',title:`${p.displayName}: ${action.name}`,body:action.description,actorId:id,district:p.district,createdAt:timestamp},session);if(row.enforcement!==existing.enforcement)await this.event(cycle.id,{kind:'investigation',title:row.enforcement==='efcc-raid'?`EFCC storyline raid opened for ${p.displayName}`:row.enforcement==='detained-pending-hearing'?`${p.displayName} detained pending fictional court hearing`:row.status==='disqualified'?`${p.displayName} removed from the fictional ballot`:`Financial scrutiny opened for ${p.displayName}`,body:'This is an in-game fictional integrity storyline involving fictional candidates only.',actorId:id,createdAt:timestamp},session);return{candidate:publicCandidate(row),activity:action,ledgerReason};};
    const persistSql=(p,timestamp)=>{const{row,ledgerReason}=apply(p,timestamp,null);this.store.run('UPDATE civic_candidates SET support=?,heat=?,status=?,enforcement=?,updated_at=? WHERE cycle_id=? AND resident_id=?',row.support,row.heat,row.status,row.enforcement,timestamp,cycle.id,id);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'campaign',`${p.displayName}: ${action.name}`,action.description,id,p.district,timestamp,null);if(row.enforcement!==existing.enforcement)this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'investigation',row.enforcement==='efcc-raid'?`EFCC storyline raid opened for ${p.displayName}`:row.enforcement==='detained-pending-hearing'?`${p.displayName} detained pending fictional court hearing`:row.status==='disqualified'?`${p.displayName} removed from the fictional ballot`:`Financial scrutiny opened for ${p.displayName}`,'This is an in-game fictional integrity storyline involving fictional candidates only.',id,p.district,timestamp,null);return{candidate:publicCandidate(row),activity:action,ledgerReason};};
    const result=this.mongo?await this.store.economyOperation(id,'civic-campaign',body,normalized,persistMongo):await this.store.economyOperation(id,'civic-campaign',body,normalized,persistSql);return{...result,civic:await this.state(id)};}
  async vote(id,body){const cycle=civicCycle(this.now());fail(cycle.phase.id==='voting','Voting is not open right now',409,'voting_closed');const candidateId=clean(body.candidateId,80),candidate=await this.candidate(cycle.id,candidateId);fail(candidate&&!['detained','disqualified'].includes(candidate.status),'Choose an eligible candidate');const profile=await this.profile(id);fail(this.atHomePoll(profile),'Return to your home district and head outside to vote',409,'polling_location_required');fail(!await this.voteFor(cycle.id,id),'You have already voted this cycle',409,'already_voted');const now=this.now();if(this.mongo)await this.collection('civic_votes').insertOne({_id:`${cycle.id}:${id}`,cycleId:cycle.id,voterId:id,candidateId,createdAt:now});else this.store.run('INSERT INTO civic_votes VALUES(?,?,?,?)',cycle.id,id,candidateId,now);return{ok:true,receipt:{cycleId:cycle.id,candidateId,castAt:now},civic:await this.state(id)};}
  async governmentAction(id,body){const cycle=civicCycle(this.now()),action=civicGovernmentAction(clean(body.actionId,60));fail(cycle.phase.id==='results','The new administration is not active yet',409,'government_inactive');fail(action,'Choose a listed city decision');fail(keyOK(body.idempotencyKey),'Use a valid city-action request key',400,'idempotency_required');const gov=await this.ensureGovernment(cycle);fail(gov?.winnerId===id,'Only the elected AbujaLife President can make this decision',403,'not_president');const profile=await this.profile(id);fail(this.locationMatches(profile,action.venueId),`Go to ${action.venueId.replace(/-/g,' ')} to announce this decision`,409,'wrong_venue');const now=this.now(),resultView={actionId:action.id,title:action.name,startedAt:now,endsAt:now+action.durationHours*3600000};
    if(this.mongo){const result=await this.store.transaction(async session=>{const replay=await this.collection('civic_actions').findOne({cycleId:cycle.id,residentId:id,operationKey:body.idempotencyKey},{session});if(replay)return replay.result;const current=await this.collection('civic_governments').findOne({cycleId:cycle.id},{session});fail(current&&current.winnerId===id,'Administration changed; refresh',409,'government_changed');fail(current.budget>=action.cost,'The city budget is too low for this decision',409,'city_budget_low');const budget=current.budget-action.cost,integrity=Math.max(0,Math.min(100,current.integrity+Number(action.integrity||0))),heat=Math.max(0,Number(current.heat||0)+Number(action.heat||0));await this.collection('civic_governments').updateOne({cycleId:cycle.id,winnerId:id},{$set:{budget,integrity,heat,activeStory:action.name,activeStoryEndsAt:resultView.endsAt}},{session});await this.collection('civic_actions').insertOne({_id:`${cycle.id}:${id}:${body.idempotencyKey}`,cycleId:cycle.id,residentId:id,operationKey:body.idempotencyKey,kind:action.id,result:{...resultView,budget,integrity,heat},createdAt:now},{session});await this.event(cycle.id,{kind:'government',title:action.name,body:action.description,actorId:id,district:profile.district,createdAt:now,expiresAt:resultView.endsAt},session);return{...resultView,budget,integrity,heat};});return{ok:true,result,civic:await this.state(id)};}
    let result;this.store.transaction(()=>{const replay=this.store.get('SELECT result FROM civic_actions WHERE cycle_id=? AND resident_id=? AND operation_key=?',cycle.id,id,body.idempotencyKey);if(replay){result=JSON.parse(replay.result);return;}const current=this.governmentFromSql(this.store.get('SELECT * FROM civic_governments WHERE cycle_id=?',cycle.id));fail(current&&current.winnerId===id,'Administration changed; refresh',409,'government_changed');fail(current.budget>=action.cost,'The city budget is too low for this decision',409,'city_budget_low');const budget=current.budget-action.cost,integrity=Math.max(0,Math.min(100,current.integrity+Number(action.integrity||0))),heat=Math.max(0,Number(current.heat||0)+Number(action.heat||0));result={...resultView,budget,integrity,heat};this.store.run('UPDATE civic_governments SET budget=?,integrity=?,heat=?,active_story=?,active_story_ends_at=? WHERE cycle_id=?',budget,integrity,heat,action.name,resultView.endsAt,cycle.id);this.store.run('INSERT INTO civic_actions VALUES(?,?,?,?,?,?)',cycle.id,id,body.idempotencyKey,action.id,JSON.stringify(result),now);this.store.run('INSERT OR IGNORE INTO civic_events VALUES(?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),cycle.id,'government',action.name,action.description,id,profile.district,now,resultView.endsAt);});return{ok:true,result,civic:await this.state(id)};}
  async handle(req,res){try{this.cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization',...SECURITY_HEADERS});res.end();return;}const id=await this.requireResident(req),url=new URL(req.url,'https://api.abujacity.life'),path=url.pathname;this.rateLimit(id,path,req.method==='GET'?120:35);if(req.method==='GET'&&path==='/api/civic/state')return json(res,200,await this.state(id));if(req.method==='GET'&&path==='/api/civic/candidates'){const cycle=civicCycle(this.now());return json(res,200,{ok:true,cycle,candidates:await this.candidates(cycle.id)});}if(req.method==='POST')this.requireActionOrigin(req);const body=req.method==='POST'?await readJSON(req):{};if(path==='/api/civic/nominate'&&req.method==='POST')return json(res,200,await this.nominate(id,body));if(path==='/api/civic/campaign'&&req.method==='POST')return json(res,200,await this.campaign(id,body));if(path==='/api/civic/vote'&&req.method==='POST')return json(res,200,await this.vote(id,body));if(path==='/api/civic/government/action'&&req.method==='POST')return json(res,200,await this.governmentAction(id,body));return json(res,404,{ok:false,error:'Not found',code:'not_found'});}catch(error){const status=error instanceof GameError?error.status:500;this.log('civic_request_error',{status,code:error instanceof GameError?error.code:'internal_error'});return json(res,status,{ok:false,error:error instanceof GameError?error.message:'Something went wrong. Please try again.',code:error instanceof GameError?error.code:'server_error'});}}
}
