import crypto from 'node:crypto';
import { promisify } from 'node:util';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import { ABUJA_ATLAS } from '../shared/atlas.mjs';
import { LIFE_GOALS, GAME_YEAR_MS, GAME_BILL_PERIOD_MS, venueFor, venueActionFor, ownsVehicle, applyNeedEffects, furniturePlacement } from '../shared/life.mjs';
const scrypt = promisify(crypto.scrypt);
const uid = () => crypto.randomUUID();
const clean = (value, max = 80) => String(value ?? '').trim().slice(0, max);
const clamp = n => Math.max(0, Math.min(100, Math.round(n)));
const locations = new Map(ABUJA_ATLAS.map(place => [place.id, place]));
export class GameError extends Error {
  constructor(message, status = 400, code = 'invalid_action') { super(message); this.status = status; this.code = code; }
}
const check = (condition, message, status = 400, code) => { if (!condition) throw new GameError(message, status, code); };
const task = (id,prompt,options,answer) => ({id,prompt,options:options.map(([id,label])=>({id,label})),answer});
export const jobs = {
  'restaurant-host': {id:'restaurant-host',title:'Restaurant host',district:'garki-i',pay:5600,energy:12,skill:'Hospitality',description:'Welcome guests and coordinate service.',tasks:[
    task('arrival','A party of four arrives. Only a table for two is ready.',[['join','Check whether two tables can be joined'],['split','Seat them apart without asking'],['ignore','Leave them waiting without an update']],'join'),
    task('allergy','A guest mentions a groundnut allergy.',[['guess','Assume the sauce is safe'],['kitchen','Confirm ingredients and preparation with the kitchen'],['remove','Remove the garnish and serve']],'kitchen'),
    task('order','One meal is delayed while the rest are ready.',[['update','Give a clear update and coordinate service'],['hide','Avoid the table'],['promise','Promise it is ready without checking']],'update')]},
  'junior-dev': {id:'junior-dev',title:'Junior developer',district:'wuse-ii-a07',pay:8500,energy:18,skill:'Technology',description:'Triage a customer issue and ship a careful fix.',tasks:[
    task('reproduce','A customer says checkout fails on mobile. Your first step?',[['reproduce','Reproduce the issue on a mobile viewport'],['rewrite','Rewrite checkout immediately'],['dismiss','Close the report']],'reproduce'),
    task('money','The browser submits its own account balance.',[['trust','Trust the value'],['server','Calculate balances on the server'],['round','Round the submitted number']],'server'),
    task('release','Your fix passes locally. Before release?',[['check','Run relevant checks and review the change'],['ship','Skip tests'],['delete','Delete the failing checks']],'check')]},
  'media-assistant': {id:'media-assistant',title:'Creative assistant',district:'garki-ii',pay:6200,energy:15,skill:'Creative',description:'Prepare and deliver a campaign.',tasks:[
    task('brief','A client requests an event flyer. What do you confirm?',[['facts','Date, venue, audience and approval contact'],['colour','Only their favourite colour'],['guess','Invent missing details']],'facts'),
    task('rights','You find a photographer’s image online.',[['copy','Copy it without asking'],['license','Use an image with permission or a suitable licence'],['crop','Crop away the watermark']],'license'),
    task('delivery','The client approves the final design.',[['source','Deliver agreed formats and keep a versioned copy'],['small','Send only a blurry screenshot'],['edit','Change the approved text']],'source')]},
  'property-agent': {id:'property-agent',title:'Property assistant',district:'jabi',pay:9800,energy:20,skill:'Sales',description:'Match a home to a resident and verify details.',tasks:[
    task('needs','A resident wants an apartment. Start with?',[['budget','Their budget, commute and household needs'],['luxury','The highest commission property'],['rush','Ask them to pay before viewing']],'budget'),
    task('listing','A listing has unclear ownership documents.',[['verify','Verify documentation before recommending it'],['hide','Hide that concern'],['guess','Assume it is fine']],'verify'),
    task('viewing','The resident asks about service charges.',[['total','Explain rent and all disclosed recurring charges'],['omit','Mention only the rent'],['avoid','Avoid the question']],'total')]},
  'site-supervisor': {id:'site-supervisor',title:'Site coordinator',district:'guzape',pay:11000,energy:24,skill:'Construction',description:'Coordinate a safe site handover.',tasks:[
    task('safety','A contractor arrives without protective gear.',[['ppe','Check suitable protection before entering the work zone'],['ignore','Let them start immediately'],['photo','Take a photo and walk away']],'ppe'),
    task('delivery','A material delivery does not match the order.',[['record','Record the mismatch and confirm with the supplier'],['accept','Accept everything without checking'],['discard','Throw it away']],'record'),
    task('handover','Before handing over a room, you should?',[['inspect','Inspect the work and record unresolved defects'],['paint','Cover defects with paint'],['sign','Sign without inspecting']],'inspect')]}
};
export const catalog = [
  {id:'linen-shirt',name:'Linen shirt',category:'clothing',slot:'top',value:'cream',price:4200,description:'An easy neutral shirt for warm afternoons.'},
  {id:'office-shirt',name:'Office shirt',category:'clothing',slot:'top',value:'navy',price:5800,description:'A clean fit for work and city evenings.'},
  {id:'traditional-set',name:'Agbada set',category:'clothing',slot:'top',value:'agbada',price:12000,description:'A contemporary traditional outfit.'},
  {id:'white-trainers',name:'White trainers',category:'clothing',slot:'shoes',value:'white',price:4800,description:'Everyday city footwear.'},
  {id:'lounge-chair',name:'Lounge chair',category:'furniture',price:7500,description:'A comfortable chair for your living room.'},
  {id:'plant',name:'Indoor plant',category:'furniture',price:2300,description:'A little green for your home.'},
  {id:'bookshelf',name:'Bookshelf',category:'furniture',price:6500,description:'A quiet corner to read and unwind.'},
  {id:'sofa',name:'Two-seat sofa',category:'furniture',price:18000,description:'Room for a visitor and a conversation.'},
  {id:'dining-table',name:'Dining table',category:'furniture',price:4200,description:'A compact timber table for meals and visitors.'},
  {id:'bed',name:'Upholstered bed',category:'furniture',price:11000,description:'A comfortable upgrade for your bedroom.'},
  {id:'fridge',name:'Kitchen fridge',category:'furniture',price:9800,description:'Make the kitchen your own with a full-size fridge.'},
  {id:'floor-lamp',name:'Floor lamp',category:'furniture',price:3200,description:'Warm light beside your favourite chair.'},
  {id:'rug',name:'Woven rug',category:'furniture',price:2600,description:'Colour and texture for your living space.'},
  {id:'tv',name:'Living-room TV',category:'furniture',price:14500,description:'Build a proper entertainment corner.'},
  {id:'used-hatchback',name:'Used city hatchback',category:'vehicle',price:28000,model:'hatchback',colour:'#d9b959',speed:1,description:'Your first set of wheels: a characterful older hatchback. Earn one good starter shift and it is within reach.'},
  {id:'starter-hatchback',name:'Modern hatchback',category:'vehicle',price:95000,model:'hatchback',colour:'#7aa2a3',speed:1.1,description:'A practical modern hatchback for city driving.'},
  {id:'compact-car',name:'City compact',category:'vehicle',price:240000,model:'sedan',colour:'#f4eee0',speed:1.2,description:'A comfortable owned virtual car with compressed inter-district travel.'},
  {id:'city-sedan',name:'Executive sedan',category:'vehicle',price:380000,model:'sedan',colour:'#37465e',speed:1.25,description:'A refined sedan for the next chapter of city life.'},
  {id:'premium-suv',name:'Premium SUV',category:'vehicle',price:890000,model:'suv',colour:'#d9d9d2',speed:1.3,description:'A spacious premium vehicle to work towards.'}
];
export const properties = [
  {id:'garki-studio',name:'Garki starter studio',district:'garki-i',tier:0,rent:0,buy:0,bills:450,description:'A modest furnished studio with a kitchen and bathroom.'},
  {id:'lugbe-flat',name:'Lugbe one-bedroom',district:'lugbe',tier:1,rent:18000,buy:280000,bills:1200,description:'More space along the airport corridor.'},
  {id:'gwarinpa-apartment',name:'Gwarinpa apartment',district:'gwarinpa-i',tier:2,rent:38000,buy:620000,bills:2300,description:'A residential base with room for friends.'},
  {id:'jabi-apartment',name:'Jabi lake-side apartment',district:'jabi',tier:3,rent:62000,buy:980000,bills:3200,description:'A modern apartment close to city life.'},
  {id:'guzape-terrace',name:'Guzape terrace',district:'guzape',tier:4,rent:115000,buy:2200000,bills:6200,description:'A hillside terrace with a generous living room.'},
  {id:'maitama-villa',name:'Maitama villa',district:'maitama',tier:5,rent:240000,buy:5800000,bills:11000,description:'A landscaped private compound.'}
].map(item=>{
  const plans=[['studio',0,1,32],['flat',1,1,58],['apartment',2,2,105],['apartment',2,2,125],['terrace',3,4,215],['villa',5,6,420]];
  const [type,bedrooms,bathrooms,areaM2]=plans[item.tier];
  return {...item,price:item.buy,type,bedrooms,bathrooms,areaM2,rentPeriod:'game year',rentPeriodDays:28,billPeriodDays:7,serviceCharge:item.bills,agencyFee:0,cautionDeposit:0,moveInCost:item.rent,priceLabel:'Game prices',fictional:true,features:[item.tier===0?'Starter furnishings':'Separate living space',item.tier>=2?'Visitor parking':'Street parking',item.tier>=4?'Private compound':'Shared compound',item.tier>=3?'Balcony or terrace':'Practical kitchen'],viewing:{free:true,description:'Inspect the authored floor plan before spending any Abuja Naira.'}};
});
export const activities = {eat:{cost:1200,location:'home'},sleep:{cost:0,location:'home'},shower:{cost:0,location:'home'},relax:{cost:0,location:'home'},hangout:{cost:2400,location:'public'},exercise:{cost:800,location:'public'},cinema:{cost:3800,location:'public'}};
export const transportModes = [
  {id:'walk',name:'Walk',description:'Within your current neighbourhood.'},
  {id:'bus',name:'Bus',description:'A lower-cost trip with a longer compressed journey.'},
  {id:'taxi',name:'Taxi',description:'A direct city trip.'},
  {id:'ride',name:'Ride-hailing',description:'A direct pickup.'},
  {id:'car',name:'Your car',description:'Available after buying a virtual vehicle.'}
];
export const appearanceOptions = {skinTone:['deep','brown','warm','light'],hair:['crop','locs','afro','braids','bald'],top:['ochre','forest','cream','navy','agbada'],body:['regular','slim','broad'],face:['oval','round','angular'],presentation:['neutral','feminine','masculine'],facialHair:['none','beard'],bottom:['charcoal','denim','cream'],shoes:['white','black'],accessory:['none','glasses']};
const initialAppearance = {skinTone:'brown',face:'oval',body:'regular',hair:'crop',facialHair:'none',presentation:'neutral',top:'forest',bottom:'charcoal',shoes:'white',accessory:'none'};
function updateAppearance(current, incoming, inventory=[]) { if(incoming&&typeof incoming==='object')for(const [key,values] of Object.entries(appearanceOptions))if(incoming[key]!==undefined){check(values.includes(incoming[key]),`Choose a supported ${key}`);if(key==='top'&&!['forest','ochre'].includes(incoming[key])){const item=catalog.find(item=>item.category==='clothing'&&item.slot==='top'&&item.value===incoming[key]);check(item&&inventory.includes(item.id),'Buy this outfit in City Market before wearing it',403,'outfit_not_owned');}current[key]=incoming[key];}return current; }

export class GameStore {
  constructor({dataDir=process.env.ABUJALIFE_DATA_DIR||path.resolve('.local'),clock=Date.now}={}) {
    fs.mkdirSync(dataDir,{recursive:true});this.db=new DatabaseSync(path.join(dataDir,'abujalife.sqlite'));this.clock=clock;this.emitUser=()=>{};this.emitZone=()=>{};this.isOnline=()=>false;
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
      CREATE TABLE IF NOT EXISTS residents(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,profile TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,resident_id TEXT NOT NULL REFERENCES residents(id),expires_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS ledger(id TEXT PRIMARY KEY,resident_id TEXT NOT NULL REFERENCES residents(id),amount INTEGER NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS challenges(id TEXT PRIMARY KEY,resident_id TEXT NOT NULL,job_id TEXT NOT NULL,started_at INTEGER NOT NULL,completed_at INTEGER,result TEXT);
      CREATE TABLE IF NOT EXISTS friendship(id TEXT PRIMARY KEY,sender TEXT NOT NULL,recipient TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(sender,recipient));
      CREATE TABLE IF NOT EXISTS conversations(id TEXT PRIMARY KEY,kind TEXT NOT NULL,name TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS members(conversation_id TEXT NOT NULL REFERENCES conversations(id),resident_id TEXT NOT NULL REFERENCES residents(id),joined_at INTEGER NOT NULL,read_at INTEGER NOT NULL DEFAULT 0,delivered_at INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(conversation_id,resident_id));
      CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,conversation_id TEXT NOT NULL REFERENCES conversations(id),sender_id TEXT NOT NULL REFERENCES residents(id),text TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS location_messages(id TEXT PRIMARY KEY,zone TEXT NOT NULL,sender_id TEXT NOT NULL,text TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,resident_id TEXT NOT NULL,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,link TEXT,created_at INTEGER NOT NULL,read_at INTEGER);
      CREATE TABLE IF NOT EXISTS moderation(owner TEXT NOT NULL,target TEXT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY(owner,target,kind));
      CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY,reporter TEXT NOT NULL,resident_id TEXT,message_id TEXT,reason TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS invitations(id TEXT PRIMARY KEY,sender TEXT NOT NULL,recipient TEXT NOT NULL,kind TEXT NOT NULL,district TEXT NOT NULL,activity TEXT,note TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,host_id TEXT NOT NULL,title TEXT NOT NULL,district TEXT NOT NULL,starts_at INTEGER NOT NULL,description TEXT NOT NULL,created_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS rsvps(event_id TEXT NOT NULL REFERENCES events(id),resident_id TEXT NOT NULL,PRIMARY KEY(event_id,resident_id));
      CREATE INDEX IF NOT EXISTS messages_conversation ON messages(conversation_id,created_at);
      CREATE INDEX IF NOT EXISTS notices_resident ON notifications(resident_id,created_at);
      CREATE INDEX IF NOT EXISTS location_messages_zone ON location_messages(zone,created_at);`);
    if(!this.all('PRAGMA table_info(notifications)').some(column=>column.name==='sender_id'))this.db.exec('ALTER TABLE notifications ADD COLUMN sender_id TEXT');
  }
  close(){this.db.close();}
  get(sql,...args){return this.db.prepare(sql).get(...args);}
  all(sql,...args){return this.db.prepare(sql).all(...args);}
  run(sql,...args){return this.db.prepare(sql).run(...args);}
  transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.db.exec('COMMIT');return value;}catch(error){this.db.exec('ROLLBACK');throw error;}}
  profile(id){check(typeof id==='string'&&id.length>0&&id.length<=80,'Choose a valid resident');const row=this.get('SELECT profile FROM residents WHERE id=?',id);check(row,'Resident not found',404);const p=JSON.parse(row.profile);p.furnitureLayout ||= {};p.drivingVehicle ??= null;p.onboardingComplete ??= false;p.lifeGoal ||= 'explore';p.ownedProperties ||= [];p.rentPaidAt ??= p.billsPaidAt??p.createdAt;return p;}
  save(profile){this.run('UPDATE residents SET profile=? WHERE id=?',JSON.stringify(profile),profile.id);return structuredClone(profile);}
  async register({username,displayName,password,appearance}) {
    username=clean(username,24).toLowerCase();displayName=clean(displayName,40)||username;check(/^[a-z0-9_]{3,24}$/.test(username),'Use 3–24 letters, numbers or underscores for your username');check(typeof password==='string'&&password.length>=8&&password.length<=128,'Choose a password of 8–128 characters');check(!this.get('SELECT id FROM residents WHERE username=?',username),'That username is already taken',409);
    const salt=crypto.randomBytes(16).toString('hex');const hash=(await scrypt(password,salt,64)).toString('hex');const id=uid(),timestamp=this.clock();
    const profile={id,username,displayName,appearance:updateAppearance({...initialAppearance},appearance),wallet:26000,energy:82,hunger:72,hygiene:88,social:58,fun:64,stress:12,mood:76,reputation:0,district:'garki-i',location:{kind:'home',district:'garki-i',venue:'home'},home:{propertyId:'garki-studio',name:'Garki starter studio',district:'garki-i',tenure:'starter'},job:null,careerLevel:1,skills:{},inventory:[],ownedProperties:[],furnitureLayout:{},drivingVehicle:null,onboardingComplete:false,lifeGoal:'explore',settings:{presenceVisible:true,allowInvites:true,soundEnabled:true},activeTrip:null,activeShift:null,completedShifts:0,nextShiftAt:0,lastActionAt:timestamp,billsPaidAt:timestamp,rentPaidAt:timestamp,createdAt:timestamp};
    try{this.transaction(()=>{this.run('INSERT INTO residents VALUES(?,?,?,?,?)',id,username,`${salt}:${hash}`,JSON.stringify(profile),timestamp);this.run('INSERT INTO ledger VALUES(?,?,?,?,?)',uid(),id,26000,'Resident starting balance',timestamp);});}catch(error){if(error.message.includes('UNIQUE'))throw new GameError('That username is already taken',409);throw error;}
    this.notify(id,'welcome','Welcome home','Your Garki studio is ready. Settle in, then explore your neighbourhood.','home');return this.createSession(id);
  }
  async login({username,password}) {
    const row=this.get('SELECT id,password FROM residents WHERE username=?',clean(username,24).toLowerCase());const [salt,stored]=(row?.password||`${'0'.repeat(32)}:${'0'.repeat(128)}`).split(':');const hash=await scrypt(typeof password==='string'?password.slice(0,128):'',salt,64);check(row&&crypto.timingSafeEqual(hash,Buffer.from(stored,'hex')),'Username or password is incorrect',401,'invalid_credentials');return this.createSession(row.id);
  }
  hashToken(token){return crypto.createHash('sha256').update(token).digest('hex');}
  createSession(residentId){const token=crypto.randomBytes(32).toString('hex');this.run('DELETE FROM sessions WHERE expires_at<?',this.clock());this.run('INSERT INTO sessions VALUES(?,?,?)',this.hashToken(token),residentId,this.clock()+30*86400000);return{residentId,token};}
  session(token){return typeof token==='string'&&token?this.get('SELECT resident_id FROM sessions WHERE hash=? AND expires_at>?',this.hashToken(token),this.clock())?.resident_id||null:null;}
  logout(token){if(token)this.run('DELETE FROM sessions WHERE hash=?',this.hashToken(token));}
  updateProfile(id,body){const p=this.profile(id);if(body.displayName!==undefined){check(clean(body.displayName,40).length>=2,'Display name must have at least two characters');p.displayName=clean(body.displayName,40);}updateAppearance(p.appearance,body.appearance,p.inventory);if(body.settings&&typeof body.settings==='object')for(const key of ['presenceVisible','allowInvites','soundEnabled'])if(typeof body.settings[key]==='boolean')p.settings[key]=body.settings[key];if(body.lifeGoal!==undefined){check(LIFE_GOALS.some(goal=>goal.id===body.lifeGoal),'Choose a listed life goal');p.lifeGoal=body.lifeGoal;}if(body.onboardingComplete!==undefined){check(typeof body.onboardingComplete==='boolean','Choose a valid onboarding state');p.onboardingComplete=body.onboardingComplete;}return this.save(p);}
  decay(p){const mins=Math.min(120,Math.max(0,(this.clock()-p.lastActionAt)/60000));if(mins>1){p.energy=clamp(p.energy-mins*.10);p.hunger=clamp(p.hunger-mins*.12);p.social=clamp(p.social-mins*.05);}}
  publicJobs(){return Object.fromEntries(Object.entries(jobs).map(([id,{tasks,...job}])=>[id,job]));}
  activeChallenge(id){const row=this.get('SELECT * FROM challenges WHERE resident_id=? AND completed_at IS NULL ORDER BY started_at DESC LIMIT 1',id);return row?this.challengeView(row):null;}
  challengeView(row){return{id:row.id,jobId:row.job_id,title:jobs[row.job_id].title,startedAt:row.started_at,tasks:jobs[row.job_id].tasks.map(({answer,...task})=>task)};}
  quoteTravel(id,payload={}) {
    const p=this.profile(id),destination=clean(payload.district,80),mode=clean(payload.mode||'bus',16);
    check(locations.has(destination),'Choose a location from the Abuja atlas');check(transportModes.some(item=>item.id===mode),'Choose a supported transport mode');check(mode!=='walk'||destination===p.district,'Walking is available within your neighbourhood; choose transport for this trip');check(mode!=='car'||catalog.some(item=>ownsVehicle(p,catalog,item.id)),'Buy a car before choosing your own vehicle');
    const same=destination===p.district,distance=same?0:Math.max(4,Math.round(((locations.get(destination).commute||35)+(locations.get(p.district).commute||35))/3));
    const cost=same?0:mode==='bus'?250+distance*20:mode==='car'?350+distance*20:mode==='taxi'?650+distance*45:900+distance*45;
    const seconds=same?1:Math.min(14,Math.max(4,Math.round(distance/(mode==='bus'?2.5:4))));return{destination,mode,cost,seconds};
  }
  action(id,action,payload={}) {
    const result=this.transaction(()=>{
      const p=this.profile(id);this.decay(p);const before=p.wallet,timestamp=this.clock();let extra={};
      const debit=amount=>{check(Number.isSafeInteger(amount)&&amount>=0,'Invalid cost');check(p.wallet>=amount,'You need more Abuja Naira for this');p.wallet-=amount;};const home=()=>check(p.location.kind==='home','Go home to use this object');const publicPlace=()=>check(p.location.kind==='public'&&!p.activeTrip,'Head out into your neighbourhood first');
      if(p.activeTrip&&!['arrive','topup'].includes(action))throw new GameError('Your journey is still in progress');
      switch(action){
        case 'eat':home();debit(1200);p.hunger=clamp(p.hunger+34);p.mood=clamp(p.mood+4);break;
        case 'sleep':home();p.energy=clamp(p.energy+46);p.hunger=clamp(p.hunger-9);p.stress=clamp(p.stress-12);break;
        case 'shower':home();p.hygiene=clamp(p.hygiene+42);p.mood=clamp(p.mood+2);break;
        case 'relax':home();p.fun=clamp(p.fun+22);p.stress=clamp(p.stress-14);p.energy=clamp(p.energy+8);break;
        case 'hangout':publicPlace();debit(2400);p.social=clamp(p.social+28);p.fun=clamp(p.fun+20);p.energy=clamp(p.energy-8);break;
        case 'exercise':publicPlace();debit(800);p.fun=clamp(p.fun+12);p.stress=clamp(p.stress-18);p.energy=clamp(p.energy-14);p.hygiene=clamp(p.hygiene-10);break;
        case 'cinema':publicPlace();debit(3800);p.fun=clamp(p.fun+34);p.stress=clamp(p.stress-16);p.energy=clamp(p.energy-5);break;
        case 'leave-home':home();p.drivingVehicle=null;p.location={kind:'public',district:p.district,venue:'neighbourhood'};break;
        case 'enter-home':check(p.district===p.home.district,'Travel to your home neighbourhood first');check(!p.drivingVehicle,'Park your car before entering');check(['public','home'].includes(p.location.kind),'Head outside before entering your home');p.location={kind:'home',district:p.district,venue:'home'};break;
        case 'enter-venue':{publicPlace();const venue=venueFor(payload.venueId);check(venue,'Choose a place in your neighbourhood');check(!payload.district||payload.district===p.district,'Travel to this neighbourhood first');check(!p.drivingVehicle,'Park your car before entering');p.location={kind:'venue',district:p.district,venue:venue.id};extra.venue=venue;break;}
        case 'exit-venue':check(p.location.kind==='venue','You are already outside');p.drivingVehicle=null;p.location={kind:'public',district:p.district,venue:'neighbourhood'};break;
        case 'venue-action':{const activity=venueActionFor(payload.activityId);check(activity,'Choose an activity from this place');check(p.location.kind==='venue'&&p.location.venue===activity.venueId,'Enter this place before using its facilities');check(!(activity.effects.energy<0)||p.energy>=-activity.effects.energy,'Rest before doing this activity');debit(activity.cost);applyNeedEffects(p,activity.effects);if(activity.skill)p.skills[activity.skill]=(p.skills[activity.skill]||0)+1;extra.activity={...activity,startedAt:timestamp};break;}
        case 'toggle-driving':{publicPlace();const vehicleId=payload.vehicleId??null;if(vehicleId===null){p.drivingVehicle=null;break;}check(ownsVehicle(p,catalog,vehicleId),'Buy this car before taking the wheel');p.drivingVehicle=vehicleId;extra.vehicle=catalog.find(item=>item.id===vehicleId);break;}
        case 'place-furniture':{home();const item=catalog.find(item=>item.id===payload.itemId);check(item?.category==='furniture'&&p.inventory.includes(item.id),'Buy this furniture before placing it');let placement;try{placement=furniturePlacement(payload);}catch(error){throw new GameError(error.message);}p.furnitureLayout[item.id]=placement;extra.placement={itemId:item.id,...placement};break;}
        case 'return-home':case 'travel':{
          const destination=action==='return-home'?p.home.district:clean(payload.district,80);check(locations.has(destination),'Choose a location from the Abuja atlas');
          if(destination===p.district&&action==='return-home'){p.drivingVehicle=null;p.location={kind:'home',district:destination,venue:'home'};break;}
          const {mode,cost,seconds}=this.quoteTravel(id,{district:destination,mode:payload.mode});
          const vehicleId=mode==='car'?(ownsVehicle(p,catalog,p.drivingVehicle)?p.drivingVehicle:catalog.find(item=>ownsVehicle(p,catalog,item.id))?.id):null;
          debit(cost);p.drivingVehicle=null;p.activeTrip={id:uid(),destination,mode,cost,seconds,vehicleId,arrivesAt:timestamp+seconds*1000,returningHome:action==='return-home'};extra.trip=p.activeTrip;p.location={kind:'transit',district:p.district,venue:'journey'};break;
        }
        case 'arrive':{const trip=p.activeTrip;check(trip&&trip.id===payload.tripId,'This journey is no longer active');check(timestamp>=trip.arrivesAt,'Your journey is still in progress',409,'trip_in_progress');p.district=trip.destination;p.location={kind:trip.returningHome?'home':'public',district:trip.destination,venue:trip.returningHome?'home':'neighbourhood'};p.drivingVehicle=!trip.returningHome&&trip.mode==='car'&&ownsVehicle(p,catalog,trip.vehicleId)?trip.vehicleId:null;p.activeTrip=null;p.energy=clamp(p.energy-3);break;}
        case 'take-job':check(typeof payload.jobId==='string'&&Object.hasOwn(jobs,payload.jobId),'Choose a listed job');check(!this.activeChallenge(id),'Finish your current shift before switching careers');p.job=payload.jobId;break;
        case 'start-shift':{const job=jobs[p.job];check(job,'Choose a job before starting a shift');publicPlace();check(p.district===job.district,`Travel to ${locations.get(job.district)?.name||job.district} for your shift`);const active=this.activeChallenge(id);if(active){extra.challenge=active;break;}check(timestamp>=p.nextShiftAt,'Take a moment between shifts',409,'shift_cooldown');check(p.energy>=job.energy,'Rest before starting another shift');const row={id:uid(),resident_id:id,job_id:p.job,started_at:timestamp};this.run('INSERT INTO challenges(id,resident_id,job_id,started_at) VALUES(?,?,?,?)',row.id,id,row.job_id,timestamp);extra.challenge=this.challengeView(row);p.activeShift=row.id;break;}
        case 'complete-shift':{const row=this.get('SELECT * FROM challenges WHERE id=? AND resident_id=?',clean(payload.challengeId,80),id);check(row,'Shift not found');if(row.completed_at){extra.result=JSON.parse(row.result);break;}const job=jobs[row.job_id];check(p.district===job.district&&p.location.kind==='public','Complete your shift at the workplace');check(timestamp-row.started_at>=1500,'Read the tasks before submitting your shift',409,'shift_too_fast');check(Array.isArray(payload.answers)&&payload.answers.length===job.tasks.length,'Answer each shift task');const answers=new Map(payload.answers.map(a=>[a.taskId,a.optionId]));check(answers.size===job.tasks.length&&job.tasks.every(t=>answers.has(t.id)&&t.options.some(o=>o.id===answers.get(t.id))),'Choose one valid answer for every task');const correct=job.tasks.filter(t=>answers.get(t.id)===t.answer).length,pay=Math.round(job.pay*(.4+.6*correct/job.tasks.length));p.wallet+=pay;p.energy=clamp(p.energy-job.energy);p.hunger=clamp(p.hunger-10);p.stress=clamp(p.stress+8);p.reputation+=correct===job.tasks.length?2:1;p.completedShifts++;p.skills[job.skill]=(p.skills[job.skill]||0)+correct;p.careerLevel=1+Math.floor(p.completedShifts/5);p.activeShift=null;p.nextShiftAt=timestamp+20000;extra.result={challengeId:row.id,pay,correct,total:job.tasks.length,careerLevel:p.careerLevel};this.run('UPDATE challenges SET completed_at=?,result=? WHERE id=?',timestamp,JSON.stringify(extra.result),row.id);break;}
        case 'work-shift':throw new GameError('Start a shift and complete its work tasks to earn your salary');
        case 'purchase':{const item=catalog.find(item=>item.id===payload.itemId);check(item,'Choose an item from City Market');check(!p.inventory.includes(item.id),'You already own this item',409);debit(item.price);p.inventory.push(item.id);extra.item=item;break;}
        case 'equip':{const item=catalog.find(item=>item.id===payload.itemId);check(item?.category==='clothing'&&p.inventory.includes(item.id),'You can wear clothing you own');p.appearance[item.slot]=item.value;break;}
        case 'move-home':{const property=properties.find(item=>item.id===payload.propertyId);check(property&&property.tier>0,'Choose a listed home');check(['rent','own'].includes(payload.tenure),'Choose rent or ownership');check(p.home.propertyId!==property.id||p.home.tenure!==payload.tenure,'You already live here');p.ownedProperties ||= [];debit(payload.tenure==='rent'?property.rent:p.ownedProperties.includes(property.id)?0:property.buy);if(payload.tenure==='own'&&!p.ownedProperties.includes(property.id))p.ownedProperties.push(property.id);p.home={propertyId:property.id,name:property.name,district:property.district,tenure:payload.tenure,rentDueAt:payload.tenure==='rent'?timestamp+GAME_YEAR_MS:null};if(p.district===property.district){p.drivingVehicle=null;p.location={kind:'home',district:p.district,venue:'home'};}else if(p.location.kind==='home')p.location={kind:'public',district:p.district,venue:'neighbourhood'};p.billsPaidAt=timestamp;p.rentPaidAt=timestamp;break;}
        case 'pay-bills':{check(timestamp-p.billsPaidAt>=GAME_BILL_PERIOD_MS,'Your home bills are up to date');const property=properties.find(item=>item.id===p.home.propertyId);debit(property.bills);p.billsPaidAt=timestamp;break;}
        case 'renew-rent':{check(p.home.tenure==='rent','Your home is not rented');check(timestamp-p.rentPaidAt>=GAME_YEAR_MS,'Your rent is already paid for this game year');const property=properties.find(item=>item.id===p.home.propertyId);debit(property.rent);p.rentPaidAt=timestamp;p.home.rentDueAt=timestamp+GAME_YEAR_MS;break;}
        case 'topup':throw new GameError('Money purchases are unavailable until a verified payment provider is connected',403,'payments_unavailable');
        default:throw new GameError('Unknown action');
      }
      p.lastActionAt=timestamp;this.save(p);if(p.wallet!==before)this.run('INSERT INTO ledger VALUES(?,?,?,?,?)',uid(),id,p.wallet-before,action,timestamp);return{ok:true,profile:p,...extra};
    });this.emitUser(id,'profile',{profile:result.profile});return result;
  }
  blocked(a,b){return Boolean(this.get("SELECT 1 FROM moderation WHERE kind='block' AND ((owner=? AND target=?) OR (owner=? AND target=?))",a,b,b,a));}
  muted(a,b){return Boolean(this.get("SELECT 1 FROM moderation WHERE kind='mute' AND owner=? AND target=?",a,b));}
  resident(viewer,id){const p=this.profile(id),visible=p.settings.presenceVisible&&(!viewer||!this.blocked(viewer,id));return{id,username:p.username,displayName:p.displayName,appearance:p.appearance,reputation:p.reputation,online:visible&&this.isOnline(id),district:visible?p.district:null,location:visible?p.location:null};}
  people(id){return this.all('SELECT id FROM residents WHERE id<>? ORDER BY created_at DESC LIMIT 200',id).filter(row=>!this.blocked(id,row.id)).map(row=>this.resident(id,row.id));}
  nearby(id){const p=this.profile(id);return p.location.kind==='public'?this.people(id).filter(person=>person.online&&person.district===p.district&&person.location?.kind==='public'):[];}
  friendIds(id){return this.all("SELECT sender,recipient FROM friendship WHERE status='accepted' AND (sender=? OR recipient=?)",id,id).map(row=>row.sender===id?row.recipient:row.sender).filter(target=>!this.blocked(id,target));}
  friends(id){return this.friendIds(id).map(target=>this.resident(id,target));}
  friendRequests(id){return this.all("SELECT * FROM friendship WHERE status='pending' AND (sender=? OR recipient=?) ORDER BY created_at DESC",id,id).filter(row=>!this.blocked(id,row.sender===id?row.recipient:row.sender)).map(row=>({id:row.id,from:row.sender,to:row.recipient,status:row.status,createdAt:row.created_at,resident:this.resident(id,row.sender===id?row.recipient:row.sender)}));}
  socialState(id){return{ok:true,friends:this.friends(id),friendRequests:this.friendRequests(id),conversations:this.conversations(id),notifications:this.notifications(id)};}
  requestFriend(id,target){check(target!==id,'You cannot send yourself a friend request');this.profile(target);check(!this.blocked(id,target),'This resident is unavailable',403);const existing=this.get('SELECT * FROM friendship WHERE (sender=? AND recipient=?) OR (sender=? AND recipient=?)',id,target,target,id);if(existing?.status==='accepted'||existing?.status==='pending')return this.socialState(id);const requestId=existing?.id||uid();if(existing)this.run("UPDATE friendship SET sender=?,recipient=?,status='pending',created_at=? WHERE id=?",id,target,this.clock(),requestId);else this.run("INSERT INTO friendship VALUES(?,?,?,'pending',?)",requestId,id,target,this.clock());this.notify(target,'friend-request','New friend request',`${this.profile(id).displayName} would like to connect.`,'friends',id);return this.socialState(id);}
  respondFriend(id,requestId,accept){check(typeof requestId==='string','Choose a friend request');const row=this.get("SELECT * FROM friendship WHERE id=? AND recipient=? AND status='pending'",requestId,id);check(row,'Friend request not found',404);check(!this.blocked(id,row.sender),'This resident is unavailable',403);this.run('UPDATE friendship SET status=? WHERE id=?',accept?'accepted':'declined',row.id);if(accept)this.notify(row.sender,'friend-accepted','Friend request accepted',`${this.profile(id).displayName} is now your friend.`,'friends',id);return this.socialState(id);}
  removeFriend(id,target){this.profile(target);this.run('DELETE FROM friendship WHERE (sender=? AND recipient=?) OR (sender=? AND recipient=?)',id,target,target,id);return this.socialState(id);}
  notify(id,kind,title,body,link=null,sender=null){if(sender&&this.muted(id,sender))return;const notice={id:uid(),kind,title,body,link,createdAt:this.clock(),readAt:null};this.run('INSERT INTO notifications(id,resident_id,kind,title,body,link,created_at,read_at,sender_id) VALUES(?,?,?,?,?,?,?,NULL,?)',notice.id,id,kind,title,body,link,notice.createdAt,sender);this.emitUser(id,'notification',notice);return notice;}
  notifications(id){return this.all('SELECT * FROM notifications WHERE resident_id=? ORDER BY created_at DESC LIMIT 100',id).filter(row=>!row.sender_id||!this.blocked(id,row.sender_id)).map(row=>({id:row.id,kind:row.kind,title:row.title,body:row.body,link:row.link,createdAt:row.created_at,readAt:row.read_at}));}
  readNotifications(id,noticeId){check(noticeId===undefined||typeof noticeId==='string','Choose a valid notification');if(noticeId)this.run('UPDATE notifications SET read_at=? WHERE resident_id=? AND id=?',this.clock(),id,noticeId);else this.run('UPDATE notifications SET read_at=? WHERE resident_id=? AND read_at IS NULL',this.clock(),id);return{ok:true,notifications:this.notifications(id)};}
  conversationAccess(id,conversationId){check(typeof conversationId==='string'&&conversationId.length>0,'Choose a conversation');const member=this.get('SELECT * FROM members WHERE resident_id=? AND conversation_id=?',id,conversationId);check(member,'Conversation not found',404);return member;}
  conversation(id,conversationId){const me=this.conversationAccess(id,conversationId),row=this.get('SELECT * FROM conversations WHERE id=?',conversationId),members=this.all('SELECT resident_id FROM members WHERE conversation_id=?',conversationId).map(row=>this.resident(id,row.resident_id));const visible="NOT EXISTS(SELECT 1 FROM moderation d WHERE d.kind='block' AND ((d.owner=? AND d.target=m.sender_id) OR (d.owner=m.sender_id AND d.target=?)))";const last=this.get(`SELECT m.* FROM messages m WHERE m.conversation_id=? AND ${visible} ORDER BY m.created_at DESC,m.id DESC LIMIT 1`,conversationId,id,id),unread=this.get(`SELECT count(*) n FROM messages m WHERE m.conversation_id=? AND m.sender_id<>? AND m.created_at>? AND ${visible}`,conversationId,id,me.read_at,id,id).n;return{id:row.id,kind:row.kind,name:row.kind==='dm'?(members.find(member=>member.id!==id)?.displayName||'Conversation'):row.name,members,unread,lastMessage:last?this.messageView(last):null};}
  conversations(id){return this.all('SELECT conversation_id FROM members WHERE resident_id=? ORDER BY joined_at DESC',id).map(row=>this.conversation(id,row.conversation_id)).filter(c=>c.kind!=='dm'||!c.members.some(member=>member.id!==id&&this.blocked(id,member.id)));}
  createConversation(id,body){const kind=body.kind==='group'?'group':'dm';let targets;if(kind==='dm'){const target=clean(body.residentId,80);check(target!==id,'Choose another resident');this.profile(target);check(!this.blocked(id,target),'This resident is unavailable',403);targets=[target];const existing=this.get("SELECT c.id FROM conversations c JOIN members a ON a.conversation_id=c.id JOIN members b ON b.conversation_id=c.id WHERE c.kind='dm' AND a.resident_id=? AND b.resident_id=?",id,target);if(existing)return{ok:true,conversation:this.conversation(id,existing.id)};}else{check(Array.isArray(body.memberIds)&&body.memberIds.length>=1&&body.memberIds.length<=20,'Choose 1–20 friends for your group');targets=[...new Set(body.memberIds)].filter(target=>target!==id);check(targets.length>0,'Choose another friend');const friends=this.friendIds(id);check(targets.every(target=>friends.includes(target)),'Group members must be accepted friends');check(clean(body.name,60).length>=2,'Give your group a name');}const conversationId=uid(),timestamp=this.clock();this.transaction(()=>{this.run('INSERT INTO conversations VALUES(?,?,?,?)',conversationId,kind,kind==='group'?clean(body.name,60):'',timestamp);for(const target of [id,...targets])this.run('INSERT INTO members(conversation_id,resident_id,joined_at) VALUES(?,?,?)',conversationId,target,timestamp);});if(kind==='group')for(const target of targets)this.notify(target,'group','New group',`${this.profile(id).displayName} added you to ${clean(body.name,60)}.`,`conversation:${conversationId}`,id);return{ok:true,conversation:this.conversation(id,conversationId)};}
  messageView(row){const members=this.all('SELECT * FROM members WHERE conversation_id=?',row.conversation_id);return{id:row.id,conversationId:row.conversation_id,senderId:row.sender_id,text:row.text,createdAt:row.created_at,deliveredTo:members.filter(m=>m.resident_id!==row.sender_id&&m.delivered_at>=row.created_at).map(m=>m.resident_id),readBy:members.filter(m=>m.resident_id!==row.sender_id&&m.read_at>=row.created_at).map(m=>m.resident_id)};}
  messages(id,conversationId){this.conversationAccess(id,conversationId);this.readConversation(id,conversationId);const rows=this.all('SELECT * FROM messages WHERE conversation_id=? ORDER BY created_at DESC,id DESC LIMIT 100',conversationId).reverse().filter(row=>!this.blocked(id,row.sender_id));return{ok:true,conversation:this.conversation(id,conversationId),messages:rows.map(row=>this.messageView(row))};}
  sendMessage(id,conversationId,text){this.conversationAccess(id,conversationId);text=clean(text,4000);check(text.length>0,'Write a message first');const members=this.all('SELECT resident_id FROM members WHERE conversation_id=?',conversationId).map(row=>row.resident_id),row=this.get('SELECT kind FROM conversations WHERE id=?',conversationId);check(row.kind!=='dm'||members.every(target=>target===id||!this.blocked(id,target)),'This conversation is unavailable',403);const latest=this.get('SELECT MAX(created_at) last FROM messages WHERE conversation_id=?',conversationId).last||0;const lastRead=this.get('SELECT MAX(read_at) last FROM members WHERE conversation_id=?',conversationId).last||0;const timestamp=Math.max(this.clock(),latest+1,lastRead+1),message={id:uid(),conversation_id:conversationId,sender_id:id,text,created_at:timestamp};this.run('INSERT INTO messages VALUES(?,?,?,?,?)',message.id,conversationId,id,text,timestamp);this.run('UPDATE members SET read_at=?,delivered_at=? WHERE resident_id=? AND conversation_id=?',timestamp,timestamp,id,conversationId);for(const target of members)if(target!==id&&!this.blocked(id,target)&&this.isOnline(target))this.run('UPDATE members SET delivered_at=? WHERE resident_id=? AND conversation_id=?',timestamp,target,conversationId);const view=this.messageView(message);for(const target of members)if(!this.blocked(id,target)){this.emitUser(target,'message',view);if(target!==id)this.notify(target,'message',this.profile(id).displayName,text.slice(0,140),`conversation:${conversationId}`,id);}return{ok:true,message:view};}
  readConversation(id,conversationId){this.conversationAccess(id,conversationId);const latest=this.get('SELECT MAX(created_at) last FROM messages WHERE conversation_id=?',conversationId).last||0;const timestamp=Math.max(this.clock(),latest);this.run('UPDATE members SET read_at=?,delivered_at=? WHERE resident_id=? AND conversation_id=?',timestamp,timestamp,id,conversationId);const receipt={conversationId,residentId:id,readAt:timestamp,receipt:true};for(const member of this.all('SELECT resident_id FROM members WHERE conversation_id=?',conversationId))if(!this.blocked(id,member.resident_id))this.emitUser(member.resident_id,'message',receipt);this.run('UPDATE notifications SET read_at=? WHERE resident_id=? AND link=? AND read_at IS NULL',timestamp,id,`conversation:${conversationId}`);return{ok:true};}
  delivered(id){for(const row of this.all('SELECT conversation_id FROM members WHERE resident_id=?',id)){const latest=this.get('SELECT MAX(created_at) last FROM messages WHERE conversation_id=?',row.conversation_id).last||0;const timestamp=Math.max(this.clock(),latest);this.run('UPDATE members SET delivered_at=? WHERE resident_id=? AND conversation_id=?',timestamp,id,row.conversation_id);for(const member of this.all('SELECT resident_id FROM members WHERE conversation_id=?',row.conversation_id))if(member.resident_id!==id&&!this.blocked(id,member.resident_id))this.emitUser(member.resident_id,'message',{conversationId:row.conversation_id,residentId:id,deliveredAt:timestamp,receipt:true});}}
  zone(id){const p=this.profile(id);return p.location.kind==='home'?`home:${id}`:p.location.kind==='public'?`district:${p.district}`:`transit:${id}`;}
  locationMessages(id){return{ok:true,messages:this.all('SELECT * FROM location_messages WHERE zone=? ORDER BY created_at DESC,id DESC LIMIT 60',this.zone(id)).reverse().filter(row=>!this.blocked(id,row.sender_id)).map(row=>({id:row.id,senderId:row.sender_id,resident:this.resident(id,row.sender_id),text:row.text,createdAt:row.created_at,zone:row.zone}))};}
  sendLocationMessage(id,text){check(this.profile(id).location.kind==='public','Neighbourhood chat is available when you head out');text=clean(text,2000);check(text.length>0,'Write a message first');const message={id:uid(),senderId:id,resident:this.resident(id,id),text,createdAt:this.clock(),zone:this.zone(id)};this.run('INSERT INTO location_messages VALUES(?,?,?,?,?)',message.id,message.zone,id,text,message.createdAt);this.emitZone(id,'location-chat',message);return{ok:true,message};}
  typing(id,conversationId){const event={residentId:id,displayName:this.profile(id).displayName,conversationId:conversationId||null,at:this.clock()};if(conversationId){this.conversationAccess(id,conversationId);for(const member of this.all('SELECT resident_id FROM members WHERE conversation_id=?',conversationId))if(member.resident_id!==id&&!this.blocked(id,member.resident_id))this.emitUser(member.resident_id,'typing',event);}else this.emitZone(id,'typing',event);return{ok:true};}
  moderate(id,kind,target,enabled){check(['block','mute'].includes(kind),'Invalid moderation control');check(target!==id,'Choose another resident');this.profile(target);if(enabled)this.run('INSERT OR IGNORE INTO moderation VALUES(?,?,?)',id,target,kind);else this.run('DELETE FROM moderation WHERE owner=? AND target=? AND kind=?',id,target,kind);return{ok:true,blocked:this.all("SELECT target FROM moderation WHERE owner=? AND kind='block'",id).map(row=>row.target),muted:this.all("SELECT target FROM moderation WHERE owner=? AND kind='mute'",id).map(row=>row.target)};}
  report(id,body){const reason=clean(body.reason,1000);check(reason.length>=5,'Tell us what happened');let target=null,messageId=null;if(body.residentId){this.profile(body.residentId);target=body.residentId;}if(body.messageId){const row=this.get('SELECT * FROM messages WHERE id=?',body.messageId);check(row,'Message not found',404);this.conversationAccess(id,row.conversation_id);messageId=row.id;target=row.sender_id;}check(target||messageId,'Choose a resident or message to report');const reportId=uid();this.run('INSERT INTO reports VALUES(?,?,?,?,?,?)',reportId,id,target,messageId,reason,this.clock());return{ok:true,reportId};}
  invitations(id){return this.all('SELECT * FROM invitations WHERE sender=? OR recipient=? ORDER BY created_at DESC LIMIT 100',id,id).filter(row=>!this.blocked(id,row.sender===id?row.recipient:row.sender)).map(row=>({id:row.id,from:row.sender,to:row.recipient,kind:row.kind,district:row.district,activity:row.activity,note:row.note,status:row.status,createdAt:row.created_at,resident:this.resident(id,row.sender===id?row.recipient:row.sender)}));}
  invite(id,body){const target=clean(body.residentId,80);check(target!==id,'Choose another resident');const p=this.profile(id),other=this.profile(target);check(other.settings.allowInvites&&!this.blocked(id,target),'This resident is not accepting invitations',403);check(['meetup','home','activity'].includes(body.kind),'Choose an invitation type');const district=body.kind==='home'?p.home.district:clean(body.district||p.district,80);check(locations.has(district),'Choose a location from the atlas');const inviteId=uid();this.run("INSERT INTO invitations VALUES(?,?,?,?,?,?,?,'pending',?)",inviteId,id,target,body.kind,district,clean(body.activity,60),clean(body.note,300),this.clock());const invitation=this.invitations(id).find(row=>row.id===inviteId);this.emitUser(target,'invitation',this.invitations(target).find(row=>row.id===inviteId));this.notify(target,'invitation','You are invited',`${p.displayName} sent you a ${body.kind} invitation.`,'invitations',id);return{ok:true,invitation};}
  respondInvite(id,inviteId,accept){check(typeof inviteId==='string','Choose an invitation');const row=this.get("SELECT * FROM invitations WHERE id=? AND recipient=? AND status='pending'",inviteId,id);check(row,'Invitation not found',404);check(!this.blocked(id,row.sender),'This invitation is unavailable',403);this.run('UPDATE invitations SET status=? WHERE id=?',accept?'accepted':'declined',inviteId);this.notify(row.sender,'invitation-response','Invitation update',`${this.profile(id).displayName} ${accept?'accepted':'declined'} your invitation.`,'invitations',id);return{ok:true,invitations:this.invitations(id)};}
  events(id){return this.all('SELECT * FROM events WHERE starts_at>? ORDER BY starts_at LIMIT 100',this.clock()-86400000).filter(row=>!this.blocked(id,row.host_id)).map(row=>({id:row.id,host:this.resident(id,row.host_id),title:row.title,district:row.district,startsAt:row.starts_at,description:row.description,attendeeIds:this.all('SELECT resident_id FROM rsvps WHERE event_id=?',row.id).map(m=>m.resident_id)}));}
  createEvent(id,body){const title=clean(body.title,80),district=clean(body.district,80),startsAt=Number(body.startsAt);check(title.length>=3,'Give your event a title');check(locations.has(district),'Choose a location from the atlas');check(Number.isSafeInteger(startsAt)&&startsAt>this.clock()&&startsAt<this.clock()+90*86400000,'Choose a future event time within 90 days');const eventId=uid();this.transaction(()=>{this.run('INSERT INTO events VALUES(?,?,?,?,?,?,?)',eventId,id,title,district,startsAt,clean(body.description,600),this.clock());this.run('INSERT INTO rsvps VALUES(?,?)',eventId,id);});return{ok:true,event:this.events(id).find(event=>event.id===eventId)};}
  rsvp(id,eventId,attending){const row=this.get('SELECT * FROM events WHERE id=?',eventId);check(row,'Event not found',404);check(!this.blocked(id,row.host_id),'This event is unavailable',403);if(attending)this.run('INSERT OR IGNORE INTO rsvps VALUES(?,?)',eventId,id);else this.run('DELETE FROM rsvps WHERE event_id=? AND resident_id=?',eventId,id);return{ok:true,events:this.events(id)};}
  bootstrap(id){return{authenticated:true,profile:this.profile(id),activeChallenge:this.activeChallenge(id),people:this.people(id),friends:this.friends(id),friendRequests:this.friendRequests(id),conversations:this.conversations(id),notifications:this.notifications(id),invitations:this.invitations(id),nearby:this.nearby(id),events:this.events(id),blocked:this.all("SELECT target FROM moderation WHERE owner=? AND kind='block'",id).map(row=>row.target),muted:this.all("SELECT target FROM moderation WHERE owner=? AND kind='mute'",id).map(row=>row.target),transactions:this.all('SELECT * FROM ledger WHERE resident_id=? ORDER BY created_at DESC LIMIT 60',id).map(row=>({id:row.id,amount:row.amount,reason:row.reason,createdAt:row.created_at}))};}
}
