import crypto from 'node:crypto';
import { GameError } from './gameStore.mjs';
import { isProviderPath, isTransactionId, verifyFlutterwaveOrder } from './flutterwaveVerification.mjs';

const PROVIDER_ORIGIN = 'https://api.flutterwave.com';
const fail = (condition,message,status=400,code='invalid_payment') => { if (!condition) throw new GameError(message,status,code); };
const uuid = () => crypto.randomUUID();
const clean = (value,max=200) => typeof value==='string'?value.trim().slice(0,max):'';
const requestKey = key => typeof key==='string' && /^[A-Za-z0-9_-]{8,100}$/.test(key);
const paymentView = row => ({txRef:row.tx_ref,status:row.status,amount:row.amount,currency:'NGN',credits:row.credits,mode:row.mode,checkoutUrl:row.checkout_url||null,transactionId:row.transaction_id||null,createdAt:row.created_at,creditedAt:row.credited_at||null});
function encryptionKey(value) { if (!value) return null;const key=/^[a-f\d]{64}$/i.test(value)?Buffer.from(value,'hex'):Buffer.from(value,'base64');fail(key.length===32,'ABUJALIFE_CONFIG_KEY must contain a 32-byte key encoded as hex or base64',503,'config_key_required');return key; }
function publicOrigin(value) { try { const url=new URL(value); fail(url.protocol==='https:'&&!url.username&&!url.password&&url.pathname==='/'&&!url.search&&!url.hash,'Use the HTTPS origin of this AbujaLife deployment');fail(!['localhost','127.0.0.1','::1','0.0.0.0'].includes(url.hostname),'Use a public HTTPS deployment origin');return url.origin; } catch(error) { if(error instanceof GameError)throw error;throw new GameError('Use the HTTPS origin of this AbujaLife deployment'); } }
const mask = secret => secret ? `••••${secret.slice(-4)}` : null;

/** Provider secrets never leave the server. Verified credits and payment state
 * share one SQLite transaction with the existing authoritative game ledger. */
export class PaymentStore {
  constructor({store,admin,fetchImpl=fetch,configKey=process.env.ABUJALIFE_CONFIG_KEY,publicOrigin:origin=process.env.ABUJALIFE_PUBLIC_ORIGIN||''}={}) {
    fail(store?.db&&admin,'Game and administrator stores are required',500);this.store=store;this.admin=admin;this.fetch=fetchImpl;this.key=encryptionKey(configKey);this.origin=origin?publicOrigin(origin):'';this.clock=()=>store.clock();
    store.db.exec(`CREATE TABLE IF NOT EXISTS payment_config(mode TEXT PRIMARY KEY,enabled INTEGER NOT NULL,credit_rate INTEGER NOT NULL,public_origin TEXT NOT NULL,secrets TEXT NOT NULL,updated_at INTEGER NOT NULL);
      CREATE TABLE IF NOT EXISTS payment_orders(tx_ref TEXT PRIMARY KEY,resident_id TEXT NOT NULL REFERENCES residents(id),operation_key TEXT NOT NULL,fingerprint TEXT NOT NULL,amount INTEGER NOT NULL,credits INTEGER NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL,checkout_url TEXT,transaction_id TEXT UNIQUE,encrypted_secret TEXT NOT NULL,created_at INTEGER NOT NULL,credited_at INTEGER,UNIQUE(resident_id,operation_key));
      CREATE TABLE IF NOT EXISTS payment_preferences(key TEXT PRIMARY KEY,value TEXT NOT NULL);
      CREATE INDEX IF NOT EXISTS payment_orders_resident_page ON payment_orders(resident_id,created_at DESC,tx_ref DESC);
      CREATE INDEX IF NOT EXISTS payment_orders_admin_page ON payment_orders(created_at DESC,tx_ref DESC);`);
  }
  encrypt(value,scope) { fail(this.key,'Set ABUJALIFE_CONFIG_KEY on the server before saving provider credentials',503,'config_key_required');const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',this.key,iv);cipher.setAAD(Buffer.from('abujalife-payments:'+scope));const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return JSON.stringify({v:1,iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),body:body.toString('base64')}); }
  decrypt(value,scope) { fail(this.key,'Payment encryption key is unavailable',503,'config_key_required');try {const stored=JSON.parse(value),decipher=crypto.createDecipheriv('aes-256-gcm',this.key,Buffer.from(stored.iv,'base64'));fail(stored.v===1,'Unsupported payment configuration');decipher.setAAD(Buffer.from('abujalife-payments:'+scope));decipher.setAuthTag(Buffer.from(stored.tag,'base64'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(stored.body,'base64')),decipher.final()]).toString());}catch{throw new GameError('Payment credentials could not be decrypted; check the server configuration key',503,'config_key_mismatch');} }
  activeMode() { return this.store.get("SELECT value FROM payment_preferences WHERE key='active-mode'")?.value||'test'; }
  config(mode=this.activeMode()) { const row=this.store.get('SELECT * FROM payment_config WHERE mode=?',mode);return row?{...row,secrets:this.decrypt(row.secrets,'config:'+mode)}:null; }
  publicConfig() { let config;try{config=this.config();}catch{return{ok:true,enabled:false,provider:'Flutterwave',mode:this.activeMode(),currency:'NGN',creditRate:1,reason:'Payments need server configuration'};}const enabled=Boolean(config?.enabled&&config.secrets.secretKey&&config.public_origin&&this.key);return{ok:true,enabled,provider:'Flutterwave',mode:this.activeMode(),currency:'NGN',creditRate:config?.credit_rate||1,minAmount:1,maxAmount:Math.floor(Number.MAX_SAFE_INTEGER/(config?.credit_rate||1)),...(enabled?{}:{reason:'An administrator must configure Flutterwave on this deployment before payments are available'})}; }
  adminConfig(id) { this.admin.requirePermission(id,'payments');const modes={};for(const mode of ['test','live']){let c;try{c=this.config(mode);}catch{modes[mode]={configured:false,readiness:'Server encryption key does not match stored credentials'};continue;}modes[mode]={configured:Boolean(c?.secrets.secretKey),enabled:Boolean(c?.enabled),creditRate:c?.credit_rate||1,publicOrigin:c?.public_origin||this.origin,secretKey:mask(c?.secrets.secretKey),webhookSecret:mask(c?.secrets.webhookSecret),updatedAt:c?.updated_at||null};}return{ok:true,provider:'Flutterwave',activeMode:this.activeMode(),encryptionReady:Boolean(this.key),modes,webhook:{header:'flutterwave-signature',algorithm:'HMAC-SHA256',encoding:'base64',verification:'Every webhook payment is verified through the Flutterwave transaction API before credit'},liveVerified:false}; }
  configure(id,body) { this.admin.requirePermission(id,'payments');fail(body&&typeof body==='object'&&!Array.isArray(body),'Use payment configuration');const allowed=['mode','enabled','creditRate','publicOrigin','secretKey','webhookSecret','activate'];fail(Object.keys(body).every(key=>allowed.includes(key)),'Choose supported payment configuration fields');const mode=body.mode;fail(['test','live'].includes(mode),'Choose test or live mode');const old=this.config(mode),creditRate=body.creditRate??old?.credit_rate??1;fail(Number.isSafeInteger(creditRate)&&creditRate>0,'Choose a positive whole credit rate');const enabled=body.enabled??Boolean(old?.enabled),origin=publicOrigin(body.publicOrigin||old?.public_origin||this.origin);fail(typeof enabled==='boolean'&&(body.activate===undefined||typeof body.activate==='boolean'),'Use boolean payment settings');const secretKey=body.secretKey===undefined?old?.secrets.secretKey:clean(body.secretKey,500),webhookSecret=body.webhookSecret===undefined?old?.secrets.webhookSecret:clean(body.webhookSecret,500);fail(!enabled||secretKey,'A Flutterwave secret key is required to enable checkout');fail(!secretKey||/^FLWSECK[-_][A-Za-z0-9_-]+$/i.test(secretKey),'Use a Flutterwave secret key');if(secretKey){const isTest=secretKey.toUpperCase().includes('TEST');fail(mode==='test'?isTest:!isTest,'The secret key does not match the selected test/live mode');}fail(!webhookSecret||webhookSecret.length>=16,'Use a webhook signing secret of at least 16 characters');const sealed=this.encrypt({secretKey:secretKey||'',webhookSecret:webhookSecret||''},'config:'+mode);this.store.transaction(()=>{this.store.run('INSERT INTO payment_config VALUES(?,?,?,?,?,?) ON CONFLICT(mode) DO UPDATE SET enabled=excluded.enabled,credit_rate=excluded.credit_rate,public_origin=excluded.public_origin,secrets=excluded.secrets,updated_at=excluded.updated_at',mode,Number(enabled),creditRate,origin,sealed,this.clock());if(body.activate)this.store.run("INSERT INTO payment_preferences VALUES('active-mode',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",mode);this.admin.record(id,'configure-payments',null,{mode,enabled,creditRate,publicOrigin:origin,secretKeyChanged:body.secretKey!==undefined,webhookSecretChanged:body.webhookSecret!==undefined,activated:Boolean(body.activate)});});return this.adminConfig(id); }
  async provider(path,secretKey,options={}) { fail(isProviderPath(path),'Unsupported provider request',500);let response,data;try{response=await this.fetch(PROVIDER_ORIGIN+path,{...options,redirect:'error',headers:{'content-type':'application/json','authorization':`Bearer ${secretKey}`,...options.headers},signal:AbortSignal.timeout(20000)});data=await response.json();}catch{throw new GameError('Flutterwave could not be reached. No payment has been credited',502,'provider_unavailable');}fail(response.ok&&data.status==='success','Flutterwave could not confirm this request. No payment has been credited',502,'provider_rejected');return data.data; }
  async checkout(id,{amount,email,idempotencyKey}={}) { fail(!this.admin.isSuspended(id),'This account is suspended',403,'account_suspended');this.store.profile(id);fail(requestKey(idempotencyKey),'Use a valid payment request key');const config=this.config();fail(config?.enabled&&config.secrets.secretKey&&config.public_origin,'Payments are not configured on this deployment',503,'payments_unavailable');fail(Number.isSafeInteger(amount)&&amount>0&&Number.isSafeInteger(amount*config.credit_rate),'Enter a positive whole Naira amount within the safe numeric range');email=clean(email,254);fail(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Enter your payment receipt email');const credits=amount*config.credit_rate,fingerprint=JSON.stringify({amount,email});let existing=false;const row=this.store.transaction(()=>{const old=this.store.get('SELECT * FROM payment_orders WHERE resident_id=? AND operation_key=?',id,idempotencyKey);if(old){fail(old.fingerprint===fingerprint,'This payment key was already used for a different checkout',409,'idempotency_conflict');existing=true;return old;}const wallet=this.store.profile(id).wallet;fail(Number.isSafeInteger(wallet)&&wallet>=0&&BigInt(wallet)+BigInt(credits)<=BigInt(Number.MAX_SAFE_INTEGER),'This checkout would exceed the safe numeric wallet range',409,'wallet_limit');const txRef='abjl_'+uuid(),sealed=this.encrypt({secretKey:config.secrets.secretKey},'order:'+txRef);this.store.run('INSERT INTO payment_orders VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',txRef,id,idempotencyKey,fingerprint,amount,credits,config.mode,'creating',null,null,sealed,this.clock(),null);return this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',txRef);});if(existing){fail(row.status!=='creating','This checkout is being created. Check its status before retrying',409,'checkout_processing');fail(row.checkout_url,'The checkout could not be created. Start a new payment request',502,'checkout_failed');return{ok:true,checkout:paymentView(row),replayed:true};}
    try{const profile=this.store.profile(id),data=await this.provider('/v3/payments',config.secrets.secretKey,{method:'POST',body:JSON.stringify({tx_ref:row.tx_ref,amount,currency:'NGN',redirect_url:`${config.public_origin}/?payment_ref=${encodeURIComponent(row.tx_ref)}`,customer:{email,name:profile.displayName},customizations:{title:'AbujaLife',description:`${credits.toLocaleString()} game Naira`},meta:{abujalife_reference:row.tx_ref}})});let link;try{link=new URL(data.link);}catch{throw new GameError('Flutterwave returned an invalid checkout link',502,'invalid_checkout');}fail(link.protocol==='https:'&&(link.hostname==='checkout.flutterwave.com'||link.hostname.endsWith('.flutterwave.com'))&&!link.username&&!link.password,'Flutterwave returned an untrusted checkout link',502,'invalid_checkout');this.store.run("UPDATE payment_orders SET status=CASE WHEN status='creating' THEN 'pending' ELSE status END,checkout_url=? WHERE tx_ref=?",link.href,row.tx_ref);return{ok:true,checkout:paymentView(this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',row.tx_ref)),replayed:false};}catch(error){this.store.run("UPDATE payment_orders SET status='checkout_failed' WHERE tx_ref=? AND status='creating'",row.tx_ref);throw error;}
  }
  status(id,txRef) { const row=this.store.get('SELECT * FROM payment_orders WHERE tx_ref=? AND resident_id=?',clean(txRef,80),id);fail(row,'Payment not found',404,'payment_not_found');return{ok:true,payment:paymentView(row)}; }
  async verifiedOrder(transactionId,txRef,id=null) {
    transactionId=String(transactionId??'');fail(!transactionId||isTransactionId(transactionId),'Use the Flutterwave transaction ID',400,'invalid_transaction');
    let order=txRef?this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',clean(txRef,80)):null;
    if(txRef)fail(order,'Payment not found',404,'payment_not_found');
    fail(!id||!order||order.resident_id===id,'Payment not found',404,'payment_not_found');
    if(!order){fail(isTransactionId(transactionId),'Use your saved checkout reference',400,'invalid_transaction');const secrets=this.config()?.secrets;fail(secrets?.secretKey,'Payments are not configured',503,'payments_unavailable');const data=await this.provider(`/v3/transactions/${transactionId}/verify`,secrets.secretKey);order=this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',String(data?.tx_ref||''));}
    fail(order&&(!id||order.resident_id===id),'Payment not found',404,'payment_not_found');
    const confirmed=await verifyFlutterwaveOrder(this,{transactionId,txRef:order.tx_ref,amount:order.amount,secretKey:this.decrypt(order.encrypted_secret,'order:'+order.tx_ref).secretKey});
    return{order,...confirmed};
  }
  creditVerified({order,data,transactionId},actor='provider') { let replayed=false;const result=this.store.transaction(()=>{const current=this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',order.tx_ref);if(current.status==='credited'){fail(current.transaction_id===transactionId,'This checkout was already credited using another transaction',409,'payment_duplicate');replayed=true;return{ok:true,payment:paymentView(current),profile:this.store.profile(current.resident_id)};}fail(!this.store.get('SELECT tx_ref FROM payment_orders WHERE transaction_id=? AND tx_ref<>?',transactionId,current.tx_ref),'This provider transaction has already been credited',409,'payment_duplicate');const profile=this.store.profile(current.resident_id);fail(Number.isSafeInteger(profile.wallet)&&profile.wallet>=0&&Number.isSafeInteger(current.credits)&&current.credits>0&&BigInt(profile.wallet)+BigInt(current.credits)<=BigInt(Number.MAX_SAFE_INTEGER),'This credit would exceed the safe numeric wallet range',409,'wallet_limit');profile.wallet+=current.credits;this.store.save(profile);const creditedAt=this.clock();this.store.run('INSERT INTO ledger VALUES(?,?,?,?,?)',uuid(),profile.id,current.credits,`Verified Flutterwave ${current.mode} payment · ${current.tx_ref}`,creditedAt);this.store.run("UPDATE payment_orders SET status='credited',transaction_id=?,credited_at=? WHERE tx_ref=?",transactionId,creditedAt,current.tx_ref);this.admin.record(actor,'credit-verified-payment',profile.id,{txRef:current.tx_ref,transactionId,mode:current.mode,amount:current.amount,credits:current.credits});return{ok:true,payment:paymentView(this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',current.tx_ref)),profile};});if(!replayed)this.store.emitUser(result.profile.id,'profile',{profile:result.profile});return{...result,replayed}; }
  async verify(id,{transactionId,txRef}={}) { fail(!this.admin.isSuspended(id),'This account is suspended',403,'account_suspended');this.store.profile(id);return this.creditVerified(await this.verifiedOrder(transactionId,txRef,id),id); }
  async handleWebhook(rawBody,signature) { fail(Buffer.isBuffer(rawBody)&&rawBody.length<=65536,'Invalid webhook body');fail(typeof signature==='string'&&/^[A-Za-z0-9+/]{43}=$/.test(signature),'Invalid Flutterwave webhook signature',401,'invalid_webhook_signature');const supplied=Buffer.from(signature,'base64'),matched=[];for(const mode of ['test','live']){let config;try{config=this.config(mode);}catch{continue;}if(config?.secrets.webhookSecret){const expected=crypto.createHmac('sha256',config.secrets.webhookSecret).update(rawBody).digest();if(supplied.length===expected.length&&crypto.timingSafeEqual(supplied,expected))matched.push(mode);}}fail(matched.length,'Invalid Flutterwave webhook signature',401,'invalid_webhook_signature');let body;try{body=JSON.parse(rawBody.toString('utf8'));}catch{throw new GameError('Invalid webhook JSON');}if(body.event!=='charge.completed')return{ok:true,ignored:true};const txRef=body.data?.tx_ref,order=this.store.get('SELECT * FROM payment_orders WHERE tx_ref=?',clean(txRef,80));if(!order)return{ok:true,ignored:true};fail(matched.includes(order.mode),'Webhook signing mode does not match the payment',401,'invalid_webhook_signature');return this.creditVerified(await this.verifiedOrder(body.data?.id,txRef),'flutterwave-webhook'); }
  list(id,{cursor,limit=30}={}) { this.admin.requirePermission(id,'payments');const size=Math.max(1,Math.min(100,Number.isSafeInteger(Number(limit))?Number(limit):30));let page=null;if(cursor){try{page=JSON.parse(Buffer.from(cursor,'base64url').toString());}catch{throw new GameError('Invalid page cursor');}fail(Array.isArray(page)&&page.length===2&&Number.isSafeInteger(page[0])&&typeof page[1]==='string','Invalid page cursor');}const rows=this.store.all(`SELECT * FROM payment_orders ${page?'WHERE created_at<? OR (created_at=? AND tx_ref<?)':''} ORDER BY created_at DESC,tx_ref DESC LIMIT ?`,...(page?[page[0],page[0],page[1]]:[]),size+1),more=rows.length>size;rows.length=Math.min(rows.length,size);return{ok:true,payments:rows.map(row=>({...paymentView(row),residentId:row.resident_id})),nextCursor:more?Buffer.from(JSON.stringify([rows.at(-1).created_at,rows.at(-1).tx_ref])).toString('base64url'):null}; }
  async adminVerify(id,body) { this.admin.requirePermission(id,'payments');return this.creditVerified(await this.verifiedOrder(body.transactionId,body.txRef),id); }
}
