import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { GameStore } from '../src/server/gameStore.mjs';
import { AdminStore } from '../src/server/adminStore.mjs';

async function fixture(t) { const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'abujalife-admin-test-'));const store=new GameStore({dataDir});t.after(()=>{store.close();fs.rmSync(dataDir,{recursive:true,force:true});});const owner=await store.register({username:'owner_admin',displayName:'Owner',password:'Local fixture password 123!'});const resident=await store.register({username:'resident_beta',displayName:'Resident',password:'Local fixture password 123!'});const admin=new AdminStore({store,bootstrapUsername:'owner_admin'});return{store,admin,owner:owner.residentId,resident:resident.residentId,residentToken:resident.token,initialWallet:store.profile(resident.residentId).wallet}; }

test('admin bootstrap binds only an existing resident, never a later username claimant',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'abujalife-admin-bootstrap-'));const store=new GameStore({dataDir:dir});t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});const admin=new AdminStore({store,bootstrapUsername:'future_owner'});const account=await store.register({username:'future_owner',password:'Local fixture password 123!'});assert.equal(admin.status(account.residentId).role,null);assert.throws(()=>admin.requirePermission(account.residentId,'payments'),{status:403});assert.equal(store.get('SELECT COUNT(*) count FROM admin_roles').count,0);});

test('roles enforce server permissions and preserve an active super administrator',async t=>{const f=await fixture(t);assert.equal(f.admin.status(f.owner).role,'superadmin');assert.throws(()=>f.admin.assignRole(f.resident,{residentId:f.resident,role:'superadmin'}),{status:403});assert.throws(()=>f.admin.assignRole(f.owner,{residentId:f.owner,role:null}),{code:'last_superadmin'});f.admin.assignRole(f.owner,{residentId:f.resident,role:'moderator'});f.admin.requirePermission(f.resident,'moderation');assert.throws(()=>f.admin.requirePermission(f.resident,'finance'),{status:403});assert.throws(()=>f.admin.setSuspension(f.resident,{residentId:f.owner,suspended:true,reason:'Attempted administrator suspension'}),{status:403});});

test('audited wallet adjustments are safe, idempotent and cannot debit below zero',async t=>{const f=await fixture(t);const input={residentId:f.resident,amount:200000000,reason:'Approved administrative fixture credit',idempotencyKey:'admin_credit_key_001'};const first=f.admin.adjustWallet(f.owner,input);assert.equal(first.profile.wallet,(f.initialWallet+200000000));assert.equal(first.replayed,false);const replay=f.admin.adjustWallet(f.owner,input);assert.equal(replay.profile.wallet,first.profile.wallet);assert.equal(replay.replayed,true);assert.equal(f.store.transactions(f.resident).filter(row=>row.reason.includes('administrative fixture credit')).length,1);assert.throws(()=>f.admin.adjustWallet(f.owner,{...input,amount:10}),{code:'idempotency_conflict'});assert.throws(()=>f.admin.adjustWallet(f.owner,{...input,amount:-(f.initialWallet+200000001),idempotencyKey:'admin_bad_debit_001'}),{code:'wallet_limit'});assert.throws(()=>f.admin.adjustWallet(f.owner,{...input,amount:Number.MAX_SAFE_INTEGER,idempotencyKey:'admin_unsafe_credit_001'}),{code:'wallet_limit'});assert.equal(f.store.profile(f.resident).wallet,(f.initialWallet+200000000));const audit=f.admin.audit(f.owner);assert.equal(audit.audit.filter(row=>row.action==='adjust-wallet').length,1);});

test('suspension revokes active sessions, respects roles and records restoration',async t=>{const f=await fixture(t);assert.equal(f.store.session(f.residentToken),f.resident);f.admin.setSuspension(f.owner,{residentId:f.resident,suspended:true,reason:'Repeated abusive behavior in fixture'});assert.equal(f.admin.isSuspended(f.resident),true);assert.equal(f.store.session(f.residentToken),null);assert.throws(()=>f.admin.setSuspension(f.owner,{residentId:f.owner,suspended:true,reason:'Invalid last administrator suspension'}),{code:'last_superadmin'});f.admin.setSuspension(f.owner,{residentId:f.resident,suspended:false,reason:'Moderation review completed in fixture'});assert.equal(f.admin.isSuspended(f.resident),false);assert.equal(f.store.session(f.residentToken),null);assert.equal(f.admin.audit(f.owner).audit.filter(row=>row.target_id===f.resident).length,2);});

test('resident keyset pages have no duplication and username prefix search stays bounded',async t=>{const f=await fixture(t);for(const username of ['resident_alpha','resident_gamma','zeta_resident'])await f.store.register({username,password:'Local fixture password 123!'});const first=f.admin.residents(f.owner,{query:'resident_',limit:2});assert.deepEqual(first.residents.map(r=>r.username),['resident_alpha','resident_beta']);assert.ok(first.nextCursor);const second=f.admin.residents(f.owner,{query:'resident_',limit:2,cursor:first.nextCursor});assert.deepEqual(second.residents.map(r=>r.username),['resident_gamma']);assert.equal(second.nextCursor,null);assert.throws(()=>f.admin.residents(f.owner,{cursor:'not_json'}));assert.throws(()=>f.admin.residents(f.resident,{}),{status:403});assert.ok(!JSON.stringify(first).includes('password'));});

test('moderation report review preserves the source report and writes an audit trail',async t=>{const f=await fixture(t);const report=f.store.report(f.resident,{residentId:f.owner,reason:'Fixture report explains concerning behavior'});const row=f.admin.reports(f.owner).reports[0];assert.equal(row.status,'open');f.admin.reviewReport(f.owner,{reportId:row.id,status:'resolved',note:'Reviewed the original report and resolved'});assert.equal(f.admin.reports(f.owner).reports[0].status,'resolved');assert.equal(f.store.get('SELECT reason FROM reports WHERE id=?',row.id).reason,'Fixture report explains concerning behavior');assert.equal(f.admin.overview(f.owner).stats.openReports,0);assert.ok(report.ok);});

test('game setting writes reject unknown fields and persist through restart',async t=>{const f=await fixture(t);assert.equal(f.admin.publicSettings().gameTopupsEnabled,false);assert.throws(()=>f.admin.saveSettings(f.owner,{wallet:999999}));f.admin.saveSettings(f.owner,{registrationOpen:false,maintenance:true});const restartedAdmin=new AdminStore({store:f.store});assert.equal(restartedAdmin.publicSettings().registrationOpen,false);assert.equal(restartedAdmin.publicSettings().maintenance,true);assert.equal(restartedAdmin.status(f.owner).role,'superadmin');assert.throws(()=>f.admin.settings(f.resident),{status:403});});
