import crypto from 'node:crypto';
import { GameError } from '../errors.mjs';

const uid = () => crypto.randomUUID();
const DEFAULT_ID = 'share-abuja-life';
const DEFAULT_REWARD = 100000;
const SESSION_TTL = 15 * 60 * 1000;
const clean = (value, max = 240) => String(value ?? '').trim().slice(0, max);
const check = (condition, message, status = 400, code = 'invalid_request') => { if (!condition) throw new GameError(message, status, code); };

export const MONGO_REWARD_INDEXES = Object.freeze({
  reward_campaigns: [[{ id: 1 }, { unique: true }]],
  reward_share_sessions: [[{ residentId: 1, createdAt: -1 }, {}], [{ residentId: 1, campaignId: 1, status: 1 }, {}], [{ expiresAt: 1 }, { expireAfterSeconds: 0 }]],
  reward_claims: [[{ campaignId: 1, residentId: 1 }, { unique: true }], [{ campaignId: 1, shareSessionId: 1 }, { unique: true }], [{ residentId: 1, createdAt: -1 }, {}]]
});

export async function ensureMongoRewardSchema(db) {
  const now = Date.now();
  await db.collection('reward_campaigns').updateOne({ id: DEFAULT_ID }, { $setOnInsert: { _id: DEFAULT_ID, id: DEFAULT_ID, title: 'Share AbujaLife', description: 'Share AbujaLife with your people.', rewardGameNaira: DEFAULT_REWARD, enabled: true, startAt: null, endAt: null, maxClaims: 1, shareText: 'I am building my life in AbujaLife 👀 Join me in AbujaLife. 🏙️ abujacity.life', shareUrl: 'https://abujacity.life/', createdAt: now, updatedAt: now } }, { upsert: true });
  await db.collection('reward_activity_definitions').updateOne({ id: 'gym-workout' }, { $setOnInsert: { _id: 'gym-workout', id: 'gym-workout', title: 'Gym workout', description: 'Complete a focused workout at Neighbourhood Fitness.', venueId: 'gym', rewardGameNaira: 5000, durationMs: 5 * 60 * 1000, cooldownMs: 60 * 60 * 1000, enabled: true } }, { upsert: true });
  return true;
}

export class MongoRewardStore {
  constructor({ store, admin, publicWebUrl = 'https://abujacity.life' } = {}) { check(store?.db && store.economyOperation, 'Reward storage is unavailable', 500, 'rewards_unavailable'); this.store = store; this.admin = admin; this.publicWebUrl = publicWebUrl.replace(/\/$/, ''); }
  collection(name) { return this.store.collection(name); }
  active(row, now = this.store.clock()) { return row && row.enabled === true && (row.startAt == null || now >= row.startAt) && (row.endAt == null || now <= row.endAt); }
  view(row, claimed = false) { return { id: row.id, title: row.title, description: row.description, rewardGameNaira: row.rewardGameNaira, maxClaims: row.maxClaims, shareText: row.shareText, shareUrl: row.shareUrl, startsAt: row.startAt, endsAt: row.endAt, enabled: row.enabled === true, claimed }; }
  claimView(row) { return { id: row.id, campaignId: row.campaignId, rewardGameNaira: row.rewardGameNaira, createdAt: row.createdAt }; }
  async campaigns(residentId) { const rows = await this.collection('reward_campaigns').find({}).sort({ createdAt: 1 }).toArray(); const claims = residentId ? await this.collection('reward_claims').find({ residentId, campaignId: { $in: rows.map(row => row.id) } }).project({ campaignId: 1 }).toArray() : []; const claimed = new Set(claims.map(row => row.campaignId)); return { ok: true, campaigns: rows.map(row => this.view(row, claimed.has(row.id))) }; }
  async earnOverview(residentId) { const profile = await this.store.profile(residentId), activities = await this.collection('reward_activity_definitions').find({ enabled: true }).toArray(); return { ok: true, balance: profile.wallet, jobs: this.store.publicJobs(), activities: activities.map(row => ({ id: row.id, title: row.title, description: row.description, venueId: row.venueId, rewardGameNaira: row.rewardGameNaira, durationMs: row.durationMs, cooldownMs: row.cooldownMs })), campaigns: (await this.campaigns(residentId)).campaigns, recommendations: [{ type: 'job', title: 'Complete a job shift', rewardHint: 'Career payout' }, { type: 'activity', title: activities[0]?.title || 'Explore a venue', rewardGameNaira: activities[0]?.rewardGameNaira || 5000 }, { type: 'share', title: 'Share AbujaLife', rewardGameNaira: DEFAULT_REWARD }] }; }
  async startActivity(residentId, body = {}) { const activityId = clean(body.activityId, 80), row = await this.collection('reward_activity_definitions').findOne({ id: activityId, enabled: true }); check(row, 'Choose an available activity', 404, 'activity_not_found'); const profile = await this.store.profile(residentId); check(!row.venueId || profile.location?.venue === row.venueId, 'Be inside the activity venue before starting', 409, 'activity_location_required'); const now = this.store.clock(), last = await this.collection('reward_activity_claims').findOne({ residentId, activityId }, { sort: { createdAt: -1 } }); check(!last || now - last.createdAt >= row.cooldownMs, 'Try a different activity for a while; this reward is cooling down', 409, 'activity_cooldown'); const session = { _id: uid(), id: uid(), residentId, activityId, startedAt: now, readyAt: now + row.durationMs, expiresAt: new Date(now + row.durationMs + 10 * 60 * 1000), status: 'started', completedAt: null }; session.id = session._id; await this.collection('reward_activity_sessions').insertOne(session); return { ok: true, activity: { id: row.id, title: row.title, rewardGameNaira: row.rewardGameNaira, readyAt: session.readyAt, expiresAt: session.expiresAt.valueOf() }, activitySessionId: session.id }; }
  async completeActivity(residentId, body = {}) { const sessionId = clean(body.activitySessionId, 80), session = await this.collection('reward_activity_sessions').findOne({ id: sessionId, residentId }); check(session, 'Activity session was not found', 404, 'activity_session_not_found'); const key = `activity-reward-${session.id}`; return this.store.economyOperation(residentId, 'activity-reward', { idempotencyKey: key }, { activityId: session.activityId, activitySessionId: session.id }, async (profile, timestamp, mongoSession) => { const current = await this.collection('reward_activity_sessions').findOne({ id: session.id, residentId }, { session: mongoSession }); check(current?.status === 'started', 'This activity has already been settled', 409, 'activity_already_settled'); check(timestamp >= current.readyAt, 'Keep going until the activity is complete', 409, 'activity_not_complete'); check(timestamp <= Number(current.expiresAt), 'This activity session has expired', 409, 'activity_expired'); const row = await this.collection('reward_activity_definitions').findOne({ id: current.activityId, enabled: true }, { session: mongoSession }); check(row, 'This activity is no longer available', 409, 'activity_unavailable'); const claim = { _id: uid(), id: uid(), residentId, activityId: row.id, sessionId: current.id, rewardGameNaira: row.rewardGameNaira, createdAt: timestamp }; await this.collection('reward_activity_sessions').updateOne({ id: current.id, status: 'started' }, { $set: { status: 'completed', completedAt: timestamp } }, { session: mongoSession }); await this.collection('reward_activity_claims').insertOne(claim, { session: mongoSession }); profile.wallet += row.rewardGameNaira; return { activityClaim: { id: claim.id, activityId: row.id, rewardGameNaira: row.rewardGameNaira, createdAt: timestamp }, rewardGameNaira: row.rewardGameNaira, ledgerReason: `activity_reward · ${row.title}` }; }); }
  async start(residentId, body = {}) { const campaignId = clean(body.campaignId || DEFAULT_ID, 80); check(/^[A-Za-z0-9_-]{1,80}$/.test(campaignId), 'Choose a valid earn campaign'); const now = this.store.clock(), row = await this.collection('reward_campaigns').findOne({ id: campaignId }); check(this.active(row, now), 'This earn campaign is not available right now', 409, 'campaign_unavailable'); const previous = await this.collection('reward_claims').findOne({ campaignId, residentId }); if (previous) return { ok: true, claimed: true, claim: this.claimView(previous), campaign: this.view(row, true) }; const session = { _id: uid(), id: uid(), residentId, campaignId, rewardGameNaira: row.rewardGameNaira, shareText: row.shareText, shareUrl: row.shareUrl, expiresAt: new Date(now + SESSION_TTL), status: 'started', createdAt: now, completedAt: null }; session.id = session._id; await this.collection('reward_share_sessions').insertOne(session); return { ok: true, claimed: false, shareSessionId: session.id, expiresAt: session.expiresAt.valueOf(), campaign: this.view(row), share: { text: session.shareText, url: session.shareUrl, title: 'AbujaLife' } }; }
  async complete(residentId, body = {}) { const sessionId = clean(body.shareSessionId, 80); check(/^[0-9a-f-]{20,80}$/i.test(sessionId), 'Share session is invalid', 400, 'invalid_share_session'); const session = await this.collection('reward_share_sessions').findOne({ id: sessionId, residentId }); check(session, 'Share session was not found', 404, 'share_session_not_found'); const key = `share-reward-${session.id}`; return this.store.economyOperation(residentId, 'social-share-reward', { idempotencyKey: key }, { campaignId: session.campaignId, shareSessionId: session.id }, async (profile, timestamp, mongoSession) => { const current = await this.collection('reward_share_sessions').findOne({ id: session.id, residentId }, { session: mongoSession }); check(current && current.status === 'started', 'This share has already been settled', 409, 'share_already_settled'); check(timestamp <= Number(current.expiresAt), 'This share session has expired', 409, 'share_session_expired'); const campaign = await this.collection('reward_campaigns').findOne({ id: current.campaignId }, { session: mongoSession }); check(this.active(campaign, timestamp), 'This earn campaign is no longer available', 409, 'campaign_unavailable'); check(!await this.collection('reward_claims').findOne({ campaignId: campaign.id, residentId }, { session: mongoSession }), 'This campaign reward was already collected', 409, 'reward_already_claimed'); const claim = { _id: uid(), id: uid(), residentId, campaignId: campaign.id, shareSessionId: current.id, rewardGameNaira: campaign.rewardGameNaira, createdAt: timestamp }; await this.collection('reward_share_sessions').updateOne({ id: current.id, status: 'started' }, { $set: { status: 'completed', completedAt: timestamp } }, { session: mongoSession }); await this.collection('reward_claims').insertOne(claim, { session: mongoSession }); profile.wallet += claim.rewardGameNaira; return { claim: this.claimView(claim), rewardGameNaira: claim.rewardGameNaira, campaign: this.view(campaign, true), ledgerReason: `SOCIAL_SHARE_REWARD · ${campaign.title}` }; }); }
  async adminList(id) { await this.admin.requirePermission(id, 'payments'); return this.campaigns(); }
  async adminSave(id, body = {}) { await this.admin.requirePermission(id, 'payments'); const campaignId = clean(body.id || DEFAULT_ID, 80), title = clean(body.title, 100), description = clean(body.description, 300), shareText = clean(body.shareText, 500), shareUrl = clean(body.shareUrl || this.publicWebUrl + '/', 500); check(/^[A-Za-z0-9_-]{1,80}$/.test(campaignId) && title.length >= 3 && description.length >= 3 && shareText.length >= 5, 'Complete the campaign fields'); const amount = Number(body.rewardGameNaira), maxClaims = Number(body.maxClaims ?? 1); check(Number.isSafeInteger(amount) && amount > 0 && amount <= 10000000, 'Reward must be a positive whole Game Naira amount'); check(Number.isSafeInteger(maxClaims) && maxClaims >= 1 && maxClaims <= 100, 'Choose a valid claim limit'); const now = this.store.clock(); await this.collection('reward_campaigns').updateOne({ id: campaignId }, { $set: { title, description, rewardGameNaira: amount, enabled: body.enabled !== false, startAt: body.startAt == null ? null : Number(body.startAt), endAt: body.endAt == null ? null : Number(body.endAt), maxClaims, shareText, shareUrl, updatedAt: now }, $setOnInsert: { _id: campaignId, id: campaignId, createdAt: now } }, { upsert: true }); return this.campaigns(); }
}

export { DEFAULT_ID as DEFAULT_REWARD_CAMPAIGN_ID, DEFAULT_REWARD };
