import crypto from 'node:crypto';
import { inflateSync } from 'node:zlib';
import { GameError } from '../errors.mjs';
import { catalog } from '../../shared/catalogue.mjs';
import { ABUJA_ATLAS } from '../../shared/atlas.mjs';
export const SOCIAL_META = Object.freeze({statusDurationMs:86400000,maxImageBytes:524288,maxTextLength:4000,maxCommentLength:2000,maxPageSize:50,maxGroupMembers:50});
const uid=()=>crypto.randomUUID();
export const check=(condition,message,status=400,code='invalid_social_action')=>{if(!condition)throw new GameError(message,status,code);};
export const identifier=(value,label='Choose a valid item')=>{check(typeof value==='string'&&/^[A-Za-z0-9:_-]{1,80}$/.test(value),label);return value;};
const textValue=(value,max,label)=>{check(value===undefined||typeof value==='string',`${label} must be text`);const text=(value||'').trim();check(text.length<=max,`${label} is too long`,413,'content_too_large');return text;};
const operationKey=value=>{check(typeof value==='string'&&/^[A-Za-z0-9:_-]{8,128}$/.test(value),'Include a unique idempotency key',400,'idempotency_required');return value;};
const fingerprint=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
export const cursorFor=(row,column='createdAt')=>row?Buffer.from(JSON.stringify([row[column],row.id])).toString('base64url'):null;
export function pageOptions({cursor,limit=20}={}){limit=Number(limit);check(Number.isSafeInteger(limit)&&limit>=1&&limit<=50,'Choose a page size of 1–50');if(!cursor)return{limit,after:null};check(typeof cursor==='string'&&cursor.length<=256,'Invalid page cursor',400,'invalid_cursor');try{const v=JSON.parse(Buffer.from(cursor,'base64url').toString());check(Array.isArray(v)&&v.length===2&&Number.isSafeInteger(v[0])&&v[0]>=0&&typeof v[1]==='string'&&/^[A-Za-z0-9:_-]{1,80}$/.test(v[1]),'Invalid page cursor',400,'invalid_cursor');return{limit,after:v};}catch{throw new GameError('Invalid page cursor',400,'invalid_cursor');}}
export const keyset=(after,column='createdAt')=>after?{$or:[{[column]:{$lt:after[0]}},{[column]:after[0],id:{$lt:after[1]}}]}:{};
const pair=(a,b)=>[a,b].sort().join(':');
const membershipKeyset=(after,column='joinedAt')=>after?{$or:[{[column]:{$lt:after[0]}},{[column]:after[0],residentId:{$lt:after[1]}}]}:{};
const membershipCursor=(row,column='joinedAt')=>row?cursorFor({...row,id:row.residentId},column):null;
const locations=new Set(ABUJA_ATLAS.map(p=>p.id));
const opts=session=>session&&Object.hasOwn(session,'session')?session:session?{session}:{};
const crcTable = Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(buffer){let n=0xffffffff;for(const byte of buffer)n=crcTable[(n^byte)&255]^(n>>>8);return(n^0xffffffff)>>>0;}
function dimensions(width,height){check(width>0&&height>0&&width<=4096&&height<=4096&&width*height<=16777216,'Use an image no larger than 4096 pixels per side',413,'image_dimensions');}
function validatePng(bytes) {
  check(bytes.length>=57&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),'Invalid PNG image');
  let offset=8,header=null,ended=false;const compressed=[];
  while(offset+12<=bytes.length){const length=bytes.readUInt32BE(offset),end=offset+12+length;check(end<=bytes.length,'Invalid PNG image');const type=bytes.toString('ascii',offset+4,offset+8),data=bytes.subarray(offset+8,offset+8+length);check(bytes.readUInt32BE(offset+8+length)===crc32(bytes.subarray(offset+4,offset+8+length)),'Invalid PNG checksum');
    if(!header){check(type==='IHDR'&&length===13,'Invalid PNG header');const width=data.readUInt32BE(0),height=data.readUInt32BE(4),depth=data[8],colour=data[9],channels={0:1,2:3,3:1,4:2,6:4}[colour];dimensions(width,height);check(channels&&[1,2,4,8,16].includes(depth)&&([0,3].includes(colour)||depth>=8)&&!(colour===3&&depth===16)&&data[10]===0&&data[11]===0&&data[12]<=1,'Unsupported PNG image');header={width,height,depth,channels,interlace:data[12]};}
    else check(type!=='IHDR','Invalid PNG image');
    if(type==='IDAT')compressed.push(data);
    if(type==='IEND'){check(length===0&&end===bytes.length,'Invalid PNG ending');ended=true;break;}offset=end;
  }
  check(ended&&compressed.length,'Incomplete PNG image');
  const {width,height,depth,channels,interlace}=header;
  const passes=interlace?[[0,0,8,8],[4,0,8,8],[0,4,4,8],[2,0,4,4],[0,2,2,4],[1,0,2,2],[0,1,1,2]]:[[0,0,1,1]];
  const rows=passes.map(([x,y,dx,dy])=>({width:Math.max(0,Math.ceil((width-x)/dx)),height:Math.max(0,Math.ceil((height-y)/dy))})).filter(p=>p.width&&p.height).map(p=>({...p,stride:1+Math.ceil(p.width*channels*depth/8)}));
  const length=rows.reduce((sum,p)=>sum+p.height*p.stride,0);check(length<=67108864,'PNG expands beyond the image limit',413,'image_dimensions');
  let pixels;try{pixels=inflateSync(Buffer.concat(compressed),{maxOutputLength:length});}catch{throw new GameError('Invalid PNG pixel data');}check(pixels.length===length,'Invalid PNG pixel data');let position=0;for(const pass of rows)for(let row=0;row<pass.height;row++){check(pixels[position]<=4,'Invalid PNG pixel filter');position+=pass.stride;}
}
function validateJpeg(bytes) {
  check(bytes.length>12&&bytes[0]===255&&bytes[1]===216&&bytes.at(-2)===255&&bytes.at(-1)===217,'Invalid JPEG image');
  let offset=2,foundSize=false,foundScan=false;
  while(offset<bytes.length-2){check(bytes[offset]===255,'Invalid JPEG marker');while(bytes[offset]===255)offset++;const marker=bytes[offset++];if(marker===217)break;if(marker===0||marker===216)throw new GameError('Invalid JPEG marker');if(marker>=208&&marker<=215||marker===1)continue;check(offset+2<=bytes.length,'Invalid JPEG segment');const length=bytes.readUInt16BE(offset);check(length>=2&&offset+length<=bytes.length,'Invalid JPEG segment');
    if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker)){check(length>=8,'Invalid JPEG dimensions');dimensions(bytes.readUInt16BE(offset+5),bytes.readUInt16BE(offset+3));foundSize=true;}
    if(marker===218){foundScan=true;break;}offset+=length;
  }
  check(foundSize&&foundScan,'Incomplete JPEG image');
}
function validateWebp(bytes) {
  check(bytes.length>=30&&bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP'&&bytes.readUInt32LE(4)+8===bytes.length,'Invalid WebP image');
  let offset=12,image=false;
  while(offset+8<=bytes.length){const kind=bytes.toString('ascii',offset,offset+4),length=bytes.readUInt32LE(offset+4),start=offset+8,end=start+length;check(end<=bytes.length,'Invalid WebP segment');
    if(kind==='VP8 '){check(length>=10&&bytes[start+3]===157&&bytes[start+4]===1&&bytes[start+5]===42,'Invalid WebP pixels');dimensions(bytes.readUInt16LE(start+6)&16383,bytes.readUInt16LE(start+8)&16383);image=true;}
    if(kind==='VP8L'){check(length>=5&&bytes[start]===47,'Invalid WebP pixels');const bits=bytes.readUInt32LE(start+1);dimensions((bits&16383)+1,((bits>>>14)&16383)+1);check((bits>>>29)===0,'Invalid WebP version');image=true;}
    if(kind==='VP8X'){check(length===10,'Invalid WebP header');dimensions(1+bytes.readUIntLE(start+4,3),1+bytes.readUIntLE(start+7,3));check(!(bytes[start]&2),'Upload a still image for this post');}
    offset=end+(length%2);
  }
  check(image&&offset===bytes.length,'Incomplete WebP image');
}
function imageValue(value) {
  if(value===undefined||value===null||value==='')return null;
  check(typeof value==='string'&&value.length<=Math.ceil(SOCIAL_META.maxImageBytes/3)*4+40,'Image is too large; use an image under 512 KiB',413,'image_too_large');
  const match=value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/);check(match&&match[2].length%4===0,'Upload a PNG, JPEG or WebP image',400,'invalid_image');const bytes=Buffer.from(match[2],'base64');check(bytes.length<=SOCIAL_META.maxImageBytes&&bytes.toString('base64')===match[2],'Invalid image encoding',400,'invalid_image');
  ({png:validatePng,jpeg:validateJpeg,webp:validateWebp})[match[1]](bytes);return`data:image/${match[1]};base64,${bytes.toString('base64')}`;
}


export const MONGO_SOCIAL_INDEXES={
      conversations:[[{id:1},{unique:true}],[{dmKey:1},{unique:true,partialFilterExpression:{kind:'dm'}}]],
      members:[[{conversationId:1,residentId:1},{unique:true}],[{residentId:1,updatedAt:-1,conversationId:1},{}],[{residentId:1,leftAt:1,updatedAt:-1,id:-1},{}],[{conversationId:1,leftAt:1,joinedAt:-1,residentId:-1},{}],[{conversationId:1,leftAt:1,deliveredSeq:1},{}],[{conversationId:1,leftAt:1,readSeq:1},{}]],
      messages:[[{id:1},{unique:true}],[{conversationId:1,seq:-1},{unique:true}],[{conversationId:1,createdAt:-1,id:-1},{}],[{conversationId:1,senderId:1,seq:1},{}],[{senderId:1,operationKey:1},{unique:true,partialFilterExpression:{operationKey:{$type:'string'}}}],[{transferId:1},{unique:true,partialFilterExpression:{transferId:{$type:'string'}}}]],
      friendships:[[{pair:1},{unique:true}],[{sender:1,status:1,createdAt:-1},{}],[{recipient:1,status:1,createdAt:-1},{}],[{id:1},{unique:true}]],
      moderation:[[{owner:1,target:1,kind:1},{unique:true}],[{target:1,kind:1,owner:1},{}]],
      notifications:[[{id:1},{unique:true}],[{residentId:1,createdAt:-1,id:-1},{}],[{residentId:1,link:1,readAt:1},{}]],
      follows:[[{owner:1,target:1},{unique:true}],[{owner:1,createdAt:-1,target:-1},{}],[{target:1,createdAt:-1},{}]],
      reports:[[{id:1},{unique:true}],[{createdAt:-1,id:-1},{}]],
      invitations:[[{id:1},{unique:true}],[{sender:1,createdAt:-1,id:-1},{}],[{recipient:1,createdAt:-1,id:-1},{}]],
      events:[[{id:1},{unique:true}],[{startsAt:1,id:1},{}]],event_rsvps:[[{eventId:1,residentId:1},{unique:true}]],
      location_messages:[[{id:1},{unique:true}],[{zone:1,createdAt:-1,id:-1},{}],[{purgeAt:1},{expireAfterSeconds:0}]],
      social_posts:[[{id:1},{unique:true}],[{kind:1,deletedAt:1,createdAt:-1,id:-1},{}],[{authorId:1,createdAt:-1,id:-1},{}],[{authorId:1,operationKey:1},{unique:true}],[{purgeAt:1},{expireAfterSeconds:0}]],
      social_likes:[[{postId:1,residentId:1},{unique:true}],[{purgeAt:1},{expireAfterSeconds:0}]],social_comments:[[{id:1},{unique:true}],[{postId:1,createdAt:-1,id:-1},{}],[{authorId:1,operationKey:1},{unique:true}],[{purgeAt:1},{expireAfterSeconds:0}]],
      home_visit_requests:[[{id:1},{unique:true}],[{ownerId:1,guestId:1},{unique:true,partialFilterExpression:{status:'pending'}}],[{guestId:1,operationKey:1},{unique:true}],[{ownerId:1,createdAt:-1,id:-1},{}],[{guestId:1,createdAt:-1,id:-1},{}]],
      home_visit_sessions:[[{id:1},{unique:true}],[{requestId:1},{unique:true}],[{guestId:1},{unique:true,partialFilterExpression:{endedAt:null}}],[{ownerId:1,endedAt:1,startedAt:-1,id:-1},{}]],
      community_groups:[[{id:1},{unique:true}],[{visibility:1,createdAt:-1,id:-1},{}],[{createdAt:-1,id:-1},{}],[{ownerId:1,id:1},{}]],community_members:[[{groupId:1,residentId:1},{unique:true}],[{residentId:1,createdAt:-1},{}],[{groupId:1,createdAt:-1,residentId:-1},{}]]
    };

export async function ensureMongoSocialSchema(db){ await new MongoSocialStore({db,clock:Date.now}).init(); }

/** All durable social state lives in MongoDB; SSE transports are supplied by HTTP. */
export class MongoSocialStore {
  constructor(game){this.game=game;this.db=game.db;this.buckets=new Map();this.authorizeModeration=()=>{throw new GameError('Content moderation permission is required',403,'admin_permission_required');};}
  collection(name){return this.db.collection(name);}
  clock(){return this.game.clock();}
  profile(id,session=null){identifier(id);return this.game.profile(id,opts(session));}
  transaction(fn){return this.game.transaction(fn);}
  async authenticate(id,session=null){identifier(id);check(await this.collection('residents').findOne({id},{projection:{id:1},...opts(session)}),'Sign in to your resident account',401,'authentication_required');return id;}
  async displayName(id){identifier(id);const row=await this.collection('residents').findOne({id},{projection:{displayName:1}});check(row,'Resident not found',404);return row.displayName;}
  async init({ensureIndexes=true}={}){
    if(!ensureIndexes)return this;
    await Promise.all(Object.entries(MONGO_SOCIAL_INDEXES).flatMap(([name,list])=>list.map(([keys,options])=>this.collection(name).createIndex(keys,options))));return this;
  }
  attachToGame(){this.game.social=this;for(const name of ['blocked','muted','resident','people','nearby','friendIds','friends','friendRequests','socialState','requestFriend','respondFriend','removeFriend','notify','notifications','readNotifications','conversationAccess','conversation','conversations','createConversation','messageView','messages','sendMessage','readConversation','delivered','zone','locationMessages','sendLocationMessage','typing','moderate','report','invitations','invite','respondInvite','events','createEvent','rsvp'])this.game[name]=this[name].bind(this);return this;}
  rate(id,kind,maximum=90){const now=this.clock(),key=`${id}:${kind}`,old=this.buckets.get(key),b=old&&now-old.at<60000?old:{at:now,count:0};b.count++;this.buckets.set(key,b);if(this.buckets.size>10000)for(const [k,v]of this.buckets)if(now-v.at>60000)this.buckets.delete(k);check(b.count<=maximum,'Please wait a moment before trying again',429,'rate_limited');}
  async blocked(a,b,session=null){if(a===b)return false;return Boolean(await this.collection('moderation').findOne({kind:'block',$or:[{owner:a,target:b},{owner:b,target:a}]},opts(session)));}
  async blockedIds(id,session=null){const rows=await this.collection('moderation').find({kind:'block',$or:[{owner:id},{target:id}]},{projection:{owner:1,target:1},...opts(session)}).toArray();return [...new Set(rows.map(r=>r.owner===id?r.target:r.owner))];}
  async muted(a,b,session=null){return Boolean(await this.collection('moderation').findOne({kind:'mute',owner:a,target:b},opts(session)));}
  async resident(viewer,id){identifier(id);const [r,a,state,progress]=await Promise.all([this.collection('residents').findOne({id},{projection:{id:1,username:1,displayName:1,settings:1}}),this.collection('appearances').findOne({residentId:id}),this.collection('player_state').findOne({residentId:id},{projection:{district:1,location:1}}),this.collection('progression').findOne({residentId:id},{projection:{reputation:1}})]);check(r&&a&&state,'Resident not found',404);const {_id,residentId,...appearance}=a,p={...r,...state},allowed=!viewer||!await this.blocked(viewer,id),visible=allowed&&p.settings.presenceVisible!==false;return{id:r.id,username:r.username,displayName:r.displayName,appearance,reputation:progress?.reputation??0,online:visible&&Boolean(await this.game.isOnline?.(id)),district:visible?p.district:null,location:visible?this.publicLocation(p,viewer):null};}
  publicLocation(p,viewer){if(p.location.kind==='home')return{kind:'home',district:p.district,venue:'home'};if(p.location.kind==='visit')return{kind:'visit',district:p.district,venue:'home'};return structuredClone(p.location);}
  async people(id){return(await this.game.directory.people(id,{limit:40})).people;}
  async nearby(id){return this.game.presence?(await this.game.presence.nearby(id)):[];}
  async friendIds(id,session=null){const blocked=await this.blockedIds(id,session),rows=await this.collection('friendships').find({status:'accepted',$or:[{sender:id},{recipient:id}]},opts(session)).toArray();return rows.map(r=>r.sender===id?r.recipient:r.sender).filter(target=>!blocked.includes(target));}
  async acceptedFriends(a,b,session=null){return Boolean(await this.collection('friendships').findOne({pair:pair(a,b),status:'accepted'},opts(session)));}
  async friends(id){await this.authenticate(id);return Promise.all((await this.friendIds(id)).slice(0,100).map(target=>this.resident(id,target)));}
  async friendRequests(id){await this.authenticate(id);const blocked=await this.blockedIds(id),rows=await this.collection('friendships').find({status:'pending',sender:{$nin:blocked},recipient:{$nin:blocked},$or:[{sender:id},{recipient:id}]}).sort({createdAt:-1,id:-1}).limit(100).toArray();return Promise.all(rows.map(async r=>({id:r.id,from:r.sender,to:r.recipient,status:r.status,createdAt:r.createdAt,resident:await this.resident(id,r.sender===id?r.recipient:r.sender)})));}
  async socialState(id){const [friends,friendRequests,conversations,notifications]=await Promise.all([this.friends(id),this.friendRequests(id),this.conversations(id),this.notifications(id)]);return{ok:true,friends,friendRequests,conversations,notifications};}
  async requestFriend(id,target){await this.authenticate(id);identifier(target);check(target!==id,'You cannot send yourself a friend request');await this.authenticate(target);this.rate(id,'friend',30);let created=false;await this.transaction(async session=>{check(!await this.blocked(id,target,session),'This resident is unavailable',403);const col=this.collection('friendships'),prior=await col.findOne({pair:pair(id,target)},opts(session));if(prior&&['accepted','pending'].includes(prior.status))return;await col.updateOne({pair:pair(id,target)},{$set:{sender:id,recipient:target,status:'pending',createdAt:this.clock()},$setOnInsert:{id:uid(),pair:pair(id,target)}},{upsert:true,...opts(session)});created=true;});if(created)await this.notify(target,'friend-request','New friend request',`${(await this.displayName(id))} would like to connect.`,'friends',id);return this.socialState(id);}
  async respondFriend(id,requestId,accept){await this.authenticate(id);identifier(requestId);check(typeof accept==='boolean','Accept or reject this request');let row;await this.transaction(async session=>{row=await this.collection('friendships').findOne({id:requestId,recipient:id,status:'pending'},opts(session));check(row,'Friend request not found',404);check(!await this.blocked(id,row.sender,session),'This resident is unavailable',403);await this.collection('friendships').updateOne({id:requestId,status:'pending'},{$set:{status:accept?'accepted':'declined'}},opts(session));});if(accept)await this.notify(row.sender,'friend-accepted','Friend request accepted',`${(await this.displayName(id))} is now your friend.`,'friends',id);return this.socialState(id);}
  async removeFriend(id,target){await this.authenticate(id);identifier(target);await this.collection('friendships').deleteOne({pair:pair(id,target)});await this.reconcileVisits(id);return this.socialState(id);}
  async notify(id,kind,title,body,link=null,sender=null){
    if(sender&&(await this.blocked(id,sender)||await this.muted(id,sender)))return null;
    if(typeof link==='string'&&link.startsWith('conversation:')){try{await this.conversationAccess(id,link.slice('conversation:'.length));}catch(error){if([401,403,404].includes(error.status))return null;throw error;}}
    const notice={id:uid(),residentId:id,kind,title,body,link,createdAt:this.clock(),readAt:null,senderId:sender};await this.collection('notifications').insertOne(notice);const view=this.noticeView(notice);this.game.emitUser?.(id,'notification',view);return view;
  }
  noticeView(r){return{id:r.id,kind:r.kind,title:r.title,body:r.body,link:r.link,createdAt:r.createdAt,readAt:r.readAt};}
  async notificationPage(id,options={}){
    await this.authenticate(id);const {limit,after}=pageOptions(options),blocked=await this.blockedIds(id),rows=await this.collection('notifications').find({residentId:id,senderId:{$nin:blocked},...keyset(after)}).sort({createdAt:-1,id:-1}).limit(limit+1).toArray(),notices=[];
    for(const row of rows.slice(0,limit)){if(typeof row.link==='string'&&row.link.startsWith('conversation:')){try{await this.conversationAccess(id,row.link.slice('conversation:'.length));}catch(error){if([401,403,404].includes(error.status))continue;throw error;}}notices.push(this.noticeView(row));}
    return{ok:true,notifications:notices,nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};
  }
  async notifications(id){return(await this.notificationPage(id,{limit:50})).notifications;}
  async readNotifications(id,noticeId){await this.authenticate(id);if(noticeId!==undefined)identifier(noticeId);await this.collection('notifications').updateMany({residentId:id,readAt:null,...(noticeId?{id:noticeId}:{})},{$set:{readAt:this.clock()}});return{ok:true,notifications:await this.notifications(id)};}
  async conversationAccess(id,conversationId,session=null){await this.authenticate(id,session);identifier(conversationId,'Choose a conversation');const member=await this.collection('members').findOne({residentId:id,conversationId,leftAt:null},opts(session));check(member,'Conversation not found',404,'conversation_unavailable');const row=await this.collection('conversations').findOne({id:conversationId},opts(session));check(row,'Conversation not found',404);if(row.kind==='dm'){const other=await this.collection('members').findOne({conversationId,residentId:{$ne:id},leftAt:null},opts(session));check(other&&!await this.blocked(id,other.residentId,session),'This conversation is unavailable',403,'conversation_unavailable');}if(row.kind==='community')await this.groupAccess(id,row.communityGroupId,false,session);return member;}
  async conversationMembers(id,conversationId,options={}){
    await this.conversationAccess(id,conversationId);const {limit,after}=pageOptions(options),filter={conversationId,leftAt:null,residentId:{$nin:await this.blockedIds(id)},...membershipKeyset(after)};
    const rows=await this.collection('members').find(filter).sort({joinedAt:-1,residentId:-1}).limit(limit+1).toArray();
    return{ok:true,conversationId,members:await Promise.all(rows.slice(0,limit).map(r=>this.resident(id,r.residentId))),memberCount:await this.collection('members').countDocuments({conversationId,leftAt:null,residentId:filter.residentId}),nextCursor:rows.length>limit?membershipCursor(rows[limit-1]):null};
  }
  async conversation(id,conversationId){
    const me=await this.conversationAccess(id,conversationId),row=await this.collection('conversations').findOne({id:conversationId}),blocked=await this.blockedIds(id),memberPage=await this.conversationMembers(id,conversationId,{limit:50});
    const filter={conversationId,seq:{$gt:me.joinSeq??0},senderId:{$nin:blocked}},[last,unread]=await Promise.all([this.collection('messages').find(filter).sort({seq:-1}).limit(1).next(),this.collection('messages').countDocuments({...filter,senderId:{$nin:[...blocked,id]},seq:{$gt:Math.max(me.readSeq??0,me.joinSeq??0)}})]);
    return{id:row.id,kind:row.kind,name:row.kind==='dm'?(memberPage.members.find(m=>m.id!==id)?.displayName||'Conversation'):row.name,members:memberPage.members,memberCount:memberPage.memberCount,nextMembersCursor:memberPage.nextCursor,unread,lastMessage:last?await this.messageView(last,id):null};
  }
  async conversationPage(id,options={}){await this.authenticate(id);const {limit,after}=pageOptions(options),blocked=await this.blockedIds(id);const pipeline=[{$match:{residentId:id,leftAt:null,...keyset(after,'updatedAt')}},{$sort:{updatedAt:-1,id:-1}},{$lookup:{from:'conversations',localField:'conversationId',foreignField:'id',as:'conv'}},{$unwind:'$conv'},{$match:{$and:[{$or:[{'conv.kind':{$ne:'dm'}},{'conv.participantIds':{$nin:blocked}}]},{$or:[{'conv.kind':{$ne:'community'}},{'conv.ownerId':{$nin:blocked}}]}]}},{$limit:limit+1}];const rows=await this.collection('members').aggregate(pipeline).toArray(),selected=rows.slice(0,limit);return{ok:true,conversations:await Promise.all(selected.map(r=>this.conversation(id,r.conversationId))),nextCursor:rows.length>limit?cursorFor(selected.at(-1),'updatedAt'):null};}
  async conversations(id){return(await this.conversationPage(id,{limit:50})).conversations;}
  async createConversation(id,body={}){await this.authenticate(id);this.rate(id,'conversation',20);const kind=body.kind??'dm';check(['dm','group'].includes(kind),'Choose a conversation type');let targets,name='';if(kind==='dm'){const target=identifier(body.residentId);check(target!==id,'Choose another resident');await this.authenticate(target);check(!await this.blocked(id,target),'This resident is unavailable',403);targets=[target];}else{check(Array.isArray(body.memberIds)&&body.memberIds.length>=1&&body.memberIds.length<SOCIAL_META.maxGroupMembers,'Choose 1–49 friends for your group');targets=[...new Set(body.memberIds.map(t=>identifier(t)))].filter(t=>t!==id);check(targets.length,'Choose another friend');name=textValue(body.name,60,'Group name');check(name.length>=2,'Give your group a name');const friends=new Set(await this.friendIds(id));check(targets.every(t=>friends.has(t)),'Group members must be accepted friends');}
    let conversationId;try{await this.transaction(async session=>{if(kind==='dm'){const prior=await this.collection('conversations').findOne({dmKey:pair(id,targets[0])},opts(session));if(prior){conversationId=prior.id;return;}}for(const t of targets)check(!await this.blocked(id,t,session),'This resident is unavailable',403);const now=this.clock();conversationId=uid();await this.collection('conversations').insertOne({id:conversationId,kind,name,ownerId:id,participantIds:[id,...targets],...(kind==='dm'?{dmKey:pair(id,targets[0])}:{}),seq:0,createdAt:now,updatedAt:now},opts(session));await this.collection('members').insertMany([id,...targets].map(residentId=>({id:conversationId,conversationId,residentId,role:residentId===id?'owner':'member',joinedAt:now,updatedAt:now,joinSeq:0,readSeq:0,deliveredSeq:0,readAt:0,deliveredAt:0,leftAt:null})),opts(session));});}catch(e){if(e.code===11000&&kind==='dm'){conversationId=(await this.collection('conversations').findOne({dmKey:pair(id,targets[0])}))?.id;if(!conversationId)throw e;}else throw e;}
    if(kind==='group')for(const target of targets)await this.notify(target,'group','New group',`${(await this.displayName(id))} added you to ${name}.`,`conversation:${conversationId}`,id);
    // A new DM only needs its id to open instantly. Hydration of member names,
    // unread counts and the latest message happens in the messages request;
    // avoid the old multi-query conversation read on this latency-sensitive
    // button path.
    const conversation=kind==='dm'
      ? {id:conversationId,kind:'dm',members:[{id},{id:targets[0]}],memberCount:2,unread:0,lastMessage:null}
      : await this.conversation(id,conversationId);
    return{ok:true,conversation};
  }
  async receiptPage(row,viewer,options={}){
    const {limit,after}=pageOptions(options),blocked=viewer?await this.blockedIds(viewer):[],base={conversationId:row.conversationId,leftAt:null,residentId:{$nin:[row.senderId,...blocked]},$and:[{$or:[{joinSeq:{$lt:row.seq}},{joinSeq:{$exists:false}}]}]},filter={...base,deliveredSeq:{$gte:row.seq},...membershipKeyset(after)};
    const [rows,deliveredCount,readCount]=await Promise.all([this.collection('members').find(filter).sort({joinedAt:-1,residentId:-1}).limit(limit+1).toArray(),this.collection('members').countDocuments({...base,deliveredSeq:{$gte:row.seq}}),this.collection('members').countDocuments({...base,readSeq:{$gte:row.seq}})]);
    const selected=rows.slice(0,limit);return{receipts:selected.map(m=>({residentId:m.residentId,delivered:m.deliveredSeq>=row.seq,read:m.readSeq>=row.seq,deliveredAt:m.deliveredAt,readAt:m.readAt})),deliveredCount,readCount,nextCursor:rows.length>limit?membershipCursor(rows[limit-1]):null};
  }
  async messageReceipts(id,conversationId,messageId,options={}){const member=await this.conversationAccess(id,conversationId);identifier(messageId);const row=await this.collection('messages').findOne({id:messageId,conversationId});check(row&&row.seq>(member.joinSeq??0)&&!await this.blocked(id,row.senderId),'Message is unavailable',404,'message_unavailable');return{ok:true,messageId,conversationId,...await this.receiptPage(row,id,options)};}
  messageEvent(row){return{id:row.id,conversationId:row.conversationId,senderId:row.senderId,kind:row.kind??'text',text:row.text,createdAt:row.createdAt,seq:row.seq,...(row.kind==='transfer'?{transferId:row.transferId,transfer:structuredClone(row.transfer)}:{}),deliveredTo:[],readBy:[]};}
  async messageView(row,viewer=null){const page=await this.receiptPage(row,viewer,{limit:50});return{...this.messageEvent(row),deliveredTo:page.receipts.filter(m=>m.delivered).map(m=>m.residentId),readBy:page.receipts.filter(m=>m.read).map(m=>m.residentId),deliveredCount:page.deliveredCount,readCount:page.readCount,nextReceiptsCursor:page.nextCursor};}
  async messages(id,conversationId,options={}){const me=await this.conversationAccess(id,conversationId),{limit,after}=pageOptions(options),blocked=await this.blockedIds(id),rows=await this.collection('messages').find({conversationId,senderId:{$nin:blocked},seq:{$gt:me.joinSeq??0},...keyset(after)}).sort({createdAt:-1,id:-1}).limit(limit+1).toArray();if(rows.length)await this.receipt(id,conversationId,true,rows[0].seq);return{ok:true,conversation:await this.conversation(id,conversationId),messages:await Promise.all(rows.slice(0,limit).reverse().map(r=>this.messageView(r,id))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};}
  async *fanoutMembers(conversationId,senderId){
    const conversation=await this.collection('conversations').findOne({id:conversationId}),blocked=await this.blockedIds(senderId);if(conversation?.kind==='community')blocked.push(...await this.blockedIds(conversation.ownerId));
    const cursor=this.collection('members').find({conversationId,leftAt:null,residentId:{$nin:[...new Set(blocked)]}},{projection:{residentId:1}}).batchSize(50);
    for await(const member of cursor){
      // A cursor batch may predate a block or departure; authorize each delivery again.
      if(await this.blocked(senderId,member.residentId))continue;
      if(!await this.collection('members').findOne({conversationId,residentId:member.residentId,leftAt:null},{projection:{_id:1}}))continue;
      if(conversation?.kind==='community'&&(await this.blocked(conversation.ownerId,member.residentId)||!await this.collection('community_members').findOne({groupId:conversation.communityGroupId,residentId:member.residentId},{projection:{_id:1}})))continue;
      yield member;
    }
  }
  async sendMessage(id,conversationId,input,body={}){
    check(input!==null,'Message must be text');
    const text=textValue(typeof input==='object'?input.text:input,4000,'Message');
    check(text.length,'Write a message first');
    this.rate(id,'message',90);
    body=typeof input==='object'?input:body;
    const key=body.idempotencyKey===undefined?null:operationKey(body.idempotencyKey),hash=fingerprint({conversationId,text});
    let row,replayed=false;
    await this.transaction(async session=>{
      await this.conversationAccess(id,conversationId,session);
      if(key){
        row=await this.collection('messages').findOne({senderId:id,operationKey:key},opts(session));
        if(row){check(row.fingerprint===hash,'This message key was already used for different content',409,'idempotency_conflict');replayed=true;return;}
      }
      const conv=await this.collection('conversations').findOneAndUpdate({id:conversationId},{$inc:{seq:1}},{returnDocument:'after',...opts(session)});
      const now=Math.max(this.clock(),(conv.updatedAt??0)+1);
      await this.collection('conversations').updateOne({id:conversationId},{$set:{updatedAt:now}},opts(session));
      row={id:uid(),conversationId,senderId:id,kind:'text',text,seq:conv.seq,createdAt:now,...(key?{operationKey:key,fingerprint:hash}:{})};
      await this.collection('messages').insertOne(row,opts(session));
      await this.collection('members').updateMany({conversationId,leftAt:null},{$set:{updatedAt:now}},opts(session));
      await this.collection('members').updateOne({conversationId,residentId:id},{$max:{readSeq:row.seq,deliveredSeq:row.seq,readAt:now,deliveredAt:now}},opts(session));
    });

    // Replays need the canonical receipt view. A fresh send has no recipient
    // receipts yet, so avoid three extra aggregate queries on the hot path.
    const view=replayed?await this.messageView(row,id):{...this.messageEvent(row),deliveredTo:[],readBy:[],deliveredCount:0,readCount:0,nextReceiptsCursor:null};
    if(!replayed)await this.fanoutMessage(row,id);
    return{ok:true,message:view,replayed};
  }

  /**
   * Fan out a saved message with bounded Mongo work. The old implementation
   * walked members serially and called notify() for each recipient, making the
   * sender wait on N authorization queries and N inserts. We fetch the live
   * membership once, emit realtime messages immediately, then insert notices
   * as one batch. Block and mute checks remain server-side and are applied
   * before either delivery path.
   */
  async fanoutMessage(row,senderId){
    const conversation=await this.collection('conversations').findOne({id:row.conversationId},{projection:{kind:1,ownerId:1}});
    if(!conversation)return;
    const blocked=new Set(await this.blockedIds(senderId));
    if(conversation.kind==='community'&&conversation.ownerId)for(const residentId of await this.blockedIds(conversation.ownerId))blocked.add(residentId);
    const members=await this.collection('members').find({conversationId:row.conversationId,leftAt:null,residentId:{$nin:[senderId,...blocked]}},{projection:{residentId:1}}).toArray();
    const memberIds=[...new Set(members.map(member=>member.residentId).filter(residentId=>!blocked.has(residentId)))];
    const event=this.messageEvent(row);
    // Include the sender so other signed-in devices receive the same event;
    // the phone de-duplicates it against its optimistic message bubble.
    for(const residentId of memberIds)this.game.emitUser?.(residentId,'message',event);
    const recipientIds=memberIds.filter(residentId=>residentId!==senderId);
    if(!recipientIds.length)return;
    const muted=await this.collection('moderation').find({kind:'mute',owner:{$in:recipientIds},target:senderId},{projection:{owner:1}}).toArray();
    const mutedIds=new Set(muted.map(row=>row.owner));
    const name=await this.displayName(senderId),now=this.clock();
    const notices=recipientIds.filter(residentId=>!mutedIds.has(residentId)).map(residentId=>({id:uid(),residentId,kind:'message',title:name,body:row.text.slice(0,140),link:`conversation:${row.conversationId}`,createdAt:now,readAt:null,senderId}));
    if(!notices.length)return;
    await this.collection('notifications').insertMany(notices,{ordered:false});
    for(const notice of notices)this.game.emitUser?.(notice.residentId,'notification',this.noticeView(notice));
  }
  async recordTransferReceipt(senderId,recipientId,conversationId,transfer,session){
    check(session,'Transfer receipts require the wallet transaction',500,'transaction_required');await this.conversationAccess(senderId,conversationId,session);
    const conversation=await this.collection('conversations').findOne({id:conversationId},opts(session));check(conversation?.kind==='dm'&&conversation.dmKey===pair(senderId,recipientId),'Choose your direct conversation with this recipient',403,'transfer_conversation_mismatch');
    const members=await this.collection('members').find({conversationId,leftAt:null},{projection:{residentId:1},...opts(session)}).limit(3).toArray();check(members.length===2&&members.some(member=>member.residentId===senderId)&&members.some(member=>member.residentId===recipientId),'Choose your direct conversation with this recipient',403,'transfer_conversation_mismatch');check(!await this.blocked(senderId,recipientId,session),'This conversation is unavailable',403,'conversation_unavailable');
    identifier(transfer.id);check(Number.isSafeInteger(transfer.amount)&&transfer.amount>0,'Transfer must use exact whole game Naira',400,'invalid_amount');
    const conv=await this.collection('conversations').findOneAndUpdate({id:conversationId},{$inc:{seq:1}},{returnDocument:'after',...opts(session)}),now=Math.max(this.clock(),(conv.updatedAt??0)+1);
    const metadata={id:transfer.id,from:senderId,to:recipientId,fromId:senderId,toId:recipientId,senderId,recipientId,amount:transfer.amount,note:textValue(transfer.note,120,'Transfer note'),createdAt:transfer.createdAt,virtual:true,currency:'game-naira',senderName:transfer.senderName,recipientName:transfer.recipientName};
    const row={id:uid(),conversationId,senderId,kind:'transfer',transferId:transfer.id,transfer:metadata,text:`Sent ₦${transfer.amount.toLocaleString('en-NG')}`,seq:conv.seq,createdAt:now};
    await this.collection('messages').insertOne(row,opts(session));await this.collection('conversations').updateOne({id:conversationId},{$set:{updatedAt:now}},opts(session));await this.collection('members').updateMany({conversationId,leftAt:null},{$set:{updatedAt:now}},opts(session));await this.collection('members').updateOne({conversationId,residentId:senderId},{$max:{readSeq:row.seq,deliveredSeq:row.seq,readAt:now,deliveredAt:now}},opts(session));
    return row;
  }
  async publishTransferReceipt(senderId,conversationId,row){check(row.kind==='transfer'&&row.senderId===senderId&&row.conversationId===conversationId,'Transfer receipt is unavailable',400,'transfer_conversation_mismatch');const members=await this.fanoutMembers(conversationId,senderId);for await(const member of members)this.game.emitUser?.(member.residentId,'message',this.messageEvent(row));return{message:await this.messageView(row,senderId)};}
  async receipt(id,conversationId,read,uptoSeq=null){let row;await this.transaction(async session=>{await this.conversationAccess(id,conversationId,session);row=await this.collection('conversations').findOne({id:conversationId},opts(session));const at=this.clock(),seq=uptoSeq===null?row.seq:uptoSeq;check(Number.isSafeInteger(seq)&&seq>=0&&seq<=row.seq,'Invalid receipt watermark');const update=read?{readSeq:seq,deliveredSeq:seq,readAt:at,deliveredAt:at}:{deliveredSeq:seq,deliveredAt:at};await this.collection('members').updateOne({conversationId,residentId:id,leftAt:null},{$max:update},opts(session));if(read)await this.collection('notifications').updateMany({residentId:id,link:`conversation:${conversationId}`,readAt:null},{$set:{readAt:at}},opts(session));});const members=await this.fanoutMembers(conversationId,id),receipt={conversationId,residentId:id,receipt:true,[read?'readAt':'deliveredAt']:this.clock()};for await(const m of members)this.game.emitUser?.(m.residentId,'message',receipt);return{ok:true};}
  readConversation(id,conversationId){return this.receipt(id,conversationId,true);}
  async delivered(id,conversationId){if(conversationId)return this.receipt(id,conversationId,false);const members=await this.collection('members').find({residentId:id,leftAt:null}).sort({updatedAt:-1}).limit(100).toArray();for(const m of members){try{await this.receipt(id,m.conversationId,false);}catch(e){if(e.status!==403)throw e;}}return{ok:true};}
  async typing(id,conversationId){await this.authenticate(id);this.rate(id,'typing',180);const event={residentId:id,displayName:(await this.displayName(id)),conversationId:conversationId||null,at:this.clock()};if(conversationId){await this.conversationAccess(id,conversationId);const members=await this.fanoutMembers(conversationId,id);for await(const m of members)if(m.residentId!==id)this.game.emitUser?.(m.residentId,'typing',event);}else this.game.emitZone?.(id,'typing',event);return{ok:true};}
  async moderate(id,kind,target,enabled){await this.authenticate(id);identifier(target);check(['block','mute'].includes(kind)&&typeof enabled==='boolean','Invalid moderation control');check(target!==id,'Choose another resident');await this.authenticate(target);await this.transaction(async session=>{if(enabled)await this.collection('moderation').updateOne({owner:id,target,kind},{$setOnInsert:{createdAt:this.clock()}},{upsert:true,...opts(session)});else await this.collection('moderation').deleteOne({owner:id,target,kind},opts(session));if(kind==='block'&&enabled){await this.collection('friendships').deleteOne({pair:pair(id,target)},opts(session));await this.collection('follows').deleteMany({$or:[{owner:id,target},{owner:target,target:id}]},opts(session));await this.collection('home_visit_requests').updateMany({status:'pending',$or:[{ownerId:id,guestId:target},{ownerId:target,guestId:id}]},{$set:{status:'cancelled',answeredAt:this.clock()}},opts(session));const groups=this.collection('community_groups').find({ownerId:{$in:[id,target]}},{projection:{id:1,ownerId:1,conversationId:1},...opts(session)}).batchSize(50);for await(const group of groups){const revoked=group.ownerId===id?target:id;await this.collection('community_members').deleteOne({groupId:group.id,residentId:revoked},opts(session));await this.collection('members').updateOne({conversationId:group.conversationId,residentId:revoked,leftAt:null},{$set:{leftAt:this.clock()}},opts(session));}}});if(kind==='block'&&enabled){await this.reconcileVisits(id);await this.game.presence?.invalidatePair?.(id,target);}const rows=await this.collection('moderation').find({owner:id}).toArray();return{ok:true,blocked:rows.filter(r=>r.kind==='block').map(r=>r.target),muted:rows.filter(r=>r.kind==='mute').map(r=>r.target)};}
  async report(id,body={}){await this.authenticate(id);this.rate(id,'report',10);const reason=textValue(body.reason,1000,'Report reason');check(reason.length>=5,'Tell us what happened');let target=null,messageId=null;if(body.residentId){target=identifier(body.residentId);await this.authenticate(target);}if(body.messageId){identifier(body.messageId);const row=await this.collection('messages').findOne({id:body.messageId});check(row,'Message not found',404);await this.conversationAccess(id,row.conversationId);messageId=row.id;target=row.senderId;}check(target||messageId,'Choose a resident or message to report');const reportId=uid();await this.collection('reports').insertOne({id:reportId,reporterId:id,targetId:target,messageId,reason,createdAt:this.clock(),status:'pending'});return{ok:true,reportId};}
  async follow(id,target,enabled=true){await this.authenticate(id);identifier(target);check(target!==id&&typeof enabled==='boolean','Choose another resident');await this.authenticate(target);this.rate(id,'follow',30);check(!await this.blocked(id,target),'This resident is unavailable',403);if(enabled)await this.collection('follows').updateOne({owner:id,target},{$setOnInsert:{createdAt:this.clock()}},{upsert:true});else await this.collection('follows').deleteOne({owner:id,target});return{ok:true,residentId:target,following:enabled};}
  async follows(id,options={}){await this.authenticate(id);const {limit,after}=pageOptions(options),rows=await this.collection('follows').find({owner:id,target:{$nin:await this.blockedIds(id)},...(after?{$or:[{createdAt:{$lt:after[0]}},{createdAt:after[0],target:{$lt:after[1]}}]}:{})}).sort({createdAt:-1,target:-1}).limit(limit+1).toArray();return{ok:true,people:await Promise.all(rows.slice(0,limit).map(r=>this.resident(id,r.target))),nextCursor:rows.length>limit?cursorFor({...rows[limit-1],id:rows[limit-1].target}):null};}
  async postView(id,row){const blocked=await this.blockedIds(id),[resident,likes,liked,comments]=await Promise.all([this.resident(id,row.authorId),this.collection('social_likes').countDocuments({postId:row.id,residentId:{$nin:blocked}}),this.collection('social_likes').findOne({postId:row.id,residentId:id}),this.collection('social_comments').countDocuments({postId:row.id,authorId:{$nin:blocked}})]);return{id:row.id,userId:row.authorId,resident,text:row.text,imageDataUrl:row.imageDataUrl,kind:row.kind,createdAt:row.createdAt,expiresAt:row.expiresAt,likes,likedByMe:Boolean(liked),commentCount:comments};}
  async postAccess(id,postId,session=null){await this.authenticate(id,session);identifier(postId,'Choose a post');const row=await this.collection('social_posts').findOne({id:postId,deletedAt:null,$or:[{expiresAt:null},{expiresAt:{$gt:this.clock()}}]},opts(session));check(row&&!await this.blocked(id,row.authorId,session),'Post is unavailable',404,'post_unavailable');return row;}
  async contentPage(id,kind,options={}){
    await this.authenticate(id);const {limit,after}=pageOptions(options),now=this.clock(),filter={kind,deletedAt:null,authorId:{$nin:await this.blockedIds(id)},...(kind==='status'?{expiresAt:{$gt:now},createdAt:{$gt:now-SOCIAL_META.statusDurationMs}}:{expiresAt:null}),...keyset(after)};if(kind==='status'&&after)filter.$and=[{createdAt:{$gt:now-SOCIAL_META.statusDurationMs}}];
    let rows;if(options.following){rows=await this.collection('social_posts').aggregate([{$match:filter},{$sort:{createdAt:-1,id:-1}},{$lookup:{from:'follows',let:{author:'$authorId'},pipeline:[{$match:{$expr:{$and:[{$eq:['$owner',id]},{$eq:['$target','$$author']}]}}},{$limit:1}],as:'viewerFollow'}},{$match:{$or:[{authorId:id},{'viewerFollow.0':{$exists:true}}]}},{$limit:limit+1}]).toArray();}else rows=await this.collection('social_posts').find(filter).sort({createdAt:-1,id:-1}).limit(limit+1).toArray();
    return{ok:true,[kind==='status'?'statuses':'posts']:await Promise.all(rows.slice(0,limit).map(row=>this.postView(id,row))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null,serverTime:now};
  }
  feed(id,options={}){return this.contentPage(id,'post',options);}
  statuses(id,options={}){return this.contentPage(id,'status',options);}
  async createPost(id,body={}){await this.authenticate(id);this.rate(id,'post',20);const text=textValue(body.text,4000,'Post'),image=imageValue(body.imageDataUrl),kind=body.kind??'post',key=operationKey(body.idempotencyKey);check(kind==='post'||kind==='status','Choose a post or 24-hour status');check(text||image,'Write something or choose an image');const hash=fingerprint({text,image,kind});let replayed=false,row;try{await this.transaction(async session=>{row=await this.collection('social_posts').findOne({authorId:id,operationKey:key},opts(session));if(row){check(row.fingerprint===hash,'This idempotency key was already used for different content',409,'idempotency_conflict');check(row.deletedAt===null,'This post was deleted',410,'post_unavailable');check(row.expiresAt===null||row.expiresAt>this.clock(),'This status has expired',410,'status_expired');replayed=true;return;}const now=this.clock();row={id:uid(),authorId:id,kind,text,imageDataUrl:image,createdAt:now,expiresAt:kind==='status'?now+SOCIAL_META.statusDurationMs:null,...(kind==='status'?{purgeAt:new Date(now+SOCIAL_META.statusDurationMs)}:{}),deletedAt:null,deletedBy:null,deletionReason:null,operationKey:key,fingerprint:hash};await this.collection('social_posts').insertOne(row,opts(session));});}catch(e){if(e.code===11000){row=await this.collection('social_posts').findOne({authorId:id,operationKey:key});check(row&&row.fingerprint===hash,'This idempotency key was already used for different content',409,'idempotency_conflict');replayed=true;}else throw e;}const post=await this.postView(id,row);if(!replayed){this.game.emitUser?.(id,'social-post',{post});this.game.emitZone?.(id,'social-change',{postId:row.id});}return{ok:true,post,replayed};}
  async toggleLike(id,postId){this.rate(id,'like',90);let row;await this.transaction(async session=>{row=await this.postAccess(id,postId,session);const col=this.collection('social_likes'),prior=await col.findOne({postId,residentId:id},opts(session));if(prior)await col.deleteOne({postId,residentId:id},opts(session));else await col.insertOne({postId,residentId:id,createdAt:this.clock(),...(row.purgeAt?{purgeAt:row.purgeAt}:{})},opts(session));await this.collection('social_posts').updateOne({id:postId},{$inc:{revision:1}},opts(session));});const post=await this.postView(id,row);this.game.emitUser?.(id,'social-post',{post});if(row.authorId!==id){this.game.emitUser?.(row.authorId,'social-change',{postId});await this.notify(row.authorId,'social-like','New like',`${(await this.displayName(id))} liked your post.`,'feed',id);}return{ok:true,post};}
  async commentView(id,row){return{id:row.id,postId:row.postId,userId:row.authorId,resident:await this.resident(id,row.authorId),text:row.text,createdAt:row.createdAt};}
  async comments(id,postId,options={}){await this.postAccess(id,postId);const {limit,after}=pageOptions(options),rows=await this.collection('social_comments').find({postId,authorId:{$nin:await this.blockedIds(id)},...keyset(after)}).sort({createdAt:-1,id:-1}).limit(limit+1).toArray();return{ok:true,comments:await Promise.all(rows.slice(0,limit).map(r=>this.commentView(id,r))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};}
  async addComment(id,postId,body={}){this.rate(id,'comment',45);const text=textValue(body.text,2000,'Comment'),key=operationKey(body.idempotencyKey);check(text,'Write a comment first');const hash=fingerprint({postId,text});let row,post,replayed=false;await this.transaction(async session=>{post=await this.postAccess(id,postId,session);row=await this.collection('social_comments').findOne({authorId:id,operationKey:key},opts(session));if(row){check(row.fingerprint===hash,'This comment key was already used for different content',409,'idempotency_conflict');replayed=true;return;}row={id:uid(),postId,authorId:id,text,createdAt:this.clock(),operationKey:key,fingerprint:hash,...(post.purgeAt?{purgeAt:post.purgeAt}:{})};await this.collection('social_comments').insertOne(row,opts(session));await this.collection('social_posts').updateOne({id:postId},{$inc:{revision:1}},opts(session));});const comment=await this.commentView(id,row);if(!replayed){this.game.emitUser?.(id,'social-comment',{comment});if(post.authorId!==id){this.game.emitUser?.(post.authorId,'social-comment',{comment});await this.notify(post.authorId,'social-comment','New comment',`${(await this.displayName(id))} commented on your post.`,'feed',id);}}return{ok:true,comment,replayed};}
  async deleteOwnPost(id,postId){await this.authenticate(id);identifier(postId);const row=await this.collection('social_posts').findOne({id:postId,authorId:id});check(row,'Your post was not found',404,'post_unavailable');const result=await this.collection('social_posts').updateOne({id:postId,authorId:id,deletedAt:null},{$set:{deletedAt:this.clock(),deletedBy:id,deletionReason:'Author deleted'}});if(result.modifiedCount){this.game.emitUser?.(id,'social-delete',{postId});this.game.emitZone?.(id,'social-delete',{postId});}return{ok:true,postId,deleted:true,replayed:!result.modifiedCount};}
  async moderationPosts(id,options={}){await this.authenticate(id);await this.authorizeModeration(id);const {limit,after}=pageOptions(options),rows=await this.collection('social_posts').find({...(options.includeDeleted?{}:{deletedAt:null}),...keyset(after)}).sort({createdAt:-1,id:-1}).limit(limit+1).toArray();return{ok:true,posts:await Promise.all(rows.slice(0,limit).map(async r=>({...await this.postView(id,r),deletedAt:r.deletedAt,deletedBy:r.deletedBy,deletionReason:r.deletionReason}))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};}
  async moderateDeletePost(id,postId,body={}){await this.authenticate(id);await this.authorizeModeration(id);identifier(postId);const reason=textValue(body.reason,500,'Moderation reason');check(reason.length>=3,'Explain why this post is being removed');const row=await this.collection('social_posts').findOne({id:postId});check(row,'Post was not found',404);const r=await this.collection('social_posts').updateOne({id:postId,deletedAt:null},{$set:{deletedAt:this.clock(),deletedBy:id,deletionReason:reason}});if(r.modifiedCount)this.game.emitUser?.(row.authorId,'social-delete',{postId,moderated:true});return{ok:true,postId,deleted:true,replayed:!r.modifiedCount};}
  async visitPermission(owner,guestId,session=null){return owner.settings.allowInvites!==false&&owner.settings.allowHomeVisits!==false&&!await this.blocked(owner.id,guestId,session)&&(!owner.settings.homeVisitsFriendsOnly||await this.acceptedFriends(owner.id,guestId,session));}
  ownHome(owner){return owner.location.kind==='home'&&owner.location.district===owner.home.district&&owner.district===owner.home.district&&!owner.activeTrip;}
  async requestView(viewer,row){check(viewer===row.ownerId||viewer===row.guestId,'Home visit request is unavailable',404);return{id:row.id,ownerId:row.ownerId,guestId:row.guestId,owner:await this.resident(viewer,row.ownerId),guest:await this.resident(viewer,row.guestId),note:row.note,status:row.status,createdAt:row.createdAt,answeredAt:row.answeredAt};}
  async requestVisit(id,body={}){await this.authenticate(id);this.rate(id,'visit',15);const ownerId=identifier(body.ownerId??body.residentId,'Choose a home owner');check(ownerId!==id,'Choose another resident to visit');const note=textValue(body.note,300,'Visit note'),key=operationKey(body.idempotencyKey),hash=fingerprint({ownerId,note});let row,replayed=false;await this.transaction(async session=>{const guest=await this.profile(id,session),owner=await this.profile(ownerId,session);check(await this.visitPermission(owner,id,session),'This resident is not accepting home visits',403,'visit_unavailable');row=await this.collection('home_visit_requests').findOne({guestId:id,operationKey:key},opts(session));if(row){check(row.fingerprint===hash,'This visit key was already used for another visit',409,'idempotency_conflict');replayed=true;return;}check(guest.location.kind==='public'&&guest.district===owner.home.district&&!guest.activeTrip&&!guest.activeShift&&!guest.drivingVehicle,'Head outside in the owner’s neighbourhood and park before requesting a visit',409,'visit_location');check(!await this.collection('home_visit_requests').findOne({guestId:id,ownerId,status:'pending'},opts(session)),'A visit request is already waiting for this owner',409,'visit_pending');row={id:uid(),ownerId,guestId:id,note,status:'pending',createdAt:this.clock(),answeredAt:null,operationKey:key,fingerprint:hash};await this.collection('home_visit_requests').insertOne(row,opts(session));});const request=await this.requestView(id,row);if(!replayed){this.game.emitUser?.(ownerId,'home-visit-request',{request:await this.requestView(ownerId,row)});this.game.emitUser?.(id,'home-visit-request',{request});await this.notify(ownerId,'home-visit','Home visit request',`${(await this.displayName(id))} would like to visit your home.`,'visits',id);}return{ok:true,request,replayed};}
  async answerVisit(id,requestId,accept){await this.reconcileVisits(id);identifier(requestId);check(typeof accept==='boolean','Accept or reject this visit request');let row,sessionRow=null,replayed=false;await this.transaction(async session=>{row=await this.collection('home_visit_requests').findOne({id:requestId,ownerId:id},opts(session));check(row,'Home visit request was not found',404,'visit_unavailable');if(row.status!=='pending'){check(row.status===(accept?'accepted':'rejected'),'This visit request was already answered differently',409,'visit_answered');replayed=true;sessionRow=await this.collection('home_visit_sessions').findOne({requestId},opts(session));return;}const owner=await this.profile(id,session),guest=await this.profile(row.guestId,session);check(!await this.blocked(id,guest.id,session),'This home visit request is unavailable',403,'visit_unavailable');if(accept){check(await this.visitPermission(owner,guest.id,session),'Your home privacy settings prevent this visit',403,'visit_unavailable');check(this.ownHome(owner),'Return to your own home before welcoming a visitor',409,'owner_not_home');check(guest.location.kind==='public'&&guest.district===owner.home.district&&!guest.activeTrip&&!guest.activeShift&&!guest.drivingVehicle,'The guest must be outside in your home neighbourhood and parked',409,'visit_location');check(!await this.collection('home_visit_sessions').findOne({guestId:guest.id,endedAt:null},opts(session)),'This guest is already visiting a home',409,'visit_active');sessionRow={id:uid(),requestId,ownerId:id,guestId:guest.id,propertyId:owner.home.propertyId,startedAt:this.clock(),endedAt:null,endReason:null};await this.collection('home_visit_sessions').insertOne(sessionRow,opts(session));guest.location={kind:'visit',district:owner.home.district,venue:'home',ownerId:id,visitId:sessionRow.id};guest.drivingVehicle=null;await this.game.save(guest,opts(session));}row.status=accept?'accepted':'rejected';row.answeredAt=this.clock();await this.collection('home_visit_requests').updateOne({id:requestId,status:'pending'},{$set:{status:row.status,answeredAt:row.answeredAt}},opts(session));});if(!replayed){for(const target of [id,row.guestId])this.game.emitUser?.(target,'home-visit',{request:await this.requestView(target,row),visitId:sessionRow?.id??null});if(accept)this.game.emitUser?.(row.guestId,'profile',{profile:await this.profile(row.guestId)});}return{ok:true,request:await this.requestView(id,row),visit:sessionRow?.endedAt===null?await this.visitView(id,sessionRow):null,replayed};}
  async visitView(id,row){check((row.ownerId===id||row.guestId===id)&&row.endedAt===null,'Home visit is unavailable',404,'visit_unavailable');const owner=await this.profile(row.ownerId);check(await this.visitPermission(owner,row.guestId)&&this.ownHome(owner)&&owner.home.propertyId===row.propertyId,'Home visit is unavailable',403,'visit_unavailable');const inventory=owner.inventory.filter(itemId=>catalog.some(item=>item.id===itemId&&item.category==='furniture'));return{id:row.id,requestId:row.requestId,ownerId:row.ownerId,guestId:row.guestId,owner:await this.resident(id,row.ownerId),guest:await this.resident(id,row.guestId),home:structuredClone(owner.home),furnitureLayout:structuredClone(owner.furnitureLayout),storedFurniture:[...owner.storedFurniture],startedAt:row.startedAt,ownerHome:{id:owner.id,username:owner.username,displayName:owner.displayName,appearance:structuredClone(owner.appearance),home:structuredClone(owner.home),inventory,furnitureLayout:structuredClone(owner.furnitureLayout),storedFurniture:[...owner.storedFurniture]}};}
  async endSession(row,reason){await this.transaction(async session=>{const result=await this.collection('home_visit_sessions').updateOne({id:row.id,endedAt:null},{$set:{endedAt:this.clock(),endReason:reason}},opts(session));if(!result.modifiedCount)return;const guest=await this.profile(row.guestId,session);if(guest.location.kind==='visit'&&guest.location.visitId===row.id){guest.location={kind:'public',district:guest.district,venue:'neighbourhood'};guest.drivingVehicle=null;await this.game.save(guest,opts(session));}});for(const target of [row.ownerId,row.guestId])this.game.emitUser?.(target,'home-visit-ended',{visitId:row.id,reason});this.game.emitUser?.(row.guestId,'profile',{profile:await this.profile(row.guestId)});}
  async reconcileVisits(id){await this.authenticate(id);const rows=await this.collection('home_visit_sessions').find({endedAt:null,$or:[{guestId:id},{ownerId:id}]}).toArray();for(const row of rows){const [owner,guest]=await Promise.all([this.profile(row.ownerId),this.profile(row.guestId)]);if(!this.ownHome(owner)||owner.home.propertyId!==row.propertyId||!await this.visitPermission(owner,guest.id)||guest.location.kind!=='visit'||guest.location.visitId!==row.id)await this.endSession(row,'Home visit is no longer available');}}
  async leaveVisit(id){await this.authenticate(id);const row=await this.collection('home_visit_sessions').findOne({guestId:id,endedAt:null});if(row)await this.endSession(row,'Guest left');return{ok:true,profile:await this.profile(id),visit:null,replayed:!row};}
  async visitState(id,options={}){await this.reconcileVisits(id);const {limit,after}=pageOptions(options),blocked=await this.blockedIds(id),filters={ownerId:{$nin:blocked},guestId:{$nin:blocked},$and:[{$or:[{ownerId:id},{guestId:id}]},keyset(after)]},rows=await this.collection('home_visit_requests').find(filters).sort({createdAt:-1,id:-1}).limit(limit+1).toArray(),vp=pageOptions({cursor:options.visitorsCursor,limit}),visitors=await this.collection('home_visit_sessions').find({ownerId:id,endedAt:null,...keyset(vp.after,'startedAt')}).sort({startedAt:-1,id:-1}).limit(limit+1).toArray(),visit=await this.collection('home_visit_sessions').findOne({guestId:id,endedAt:null});return{ok:true,visit:visit?await this.visitView(id,visit):null,requests:await Promise.all(rows.slice(0,limit).map(r=>this.requestView(id,r))),visitors:await Promise.all(visitors.slice(0,limit).map(r=>this.visitView(id,r))),nextRequestsCursor:rows.length>limit?cursorFor(rows[limit-1]):null,nextVisitorsCursor:visitors.length>limit?cursorFor(visitors[limit-1],'startedAt'):null};}
  async visitOwnerContext(id){const [resident,state,home]=await Promise.all([this.collection('residents').findOne({id},{projection:{id:1,settings:1}}),this.collection('player_state').findOne({residentId:id},{projection:{district:1,location:1,activeTrip:1}}),this.collection('homes').findOne({residentId:id},{projection:{district:1,propertyId:1}})]);check(resident&&state&&home,'Home visit is unavailable',403,'visit_unavailable');return{...resident,...state,home};}
  async zone(id){identifier(id);const p=await this.collection('player_state').findOne({residentId:id},{projection:{district:1,location:1}});check(p,'Resident not found',404);if(p.location.kind==='visit'){const visit=await this.collection('home_visit_sessions').findOne({id:p.location.visitId,guestId:id,ownerId:p.location.ownerId,endedAt:null});check(visit,'This home visit is unavailable',403,'visit_unavailable');const owner=await this.visitOwnerContext(visit.ownerId);check(this.ownHome(owner)&&owner.home.propertyId===visit.propertyId&&await this.visitPermission(owner,id),'This home visit is unavailable',403,'visit_unavailable');return`home:${visit.ownerId}`;}return p.location.kind==='home'?`home:${id}`:p.location.kind==='venue'?`venue:${p.district}:${p.location.venue}`:p.location.kind==='public'?`district:${p.district}`:`transit:${id}`;}
  async locationMessages(id,options={}){await this.authenticate(id);const {limit,after}=pageOptions(options),zone=await this.zone(id),rows=await this.collection('location_messages').find({zone,senderId:{$nin:await this.blockedIds(id)},...keyset(after)}).sort({createdAt:-1,id:-1}).limit(limit+1).toArray();return{ok:true,messages:await Promise.all(rows.slice(0,limit).reverse().map(async r=>({id:r.id,senderId:r.senderId,resident:await this.resident(id,r.senderId),text:r.text,createdAt:r.createdAt,zone:r.zone}))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};}
  async sendLocationMessage(id,input){await this.authenticate(id);const p=await this.collection('player_state').findOne({residentId:id},{projection:{location:1}});check(p&&['public','home','visit','venue'].includes(p.location.kind),'Local chat is unavailable during a journey');const text=textValue(input,2000,'Message');check(text,'Write a message first');this.rate(id,'location-message',60);const now=this.clock(),row={id:uid(),senderId:id,text,createdAt:now,zone:await this.zone(id),purgeAt:new Date(now+7*86400000)};await this.collection('location_messages').insertOne(row);const message={id:row.id,senderId:id,resident:await this.resident(id,id),text,createdAt:now,zone:row.zone};this.game.emitZone?.(id,'location-chat',message);return{ok:true,message};}
  async invitations(id,options={}){await this.authenticate(id);const blocked=await this.blockedIds(id),{limit,after}=pageOptions(options),rows=await this.collection('invitations').find({sender:{$nin:blocked},recipient:{$nin:blocked},$and:[{$or:[{sender:id},{recipient:id}]},keyset(after)]}).sort({createdAt:-1,id:-1}).limit(limit).toArray();return Promise.all(rows.map(async r=>({id:r.id,from:r.sender,to:r.recipient,kind:r.kind,district:r.district,activity:r.activity,note:r.note,status:r.status,createdAt:r.createdAt,resident:await this.resident(id,r.sender===id?r.recipient:r.sender)})));}
  async invitationView(id,row){return{id:row.id,from:row.sender,to:row.recipient,kind:row.kind,district:row.district,activity:row.activity,note:row.note,status:row.status,createdAt:row.createdAt,resident:await this.resident(id,row.sender===id?row.recipient:row.sender)};}
  async invite(id,body={}){
    await this.authenticate(id);const target=identifier(body.residentId);check(target!==id,'Choose another resident');
    const [p,other,state,home]=await Promise.all([this.collection('residents').findOne({id},{projection:{displayName:1}}),this.collection('residents').findOne({id:target},{projection:{settings:1}}),this.collection('player_state').findOne({residentId:id},{projection:{district:1}}),this.collection('homes').findOne({residentId:id},{projection:{district:1}})]);
    check(other,'Resident not found',404);check(other.settings.allowInvites!==false&&!await this.blocked(id,target),'This resident is not accepting invitations',403);check(['meetup','home','activity'].includes(body.kind),'Choose an invitation type');this.rate(id,'invite',30);
    const district=body.kind==='home'?home.district:textValue(body.district??state.district,80,'District');check(locations.has(district),'Choose a location from the atlas');const row={id:uid(),sender:id,recipient:target,kind:body.kind,district,activity:textValue(body.activity,60,'Activity'),note:textValue(body.note,300,'Invitation note'),status:'pending',createdAt:this.clock()};
    await this.collection('invitations').insertOne(row);const invitation=await this.invitationView(id,row);this.game.emitUser?.(target,'invitation',await this.invitationView(target,row));await this.notify(target,'invitation','You are invited',`${p.displayName} sent you a ${body.kind} invitation.`,'invitations',id);return{ok:true,invitation};
  }
  async respondInvite(id,inviteId,accept){
    await this.authenticate(id);identifier(inviteId);check(typeof accept==='boolean','Choose a response');let row,replayed=false;const status=accept?'accepted':'declined';
    await this.transaction(async session=>{replayed=false;row=await this.collection('invitations').findOne({id:inviteId,recipient:id},opts(session));check(row,'Invitation not found',404);check(!await this.blocked(id,row.sender,session),'This invitation is unavailable',403);if(row.status!=='pending'){check(row.status===status,'This invitation was already answered differently',409,'invitation_answered');replayed=true;return;}const result=await this.collection('invitations').updateOne({id:inviteId,recipient:id,status:'pending'},{$set:{status}},opts(session));check(result.modifiedCount===1,'This invitation was already answered',409,'invitation_answered');row.status=status;});
    if(!replayed)await this.notify(row.sender,'invitation-response','Invitation update',`${(await this.displayName(id))} ${accept?'accepted':'declined'} your invitation.`,'invitations',id);return{ok:true,invitations:await this.invitations(id),replayed};
  }
  async eventView(id,row){const attendees=await this.collection('event_rsvps').find({eventId:row.id,residentId:{$nin:await this.blockedIds(id)}}).limit(100).toArray();return{id:row.id,host:await this.resident(id,row.hostId),title:row.title,district:row.district,startsAt:row.startsAt,description:row.description,attendeeIds:attendees.map(r=>r.residentId)};}
  async events(id){await this.authenticate(id);const rows=await this.collection('events').find({startsAt:{$gt:this.clock()-86400000},hostId:{$nin:await this.blockedIds(id)}}).sort({startsAt:1,id:1}).limit(50).toArray();return Promise.all(rows.map(r=>this.eventView(id,r)));}
  async createEvent(id,body={}){await this.authenticate(id);this.rate(id,'event',10);const title=textValue(body.title,80,'Event title'),district=textValue(body.district,80,'District'),startsAt=body.startsAt;check(title.length>=3,'Give your event a title');check(locations.has(district),'Choose a location from the atlas');check(Number.isSafeInteger(startsAt)&&startsAt>this.clock()&&Number.isFinite(new Date(startsAt).getTime()),'Choose a valid future event time');const row={id:uid(),hostId:id,title,district,startsAt,description:textValue(body.description,600,'Description'),createdAt:this.clock()};await this.transaction(async session=>{await this.collection('events').insertOne(row,opts(session));await this.collection('event_rsvps').insertOne({eventId:row.id,residentId:id},opts(session));});
    this.game.emitUser?.(id,'event',{event:await this.eventView(id,row)});
    for(const friend of await this.friendIds(id)){if(await this.blocked(id,friend)||await this.muted(friend,id))continue;this.game.emitUser?.(friend,'event',{event:await this.eventView(friend,row)});await this.notify(friend,'event','A new event',`${await this.displayName(id)} created ${title}.`,'events',id);}
    return{ok:true,event:await this.eventView(id,row)};}
  async rsvp(id,eventId,attending){await this.authenticate(id);identifier(eventId);check(typeof attending==='boolean','Choose your RSVP');const row=await this.collection('events').findOne({id:eventId});check(row,'Event not found',404);check(!await this.blocked(id,row.hostId),'This event is unavailable',403);if(attending)await this.collection('event_rsvps').updateOne({eventId,residentId:id},{$setOnInsert:{createdAt:this.clock()}},{upsert:true});else await this.collection('event_rsvps').deleteOne({eventId,residentId:id});
    const targets=new Set([id,row.hostId]);for await(const attendee of this.collection('event_rsvps').find({eventId},{projection:{residentId:1}}).batchSize(50))targets.add(attendee.residentId);
    for(const target of targets)if(!await this.blocked(target,row.hostId)&&!await this.blocked(target,id))this.game.emitUser?.(target,'event',{event:await this.eventView(target,row)});
    return{ok:true,events:await this.events(id)};}
  async groupAccess(id,groupId,requireManager=false,session=null){await this.authenticate(id,session);identifier(groupId);const group=await this.collection('community_groups').findOne({id:groupId},opts(session)),member=await this.collection('community_members').findOne({groupId,residentId:id},opts(session));check(group&&member&&!await this.blocked(id,group.ownerId,session),'Group is unavailable',404,'group_unavailable');if(requireManager)check(['owner','admin'].includes(member.role),'Group manager permission is required',403,'group_permission_required');return{group,member};}
  async groupMembers(id,groupId,options={}){
    await this.groupAccess(id,groupId);const {limit,after}=pageOptions(options),blocked=await this.blockedIds(id),filter={groupId,residentId:{$nin:blocked},...membershipKeyset(after,'createdAt')};
    const rows=await this.collection('community_members').find(filter).sort({createdAt:-1,residentId:-1}).limit(limit+1).toArray();
    return{ok:true,groupId,members:await Promise.all(rows.slice(0,limit).map(async row=>({...await this.resident(id,row.residentId),role:row.role,joinedAt:row.createdAt}))),memberCount:await this.collection('community_members').countDocuments({groupId}),nextCursor:rows.length>limit?membershipCursor(rows[limit-1],'createdAt'):null};
  }
  async groupView(id,row){
    const member=await this.collection('community_members').findOne({groupId:row.id,residentId:id}),page=member?await this.groupMembers(id,row.id,{limit:50}):{members:[],memberCount:await this.collection('community_members').countDocuments({groupId:row.id}),nextCursor:null};
    return{id:row.id,name:row.name,description:row.description,visibility:row.visibility,ownerId:row.ownerId,conversationId:member?row.conversationId:null,members:page.members,memberCount:page.memberCount,nextMembersCursor:page.nextCursor,joined:Boolean(member),role:member?.role??null,createdAt:row.createdAt};
  }
  async groups(id,options={}){
    await this.authenticate(id);const {limit,after}=pageOptions(options),blocked=await this.blockedIds(id),rows=await this.collection('community_groups').aggregate([{$match:{ownerId:{$nin:blocked},...keyset(after)}},{$sort:{createdAt:-1,id:-1}},{$lookup:{from:'community_members',let:{group:'$id'},pipeline:[{$match:{$expr:{$and:[{$eq:['$groupId','$$group']},{$eq:['$residentId',id]}]}}},{$limit:1}],as:'viewerMember'}},{$match:{$or:[{visibility:'public'},{'viewerMember.0':{$exists:true}}]}},{$limit:limit+1}]).toArray();
    return{ok:true,groups:await Promise.all(rows.slice(0,limit).map(row=>this.groupView(id,row))),nextCursor:rows.length>limit?cursorFor(rows[limit-1]):null};
  }
  async createGroup(id,body={}){await this.authenticate(id);this.rate(id,'community-group',5);const name=textValue(body.name,60,'Group name'),description=textValue(body.description,600,'Group description'),visibility=body.visibility??'public';check(name.length>=2,'Give your group a name');check(['public','private'].includes(visibility),'Choose group privacy');const now=this.clock(),groupId=uid(),conversationId=uid();const row={id:groupId,ownerId:id,name,description,visibility,conversationId,createdAt:now};await this.transaction(async session=>{await this.collection('community_groups').insertOne(row,opts(session));await this.collection('community_members').insertOne({groupId,residentId:id,role:'owner',createdAt:now},opts(session));await this.collection('conversations').insertOne({id:conversationId,kind:'community',communityGroupId:groupId,ownerId:id,name,participantIds:[id],seq:0,createdAt:now,updatedAt:now},opts(session));await this.collection('members').insertOne({id:conversationId,conversationId,residentId:id,role:'owner',joinedAt:now,updatedAt:now,joinSeq:0,readSeq:0,deliveredSeq:0,readAt:0,deliveredAt:0,leftAt:null},opts(session));});return{ok:true,group:await this.groupView(id,row)};}
  async joinGroup(id,groupId){await this.authenticate(id);identifier(groupId);this.rate(id,'group-join',20);let group;await this.transaction(async session=>{group=await this.collection('community_groups').findOne({id:groupId,visibility:'public'},opts(session));check(group&&!await this.blocked(id,group.ownerId,session),'Group is unavailable',404,'group_unavailable');if(await this.collection('community_members').findOne({groupId,residentId:id},opts(session)))return;const now=this.clock(),conv=await this.collection('conversations').findOneAndUpdate({id:group.conversationId},{$inc:{revision:1}},{returnDocument:'after',...opts(session)});await this.collection('community_members').updateOne({groupId,residentId:id},{$setOnInsert:{role:'member',createdAt:now}},{upsert:true,...opts(session)});await this.collection('members').updateOne({conversationId:group.conversationId,residentId:id},{$set:{leftAt:null,joinSeq:conv.seq,readSeq:conv.seq,deliveredSeq:conv.seq,updatedAt:now},$setOnInsert:{id:group.conversationId,conversationId:group.conversationId,residentId:id,role:'member',joinedAt:now,readAt:0,deliveredAt:0}},{upsert:true,...opts(session)});});return{ok:true,group:await this.groupView(id,group)};}
  async leaveGroup(id,groupId){await this.groupAccess(id,groupId);await this.transaction(async session=>{const {group,member}=await this.groupAccess(id,groupId,false,session);check(member.role!=='owner','Transfer ownership before leaving your group',409);await this.collection('community_members').deleteOne({groupId,residentId:id},opts(session));await this.collection('members').updateOne({conversationId:group.conversationId,residentId:id},{$set:{leftAt:this.clock()}},opts(session));});return{ok:true,groupId,left:true};}
  async addGroupMember(id,groupId,target){identifier(target);await this.authenticate(target);this.rate(id,'group-add',30);let group;await this.transaction(async session=>{({group}=await this.groupAccess(id,groupId,true,session));check(!await this.blocked(id,target,session)&&!await this.blocked(group.ownerId,target,session),'This resident is unavailable',403);check(target!==id&&await this.acceptedFriends(id,target,session),'Choose an accepted friend');if(await this.collection('community_members').findOne({groupId,residentId:target},opts(session)))return;const now=this.clock(),conv=await this.collection('conversations').findOneAndUpdate({id:group.conversationId},{$inc:{revision:1}},{returnDocument:'after',...opts(session)});await this.collection('community_members').insertOne({groupId,residentId:target,role:'member',createdAt:now},opts(session));await this.collection('members').updateOne({conversationId:group.conversationId,residentId:target},{$set:{leftAt:null,joinSeq:conv.seq,readSeq:conv.seq,deliveredSeq:conv.seq,updatedAt:now},$setOnInsert:{id:group.conversationId,conversationId:group.conversationId,residentId:target,role:'member',joinedAt:now,readAt:0,deliveredAt:0}},{upsert:true,...opts(session)});});await this.notify(target,'group','New group',`${(await this.displayName(id))} added you to ${group.name}.`,`conversation:${group.conversationId}`,id);return{ok:true,group:await this.groupView(id,group)};}
  async removeGroupMember(id,groupId,target){identifier(target);await this.transaction(async session=>{const {group,member}=await this.groupAccess(id,groupId,true,session),other=await this.collection('community_members').findOne({groupId,residentId:target},opts(session));check(other&&other.role!=='owner'&&(other.role!=='admin'||member.role==='owner'),'This member cannot be removed',403,'group_permission_required');await this.collection('community_members').deleteOne({groupId,residentId:target},opts(session));await this.collection('members').updateOne({conversationId:group.conversationId,residentId:target},{$set:{leftAt:this.clock()}},opts(session));});this.game.emitUser?.(target,'group-left',{groupId});return{ok:true,groupId,residentId:target,removed:true};}
  async updateGroup(id,groupId,body={}){let group;await this.transaction(async session=>{({group}=await this.groupAccess(id,groupId,true,session));const change={};if(body.name!==undefined){change.name=textValue(body.name,60,'Group name');check(change.name.length>=2,'Give your group a name');}if(body.description!==undefined)change.description=textValue(body.description,600,'Group description');if(body.visibility!==undefined){check(['public','private'].includes(body.visibility),'Choose group privacy');change.visibility=body.visibility;}await this.collection('community_groups').updateOne({id:groupId},{$set:change},opts(session));if(change.name)await this.collection('conversations').updateOne({id:group.conversationId},{$set:{name:change.name}},opts(session));group={...group,...change};});return{ok:true,group:await this.groupView(id,group)};}

}
