import { createPhone } from './phone.js';
import { renderWorld, avatarSVG } from './world.js';
import { renderMap } from './map.js';

const root = document.querySelector('#app');
const sheetRoot = document.querySelector('#sheet-root');
let state = { authenticated:false }, view = location.hash.slice(1)||'world', cleanup, stream, refreshTimer, busy=false;
let authMode='register', selectedJob, marketFilter='all', chatMessages=[], chatOpen=false;
let onboardingStep=0, onboardingDraft, pendingVenue;
let draft={skinTone:'brown',hair:'crop',top:'forest',bottom:'charcoal',shoes:'white',body:'regular',face:'oval',presentation:'neutral',facialHair:'none',accessory:'none'};
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('en-NG',{maximumFractionDigits:0}).format(Number(n||0));
const list = value => Array.isArray(value)?value:Object.entries(value||{}).map(([id,item])=>({id,...item}));
const place = id => state.atlas?.find(p=>p.id===id);
const paths={world:'<path d="m3 10 9-7 9 7v11h-6v-8H9v8H3z"/>',map:'<path d="m3 5 6-2 6 3 6-2v16l-6 2-6-3-6 2zM9 3v16M15 6v16"/>',work:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 12h18M10 12v3h4v-3"/>',phone:'<rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 18h4M10 5h4"/>',profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',chat:'<path d="M3 4h18v13H9l-6 4zM7 9h10M7 13h6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4 10-10"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2M12 21v2M1 12h2M21 12h2M4 4l2 2M18 18l2 2M4 20l2-2M18 6l2-2"/>'};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.world}</svg>`;

async function api(path,options={}) {
 const opts={...options,headers:{...options.headers}};
 if(opts.body!==undefined&&typeof opts.body!=='string')opts.body=JSON.stringify(opts.body);
 if(opts.body!==undefined)opts.headers['content-type']='application/json';
 const response=await fetch(path,{...opts,signal:opts.signal||AbortSignal.timeout(15000)}),body=await response.json();
 if(!response.ok||body.ok===false){const error=new Error(body.error||'Please try again.');error.status=response.status;error.code=body.code;throw error;}
 return body;
}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),4000);}
async function refresh({render=true}={}){state=await api('/api/bootstrap');if(render)renderMain();phone.render();return state;}
const phone=createPhone({root:document.querySelector('#phone-root'),getState:()=>state,api,onUpdate:refresh,onNavigate:navigate,toast});
function navigate(destination,details={}){
 if(!['world','map','work','market','property','profile'].includes(destination))destination='world';
 if(details.jobId)selectedJob=details.jobId;
 phone.close();closeSheet();view=destination;
 if(location.hash!==`#${view}`)history.pushState({view},'',`#${view}`);
 renderMain();
 if(destination==='world'&&details.venueId)goToVenue(details.venueId);
 if(destination==='world'&&details.furnishItemId)beginFurniturePlacement(details.furnishItemId);
 if(destination==='world'&&details.garage)openGarage();
}
addEventListener('popstate',()=>{view=location.hash.slice(1)||'world';phone.close();closeSheet();renderMain();});
addEventListener('keydown',event=>{if(event.key==='Escape')closeSheet();});
function connectRealtime(){
 stream?.close();if(!state.authenticated)return;stream=new EventSource('/api/realtime');
 for(const type of ['ready','presence','location-chat','typing','message','notification','invitation','profile','receipt'])stream.addEventListener(type,event=>{
  let data;try{data=JSON.parse(event.data);}catch{return;}phone.handleEvent(type,data);
  if(type==='location-chat'){chatMessages.push(data.message||data);chatMessages=chatMessages.slice(-60);if(chatOpen)renderChat();}
  if(['presence','profile','message','notification','invitation','receipt'].includes(type)){
   clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh({render:!document.querySelector('.sheet')&&!root.contains(document.activeElement)}).catch(()=>{}),250);
  }
 });
 stream.onopen=()=>{document.documentElement.dataset.connection='online';};stream.onerror=()=>{document.documentElement.dataset.connection='reconnecting';};
}
async function action(name,payload={}){
 if(busy)return;busy=true;
 try{const result=await api('/api/action',{method:'POST',body:{action:name,payload}});if(result.profile)state.profile=result.profile;await refresh();return result;}
 catch(error){toast(error.message);return null;}finally{busy=false;}
}
function currentVenue(){return list(state.venues).find(v=>v.id===(state.profile?.location?.venueId||state.profile?.location?.venue));}
function venueActions(venue){const all=list(state.venueActions);return all.filter(a=>a.venueId===venue?.id||(venue?.activities||venue?.actions||[]).includes(a.id));}
function playTime(){return new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Africa/Lagos'}).format(new Date());}
function perform(name,payload={}){if(cleanup?.perform)return cleanup.perform(name,payload);return interact(name,payload);}
let previousFocus,sheetCleanup;
function openSheet(content,{wide=false}={}){
 sheetCleanup?.();sheetCleanup=undefined;
 previousFocus=document.activeElement;
 sheetRoot.innerHTML=`<div class="sheet-backdrop"><section class="sheet ${wide?'game-sheet-wide':''}" role="dialog" aria-modal="true" aria-labelledby="sheet-title"><button class="sheet-close icon-button" data-close aria-label="Close">${icon('close')}</button>${content}</section></div>`;
 sheetRoot.querySelector('[data-close]').onclick=closeSheet;
 sheetRoot.querySelector('.sheet-backdrop').onclick=e=>{if(e.target.classList.contains('sheet-backdrop'))closeSheet();};
 sheetRoot.querySelector('button:not([data-close]),input,select')?.focus();
 sheetRoot.querySelector('.sheet').onkeydown=e=>{if(e.key!=='Tab')return;const controls=[...sheetRoot.querySelectorAll('button,input,select,textarea,a[href]')].filter(el=>!el.disabled);if(e.shiftKey&&document.activeElement===controls[0]){e.preventDefault();controls.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===controls.at(-1)){e.preventDefault();controls[0]?.focus();}};
}
function closeSheet(){sheetCleanup?.();sheetCleanup=undefined;sheetRoot.innerHTML='';chatOpen=false;if(previousFocus?.isConnected)previousFocus.focus();cleanup?.focus?.();}
const appearanceOptions={skinTone:[['deep','Deep'],['brown','Brown'],['warm','Warm'],['light','Light']],hair:[['crop','Low cut'],['afro','Afro'],['locs','Locs'],['braids','Braids'],['bald','Shaved']],top:[['forest','Forest tee'],['ochre','Ochre tee'],['cream','Cream shirt'],['navy','Navy shirt'],['agbada','Agbada']],body:[['regular','Regular'],['slim','Slim'],['broad','Broad']],face:[['oval','Oval'],['round','Round'],['angular','Angular']],presentation:[['neutral','Your style'],['feminine','Feminine'],['masculine','Masculine']],facialHair:[['none','Clean shaven'],['beard','Beard']],bottom:[['charcoal','Charcoal'],['denim','Denim'],['cream','Cream']],shoes:[['white','White trainers'],['black','Black shoes']],accessory:[['none','None'],['glasses','Glasses']]};
function appearanceFields(appearance,compact=false){const paid={cream:'linen-shirt',navy:'office-shirt',agbada:'traditional-set'};return Object.entries(appearanceOptions).filter(([key])=>!compact||['skinTone','hair','top'].includes(key)).map(([key,options])=>`<label>${({skinTone:'Skin tone',top:'Outfit',facialHair:'Facial hair',bottom:'Trousers',presentation:'Presentation'})[key]||key[0].toUpperCase()+key.slice(1)}<select name="${key}" data-appearance>${options.map(([value,label])=>{const locked=key==='top'&&paid[value]&&!state.profile?.inventory?.includes(paid[value]);return `<option value="${value}" ${appearance[key]===value?'selected':''} ${locked?'disabled':''}>${label}${locked?' · City Market':''}</option>`;}).join('')}</select></label>`).join('');}
function renderAuth(){
 root.innerHTML=`<main class="welcome"><div class="welcome-art"><div class="welcome-brand">Abuja<span>Life</span><i></i></div><div id="welcome-scene"></div><div class="welcome-title"><span class="eyebrow">YOUR CITY. YOUR PEOPLE.</span><h1>A life<br>of your own.</h1><p>Make Abuja home.</p></div><div class="welcome-geography">Abuja, Federal Capital Territory · Nigeria</div></div><section class="welcome-form"><div class="auth-switch"><button data-mode="register" class="${authMode==='register'?'active':''}">Create a resident</button><button data-mode="login" class="${authMode==='login'?'active':''}">Sign in</button></div><h2>${authMode==='register'?'Start your next chapter.':'Welcome home.'}</h2><form id="auth-form"><div class="auth-portrait">${avatarSVG(draft,{size:145,fullBody:true})}</div>${authMode==='register'?'<label>Your name<input name="displayName" required maxlength="40" autocomplete="nickname" placeholder="What should people call you?"></label>':''}<label>Username<input name="username" required minlength="3" maxlength="24" pattern="[A-Za-z0-9_]+" autocomplete="username" placeholder="e.g. zara_abuja" autocapitalize="none"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="${authMode==='register'?'new-password':'current-password'}" placeholder="At least 8 characters"></label>${authMode==='register'?`<div class="appearance-fields compact">${appearanceFields(draft,true)}</div>`:''}<p class="form-error" id="auth-error" role="alert"></p><button type="submit" class="primary auth-submit">${authMode==='register'?'Begin your life':'Sign in'}${icon('arrow')}</button><p class="auth-note">Your progress saves as you play. Abuja Naira is virtual game money.</p></form></section></main>`;
 cleanup=renderWorld(document.querySelector('#welcome-scene'),{profile:{appearance:draft,location:{kind:'home'},home:{name:'Garki starter studio'}},place:{id:'garki-i',name:'Garki I'},people:[],onInteract:()=>{},onResident:()=>{}});
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;renderMain();});
 root.querySelectorAll('[data-appearance]').forEach(s=>s.onchange=()=>{draft[s.name]=s.value;root.querySelector('.auth-portrait').innerHTML=avatarSVG(draft,{size:145,fullBody:true});});
 document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,submit=form.querySelector('[type=submit]');submit.disabled=true;const values=Object.fromEntries(new FormData(form));if(authMode==='register')values.appearance=draft;try{state=await api(`/api/auth/${authMode}`,{method:'POST',body:values});view='world';renderMain();connectRealtime();toast('Welcome home.');}catch(error){document.querySelector('#auth-error').textContent=error.message;submit.disabled=false;}};
}
function renderOnboarding(){
 const p=state.profile;
 onboardingDraft||={displayName:p.displayName||'Abuja resident',appearance:{...draft,...p.appearance},lifeGoal:p.lifeGoal||list(state.lifeGoals)[0]?.id||'career'};
 const goals=list(state.lifeGoals).length?list(state.lifeGoals):[{id:'career',name:'Build my career',description:'Find work, learn skills and grow your income.'},{id:'home',name:'Make a home',description:'Find your place, furnish it and build a life.'},{id:'social',name:'Explore the city',description:'Go out, meet people and find your favourite places.'}];
 const stepContent=[`<span class="eyebrow">01 · YOUR RESIDENT</span><h1>Who will you be?</h1><p class="muted">Make a character that feels like you. You can change your look later.</p><label>Your name<input name="displayName" value="${esc(onboardingDraft.displayName)}" required minlength="2" maxlength="40" autocomplete="nickname"></label><div class="appearance-fields onboarding-appearance">${appearanceFields(onboardingDraft.appearance)}</div>`,
 `<span class="eyebrow">02 · YOUR LIFE IN ABUJA</span><h1>What’s your first chapter?</h1><p class="muted">Choose a direction for your first day. It is a guide; you can change your plans whenever you want.</p><div class="life-goals">${goals.map((goal,index)=>`<label class="life-goal"><input type="radio" name="lifeGoal" value="${esc(goal.id)}" ${goal.id===onboardingDraft.lifeGoal?'checked':''} required><span class="life-goal-icon">${icon(index===0?'work':index===1?'world':'map')}</span><span><strong>${esc(goal.name||goal.title||goal.label)}</strong><small>${esc(goal.description||goal.detail||'Choose your own pace.')}</small></span>${icon('check')}</label>`).join('')}</div><div class="starter-life"><span>${icon('world')}</span><div><strong>${esc(p.home?.name||'Your starter studio')}</strong><p>A home to start from, ₦${money(p.wallet)} to make your first choices. Work pays for the bigger plans.</p></div></div>`,
 `<span class="eyebrow">03 · TAKE CONTROL</span><h1>The city is yours to explore.</h1><p class="muted">Walk through your front door, cross the neighbourhood and enter the places you see.</p><div class="control-guide"><div><span class="control-keys"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><strong>Move your resident</strong><small>Arrow keys work too. Use the joystick on your phone.</small></div><div><span class="control-keys"><kbd>Shift</kbd><kbd>E</kbd></span><strong>Run and interact</strong><small>Hold Shift to run. Press E near a door or object.</small></div><div><span class="control-keys">${icon('map')}</span><strong>Choose where to go</strong><small>Open Places, pick a destination and watch your resident walk there.</small></div></div><p class="onboarding-note">Abuja Naira, houses and vehicles are virtual game items. Your choices save as you play.</p>`][onboardingStep];
 root.innerHTML=`<main class="resident-onboarding"><aside class="onboarding-preview"><div class="onboarding-wordmark wordmark">Abuja<span>Life</span><i></i></div><span class="onboarding-city">ABUJA · NIGERIA</span><div class="onboarding-avatar" id="onboarding-avatar">${avatarSVG(onboardingDraft.appearance,{size:330,fullBody:true})}</div><div class="onboarding-resident-name" id="onboarding-resident-name">${esc(onboardingDraft.displayName)}</div><p>Your story starts here.</p></aside><section class="onboarding-details"><div class="onboarding-steps" aria-label="Character setup progress">${['Your character','Your direction','Your controls'].map((label,i)=>`<span class="${i===onboardingStep?'current':i<onboardingStep?'done':''}"><i>${i<onboardingStep?'✓':i+1}</i>${label}</span>`).join('')}</div><form id="onboarding-form">${stepContent}<p class="form-error" id="onboarding-error" role="alert"></p><div class="onboarding-buttons">${onboardingStep?'<button class="secondary" type="button" data-onboarding-back>Back</button>':''}<button class="primary" type="submit" ${onboardingStep===2?'id="begin-life"':'data-onboarding-next'}>${onboardingStep===2?'Start playing':'Continue'}${icon('arrow')}</button></div></form></section></main>`;
 const form=root.querySelector('#onboarding-form');
 form.querySelectorAll('[data-appearance]').forEach(select=>select.onchange=()=>{onboardingDraft.appearance[select.name]=select.value;root.querySelector('#onboarding-avatar').innerHTML=avatarSVG(onboardingDraft.appearance,{size:330,fullBody:true});});
 form.querySelector('[name=displayName]')?.addEventListener('input',e=>{onboardingDraft.displayName=e.target.value;root.querySelector('#onboarding-resident-name').textContent=e.target.value||'Your resident';});
 form.querySelector('[data-onboarding-back]')?.addEventListener('click',()=>{onboardingStep--;renderMain();});
 form.onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(form));if(values.displayName)onboardingDraft.displayName=values.displayName.trim();if(values.lifeGoal)onboardingDraft.lifeGoal=values.lifeGoal;if(onboardingStep<2){onboardingStep++;renderMain();window.scrollTo(0,0);return;}const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await api('/api/profile',{method:'POST',body:{...onboardingDraft,onboardingComplete:true}});onboardingDraft=undefined;onboardingStep=0;view='world';await refresh();toast('Your life in Abuja starts now. Walk to your door to explore.');}catch(error){root.querySelector('#onboarding-error').textContent=error.message;submit.disabled=false;}};
}
function header(){const p=state.profile,loc=place(p.district);return `<header class="game-header"><a href="#world" class="wordmark" data-view="world" aria-label="AbujaLife home">Abuja<span>Life</span><i></i></a><div class="header-place">${esc(loc?.name||'Abuja')}<span>${p.location?.kind==='home'?'Your home':currentVenue()?.name||'Your neighbourhood'}</span></div><button class="wallet-button" data-phone="wallet" aria-label="Open wallet"><span>ABUJA NAIRA</span><strong>₦${money(p.wallet)}</strong></button><button class="resident-button" data-view="profile" aria-label="Your resident profile">${avatarSVG(p.appearance,{size:40})}</button></header>`;}
function nav(){const unread=list(state.conversations).reduce((n,c)=>n+Number(c.unread||0),0)+list(state.notifications).filter(n=>!n.readAt&&!n.read).length;return `<nav class="game-nav" aria-label="Game navigation">${[['world','Home'],['map','Explore'],['work','Work']].map(([id,label])=>`<button data-view="${id}" class="${view===id?'active':''}" ${view===id?'aria-current="page"':''}>${icon(id)}<span>${label}</span></button>`).join('')}<button data-phone="home" class="phone-launch">${icon('phone')}<span>Phone</span>${unread?`<i class="nav-badge">${unread}</i>`:''}</button></nav>`;}
function renderMain(){
 cleanup?.();cleanup=undefined;if(!state.authenticated){renderAuth();return;}
 if(!state.profile?.onboardingComplete){phone.close();renderOnboarding();return;}
 if(!['world','map','work','market','property','profile'].includes(view))view='world';
 root.innerHTML=`<div class="game-shell ${view==='world'?'is-playing':''}">${header()}<main class="game-content view-${view}">${({world:worldMarkup,map:mapMarkup,work:workMarkup,market:marketMarkup,property:propertyMarkup,profile:profileMarkup})[view]()}</main>${nav()}</div>`;
 root.querySelectorAll('[data-view]').forEach(b=>b.onclick=e=>{e.preventDefault();navigate(b.dataset.view);});root.querySelectorAll('[data-phone]').forEach(b=>b.onclick=()=>phone.open(b.dataset.phone==='home'?undefined:b.dataset.phone));
 ({world:bindWorld,map:bindMap,work:bindWork,market:bindMarket,property:bindProperties,profile:bindProfile})[view]();
}
function worldMarkup(){
 const p=state.profile,atHome=p.location?.kind==='home',venue=currentVenue(),loc=place(p.district),car=list(state.catalog).find(i=>i.id===p.drivingVehicle),goal=list(state.lifeGoals).find(g=>g.id===p.lifeGoal);
 const guide=p.activeTrip?'Your journey is under way.':atHome?'Walk to the front door to explore your neighbourhood.':venue?`You’re inside ${venue.name}. Walk near an object and interact.`:p.drivingVehicle?'You’re driving. Follow the roads and stop near a destination.':'Walk to a door to enter. Open Places to choose your destination.';
 return `<div class="scene-heading"><div><span class="eyebrow">${p.drivingVehicle?'BEHIND THE WHEEL':venue?esc(venue.category||'AROUND THE CITY'):atHome?'YOUR PLACE':'YOUR NEIGHBOURHOOD'}</span><h1>${venue?esc(venue.name):atHome?esc(p.home?.name||'Your home'):esc(loc?.name||'Abuja')}</h1></div><button class="quiet-button" data-day>${icon('sun')}<span>Your needs</span></button></div><section class="world-stage playable-stage" aria-label="Your playable location"><div id="world-scene"></div><div class="play-hud"><div class="play-clock"><i class="state-dot"></i><span data-world-time>${playTime()}</span><small>ABUJA</small></div><div class="play-needs">${[['energy','Energy'],['hunger','Food'],['fun','Fun']].map(([id,label])=>`<span><small>${label}</small><i><b style="width:${Math.max(0,Math.min(100,p[id]||0))}%"></b></i></span>`).join('')}</div></div>${p.activeTrip?tripMarkup(p.activeTrip):''}<div class="play-guide"><span class="eyebrow">${car?esc(car.name):esc(goal?.name||goal?.title||'YOUR FIRST CHAPTER')}</span><p>${esc(guide)}</p></div><button class="play-chat icon-button" data-chat aria-label="Nearby residents and chat">${icon('chat')}</button></section><div class="world-toolbar" aria-label="Game actions">${[...(venue?[['activity','sun','Do something']]:[]),['places','map','Places'],['garage','map','Garage'],['furnish','world','Furnish'],['houses','world','Homes'],['work','work','Work']].map(([id,symbol,label])=>`<button data-world-tool="${id}">${icon(symbol)}<span>${label}</span></button>`).join('')}</div><div class="world-footer"><div class="status-summary"><i class="state-dot"></i><span>${p.drivingVehicle?'Driving your own car':atHome?'Your furniture. Your home.':venue?'Inside · Explore the room':`${list(state.nearby).length} residents nearby`}</span></div><button class="text-button" id="world-door">${atHome?'Step outside':venue?'Exit to the street':'Go home'}${icon('arrow')}</button></div>`;
}
function tripMarkup(trip){return `<div class="trip-banner" role="status"><span class="eyebrow">ON THE WAY · ${esc(trip.mode)}</span><strong>${esc(place(trip.destination)?.name||trip.destination)}</strong><span data-trip-countdown>Arriving soon</span><button class="primary" data-arrive disabled>Arrive</button></div>`;}
function bindWorld(){
 const p=state.profile;cleanup=renderWorld(document.querySelector('#world-scene'),{profile:p,place:place(p.district),people:list(state.nearby),venues:list(state.venues),venueActions:list(state.venueActions),catalog:list(state.catalog),onInteract:interact,onResident:residentSheet,onArrive:async tripId=>{if(p.activeTrip&&Date.now()>=Number(p.activeTrip.arrivesAt)){if(await action('arrive',{tripId:tripId||p.activeTrip.id})){toast('You’ve arrived.');if(pendingVenue){const venueId=pendingVenue;pendingVenue=undefined;perform('enter-venue',{venueId});}}}}});
 document.querySelector('[data-day]').onclick=()=>openSheet(`<span class="eyebrow">YOUR DAY</span><h2 id="sheet-title">How you’re doing</h2><div class="daily-needs">${[['Energy','energy'],['Food','hunger'],['Cleanliness','hygiene'],['Social','social'],['Fun','fun'],['Stress','stress']].map(([label,key])=>`<div><label>${label}<span>${p[key]??0}%</span></label><progress max="100" value="${p[key]??0}" aria-label="${label}"></progress></div>`).join('')}</div><p class="muted">Rest at home, get something to eat, or spend time in the city. Find a rhythm that works for you.</p>`);
 document.querySelector('[data-chat]').onclick=openLocalChat;
 document.querySelector('#world-door').onclick=()=>{if(p.location?.kind==='home'){perform('leave-home');return;}if(currentVenue()){perform('exit-venue');return;}if(p.district===p.home.district){perform('enter-home');return;}travelSheet(p.home.district,true);};
 root.querySelectorAll('[data-world-tool]').forEach(button=>button.onclick=()=>({activity:()=>openVenueMenu(currentVenue()),places:openCityPlaces,garage:openGarage,furnish:openFurniture,houses:()=>navigate('property'),work:()=>navigate('work')})[button.dataset.worldTool]());
 const worldCleanup=cleanup,timeTimer=setInterval(()=>{const el=root.querySelector('[data-world-time]');if(el)el.textContent=playTime();},30000);cleanup=Object.assign(()=>{clearInterval(timeTimer);worldCleanup?.();},worldCleanup);
 if(p.activeTrip)bindTrip(p.activeTrip);
}
function bindTrip(trip){const update=()=>{const left=Math.max(0,Math.ceil((Number(trip.arrivesAt)-Date.now())/1000));const el=root.querySelector('[data-trip-countdown]'),button=root.querySelector('[data-arrive]');if(el&&button){el.textContent=left?`${left}s to go`:'You’ve arrived';button.disabled=left>0;}};update();const timer=setInterval(update,250),previous=cleanup;cleanup=Object.assign(()=>{clearInterval(timer);previous?.();},previous);root.querySelector('[data-arrive]').onclick=async()=>{if(await action('arrive',{tripId:trip.id})){toast('You’ve arrived.');if(pendingVenue){const venueId=pendingVenue;pendingVenue=undefined;perform('enter-venue',{venueId});}}};}
async function interact(name,payload={}){
 if(name==='enter-venue'){if(await action(name,payload))toast(`You’re inside ${currentVenue()?.name||'your destination'}.`);return;}
 if(name==='exit-venue'){return await action(name,payload);}
 if(name==='venue-menu'||name==='venue-actions'){openVenueMenu(currentVenue());return;}
 if(name==='venue-action'){const activity=list(state.venueActions).find(a=>a.id===payload.activityId);if(!payload.activityId){openVenueMenu(currentVenue());return;}if(await action(name,payload))toast(`${activity?.name||'Activity'} complete.`);return;}
 if(name==='toggle-driving'){if(await action(name,payload))toast(state.profile.drivingVehicle?'You’re in your car. Use the controls to drive.':'You’re back on foot.');return;}
 if(name==='place-furniture'){if(await action(name,payload))toast('Furniture placed. Open Furnish to move it again.');return;}
 if(name==='dealership'||name==='garage'){openGarage();return;}
 if(name==='estate-office'||name==='houses'){navigate('property');return;}
 if(name==='market'){if(payload.category==='furniture')openFurniture();else navigate('market');return;}
 if(name==='furniture-store'||name==='furnish'){if(payload.itemId)beginFurniturePlacement(payload.itemId);else openFurniture();return;}
 if(name==='wardrobe'){navigate('profile');return;}if(['leave-home','enter-home'].includes(name)){return await action(name);}
 const info={eat:['In the kitchen','Make a meal','A warm plate and a little time to yourself.','₦1,200'],sleep:['In the bedroom','Get some rest','Put your feet up and recharge.','Free'],shower:['In the bathroom','Freshen up','A shower makes a difference to your day.','Free'],relax:['On the sofa','Take a breather','Switch off for a moment.','Free'],hangout:['Out in the city','Spend time out','Enjoy the neighbourhood. Invite a friend from your phone.','₦2,400'],exercise:['In the fresh air','Go for a run','Clear your head and get moving.','₦800'],cinema:['An evening out','Watch a film','A little escape from your usual day.','₦3,800']}[name];if(!info)return;
 const cost=state.activities?.[name]?.cost;const costLabel=cost===undefined?info[3]:cost===0?'Free':`₦${money(cost)}`;
 openSheet(`<span class="eyebrow">${info[0]}</span><h2 id="sheet-title">${info[1]}</h2><p class="muted">${info[2]}</p><div class="detail-line"><span>Virtual cost</span><strong>${costLabel}</strong></div><button class="primary full" id="confirm-interaction">${info[1]}${icon('arrow')}</button>`);
 document.querySelector('#confirm-interaction').onclick=async()=>{if(await action(name)){closeSheet();toast('A little better than before.');}};
}
async function goOutdoors(){
 if(state.profile.drivingVehicle){if(!await action('toggle-driving',{vehicleId:null}))return false;}
 if(state.profile.location?.kind==='home')return Boolean(await (cleanup?.performAsync?cleanup.performAsync('leave-home'):action('leave-home')));
 if(currentVenue())return Boolean(await (cleanup?.performAsync?cleanup.performAsync('exit-venue'):action('exit-venue')));
 return true;
}
async function goToVenue(venueId){
 const venue=list(state.venues).find(v=>v.id===venueId);if(!venue)return;
 closeSheet();if(venue.district&&venue.district!==state.profile.district){pendingVenue=venueId;travelSheet(venue.district);return;}
 if(!await goOutdoors())return;
 if(view!=='world')navigate('world');
 perform('enter-venue',{venueId});toast(`Making your way to ${venue.name}.`);
}
function openCityPlaces(){
 const venue=currentVenue();
 openSheet(`<span class="eyebrow">${esc(place(state.profile.district)?.name||'YOUR NEIGHBOURHOOD')}</span><h2 id="sheet-title">Where shall we go?</h2><p class="muted">Choose a place and your resident will walk to the entrance. These are authored game venues in your neighbourhood.</p><div class="city-places">${list(state.venues).map(v=>`<button class="city-place ${venue?.id===v.id?'current':''}" data-city-venue="${esc(v.id)}"><span class="venue-marker venue-${esc(v.id)}">${icon(v.id==='park'?'sun':v.id==='gym'?'profile':v.id==='restaurant'||v.id==='cafe'?'world':'map')}</span><span><small>${esc(v.category||'Around the city')}</small><strong>${esc(v.name)}</strong><p>${esc(v.description||'Explore this neighbourhood spot.')}</p></span>${icon('arrow')}</button>`).join('')}</div><button class="secondary full" data-city-map>Explore another district${icon('map')}</button>`,{wide:true});
 sheetRoot.querySelectorAll('[data-city-venue]').forEach(button=>button.onclick=()=>goToVenue(button.dataset.cityVenue));
 sheetRoot.querySelector('[data-city-map]').onclick=()=>navigate('map');
}
function effectLabel(activity){return Object.entries(activity.effects||{}).map(([key,value])=>`${value>0?'+':''}${value} ${({hunger:'food',hygiene:'cleanliness'})[key]||key}`).join(' · ');}
function openVenueMenu(venue){
 if(!venue)return;
 if(venue.id==='dealership'){openGarage();return;}if(venue.id==='furniture-store'){openFurniture();return;}if(venue.id==='estate-office'){navigate('property');return;}
 const activities=venueActions(venue);
 openSheet(`<span class="eyebrow">${esc(venue.category||'YOUR DESTINATION')}</span><h2 id="sheet-title">${esc(venue.name)}</h2><p class="muted">${esc(venue.description||'Take your time and enjoy the city.')}</p><div class="venue-menu">${activities.map(activity=>`<article class="venue-menu-item"><div><strong>${esc(activity.name||activity.title)}</strong><small>${esc(effectLabel(activity))}</small><span>${activity.cost?`₦${money(activity.cost)}`:'Free'} · ${activity.duration||5}s activity</span></div><button class="primary" data-venue-activity="${esc(activity.id)}" ${state.profile.wallet<(activity.cost||0)?'disabled':''}>${activity.cost?'Choose':'Start'}</button></article>`).join('')||'<p class="muted">Explore the room, then walk to the exit when you are ready.</p>'}</div><p class="economy-note">Virtual game prices. Activities change your resident’s needs.</p>`);
 sheetRoot.querySelectorAll('[data-venue-activity]').forEach(button=>button.onclick=()=>{const activityId=button.dataset.venueActivity;closeSheet();perform('venue-action',{activityId});});
}
function vehicleArt(item){const tall=/suv/i.test(item.id),premium=/premium|sedan/i.test(item.id),color=premium?'#334d62':/hatchback/i.test(item.id)?'#b87541':'#667c66';return `<svg class="vehicle-art" viewBox="0 0 260 128" role="img" aria-label="${esc(item.name)}"><ellipse cx="133" cy="109" rx="96" ry="9" fill="#223b2914"/><path d="M28 85 39 61l39-5 20-${tall?32:24}h66l30 ${tall?29:23} 34 7 14 28v14H27Z" fill="${color}"/><path d="m100 ${tall?27:35}h30v26H81Zm36 0h26l26 26h-52Z" fill="#cee1df"/><path d="M130 29v52M197 65v30M67 64v29" fill="none" stroke="#fff4" stroke-width="2"/><rect x="143" y="68" width="11" height="3" rx="1" fill="#c9d3ce"/><circle cx="70" cy="100" r="19" fill="#24322f"/><circle cx="70" cy="100" r="10" fill="#a3aeaa"/><circle cx="200" cy="100" r="19" fill="#24322f"/><circle cx="200" cy="100" r="10" fill="#a3aeaa"/><path d="M31 76h17v10H28M224 77h13v10h-13" fill="#f3db9c"/></svg>`;}
function openGarage(){
 const cars=list(state.catalog).filter(item=>item.category==='vehicle'),owned=cars.filter(item=>state.profile.inventory.includes(item.id)),first=cars.find(item=>!state.profile.inventory.includes(item.id));
 openSheet(`<span class="eyebrow">YOUR OWN WHEELS</span><h2 id="sheet-title">The garage</h2><p class="muted">Buy a car with Abuja Naira, walk to it and take the wheel. Park before going inside a venue.</p>${!owned.length&&first?`<div class="garage-goal"><strong>Your first car · ₦${money(first.price)}</strong><span>${first.price>state.profile.wallet?`Save ₦${money(first.price-state.profile.wallet)} more. A paid shift can get you closer.`:'You can afford your first set of wheels.'}</span><button class="text-button" data-find-work>Find work${icon('arrow')}</button></div>`:''}<div class="garage-cars">${cars.map(item=>{const has=state.profile.inventory.includes(item.id),driving=state.profile.drivingVehicle===item.id;return `<article class="garage-card ${has?'owned':''}">${vehicleArt(item)}<span class="eyebrow">${has?'YOUR VEHICLE':'VIRTUAL VEHICLE'}</span><h3>${esc(item.name)}</h3><p>${esc(item.description||'Your own way to get around the city.')}</p><div class="garage-card-bottom"><strong>₦${money(item.price)}</strong>${has?`<button class="primary" data-drive="${esc(item.id)}">${driving?'Park & get out':'Drive'}</button>`:`<button class="secondary" data-purchase="${esc(item.id)}" ${state.profile.wallet<item.price?'disabled':''}>Buy car</button>`}</div></article>`;}).join('')}</div><p class="economy-note">Cars are virtual game items. Road travel uses game time and virtual fares.</p>`,{wide:true});
 sheetRoot.querySelector('[data-find-work]')?.addEventListener('click',()=>navigate('work'));
 sheetRoot.querySelectorAll('[data-purchase]').forEach(button=>button.onclick=async()=>{if(await action('purchase',{itemId:button.dataset.purchase})){openGarage();toast('Your car is waiting outside.');}});
 sheetRoot.querySelectorAll('[data-drive]').forEach(button=>button.onclick=async()=>{const vehicleId=button.dataset.drive,driving=state.profile.drivingVehicle===vehicleId;closeSheet();if(!driving&&!await goOutdoors())return;if(view!=='world')navigate('world');perform('toggle-driving',{vehicleId:driving?null:vehicleId});});
}
function furnitureArt(item){const id=item.id;return `<div class="furniture-art furniture-${/sofa|couch/.test(id)?'sofa':/bed/.test(id)?'bed':/table|desk/.test(id)?'table':/lamp/.test(id)?'lamp':/plant/.test(id)?'plant':'object'}"><i></i><b></b><span></span></div>`;}
function openFurniture(){
 const items=list(state.catalog).filter(item=>item.category==='furniture'),atHome=state.profile.location?.kind==='home',furnitureState=cleanup?.getFurnitureState?.();
 openSheet(`<span class="eyebrow">MAKE YOUR SPACE YOURS</span><h2 id="sheet-title">Room & living</h2><p class="muted">Buy the pieces you like. At home, choose Place and tap an open spot on the floor. Press R to rotate; Escape cancels.</p>${!atHome?'<div class="furniture-location-note">You can shop here. Furniture placement is available inside your own home.</div>':''}<div class="furniture-catalog">${items.map(item=>{const owned=state.profile.inventory.includes(item.id),stored=furnitureState?.stored?.includes(item.id),placed=furnitureState?furnitureState.placed.includes(item.id):Boolean(state.profile.furnitureLayout?.[item.id]||list(state.profile.furnitureLayout).find(layout=>layout.itemId===item.id));return `<article class="furniture-card">${furnitureArt(item)}<div><span class="eyebrow">${owned?stored?'IN STORAGE':placed?'IN YOUR ROOM':'OWNED':'FURNITURE'}</span><h3>${esc(item.name)}</h3><p>${esc(item.description||'A piece for your own home.')}</p><strong>₦${money(item.price)}</strong></div>${owned?`<button class="primary" data-place-furniture="${esc(item.id)}" ${atHome?'':'disabled'}>${placed?'Move':'Place'}</button>`:`<button class="secondary" data-purchase="${esc(item.id)}" ${state.profile.wallet<item.price?'disabled':''}>Buy</button>`}</article>`;}).join('')}</div><p class="economy-note">Furniture stays in your inventory if you move homes. Pieces that do not fit safely remain in storage. Arrange them again in your next space.</p>`,{wide:true});
 sheetRoot.querySelectorAll('[data-purchase]').forEach(button=>button.onclick=async()=>{if(await action('purchase',{itemId:button.dataset.purchase})){openFurniture();toast('It’s yours. Choose where it belongs.');}});
 sheetRoot.querySelectorAll('[data-place-furniture]').forEach(button=>button.onclick=()=>beginFurniturePlacement(button.dataset.placeFurniture));
}
function beginFurniturePlacement(itemId){
 if(state.profile.location?.kind!=='home'){toast('Head home to place your furniture.');return;}closeSheet();if(view!=='world')navigate('world');cleanup?.setFurnitureMode?.(itemId);toast('Tap an open floor spot to place it. Press R to rotate.');
}
function mapMarkup(){return `<div class="page-heading"><span class="eyebrow">ABUJA & THE WIDER FCT</span><h1>Find your next place.</h1><p>City districts, satellite towns, and six Area Councils.</p></div><section class="map-stage" id="map-root" aria-label="Abuja map"></section>`;}
function bindMap(){cleanup=renderMap(document.querySelector('#map-root'),{atlas:state.atlas,profile:state.profile,onSelect:()=>{},onTravel:id=>travelSheet(typeof id==='string'?id:id.id)});}
function travelSheet(district,returningHome=false){
 const destination=place(district);if(!destination)return;
 const ownsCar=list(state.catalog).some(item=>item.category==='vehicle'&&state.profile.inventory.includes(item.id));
 openSheet(`<span class="eyebrow">GETTING AROUND</span><h2 id="sheet-title">${esc(destination.name)}</h2><p class="muted">${esc(destination.vibe||'Make your way across Abuja.')}</p><form id="travel-form"><label>How are you going?<select name="mode">${list(state.transportModes).map(mode=>`<option value="${esc(mode.id||mode.mode)}" ${mode.id==='bus'?'selected':''} ${mode.id==='walk'&&district!==state.profile.district||mode.id==='car'&&!ownsCar?'disabled':''}>${esc(mode.name||mode.label||mode.id)}</option>`).join('')||'<option value="bus">Bus</option><option value="taxi">Taxi</option><option value="ride">Ride-hailing</option>'}</select></label><div class="detail-line" id="travel-quote" aria-live="polite">Checking your fare…</div><p class="muted">Fares use virtual Abuja Naira. Travel time is compressed for gameplay.</p><button class="primary full" type="submit" disabled>Start journey${icon('arrow')}</button></form>`);
 const form=document.querySelector('#travel-form');let quoteSequence=0;
 const getQuote=async()=>{const sequence=++quoteSequence;form.querySelector('[type=submit]').disabled=true;try{const result=await api(`/api/travel/quote?district=${encodeURIComponent(district)}&mode=${encodeURIComponent(form.elements.mode.value)}`);if(sequence!==quoteSequence||!form.isConnected)return;form.querySelector('#travel-quote').innerHTML=`<span>${result.quote.seconds}s journey</span><strong>₦${money(result.quote.cost)}</strong>`;form.querySelector('[type=submit]').disabled=false;}catch(error){if(form.isConnected)form.querySelector('#travel-quote').textContent=error.message;}};
 form.elements.mode.onchange=getQuote;getQuote();
 document.querySelector('#travel-form').onsubmit=async e=>{e.preventDefault();const mode=new FormData(e.currentTarget).get('mode');closeSheet();if(view!=='world')navigate('world');if(!await goOutdoors())return;if(await action(returningHome?'return-home':'travel',{district,mode})){navigate('world');toast('Your journey has started.');}};
}
function workMarkup(){
 const p=state.profile,jobs=list(state.jobs),current=jobs.find(j=>j.id===(selectedJob||p.job)),challenge=state.activeChallenge||p.activeChallenge;
 return `<div class="page-heading"><span class="eyebrow">MAKE YOUR WAY</span><h1>A good day’s work.</h1><p>Choose your path. Learn on the job. Build a reputation.</p></div>${challenge?`<section class="work-challenge"><span class="eyebrow">ON YOUR SHIFT</span><h2>${esc(challenge.title||'Your shift')}</h2><form id="shift-form">${(challenge.tasks||[]).map((task,index)=>`<fieldset><legend><span>${index+1}</span>${esc(task.prompt)}</legend>${task.options.map(option=>`<label class="task-option"><input type="radio" name="${esc(task.id)}" value="${esc(option.id)}" required><span>${esc(option.label)}</span></label>`).join('')}</fieldset>`).join('')}<button class="primary full" type="submit">Finish your shift${icon('check')}</button></form></section>`:`<div class="job-list">${jobs.map(job=>`<button class="job-row ${job.id===p.job?'chosen':''}" data-job="${esc(job.id)}"><span class="job-monogram">${esc((job.skill||job.title||'J').slice(0,1))}</span><span><strong>${esc(job.title)}</strong><small>${esc(place(job.district)?.name||'Abuja')} · ${esc(job.skill||'Career')}${job.id===p.job?' · Your job':''}</small></span><span class="job-salary">₦${money(job.pay)}<small>per shift</small></span>${icon('arrow')}</button>`).join('')}</div>${current?`<section class="job-detail"><span class="eyebrow">${esc(current.skill||'YOUR NEXT CHAPTER')}</span><h2>${esc(current.title)}</h2><p class="muted">Work in ${esc(place(current.district)?.name||'Abuja')}. Each shift brings a few real decisions and a chance to improve.</p><div class="detail-line"><span>Shift pay</span><strong>₦${money(current.pay)}</strong></div><div class="detail-line"><span>Energy needed</span><strong>${current.energy}%</strong></div>${p.job===current.id?`<button class="primary full" data-start-shift>${p.district!==current.district?'Travel to work':p.location?.kind==='home'?'Step outside to work':'Begin your shift'}${icon('arrow')}</button>`:`<button class="primary full" data-take-job="${esc(current.id)}">Take this job${icon('arrow')}</button>`}</section>`:''}`}`;
}
function bindWork(){
 root.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>{selectedJob=b.dataset.job;renderMain();});root.querySelector('[data-take-job]')?.addEventListener('click',async e=>{if(await action('take-job',{jobId:e.currentTarget.dataset.takeJob}))toast('Your new chapter starts here.');});
 root.querySelector('[data-start-shift]')?.addEventListener('click',async()=>{const job=list(state.jobs).find(j=>j.id===state.profile.job);if(state.profile.district!==job.district){travelSheet(job.district);return;}if(state.profile.location?.kind==='home'){await action('leave-home');toast('You’re outside. Begin your shift when you’re ready.');return;}await action('start-shift');});
 root.querySelector('#shift-form')?.addEventListener('submit',async e=>{e.preventDefault();const challenge=state.activeChallenge||state.profile.activeChallenge,answers=[...new FormData(e.currentTarget)].map(([taskId,optionId])=>({taskId,optionId})),before=state.profile.wallet;if(await action('complete-shift',{challengeId:challenge.id,answers}))toast(`Shift complete. ₦${money(state.profile.wallet-before)} earned.`);});
}
function marketMarkup(){const items=list(state.catalog).filter(i=>marketFilter==='all'||i.category===marketFilter),categories=[...new Set(list(state.catalog).map(i=>i.category))];return `<div class="page-heading"><span class="eyebrow">CITY MARKET</span><h1>A little more you.</h1><p>Clothes, furniture, and things for your life. All virtual, all bought with Abuja Naira.</p></div><div class="filter-row">${['all',...categories].map(c=>`<button data-filter="${esc(c)}" class="${marketFilter===c?'active':''}">${esc(c)}</button>`).join('')}</div><div class="market-list">${items.map(i=>`<article class="market-row"><div class="item-symbol">${icon(i.category==='clothing'?'profile':i.category==='vehicle'?'map':'world')}</div><div><span class="eyebrow">${esc(i.category)}</span><h2>${esc(i.name)}</h2><p>${esc(i.description||'')}</p><strong>₦${money(i.price)}</strong></div><button class="secondary" data-purchase="${esc(i.id)}" ${state.profile.inventory?.includes(i.id)?'disabled':''}>${state.profile.inventory?.includes(i.id)?'Owned':'Buy'}</button></article>`).join('')}</div>`;}
function bindMarket(){root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{marketFilter=b.dataset.filter;renderMain();});root.querySelectorAll('[data-purchase]').forEach(b=>b.onclick=async()=>{if(await action('purchase',{itemId:b.dataset.purchase}))toast('It’s yours.');});}
function houseArt(h){const villa=h.type==='villa',terrace=h.type==='terrace',apartment=h.type==='apartment',floors=apartment?3:villa||terrace?2:1;return `<svg class="house-art" viewBox="0 0 440 205" role="img" aria-label="${esc(h.type||'Home')} exterior illustration"><defs><linearGradient id="sky-${esc(h.id)}" x2="0" y2="1"><stop stop-color="#dae4df"/><stop offset="1" stop-color="#f7f0dc"/></linearGradient></defs><rect width="440" height="205" fill="url(#sky-${esc(h.id)})"/><circle cx="355" cy="44" r="24" fill="#f5d08b"/><path d="M0 152h440v53H0Z" fill="#cbd4b6"/><ellipse cx="230" cy="183" rx="154" ry="10" fill="#52665420"/><path d="M73 80 215 34 361 80Z" fill="${villa?'#5b6565':'#816855'}"/><rect x="88" y="80" width="260" height="99" fill="${villa?'#f8f4e9':terrace?'#d7c7ae':'#ebdebc'}"/><path d="M88 113h260M88 146h260" stroke="#cab998" opacity=".6"/>${Array.from({length:floors},(_,floor)=>Array.from({length:4},(_,i)=>`<rect x="${107+i*59}" y="${89+floor*(floors===3?26:40)}" width="35" height="${floors===3?18:29}" rx="1" fill="#638280"/><path d="M${124+i*59} ${89+floor*(floors===3?26:40)}v${floors===3?18:29}" stroke="#ccd3bd"/>`).join('')).join('')}<rect x="201" y="136" width="37" height="43" fill="#745b49"/><circle cx="230" cy="157" r="2" fill="#ebd28e"/><path d="M47 177v-36M390 178v-49" stroke="#857a52" stroke-width="6"/><circle cx="47" cy="124" r="26" fill="#83976c"/><circle cx="390" cy="111" r="34" fill="#83976c"/><path d="m196 179-30 26h110l-32-26" fill="#d7c8ac"/></svg>`;}
function propertyMarkup(){return `<div class="page-heading"><span class="eyebrow">ABUJA HOME FINDER</span><h1>Your next place.</h1><p>From a Garki studio to a Maitama villa. Tour the rooms, compare neighbourhoods and choose the home your game budget can afford.</p></div><div class="home-price-note"><strong>Virtual game prices</strong><span>Rent covers a game year: ${state.economyMeta?.rentPeriodDays||28} real days. Service charges are billed every ${state.economyMeta?.billPeriodDays||7} days.</span></div><div class="home-hunt">${list(state.properties).map(h=>`<article class="home-listing">${houseArt(h)}<div class="home-listing-body"><div class="home-listing-place"><span class="eyebrow">${esc(place(h.district)?.name||'Abuja')}</span>${state.profile.home?.propertyId===h.id?'<span class="home-owned">Your home</span>':state.profile.ownedProperties?.includes(h.id)?'<span class="home-owned">Owned</span>':''}</div><h2>${esc(h.name)}</h2><p>${h.bedrooms?`${h.bedrooms} bedrooms`:'Studio'} · ${h.bathrooms||1} bathroom${h.bathrooms>1?'s':''}${h.areaM2?` · ${h.areaM2} m²`:''}</p><div class="home-prices">${h.tier===0?'<div><small>YOUR STARTER RESIDENCE</small><strong>Included</strong></div>':`<div><small>RENT / GAME YEAR</small><strong>₦${money(h.rent)}</strong></div><div><small>BUY OUTRIGHT</small><strong>₦${money(h.price||h.buy)}</strong></div>`}</div><button class="secondary full" data-property="${esc(h.id)}">Tour & details${icon('arrow')}</button></div></article>`).join('')}</div>`;}
function bindProperties(){root.querySelectorAll('[data-property]').forEach(button=>button.onclick=()=>openProperty(list(state.properties).find(h=>h.id===button.dataset.property)));}
function openProperty(h){
 if(!h)return;const p=state.profile,isHome=p.home?.propertyId===h.id,owned=p.ownedProperties?.includes(h.id),starter=h.tier===0;
 openSheet(`<span class="eyebrow">${esc(place(h.district)?.name||'Abuja')} · VIRTUAL PROPERTY</span><h2 id="sheet-title">${esc(h.name)}</h2><p class="muted">${esc(h.description||'Find a home that fits the life you want.')}</p><div class="house-tour" id="house-tour" aria-label="Free interior viewing of ${esc(h.name)}"></div><p class="house-tour-caption">Free interior viewing · walk around to explore. This is a preview of the home.</p><div class="home-features">${(h.features||[]).map(feature=>`<span>${icon('check')}${esc(feature)}</span>`).join('')}</div><div class="home-view-details"><div class="detail-line"><span>Rent · ${h.rentPeriodDays||28}-day game year</span><strong>₦${money(h.rent)}</strong></div><div class="detail-line"><span>Buy outright</span><strong>₦${money(h.price||h.buy)}</strong></div><div class="detail-line"><span>Service charge · every ${h.billPeriodDays||7} days</span><strong>₦${money(h.serviceCharge??h.bills)}</strong></div>${h.agencyFee||h.cautionDeposit?`<div class="detail-line"><span>Agency & caution deposit</span><strong>₦${money((h.agencyFee||0)+(h.cautionDeposit||0))}</strong></div>`:''}</div><div class="button-pair"><button class="secondary" data-move="rent" ${starter||p.wallet<(h.moveInCost||h.rent)||isHome?'disabled':''}>${isHome?'Your current home':'Rent this home'}</button><button class="primary" data-move="own" ${starter||!owned&&p.wallet<(h.price||h.buy)||isHome&&p.home.tenure==='own'?'disabled':''}>${starter?'Included starter residence':isHome&&p.home.tenure==='own'?'You own this home':owned?'Move into owned home':'Buy this home'}</button></div><p class="economy-note">The prices and floor plans are authored for gameplay. Renting pays one game year upfront. Furniture stays in your inventory when you move.</p>`,{wide:true});
 sheetCleanup=renderWorld(sheetRoot.querySelector('#house-tour'),{profile:{...p,location:{kind:'home',district:h.district,venue:'home'},home:{propertyId:h.id,name:h.name,district:h.district,tenure:'viewing'},furnitureLayout:{}},place:place(h.district),people:[],catalog:list(state.catalog),onInteract:()=>toast('This is a free viewing. Rent or buy to make it your home.'),onResident:()=>{}});
 sheetRoot.querySelectorAll('[data-move]').forEach(button=>button.onclick=async()=>{if(await action('move-home',{propertyId:h.id,tenure:button.dataset.move})){closeSheet();navigate('world');toast(`Your new home is in ${place(h.district)?.name||'Abuja'}. Travel there to move in.`);}});
}
function profileMarkup(){const p=state.profile;return `<div class="page-heading"><span class="eyebrow">THIS IS YOU</span><h1>${esc(p.displayName)}</h1><p>@${esc(p.username)} · Reputation ${p.reputation} · Career level ${p.careerLevel||1}</p></div><section class="profile-studio"><div class="profile-portrait">${avatarSVG(p.appearance,{size:280,fullBody:true})}</div><form id="profile-form"><label>Display name<input name="displayName" value="${esc(p.displayName)}" required maxlength="40"></label><div class="appearance-fields">${appearanceFields(p.appearance||{})}</div><label>Your next chapter<select name="lifeGoal">${list(state.lifeGoals).map(goal=>`<option value="${esc(goal.id)}" ${p.lifeGoal===goal.id?'selected':''}>${esc(goal.name||goal.title)}</option>`).join('')}</select></label><button class="primary full" type="submit">Save your look${icon('check')}</button></form></section><div class="profile-actions"><button class="secondary" data-phone="settings">Privacy & settings</button><button class="text-button" data-logout>Sign out</button></div>`;}
function bindProfile(){const form=root.querySelector('#profile-form');form.querySelectorAll('[data-appearance]').forEach(s=>s.onchange=()=>{root.querySelector('.profile-portrait').innerHTML=avatarSVG(Object.fromEntries(new FormData(form)),{size:280,fullBody:true});});form.onsubmit=async e=>{e.preventDefault();const {displayName,lifeGoal,...appearance}=Object.fromEntries(new FormData(form));try{await api('/api/profile',{method:'POST',body:{displayName,lifeGoal,appearance}});await refresh();toast('Looking like yourself.');}catch(error){toast(error.message);}};root.querySelector('[data-logout]').onclick=async()=>{await api('/api/auth/logout',{method:'POST',body:{}});stream?.close();phone.close();state=await api('/api/bootstrap');authMode='login';renderMain();};}
function residentSheet(resident){
 if(typeof resident==='string')resident=list(state.people).find(p=>p.id===resident);if(!resident)return;
 openSheet(`<div class="resident-sheet-portrait">${avatarSVG(resident.appearance,{size:115})}</div><span class="eyebrow">${resident.online?'ONLINE NOW':'RESIDENT'}</span><h2 id="sheet-title">${esc(resident.displayName)}</h2><p class="muted">@${esc(resident.username)}</p><div class="button-pair"><button class="secondary" id="request-friend">Add friend</button><button class="primary" id="message-resident">Message</button></div>`);
 document.querySelector('#request-friend').onclick=async()=>{try{await api('/api/friends/request',{method:'POST',body:{residentId:resident.id}});toast('Friend request sent.');closeSheet();await refresh();}catch(error){toast(error.message);}};
 document.querySelector('#message-resident').onclick=async()=>{try{const result=await api('/api/conversations',{method:'POST',body:{residentId:resident.id}});closeSheet();await refresh();phone.open('messages',{conversationId:result.conversation.id});}catch(error){toast(error.message);}};
}
async function openLocalChat(){
 try{chatMessages=(await api('/api/chat/location')).messages||[];}catch(error){toast(error.message);return;}
 openSheet(`<span class="eyebrow">${esc(place(state.profile.district)?.name||'YOUR NEIGHBOURHOOD')}</span><h2 id="sheet-title">Around you</h2><div class="nearby-list">${list(state.nearby).map(p=>`<button data-resident="${esc(p.id)}">${avatarSVG(p.appearance,{size:40})}<span>${esc(p.displayName)}</span><i class="state-dot"></i></button>`).join('')||'<p class="muted">No other residents nearby right now. Invite a friend to join your neighbourhood.</p>'}</div><div class="local-messages" id="local-messages" aria-live="polite"></div><form id="local-chat-form" class="chat-composer"><label class="sr-only" for="local-text">Say something nearby</label><input id="local-text" name="text" required maxlength="1000" placeholder="Say hello…"><button class="primary" type="submit" aria-label="Send nearby message">${icon('arrow')}</button></form>`);
 chatOpen=true;renderChat();sheetRoot.querySelectorAll('[data-resident]').forEach(b=>b.onclick=()=>residentSheet(b.dataset.resident));document.querySelector('#local-chat-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/chat/location',{method:'POST',body:{text:new FormData(e.currentTarget).get('text')}});e.target.reset();}catch(error){toast(error.message);}};
}
function renderChat(){const el=document.querySelector('#local-messages');if(!el)return;el.innerHTML=chatMessages.map(m=>`<div><strong>${esc(m.sender?.displayName||list(state.people).find(p=>p.id===m.senderId)?.displayName||state.profile.displayName)}</strong><p>${esc(m.text)}</p></div>`).join('')||'<p class="muted">The conversation starts with you.</p>';el.scrollTop=el.scrollHeight;}
async function boot(){root.innerHTML='<div class="loading-state"><span class="wordmark">Abuja<span>Life</span><i></i></span><p>Opening your city…</p></div>';try{await refresh();connectRealtime();}catch(error){root.innerHTML=`<div class="loading-state"><h1>Let’s try that again.</h1><p>${error.status?esc(error.message):'We can’t reach the city right now. Check your connection and try again.'}</p><button class="primary" id="retry-start">Reconnect</button></div>`;root.querySelector('#retry-start').onclick=boot;}}
boot();
