import { apiFetch } from './api-client.js';

const sheetRoot=document.querySelector('#sheet-root');
const toastRoot=document.querySelector('#toast');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`₦${new Intl.NumberFormat('en-NG',{maximumFractionDigits:0}).format(Number(v||0))}`;
const ago=value=>{const ms=Date.now()-Number(value||0),m=Math.max(0,Math.floor(ms/60000));return m<1?'now':m<60?`${m}m ago`:m<1440?`${Math.floor(m/60)}h ago`:`${Math.floor(m/1440)}d ago`;};
let overlay=null,state=null,busy=false;

function toast(message){if(!toastRoot)return;toastRoot.textContent=message;toastRoot.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastRoot.classList.remove('visible'),3600);}
async function api(path,options={}){const opts={...options,headers:{...options.headers}};if(opts.body&&typeof opts.body!=='string'){opts.headers['content-type']='application/json';opts.body=JSON.stringify(opts.body);}const response=await apiFetch(path,{...opts,signal:opts.signal||AbortSignal.timeout(12000)});let body={};try{body=await response.json();}catch{}if(!response.ok||body.ok===false){const error=new Error(body.error||'Please try again.');error.status=response.status;error.code=body.code;throw error;}return body;}
const party=id=>state?.parties?.find(p=>p.id===id);
const actionReason=action=>action.phase&&action.phase!==state?.cycle?.phase?.id?`Available during ${action.phase}`:action.venueId&&!atVenue(action.venueId)?'Travel there first':action.requiresPublic&&state?.resident?.location?.kind!=='public'?'Head outside first':action.requiresCase&&state?.candidate?.enforcement==='none'?'No active case':null;
const atVenue=id=>state?.resident?.location?.kind==='venue'&&(state.resident.location.venue===id||state.resident.location.venueId===id);

function close(){overlay?.remove();overlay=null;state=null;busy=false;}
function openTravel(venueId){close();window.dispatchEvent(new CustomEvent('abj:open-map-venue',{detail:{venueId}}));}
function statusText(candidate){if(!candidate)return'';return candidate.status==='detained'?'Detained · hearing required':candidate.status==='disqualified'?'Removed from ballot':candidate.enforcement==='efcc-raid'?'EFCC storyline raid active':candidate.enforcement==='efcc-review'?'Integrity review active':'Active candidate';}

function render(){if(!overlay||!state)return;const cycle=state.cycle,phase=cycle.phase,progress=Math.round((cycle.day/state.meta.cycleDays)*100),candidate=state.candidate,gov=state.government,nomination=state.eligibility?.nominationOpen&&!candidate;
  const ranking=(state.candidates||[]).slice(0,12).map((c,i)=>`<div class="civic-candidate-row"><b>${i+1}</b><div><strong>${esc(c.displayName)}</strong><small>${esc(party(c.partyId)?.short||c.partyId)} · ${cycle.phase.id==='voting'||cycle.phase.id==='results'?`${c.votes} vote${c.votes===1?'':'s'}`:`${c.support} campaign support`}${c.status!=='active'?` · ${esc(c.status)}`:''}</small></div>${cycle.phase.id==='voting'&&!state.votedFor&&!['detained','disqualified'].includes(c.status)?`<button class="civic-vote" data-civic-vote="${esc(c.residentId)}" ${state.eligibility?.canVote?'':'disabled'}>Vote</button>`:''}</div>`).join('')||'<p>No candidate has entered this cycle yet.</p>';
  const campaign=candidate?(state.campaignActions||[]).map(a=>{const reason=actionReason(a),risk=Number(a.heat||0)>0,clean=Number(a.heat||0)<0;return a.venueId&&!atVenue(a.venueId)?`<button class="civic-action ${risk?'risk':clean?'clean':''}" data-civic-travel="${esc(a.venueId)}"><strong>${esc(a.name)}</strong><small>${esc(reason||a.description)} · Go there →</small></button>`:`<button class="civic-action ${risk?'risk':clean?'clean':''}" data-civic-action="${esc(a.id)}" ${reason?'disabled':''}><strong>${esc(a.name)}${a.cost?` · ${money(a.cost)}`:''}</strong><small>${esc(reason||a.description)}</small></button>`;}).join(''):'';
  const government=gov&&state.resident?.isPresident?`<section class="civic-card civic-government"><span class="eyebrow">YOUR ADMINISTRATION</span><h3>President ${esc(gov.winnerName)}</h3><p>Use the city budget to create multiplayer events. Decisions are public and integrity choices can trigger the fictional EFCC storyline.</p><div class="civic-stats"><div class="civic-stat"><span>City budget</span><strong>${money(gov.budget)}</strong></div><div class="civic-stat"><span>Integrity</span><strong>${gov.integrity}%</strong></div><div class="civic-stat"><span>Scrutiny</span><strong>${gov.heat}</strong></div></div><div class="civic-actions">${(state.governmentActions||[]).map(a=>atVenue(a.venueId)?`<button class="civic-action ${a.heat?'risk':''}" data-gov-action="${esc(a.id)}"><strong>${esc(a.name)} · ${money(a.cost)}</strong><small>${esc(a.description)}</small></button>`:`<button class="civic-action ${a.heat?'risk':''}" data-civic-travel="${esc(a.venueId)}"><strong>${esc(a.name)} · ${money(a.cost)}</strong><small>Go to ${esc(a.venueId.replace(/-/g,' '))} to announce it →</small></button>`).join('')}</div></section>`:'';
  const investigation=candidate&&candidate.enforcement!=='none'?`<section class="civic-card civic-enforcement"><span class="eyebrow">FICTIONAL EFCC STORYLINE</span><h3>${esc(statusText(candidate))}</h3><p>Scrutiny: ${candidate.heat}. This storyline applies only to fictional AbujaLife politics and does not accuse any real person. Transparent campaign actions and due-process hearings can change the case state.</p>${candidate.enforcement!=='none'&&!atVenue('efcc-hq')?'<button class="civic-secondary" data-civic-travel="efcc-hq">Go to EFCC HQ experience</button>':''}${candidate.status==='detained'&&!atVenue('federal-high-court-hub')?'<button class="civic-secondary" data-civic-travel="federal-high-court-hub">Go to Federal High Court</button>':''}</section>`:'';
  overlay.querySelector('.civic-scroll').innerHTML=`
    <section class="civic-phase"><div><span>LIVE CITY STORY</span><strong>${esc(phase.title)}</strong></div><div class="civic-day">Day ${Math.floor(cycle.day)+1} / ${state.meta.cycleDays}</div><p>${esc(phase.story)}</p><div class="civic-progress"><i style="width:${progress}%"></i></div></section>
    <div class="civic-disclaimer">${esc(state.meta.notice)}</div>
    ${nomination?`<section class="civic-card"><span class="eyebrow">RUN FOR PRESIDENT</span><h3>Buy a candidate ticket</h3><p>Candidate ticket: <strong>${money(state.meta.nominationFee)}</strong> game Naira · minimum reputation ${state.meta.nominationReputation}. Registration is physically tied to the INEC game destination.</p>${!state.resident.atInec?'<button class="civic-primary" data-civic-travel="inec-hq">Go to INEC Headquarters</button>':`<form class="civic-form" data-civic-nominate><select name="partyId" required>${state.parties.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · ${esc(p.short)}</option>`).join('')}</select><textarea name="manifesto" minlength="20" maxlength="260" required placeholder="What will your administration actually do for AbujaLife residents?"></textarea><button class="civic-primary" type="submit" ${state.eligibility.reputationReady&&state.eligibility.fundsReady?'':'disabled'}>Buy ticket & enter race · ${money(state.meta.nominationFee)}</button></form>${!state.eligibility.reputationReady?`<div class="civic-status">Build your reputation to ${state.meta.nominationReputation} first.</div>`:''}${!state.eligibility.fundsReady?'<div class="civic-status">You need more Game Naira for the ticket.</div>':''}`}</section>`:''}
    ${candidate?`<section class="civic-card"><span class="eyebrow">YOUR CAMPAIGN</span><h3>${esc(candidate.displayName)} · ${esc(party(candidate.partyId)?.short||candidate.partyId)}</h3><p>${esc(candidate.manifesto)}</p><div class="civic-stats"><div class="civic-stat"><span>Support</span><strong>${candidate.support}</strong></div><div class="civic-stat"><span>Votes</span><strong>${candidate.votes||0}</strong></div><div class="civic-stat"><span>Scrutiny</span><strong>${candidate.heat}</strong></div></div><div class="civic-status">${esc(statusText(candidate))}</div><div class="civic-actions">${campaign}</div></section>`:''}
    ${investigation}
    ${government}
    <section class="civic-card"><span class="eyebrow">PRESIDENTIAL RACE</span><h3>${cycle.phase.id==='voting'?'Cast your vote':'Candidate board'}</h3>${cycle.phase.id==='voting'&&!state.resident.atHomePoll&&!state.votedFor?'<p>Voting requires you to return to your home district and physically head outside. The phone then becomes your polling check-in.</p><button class="civic-secondary" data-civic-close>Return to the city</button>':''}${state.votedFor?'<div class="civic-status">Vote recorded for this cycle. You cannot vote twice.</div>':''}<div class="civic-rank">${ranking}</div></section>
    <section class="civic-card"><span class="eyebrow">ABUJA RIGHT NOW</span><h3>City stories</h3>${(state.events||[]).slice(0,12).map(e=>`<article class="civic-story"><strong>${esc(e.title)}</strong><p>${esc(e.body)}</p><time>${esc(ago(e.createdAt))}</time></article>`).join('')||'<p>The cycle is quiet. Resident actions will create the story.</p>'}</section>`;
  bind();
}

async function refresh(){if(!overlay)return;try{state=await api('/api/civic/state');render();}catch(error){overlay.querySelector('.civic-scroll').innerHTML=`<div class="civic-loading">${esc(error.message)}</div>`;}}
async function mutate(path,body){if(busy)return;busy=true;try{const result=await api(path,{method:'POST',body:{...body,idempotencyKey:body.idempotencyKey||crypto.randomUUID()}});state=result.civic||await api('/api/civic/state');render();toast('City story updated.');}catch(error){toast(error.message);}finally{busy=false;}}
function bind(){if(!overlay)return;overlay.querySelectorAll('[data-civic-travel]').forEach(b=>b.onclick=()=>openTravel(b.dataset.civicTravel));overlay.querySelectorAll('[data-civic-action]').forEach(b=>b.onclick=()=>mutate('/api/civic/campaign',{actionId:b.dataset.civicAction}));overlay.querySelectorAll('[data-gov-action]').forEach(b=>b.onclick=()=>mutate('/api/civic/government/action',{actionId:b.dataset.govAction}));overlay.querySelectorAll('[data-civic-vote]').forEach(b=>b.onclick=()=>mutate('/api/civic/vote',{candidateId:b.dataset.civicVote}));overlay.querySelectorAll('[data-civic-close]').forEach(b=>b.onclick=close);const form=overlay.querySelector('[data-civic-nominate]');if(form)form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));void mutate('/api/civic/nominate',{partyId:data.partyId,manifesto:data.manifesto});};}

export function openCivicLife(){if(overlay)return;overlay=document.createElement('div');overlay.className='civic-overlay';overlay.innerHTML=`<section class="civic-shell" role="dialog" aria-modal="true" aria-labelledby="civic-title"><header class="civic-head"><span class="eyebrow">ABUJA LIFE · CIVIC LIFE</span><h2 id="civic-title">The city has a story.</h2><p>Run. Campaign. Vote. Govern. Face the consequences of your choices.</p><button class="civic-close" type="button" aria-label="Close">×</button></header><div class="civic-scroll"><div class="civic-loading">Opening Abuja civic life…</div></div></section>`;document.body.append(overlay);overlay.querySelector('.civic-close').onclick=close;overlay.addEventListener('click',e=>{if(e.target===overlay)close();});void refresh();}

function ensureEntry(scope=document){const grid=scope.querySelector?.('.life-menu-grid');if(!grid||grid.querySelector('[data-open-civic-life]'))return;const button=document.createElement('button');button.type='button';button.className='civic-life-entry';button.dataset.openCivicLife='';button.innerHTML='<span aria-hidden="true">◆</span><strong>City & Election</strong><small>Campaigns · voting · city stories</small>';button.onclick=openCivicLife;grid.append(button);}
function scan(scope=document){ensureEntry(scope);scope.querySelectorAll?.('.life-menu-grid').forEach(grid=>ensureEntry(grid.parentElement||document));}
scan();const observer=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node instanceof Element){scan(node);scan(document);}});observer.observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('abj:open-civic-life',openCivicLife);
