import { apiFetch } from './api-client.js';
const money=value=>'₦'+new Intl.NumberFormat('en-NG').format(Number(value)||0);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>new Date(value).toLocaleString('en-NG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
let authorized=false,opened=false,overview=null,withdrawals=[],poll=null,busy='';
async function api(path,{body,...options}={}){const response=await apiFetch(path,{...options,headers:{...(body?{'content-type':'application/json'}:{}),...options.headers},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json().catch(()=>({}));if(!response.ok||result.ok===false){const error=new Error(result.error||'Please try again.');error.status=response.status;throw error;}return result;}
function toast(message){let node=document.querySelector('#jp-admin-toast');if(!node){node=document.createElement('div');node.id='jp-admin-toast';document.body.append(node);}node.textContent=message;node.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('visible'),3000);}
async function probe(){try{overview=await api('/api/admin/jackpot/overview');authorized=true;ensureButton();}catch(error){if(error.status===401||error.status===403)authorized=false;}}
function ensureButton(){if(!authorized)return;const nav=document.querySelector('.admin-sidebar nav');if(!nav||nav.querySelector('[data-jp-admin-open]'))return;const button=document.createElement('button');button.dataset.jpAdminOpen='';button.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M4 6h16v12H4z"/><path d="M8 3v6M16 3v6M7 13h10M9 17h6"/></svg>Jackpot';button.onclick=()=>void open();nav.append(button);}
function root(){let node=document.querySelector('#jp-admin-root');if(!node){node=document.createElement('div');node.id='jp-admin-root';document.body.append(node);}return node;}
async function refresh(){try{const results=await Promise.all([api('/api/admin/jackpot/overview'),api('/api/admin/jackpot/withdrawals')]);overview=results[0];withdrawals=results[1].withdrawals;render();}catch(error){toast(error.message);}}
async function open(){opened=true;root().hidden=false;render();await refresh();clearInterval(poll);poll=setInterval(()=>opened&&void refresh(),8000);}
function close(){opened=false;clearInterval(poll);root().hidden=true;}
function render(){if(!opened)return;const node=root(),stats=overview?.stats||{};node.innerHTML=`<div class="jpa-backdrop"><section class="jpa-panel"><header><div><small>ABUJALIFE OPERATIONS</small><h1>Community Jackpot</h1></div><button data-jpa="close" aria-label="Close">×</button></header><main>${overview?`<div class="jpa-stats"><article><small>PENDING PAYOUTS</small><strong>${Number(stats.pendingWithdrawals||0).toLocaleString()}</strong></article><article><small>GROSS HELD</small><strong>${money(stats.pendingGross)}</strong></article><article><small>TO SEND</small><strong>${money(stats.pendingNet)}</strong></article><article><small>ROOMS · 24H</small><strong>${Number(stats.completedRooms24h||0).toLocaleString()}</strong></article></div><section class="jpa-card"><div class="jpa-title"><div><small>LIVE ENGINE</small><h2>Five active rooms</h2></div><button data-jpa="refresh">Refresh</button></div><div class="jpa-rooms">${overview.rooms.map(room=>`<article><span><strong>${esc(room.name)}</strong><small>${esc(room.status.toUpperCase())}</small></span><b>${room.participantCount}/${room.capacity}</b><b>${money(room.potAmount)}</b></article>`).join('')}</div></section><section class="jpa-card"><div class="jpa-title"><div><small>MANUAL BANK PAYOUTS</small><h2>Withdrawal queue</h2></div></div>${withdrawals.length?`<div class="jpa-table-wrap"><table><thead><tr><th>RESIDENT</th><th>REQUEST</th><th>SEND</th><th>BANK</th><th>STATUS</th><th></th></tr></thead><tbody>${withdrawals.map(row=>`<tr><td><strong>${esc(row.resident.displayName)}</strong><small>@${esc(row.resident.username)} · ${date(row.requestedAt)}</small></td><td>${money(row.grossAmount)}<small>Fee ${money(row.feeAmount)}</small></td><td><strong>${money(row.netAmount)}</strong></td><td>${esc(row.bank.bankName)}<small>${esc(row.bank.accountName)} · ${esc(row.bank.accountNumber)}</small></td><td><span class="jpa-tag ${row.status}">${esc(row.status)}</span></td><td><div class="jpa-actions">${row.status==='requested'?`<button data-jpa="start" data-id="${esc(row.id)}">Start</button>`:''}<button data-jpa="paid" data-id="${esc(row.id)}" class="primary">Mark paid</button><button data-jpa="return" data-id="${esc(row.id)}" class="danger">Return</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="jpa-empty">No withdrawals are waiting for payment.</div>'}</section>`:'<div class="jpa-loading">Loading Jackpot operations…</div>'}</main></section></div>`;node.querySelectorAll('[data-jpa]').forEach(button=>button.onclick=()=>void action(button));}
async function action(button){const type=button.dataset.jpa;if(type==='close')return close();if(type==='refresh')return refresh();if(busy)return;const id=button.dataset.id;if(type==='start')return mutate(id,'start',{});if(type==='paid'){const reference=prompt('Enter the bank transfer reference. This confirms the payout was actually sent.');if(!reference)return;return mutate(id,'paid',{reference});}if(type==='return'){const reason=prompt('Why are you returning this withdrawal to the player’s Jackpot Balance?');if(!reason)return;return mutate(id,'return',{reason});}}
async function mutate(id,action,body){busy=id;try{await api(`/api/admin/jackpot/withdrawals/${encodeURIComponent(id)}/${action}`,{method:'POST',body});toast(action==='paid'?'Withdrawal marked paid.':action==='return'?'Full request returned to Jackpot Balance.':'Withdrawal moved to processing.');await refresh();}catch(error){toast(error.message);}finally{busy='';}}
const observer=new MutationObserver(()=>ensureButton());observer.observe(document.documentElement,{childList:true,subtree:true});void probe();
