import { apiFetch } from './api-client.js';
import { createServerClock } from './jackpot-clock.js';

const money=value=>'₦'+new Intl.NumberFormat('en-NG',{maximumFractionDigits:0}).format(Number(value)||0);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const requestKey=()=>globalThis.crypto?.randomUUID?.()||`jp-${Date.now()}-${Math.random().toString(36).slice(2)}`;
let opened=false,state=null,busy='',dialog='',pollTimer=null,clockTimer=null,returnHandled=false;
const serverClock=createServerClock();
const CACHE_KEY='abujalife.jackpot.snapshot.v1';
function cachedState(){try{const value=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');return value&&serverClock.wallNow()-Number(value.cachedAt||0)<120000?value.state:null;}catch{return null;}}
function cacheState(value){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({cachedAt:serverClock.wallNow(),state:value}));}catch{}}
function structureKey(value){return JSON.stringify({rooms:(value?.rooms||[]).map(r=>[r.id,r.status]),tickets:(value?.tickets||[]).map(t=>t.ticketId),wins:(value?.wins||[]).length,ledger:value?.ledger?.[0]?.id||value?.ledger?.[0]?.createdAt||null});}

async function api(path,{body,...options}={}){
  const response=await apiFetch(path,{...options,headers:{...(body?{'content-type':'application/json'}:{}),...options.headers},...(body?{body:JSON.stringify(body)}:{})});
  const result=await response.json().catch(()=>({}));
  if(!response.ok||result.ok===false){const error=new Error(result.error||'Please try again.');error.status=response.status;error.code=result.code;throw error;}return result;
}
function toast(message){let node=document.querySelector('#jackpot-toast');if(!node){node=document.createElement('div');node.id='jackpot-toast';document.body.append(node);}node.textContent=message;node.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('visible'),3200);}
function secondsUntil(timestamp){return serverClock.secondsUntil(timestamp);}
function timerText(room){const seconds=secondsUntil(room.status==='open'?room.closesAt:room.drawsAt);if(seconds===null)return'--:--';const m=Math.floor(seconds/60),s=seconds%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
function ticketFor(roomId){return state?.tickets?.find(ticket=>ticket.roomId===roomId);}
function ensureRoot(){const screen=document.querySelector('.phone-root .ph-screen');if(!screen)return null;let root=screen.querySelector('#jackpot-root');if(!root){root=document.createElement('div');root.id='jackpot-root';root.className='jp-root';screen.append(root);}return root;}
function ensureLauncher(){
  const grid=document.querySelector('.phone-root .ph-home-page:last-child .ph-app-grid');if(!grid||grid.querySelector('[data-jackpot-launcher]'))return;
  const button=document.createElement('button');button.type='button';button.className='ph-launcher jp-launcher';button.dataset.jackpotLauncher='';button.innerHTML='<span class="ph-app-icon jp-launcher-icon"><b>₦</b><i>★</i></span><span class="ph-app-label">Jackpot</span>';
  button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();void openJackpot();});grid.append(button);
}
function header(){return `<header class="jp-header"><button type="button" data-jp="close" aria-label="Back">‹ <span>Phone</span></button><strong>Community Jackpot</strong><button type="button" data-jp="refresh" aria-label="Refresh">↻</button></header>`;}
function balanceCard(){const account=state?.account||{available:0,pendingWithdrawal:0};return `<section class="jp-balance"><small>JACKPOT BALANCE</small><strong>${money(account.available)}</strong>${account.pendingWithdrawal?`<p>${money(account.pendingWithdrawal)} pending withdrawal</p>`:'<p>Deposit, play or withdraw your winnings.</p>'}<div><button data-jp="deposit">Deposit</button><button data-jp="withdraw" class="secondary" ${account.available<10?'disabled':''}>Withdraw</button></div></section>`;}
function roomCard(room){const mine=ticketFor(room.id),open=room.status==='open',canJoin=open&&!mine&&(state?.account?.available||0)>=room.entryAmount;return `<article class="jp-room ${room.status}" data-jp-room-id="${esc(room.id)}"><div class="jp-room-top"><div><small>${room.status==='open'?'LIVE ROOM':room.status==='locked'?'ROOM LOCKED':'DRAWING'}</small><h3>${esc(room.name)}</h3></div><span>${room.participantCount} / ${room.capacity}</span></div><div class="jp-room-numbers"><div><small>ENTRY</small><strong>${money(room.entryAmount)}</strong></div><div><small>POT</small><strong>${money(room.potAmount)}</strong></div><div><small>${open?'CLOSES IN':'WINNER IN'}</small><strong data-jp-timer="${esc(room.id)}">${timerText(room)}</strong></div></div>${mine?`<div class="jp-ticket">✓ You're in <span>${esc(mine.ticketId.split(':').at(-1).slice(0,8).toUpperCase())}</span></div>`:`<button class="jp-join" data-jp="join" data-room="${esc(room.id)}" ${canJoin?'':'disabled'}>${open?(state?.account?.available>=room.entryAmount?'JOIN · '+money(room.entryAmount):'ADD FUNDS TO JOIN'):'ENTRY CLOSED'}</button>`}<div class="jp-meter"><i style="width:${Math.min(100,(room.participantCount/room.capacity)*100)}%"></i></div></article>`;}
function winsMarkup(){const wins=state?.wins||[];return `<section class="jp-section"><div class="jp-section-head"><div><small>YOUR WINS</small><h2>${wins.length?'Jackpot moments':'Your wins will live here'}</h2></div></div>${wins.length?wins.map((win,index)=>`<article class="jp-win"><div><small>${esc(win.name)} · ${new Date(win.completedAt).toLocaleDateString('en-NG',{day:'numeric',month:'short'})}</small><strong>${money(win.potAmount)}</strong><span>Winning ticket ${esc(win.winner?.ticketId?.split(':').at(-1).slice(0,8).toUpperCase()||'')}</span></div><button data-jp="share" data-win="${index}">Share win</button></article>`).join(''):'<p class="jp-empty">Enter a live room. One valid ticket wins the full room pot.</p>'}</section>`;}
function historyMarkup(){const ledger=(state?.ledger||[]).slice(0,12);const label={deposit:'Deposit',room_entry:'Room entry',jackpot_win:'Jackpot win',room_refund:'Room refund',withdrawal_requested:'Withdrawal requested',withdrawal_paid:'Withdrawal paid',withdrawal_returned:'Withdrawal returned'};return `<section class="jp-section"><div class="jp-section-head"><div><small>ACTIVITY</small><h2>Money trail</h2></div></div><div class="jp-history">${ledger.map(row=>`<div><span><strong>${esc(label[row.type]||row.type)}</strong><small>${new Date(row.createdAt).toLocaleString('en-NG',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span><b class="${row.deltaAvailable>0?'positive':row.deltaAvailable<0?'negative':''}">${row.deltaAvailable?`${row.deltaAvailable>0?'+':''}${money(row.deltaAvailable)}`:row.deltaPending?`${row.deltaPending>0?'Held ':'Settled '}${money(Math.abs(row.deltaPending))}`:'—'}</b></div>`).join('')||'<p class="jp-empty">No Jackpot activity yet.</p>'}</div></section>`;}
function render(){const root=ensureRoot();if(!root)return;if(!opened){root.hidden=true;return;}root.hidden=false;root.innerHTML=`${header()}<main class="jp-scroll">${state?`${balanceCard()}<section class="jp-section"><div class="jp-section-head"><div><small>LIVE NOW</small><h2>Five rooms. One winner each.</h2></div><span>${money(state.entryAmount)} entry</span></div><div class="jp-rooms">${state.rooms.map(roomCard).join('')}</div></section>${winsMarkup()}${historyMarkup()}`:'<div class="jp-loading"><i></i><strong>Opening Community Jackpot…</strong></div>'}</main>${dialogMarkup()}`;bind(root);}
function dialogMarkup(){if(!dialog)return'';if(dialog==='deposit')return `<div class="jp-modal"><form data-jp-form="deposit"><button type="button" class="jp-modal-close" data-jp="dialog-close">×</button><small>ADD TO JACKPOT BALANCE</small><h2>Deposit Naira</h2><p>Your successful deposit returns here automatically.</p><label>Amount<input name="amount" type="number" min="100" step="100" inputmode="numeric" value="2000" required></label><div class="jp-presets">${[2000,5000,10000,20000].map(v=>`<button type="button" data-jp="preset" data-value="${v}">${money(v)}</button>`).join('')}</div><label>Receipt email<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><button class="jp-primary" type="submit" ${busy?'disabled':''}>${busy==='deposit'?'Opening secure checkout…':'Continue to payment'}</button></form></div>`;
if(dialog==='withdraw'){const max=state?.account?.available||0;return `<div class="jp-modal"><form data-jp-form="withdraw"><button type="button" class="jp-modal-close" data-jp="dialog-close">×</button><small>WITHDRAW WINNINGS</small><h2>Request bank payout</h2><p>AbujaLife keeps 10% when a withdrawal is paid. Your request stays pending until admin sends the bank transfer.</p><label>Amount<input name="amount" type="number" min="10" max="${max}" step="10" inputmode="numeric" value="${Math.floor(max/10)*10}" required></label><div class="jp-withdraw-quote" data-quote></div><label>Bank<input name="bankName" maxlength="80" required placeholder="e.g. GTBank"></label><label>Account number<input name="accountNumber" inputmode="numeric" pattern="[0-9]{10,20}" maxlength="20" required></label><label>Account name<input name="accountName" maxlength="100" required></label><button class="jp-primary" type="submit" ${busy?'disabled':''}>${busy==='withdraw'?'Sending request…':'Request withdrawal'}</button></form></div>`;}return'';}
function bind(root){root.querySelectorAll('[data-jp]').forEach(node=>node.addEventListener('click',onAction));root.querySelector('[data-jp-form="deposit"]')?.addEventListener('submit',deposit);const withdrawal=root.querySelector('[data-jp-form="withdraw"]');withdrawal?.addEventListener('submit',withdraw);withdrawal?.elements.amount?.addEventListener('input',()=>updateQuote(withdrawal));if(withdrawal)updateQuote(withdrawal);}
function updateQuote(form){const amount=Number(form.elements.amount.value)||0,fee=amount%10===0?amount/10:Math.round(amount*.1),quote=form.querySelector('[data-quote]');quote.innerHTML=`<span>You request <b>${money(amount)}</b></span><span>10% fee <b>${money(fee)}</b></span><strong>Admin sends <b>${money(Math.max(0,amount-fee))}</b></strong>`;}
function patchDynamic(){const root=ensureRoot();if(!root||!state)return;const balance=root.querySelector('.jp-balance>strong');if(balance)balance.textContent=money(state.account?.available);for(const room of state.rooms||[]){const card=root.querySelector(`[data-jp-room-id="${CSS.escape(room.id)}"]`);if(!card)continue;const count=card.querySelector('.jp-room-top>span');if(count)count.textContent=`${room.participantCount} / ${room.capacity}`;const pot=card.querySelector('.jp-room-numbers>div:nth-child(2) strong');if(pot)pot.textContent=money(room.potAmount);const timer=card.querySelector('[data-jp-timer]');if(timer)timer.textContent=timerText(room);const meter=card.querySelector('.jp-meter i');if(meter)meter.style.width=`${Math.min(100,(room.participantCount/room.capacity)*100)}%`;}}
async function refresh({silent=false}={}){try{const previous=structureKey(state),next=await api('/api/jackpot/state');serverClock.observe(next.serverTime);state=next;cacheState(next);if(!silent||previous!==structureKey(next))render();else patchDynamic();}catch(error){if(error.status!==401)toast(error.message);if(!state){const root=ensureRoot();if(root&&opened)root.innerHTML=`${header()}<div class="jp-error"><strong>${error.status===401?'Sign in first':'Couldn’t open Jackpot'}</strong><p>${esc(error.message)}</p></div>`;}}}
async function openJackpot(){if(!state)state=cachedState();opened=true;render();await refresh({silent:Boolean(state)});startPolling();}
function closeJackpot(){opened=false;dialog='';stopPolling();render();}
function startPolling(){stopPolling();pollTimer=setInterval(()=>opened&&void refresh({silent:true}),10000);clockTimer=setInterval(()=>{if(!opened)return;for(const room of state?.rooms||[]){const node=document.querySelector(`[data-jp-timer="${CSS.escape(room.id)}"]`);if(node)node.textContent=timerText(room);}},1000);}
function stopPolling(){clearInterval(pollTimer);clearInterval(clockTimer);pollTimer=clockTimer=null;}
async function onAction(event){const button=event.currentTarget,action=button.dataset.jp;if(action==='close')return closeJackpot();if(action==='refresh')return refresh();if(action==='deposit'){dialog='deposit';return render();}if(action==='withdraw'){dialog='withdraw';return render();}if(action==='dialog-close'){dialog='';return render();}if(action==='preset'){const input=button.closest('form').elements.amount;input.value=button.dataset.value;input.dispatchEvent(new Event('input'));return;}if(action==='join'){button.disabled=true;try{const result=await api(`/api/jackpot/rooms/${encodeURIComponent(button.dataset.room)}/join`,{method:'POST',body:{idempotencyKey:requestKey()}});if(result.state?.serverTime)serverClock.observe(result.state.serverTime);state=result.state;toast('You’re in. Your ticket is confirmed.');render();}catch(error){toast(error.message);button.disabled=false;}return;}if(action==='share'){const win=state?.wins?.[Number(button.dataset.win)];if(win)await shareWin(win);}}
async function deposit(event){event.preventDefault();if(busy)return;const form=event.currentTarget,amount=Number(form.elements.amount.value),email=form.elements.email.value.trim(),submit=form.querySelector('[type=submit]');busy='deposit';submit.disabled=true;submit.textContent='Opening secure checkout…';try{const result=await api('/api/jackpot/deposits/checkout',{method:'POST',body:{amount,email,idempotencyKey:requestKey()}}),url=new URL(result.checkout.checkoutUrl);if(url.protocol!=='https:'||!(url.hostname==='checkout.flutterwave.com'||url.hostname.endsWith('.flutterwave.com')))throw new Error('Payment provider returned an invalid checkout link.');location.assign(url.href);}catch(error){busy='';submit.disabled=false;submit.textContent='Continue to payment';toast(error.message);}}
async function withdraw(event){event.preventDefault();if(busy)return;const form=event.currentTarget,amount=Number(form.elements.amount.value);if(!Number.isSafeInteger(amount)||amount<=0||amount%10){toast('Use a whole Naira amount ending in 0.');return;}const payload={amount,bankName:form.elements.bankName.value,accountNumber:form.elements.accountNumber.value,accountName:form.elements.accountName.value,idempotencyKey:requestKey()};busy='withdraw';render();try{const result=await api('/api/jackpot/withdrawals',{method:'POST',body:payload});if(result.state?.serverTime)serverClock.observe(result.state.serverTime);state=result.state;busy='';dialog='';render();toast(`Withdrawal requested. Admin will send ${money(result.withdrawal.netAmount)}.`);}catch(error){busy='';dialog='withdraw';render();toast(error.message);}}
async function winnerCard(win){const width=1200,height=1200,canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');const g=ctx.createLinearGradient(0,0,width,height);g.addColorStop(0,'#173d31');g.addColorStop(.55,'#2d694f');g.addColorStop(1,'#d1a85d');ctx.fillStyle=g;ctx.fillRect(0,0,width,height);ctx.globalAlpha=.14;for(let x=-100;x<1300;x+=150){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,900-(x%300),180,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;ctx.fillStyle='#f7f0d9';ctx.font='700 46px system-ui';ctx.fillText('ABUJALIFE',76,105);ctx.font='600 30px system-ui';ctx.fillText('COMMUNITY JACKPOT',76,155);ctx.font='700 58px system-ui';ctx.fillText('JACKPOT WINNER',76,390);ctx.font='800 142px system-ui';ctx.fillText(money(win.potAmount),76,570);ctx.font='700 46px system-ui';ctx.fillText(`@${state.resident.username}`,76,665);ctx.font='600 34px system-ui';ctx.fillText(`${win.name} · ${win.participantCount} players`,76,730);ctx.font='500 28px system-ui';ctx.fillText('One room. One winning ticket.',76,790);ctx.fillStyle='#fff';ctx.font='700 28px system-ui';ctx.fillText('abujacity.life',76,1100);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png',.94));return new File([blob],`abujalife-${win.laneId}-winner.png`,{type:'image/png'});}
async function shareWin(win){const text=`I just won ${money(win.potAmount)} in ${win.name} on AbujaLife Community Jackpot 🏆`,url=`${location.origin}/?communityJackpot=1`;try{const file=await winnerCard(win);if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'AbujaLife Community Jackpot',text,url,files:[file]});return;}}catch(error){if(error?.name==='AbortError')return;}window.open(`https://x.com/intent/post?${new URLSearchParams({text:`${text}\n${url}`})}`,'_blank','noopener,noreferrer');}
async function handlePaymentReturn(){if(returnHandled)return;const params=new URLSearchParams(location.search);if(params.get('jackpot')!=='return'&&!params.has('jackpot_payment_ref')&&!params.has('communityJackpot'))return;if(params.has('communityJackpot')){returnHandled=true;void openJackpot();return;}const txRef=params.get('tx_ref')||params.get('jackpot_payment_ref'),transactionId=params.get('transaction_id'),status=params.get('status');if(!txRef?.startsWith('abjl_jp_'))return;returnHandled=true;await openJackpot();if(status&&status!=='successful'){toast('Payment was not completed. Your Jackpot Balance was not charged.');cleanReturnURL();return;}if(transactionId)try{const result=await api('/api/jackpot/deposits/verify',{method:'POST',body:{txRef,transactionId}});if(result.state?.serverTime)serverClock.observe(result.state.serverTime);state=result.state;render();toast(`${money(result.payment.amount)} added to Jackpot Balance.`);}catch(error){toast(error.message);}cleanReturnURL();}
function cleanReturnURL(){const url=new URL(location.href);for(const key of ['jackpot','jackpot_payment_ref','tx_ref','transaction_id','status'])url.searchParams.delete(key);history.replaceState(history.state,'',url.pathname+(url.searchParams.size?'?'+url.searchParams:'')+url.hash);}
const observer=new MutationObserver(()=>{ensureLauncher();if(!returnHandled)void handlePaymentReturn();});observer.observe(document.documentElement,{childList:true,subtree:true});ensureLauncher();void handlePaymentReturn();