import { LOAN_META, loanQuote } from '../src/shared/life.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=value=>new Intl.NumberFormat('en-NG').format(value||0);
const stamp=value=>new Intl.DateTimeFormat('en-NG',{dateStyle:'medium',timeZone:'Africa/Lagos'}).format(new Date(value));

export function createLifePanels({getState,api,onUpdate,openSheet,closeSheet,sheetRoot,toast,travelSheet}) {
  async function openLoans({borrowOnly=false}={}) {
    const p=getState().profile,loans=(p.loans||[]),active=loans.find(loan=>loan.outstanding>0),meta=getState().loanMeta||LOAN_META;
    const canRedraw=active && active.repaid*100>=active.principal*(meta.redrawAfterRepaymentPercent||50);
    const borrowForm=`<form id="borrow-loan-form"><label>Amount in game Naira<input type="number" name="amount" min="1" max="${meta.dailyPrincipalCap||10000000}" step="1" value="50000" required inputmode="numeric"></label><button class="primary full" type="submit">See repayment terms</button></form>`;
    openSheet(`<span class="eyebrow">YOUR MONEY · YOUR CHOICES</span><h2 id="sheet-title">A little breathing room.</h2><p class="muted">${esc(meta.description)}</p>${!borrowOnly&&active?`<article class="loan-card"><small>YOUR GAME LOAN</small><strong>₦${money(active.outstanding)} remaining</strong><p>Due ${stamp(active.dueAt)} · Borrowed ₦${money(active.principal)}</p><form id="repay-loan-form"><label>Amount to repay<input type="number" name="amount" min="1" max="${Math.min(p.wallet,active.outstanding)}" step="1" value="${Math.min(p.wallet,active.outstanding)}" required inputmode="numeric"></label><button class="primary full" type="submit" ${p.wallet<1?'disabled':''}>Review repayment</button></form></article>${canRedraw?'<button type="button" class="secondary full" data-loan-more>Request another advance</button>':'<p class="loan-paid">Repay at least half of this loan before requesting another advance.</p>'}`:`${loans.length&&!borrowOnly?'<p class="loan-paid">Your previous loan is settled. Self-made, small small.</p>':''}${borrowForm}`}<p class="economy-note">Fictional game borrowing only. New principal is capped at ₦10m per day and ₦100m outstanding. There is no real loan or withdrawal.</p><p class="form-error" data-loan-error role="alert"></p>`);
    sheetRoot.querySelector('[data-loan-more]')?.addEventListener('click',()=>openLoans({borrowOnly:true}));
    const form=sheetRoot.querySelector(borrowOnly||!active?'#borrow-loan-form':'#repay-loan-form');if(!form)return;
    const isBorrow=form.id==='borrow-loan-form';
    form.onsubmit=e=>{e.preventDefault();const amount=Number(new FormData(form).get('amount'));let quote;try{quote=isBorrow?loanQuote(amount):{principal:amount,totalRepayment:amount};}catch(error){sheetRoot.querySelector('[data-loan-error]').textContent=error.message;return;}
      openSheet(`<span class="eyebrow">ONE LAST LOOK</span><h2 id="sheet-title">${isBorrow?'Know your terms':'Repay your loan'}</h2><div class="detail-line"><span>${isBorrow?'You receive':'Repayment now'}</span><strong>₦${money(amount)}</strong></div>${isBorrow?`<div class="detail-line"><span>One-time fee</span><strong>₦${money(quote.fee)}</strong></div><div class="detail-line"><span>Total to repay</span><strong>₦${money(quote.totalRepayment)}</strong></div><p class="muted">Due in ${quote.termDays} real days. No compound interest.</p><label class="loan-consent"><input type="checkbox" data-loan-consent> I agree to these game-loan terms.</label>`:`<div class="detail-line"><span>Remaining after repayment</span><strong>₦${money(active.outstanding-amount)}</strong></div>`}<button class="primary full" data-loan-confirm>${isBorrow?'Accept game loan':'Confirm repayment'}</button><p class="form-error" data-loan-error role="alert"></p>`);
      const key=crypto.randomUUID(),button=sheetRoot.querySelector('[data-loan-confirm]');button.onclick=async()=>{const errorBox=sheetRoot.querySelector('[data-loan-error]');if(isBorrow&&!sheetRoot.querySelector('[data-loan-consent]').checked){errorBox.textContent='Read and accept the terms before borrowing.';return;}button.disabled=true;try{await api('/api/action',{method:'POST',body:{action:isBorrow?'borrow-loan':'repay-loan',payload:isBorrow?{amount,consent:true,consentVersion:meta.consentVersion,idempotencyKey:key}:{loanId:active.id,amount,idempotencyKey:key}}});await onUpdate({render:false});await openLoans();toast(isBorrow?'Game loan added to your balance.':'Repayment recorded.');}catch(error){if(errorBox.isConnected)errorBox.textContent=error.message;button.disabled=false;}};
    };
  }
  async function openVisits({q='',cursor='',people=[],requestsCursor=''}={}) {
    try {
      const visits=await api(`/api/home/visits${requestsCursor?`?cursor=${encodeURIComponent(requestsCursor)}`:''}`);
      const page=await api(`/api/residents?q=${encodeURIComponent(q)}${cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`);
      const all=[...people,...page.people],p=getState().profile;
      openSheet(`<span class="eyebrow">YOUR PEOPLE · THEIR PLACES</span><h2 id="sheet-title">Come through.</h2><p class="muted">Visits need the owner’s approval. Head outside in their neighbourhood, park, then send a request. Your own home stays yours.</p>${visits.visit?`<article class="visit-current"><strong>At ${esc(visits.visit.owner.displayName)}’s place</strong><p>${esc(visits.visit.home.name)}</p><button class="primary full" data-leave-visit>Step outside</button></article>`:''}${visits.visitors.length?`<div class="visit-visitors"><strong>In your home</strong>${visits.visitors.map(v=>`<span>${esc(v.guest.displayName)}</span>`).join('')}</div>`:''}<form id="visit-search" class="visit-search"><label class="sr-only" for="visit-query">Find a resident</label><input id="visit-query" name="q" type="search" value="${esc(q)}" placeholder="Name or username"><button class="secondary">Find</button></form><div class="visit-people">${all.map(person=>`<article class="visit-person"><div><strong>${esc(person.displayName)}</strong><small>@${esc(person.username)} · ${esc(getState().atlas.find(a=>a.id===person.district)?.name||'Private location')}</small></div><button class="secondary" data-visit-person="${esc(person.id)}" ${p.location.kind==='visit'?'disabled':''}>Request visit</button></article>`).join('')||'<p class="muted">No matching residents yet. Invite your people to the full game.</p>'}</div>${page.nextCursor?'<button class="secondary full" data-visits-more>More residents</button>':''}<h3>Visit requests</h3><div class="visit-requests">${visits.requests.map(r=>`<article class="visit-request"><strong>${esc(r.guestId===p.id?`To ${r.owner.displayName}`:r.guest.displayName)}</strong><p>${esc(r.note||'Would love to come through.')}</p><small>${esc(r.status)}</small>${r.ownerId===p.id&&r.status==='pending'?`<div class="button-pair"><button class="secondary" data-visit-response="${esc(r.id)}" data-accept="false">Decline</button><button class="primary" data-visit-response="${esc(r.id)}" data-accept="true">Welcome in</button></div>`:''}</article>`).join('')||'<p class="muted">Your requests appear here.</p>'}</div>${visits.nextRequestsCursor?'<button class="secondary full" data-requests-more>Older requests</button>':''}<p class="form-error" data-visit-error role="alert"></p>`);
      const report=error=>{const target=sheetRoot.querySelector('[data-visit-error]');if(target)target.textContent=error.message;};
      sheetRoot.querySelector('#visit-search').onsubmit=e=>{e.preventDefault();openVisits({q:new FormData(e.currentTarget).get('q')});};
      sheetRoot.querySelector('[data-visits-more]')?.addEventListener('click',()=>openVisits({q,cursor:page.nextCursor,people:all}));
      sheetRoot.querySelector('[data-requests-more]')?.addEventListener('click',()=>openVisits({q,requestsCursor:visits.nextRequestsCursor}));
      sheetRoot.querySelector('[data-leave-visit]')?.addEventListener('click',async()=>{try{await api('/api/home/visits/leave',{method:'POST',body:{}});closeSheet();await onUpdate();toast('You stepped outside.');}catch(error){report(error);}});
      for(const button of sheetRoot.querySelectorAll('[data-visit-response]'))button.onclick=async()=>{button.disabled=true;try{await api('/api/home/visits/respond',{method:'POST',body:{requestId:button.dataset.visitResponse,accept:button.dataset.accept==='true'}});await onUpdate();await openVisits({q});}catch(error){button.disabled=false;report(error);}};
      for(const button of sheetRoot.querySelectorAll('[data-visit-person]'))button.onclick=()=>{
        const person=all.find(r=>r.id===button.dataset.visitPerson);
        openSheet(`<span class="eyebrow">SEND A VISIT REQUEST</span><h2 id="sheet-title">${esc(person.displayName)}’s place</h2><p class="muted">The owner must be at home and approve your request. You need to be outside in the same neighbourhood.</p>${person.district&&person.district!==p.district?'<button class="secondary full" data-visit-travel>Travel to their neighbourhood</button>':''}<form id="request-visit-form"><label>Your message<textarea name="note" maxlength="300" placeholder="How far? Can I come through?"></textarea></label><button class="primary full">Send request</button><p class="form-error" role="alert"></p></form>`);
        sheetRoot.querySelector('[data-visit-travel]')?.addEventListener('click',()=>travelSheet(person.district));
        const form=sheetRoot.querySelector('form'),key=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('button');submit.disabled=true;try{await api('/api/home/visits/request',{method:'POST',body:{ownerId:person.id,note:new FormData(form).get('note'),idempotencyKey:key}});await openVisits({q});toast('Visit request sent.');}catch(error){form.querySelector('.form-error').textContent=error.message;submit.disabled=false;}};
      };
    }catch(error){toast(error.message);}
  }
  return {openLoans,openVisits};
}
