import { apiFetch } from './api-client.js';

// Living-city UI deliberately reuses app.js' single realtime connection.
// It only renders truthful server snapshots and interactions for real nearby residents.
const residents=new Map();
let stats=null,currentCanvas=null,clubDock=null;
const CLUB_NAMES=new Set(['Tokyo','Cage','Magic City','Bear Barn']);

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>new Intl.NumberFormat('en-NG',{maximumFractionDigits:0}).format(Number(value)||0);
const handleFor=person=>`@${String(person?.username||'resident').replace(/^@+/,'')}`;
async function request(path,options={}){const response=await apiFetch(path,{...options,headers:{...(options.body?{'content-type':'application/json'}:{}),...options.headers},body:options.body&&typeof options.body!=='string'?JSON.stringify(options.body):options.body});const body=await response.json().catch(()=>({}));if(!response.ok||body.ok===false)throw Object.assign(new Error(body.error||'Please try again.'),{status:response.status,code:body.code});return body;}
function toast(message){const node=document.querySelector('#toast');if(!node)return;node.textContent=message;node.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('visible'),3500);}
function canvas(){return document.querySelector('#world-scene.world-canvas.world-playable:not(.world-preview)');}
function syncLabels(){if(!currentCanvas)return;for(const node of currentCanvas.querySelectorAll('[data-world-resident]')){const person=residents.get(String(node.dataset.worldResident));if(!person)continue;const label=`${handleFor(person)} — live resident`;if(node.getAttribute('aria-label')!==label)node.setAttribute('aria-label',label);const text=node.querySelector('.online-resident-label text');const handle=handleFor(person).slice(0,24);if(text&&text.textContent!==handle)text.textContent=handle;node.dataset.presenceState=person.pose?.activity||person.pose?.moving?'moving':'idle';}}
function showStats(){if(!currentCanvas||!stats)return;let button=currentCanvas.querySelector('.world-live-stats');if(!button){button=document.createElement('button');button.type='button';button.className='world-live-stats';button.onclick=()=>{const old=currentCanvas.querySelector('.world-live-popover');if(old){old.remove();return;}const pop=document.createElement('aside');pop.className='world-live-popover';pop.innerHTML=`<small>ABUJA RIGHT NOW</small><div><span>Online now</span><strong>${number(stats.onlineNow)}</strong></div><div><span>Here with you</span><strong>${number(stats.hereNow)}</strong></div><div><span>Residents</span><strong>${number(stats.totalPlayers)}</strong></div><div><span>Visits today</span><strong>${number(stats.visitsToday)}</strong></div><div><span>Total recorded visits</span><strong>${number(stats.visitsAllTime)}</strong></div><p>Live presence only. Registered residents are never presented as online.</p>`;currentCanvas.append(pop);};currentCanvas.append(button);}const signature=[stats.onlineNow,stats.hereNow,stats.visitsToday].join(':');if(button.dataset.statsSignature!==signature){button.innerHTML=`<strong><i></i>${number(stats.onlineNow)} online</strong><span>${number(stats.hereNow)} here</span><span data-city-visits>${number(stats.visitsToday)} visits today</span>`;button.dataset.statsSignature=signature;}currentCanvas.dataset.livingStats='1';}
function openResident(person){if(!currentCanvas||!person)return;currentCanvas.querySelector('.world-resident-actions')?.remove();const card=document.createElement('section');card.className='world-resident-actions';card.setAttribute('role','dialog');card.innerHTML=`<button type="button" class="world-resident-close" aria-label="Close">×</button><div><i class="world-resident-dot"></i><strong>${esc(handleFor(person))}</strong><small>Here with you now</small></div><nav><button data-live-action="profile">Profile</button><button data-live-action="message">Say hi</button><button data-live-action="friend">Add friend</button><button data-live-action="visit">Visit</button><button data-live-action="wave">Wave</button><button data-live-action="cheer">Cheer</button></nav>`;card.querySelector('.world-resident-close').onclick=()=>card.remove();card.querySelectorAll('[data-live-action]').forEach(button=>button.onclick=async()=>{const action=button.dataset.liveAction;if(['profile','message','friend','visit'].includes(action)){dispatchEvent(new CustomEvent('abujalife:resident-action',{detail:{action,residentId:person.id}}));card.remove();return;}button.disabled=true;try{await request('/api/presence/emote',{method:'POST',body:{emote:action,targetResidentId:person.id}});card.remove();}catch(error){toast(error.message);button.disabled=false;}});currentCanvas.append(card);}
function ensureClubDock(){
 if(!currentCanvas||currentCanvas.dataset.sceneKind!=='venue'||!CLUB_NAMES.has(currentCanvas.dataset.sceneName||'')){clubDock?.remove();clubDock=null;return;}if(clubDock?.isConnected)return;
 const dock=document.createElement('div');dock.className='club-life-dock';dock.innerHTML='<button type="button" class="club-spray-button"><span>₦</span>Spray</button><div class="club-spray-menu" hidden><small>SPRAY GAME NAIRA</small></div>';const menu=dock.querySelector('.club-spray-menu');
 for(const amount of [1000,5000,10000,50000]){const button=document.createElement('button');button.type='button';button.dataset.amount=String(amount);button.textContent='₦'+number(amount);menu.append(button);}
 dock.querySelector('.club-spray-button').onclick=()=>{menu.hidden=!menu.hidden;};menu.querySelectorAll('button').forEach(button=>button.onclick=async()=>{menu.querySelectorAll('button').forEach(b=>b.disabled=true);try{await request('/api/club/spray',{method:'POST',body:{amount:Number(button.dataset.amount),idempotencyKey:crypto.randomUUID()}});menu.hidden=true;}catch(error){toast(error.message);}finally{menu.querySelectorAll('button').forEach(b=>b.disabled=false);}});currentCanvas.append(dock);clubDock=dock;
}
function showEmote(data){if(!currentCanvas||!data?.residentId)return;const node=currentCanvas.querySelector(`[data-world-resident="${CSS.escape(String(data.residentId))}"]`);if(!node)return;const box=node.getBoundingClientRect(),host=currentCanvas.getBoundingClientRect(),bubble=document.createElement('span');bubble.className='world-player-emote';bubble.textContent=data.emote==='cheer'?'✦':'👋';bubble.style.left=`${box.left-host.left+box.width/2}px`;bubble.style.top=`${box.top-host.top+18}px`;currentCanvas.append(bubble);setTimeout(()=>bubble.remove(),1450);}
function showSpray(data){if(!currentCanvas||!data?.residentId)return;const node=currentCanvas.querySelector(`[data-world-resident="${CSS.escape(String(data.residentId))}"]`),host=currentCanvas.getBoundingClientRect(),box=node?.getBoundingClientRect(),burst=document.createElement('div');burst.className='club-money-burst';burst.style.left=`${box?box.left-host.left+box.width/2:host.width*.55}px`;burst.style.top=`${box?box.top-host.top+box.height*.45:host.height*.58}px`;['₦','₦1k','₦','₦500','₦','₦5k','₦','₦1k','₦','₦'].forEach((label,index)=>{const note=document.createElement('i');note.textContent=label;note.style.setProperty('--i',String(index));note.style.setProperty('--x',`${Math.round((Math.random()-.5)*190)}px`);note.style.setProperty('--r',`${Math.round((Math.random()-.5)*80)}deg`);burst.append(note);});currentCanvas.append(burst);setTimeout(()=>burst.remove(),2100);}
function syncWorld(){const next=canvas();if(next!==currentCanvas){currentCanvas=next;}syncLabels();showStats();ensureClubDock();}
addEventListener('abujalife:living-city',event=>{const detail=event.detail||{};if(detail.type==='snapshot'){residents.clear();for(const person of (detail.nearby||[]).slice(0,50))residents.set(String(person.id),person);stats=detail.stats||stats;syncWorld();}else if(detail.type==='stats'){stats={...stats,...detail.stats};syncWorld();}else if(detail.type==='world-pose'){const person=residents.get(String(detail.data?.residentId||''));if(person&&detail.data?.pose)person.pose={...(person.pose||{}),...detail.data.pose};}else if(detail.type==='player-emote')showEmote(detail.data);else if(detail.type==='club-spray')showSpray(detail.data);});
addEventListener('pointerdown',event=>{syncWorld();if(!currentCanvas||!currentCanvas.contains(event.target))return;const node=event.target.closest?.('[data-world-resident]');if(node){const person=residents.get(String(node.dataset.worldResident));if(person){event.preventDefault();event.stopPropagation();openResident(person);}}},true);
let watchedCanvas,watchedResidents;
const worldObserver=new MutationObserver(()=>queueMicrotask(syncWorld));
function watchWorld(){
 const next=canvas(),online=next?.querySelector('.world-online');
 if(next!==watchedCanvas||online!==watchedResidents){
  worldObserver.disconnect();watchedCanvas=next;watchedResidents=online;
  if(next)worldObserver.observe(next,{childList:true});
  if(online)worldObserver.observe(online,{childList:true});
 }
 syncWorld();
}
// Observe render boundaries, never every animation/label mutation beneath them.
const observer=new MutationObserver(()=>queueMicrotask(watchWorld));observer.observe(document.querySelector('#app')||document.body,{childList:true});watchWorld();
