import {ABUJA_DISTRICT_ANCHORS,abujaToWorld,abujaNavigationNodes,abujaNavigationEdges,routeForJourney,sampleRoutePolyline} from '../src/shared/abuja-navigation.mjs';
import {vehicleFor,vehicleColorHex} from '../src/shared/vehicles.mjs';
import {buildThreeEnvironment} from './world-3d-scenes.js';
import {createCharacter,animateCharacter} from './world-character.js';
import * as THREE from './vendor/three.module.js';
import {adSpaceFromId,adSpacePage,MAP_AD_INVENTORY,COMPATIBILITY_MAP_AD_INVENTORY,BILLBOARD_IDS} from '../src/shared/advertising.mjs';
import {createMapAdDisplays} from './map-ad-displays.js';
import {createMapAdParcels} from './map-ad-parcels.js';
import {cityFallbackPosition as fallbackPosition} from '../src/shared/map-ad-land.mjs';
import { CITY_LANDMARKS } from '../src/shared/city-landmarks.mjs';
import {generateMapDetail,buildMapDetail,mapRoadWidth} from './map-city-detail.js';

// Premium authored Abuja overview. Coordinates preserve real-world relative
// relationships for game navigation; this is a stylised life-sim, not a survey map.
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toWorld=geo=>{const p=abujaToWorld(geo);return{x:p.x,z:p.y};};
const hash=text=>{let n=2166136261;for(const c of String(text||'')){n^=c.charCodeAt(0);n=Math.imul(n,16777619);}return n>>>0;};
const MOBILE=()=>globalThis.matchMedia?.('(pointer: coarse)').matches===true||(globalThis.navigator?.maxTouchPoints||0)>0;

const DISTRICT_ANCHORS=ABUJA_DISTRICT_ANCHORS;
const mapDetailCache={data:null,light:null};

const LANDMARKS=CITY_LANDMARKS;
const NIGHTLIFE_IDS=new Set(['club','club-cage','magic-city','bear-barn']);


function mat(color,opts={}){const {shadow,...rest}=opts;return new THREE.MeshStandardMaterial({color,roughness:.82,metalness:0,...rest});}
function mark(mesh,key,shadow=true){mesh.userData.destinationKey=key||mesh.userData.destinationKey;if(shadow){mesh.castShadow=true;mesh.receiveShadow=true;}return mesh;}
function box(g,c,x,y,z,w,h,d,r=0,o={},key){const m=mark(new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,o)),key,o.shadow!==false);m.position.set(x,y,z);m.rotation.y=r;g.add(m);return m;}
function cyl(g,c,x,y,z,r,h,s=24,o={},key){const m=mark(new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,s),mat(c,o)),key,o.shadow!==false);m.position.set(x,y,z);g.add(m);return m;}
function sphere(g,c,x,y,z,rx,ry=rx,rz=rx,o={},key){const m=mark(new THREE.Mesh(new THREE.SphereGeometry(1,20,14),mat(c,o)),key,o.shadow!==false);m.position.set(x,y,z);m.scale.set(rx,ry,rz);g.add(m);return m;}
function torus(g,c,x,y,z,r,tube,rx=Math.PI/2,rz=0,key){const m=mark(new THREE.Mesh(new THREE.TorusGeometry(r,tube,12,40),mat(c,{roughness:.46,metalness:.08})),key);m.position.set(x,y,z);m.rotation.x=rx;m.rotation.z=rz;g.add(m);return m;}
function cone(g,c,x,y,z,r,h,segments=4,key){const m=mark(new THREE.Mesh(new THREE.ConeGeometry(r,h,segments),mat(c,{roughness:.48})),key);m.position.set(x,y,z);g.add(m);return m;}
function pad(g,x,z,w=210,d=160,color='#9fb593',key){return box(g,color,x,1,z,w,2,d,0,{roughness:.98},key);}
function tree(g,x,z,s=1,palm=false,key){cyl(g,'#765f45',x,13*s,z,2.5*s,26*s,9,{},key);if(palm){for(let i=0;i<6;i++){const a=i*Math.PI/3;sphere(g,'#4d8057',x+Math.cos(a)*9*s,29*s,z+Math.sin(a)*9*s,12*s,3.4*s,5*s,{},key);}}else{sphere(g,'#4c7650',x,31*s,z,13*s,14*s,13*s,{},key);sphere(g,'#789665',x-5*s,40*s,z+2*s,8*s,8*s,8*s,{},key);}}
function road(g,a,b,width=38){const dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),ang=Math.atan2(dx,dz),mx=(a.x+b.x)/2,mz=(a.z+b.z)/2;box(g,'#46575a',mx,2,mz,width,4,len,ang,{roughness:.94,shadow:false});box(g,'#e7d7a9',mx,4,mz,2,1,len*.92,ang,{shadow:false});for(const side of[-1,1])box(g,'#bcc8b8',mx+Math.cos(ang)*width*.65*side,2.5,mz-Math.sin(ang)*width*.65*side,9,3,len,ang,{roughness:.9,shadow:false});}
function tag(g,key){g.traverse(o=>{if(o.isMesh){o.userData.destinationKey=key;o.castShadow=o.castShadow!==false;o.receiveShadow=true;}});}
function windows(g,key,xStart,count,step,yStart,rows,rowStep,z,w=9,h=8){for(let r=0;r<rows;r++)for(let i=0;i<count;i++)box(g,'#537781',xStart+i*step,yStart+r*rowStep,z,w,h,2,0,{roughness:.24,metalness:.18},key);}

function buildLandmark(world,item){const g=new THREE.Group();g.position.set(item.x,0,item.z);world.add(g);pad(g,0,0,225,170,'#a1b895',item.key);const b=(c,x,y,z,w,h,d,r=0,o={})=>box(g,c,x,y,z,w,h,d,r,o,item.key),cy=(c,x,y,z,r,h,s=24,o={})=>cyl(g,c,x,y,z,r,h,s,o,item.key),sp=(c,x,y,z,rx,ry,rz,o={})=>sphere(g,c,x,y,z,rx,ry,rz,o,item.key),co=(c,x,y,z,r,h,s=4)=>cone(g,c,x,y,z,r,h,s,item.key);
 switch(item.builder){
  case'airport':b('#e9ede9',0,26,0,222,44,80);b('#78a9b4',0,31,41,198,30,4,0,{roughness:.24,metalness:.18});b('#f3f2eb',0,51,2,235,9,106);b('#d7dbd5',-78,59,-13,52,23,56);cy('#dbe0db',84,50,-22,10,88);b('#547985',84,98,-22,34,13,34);b('#3b4d51',0,2,102,360,3,52,0,{shadow:false});for(let i=-4;i<=4;i++)b('#f3e5ba',i*38,4,102,20,1,2,0,{shadow:false});item.height=126;break;
  case'cityGate':for(const side of[-1,1])for(let i=0;i<6;i++){const y=19+i*15,x=side*(49-i*4),w=17-i*.8;b('#f2f0e8',x,y,0,w,29,28,side*(.04+i*.02));}b('#f4f2e9',0,54,1,92,10,22);b('#2f7952',0,69,4,29,16,6);b('#345b4f',0,8,-50,140,4,18);for(const side of[-1,1])tree(g,side*73,51,.9,true,item.key);item.height=116;break;
  case'stadium':cy('#d8d9d0',0,19,0,86,34,48);cy('#4f6961',0,37,0,69,13,48);torus(g,'#eeece2',0,48,0,76,9,Math.PI/2,0,item.key);cy('#6f9c69',0,48,0,46,3,44);item.height=93;break;
  case'magicland':b('#d8b27b',-58,23,-28,68,40,50);{const cx=43,cz=-18;cy('#79736a',cx,35,cz,3,70);torus(g,'#c78567',cx,49,cz,45,3,0,Math.PI/2,item.key);for(let i=0;i<12;i++){const a=i*Math.PI*2/12;sp(['#d6aa5d','#6799a0','#b96d67','#8173a0'][i%4],cx+Math.cos(a)*45,49+Math.sin(a)*45,cz,6,6,6);}}item.height=108;break;
  case'wtc':{const tower=(x,h,w)=>{b('#466873',x,h/2+6,0,w,h,64,0,{roughness:.22,metalness:.28});for(let y=22;y<h;y+=15)b('#d9c99e',x,y,34,w+8,2.3,7);for(const side of[-1,1])b('#d5d4cb',x+side*(w/2+4),h/2+6,0,5,h+4,68);b('#e4dcc6',x,h+10,0,w*.72,8,48);};tower(-39,194,68);tower(45,218,60);b('#c9cbbb',3,5,0,190,8,114);item.height=236;break;}
  case'cbn':b('#d9d5cb',0,97,0,150,188,88);b('#3d5d68',0,101,45,120,152,3,0,{roughness:.22,metalness:.25});for(const x of[-64,-32,0,32,64])b('#eee9de',x,104,47,7,160,7);b('#c8a062',0,18,54,140,15,25);co('#d7d0c2',0,208,-3,58,32,4);item.height=226;break;
  case'assembly':b('#f0f1ec',0,24,8,112,42,62);b('#e8ebe5',-82,21,8,62,35,52);b('#e8ebe5',82,21,8,62,35,52);cy('#ecece4',0,47,8,37,23,36);sp('#288454',0,65,8,35,22,35);b('#d9cca9',0,4,80,198,3,38,0,{shadow:false});for(const side of[-1,1])tree(g,side*91,67,.78,true,item.key);item.height=96;break;
  case'eagle':b('#ded5bd',0,3,0,170,4,120,0,{shadow:false});for(const side of[-1,1]){b('#e9e4d6',side*58,20,-18,34,36,28);cy('#d5a553',side*58,45,-18,7,24,8);}b('#6d8d75',0,5,40,110,2,22,0,{shadow:false});item.height=64;break;
  case'mosque':b('#ece9df',0,19,0,96,34,66);cy('#ede8dc',0,40,0,37,20,32);sp('#d5a63e',0,57,0,35,24,35);for(const[x,z]of[[-52,-30],[52,-30],[-52,30],[52,30]]){cy('#e7e4dc',x,48,z,6,92,12);co('#d7ad53',x,97,z,9,20,12);}item.height=112;break;
  case'church':b('#e6e0d4',0,26,0,105,48,72);b('#c7a064',0,54,35,44,18,5);for(const side of[-1,1])co('#ded8ca',side*34,78,-10,13,76,4);item.height=120;break;
  case'transcorp':b('#d7d3c7',0,56,0,188,104,58);for(let x=-80;x<=80;x+=20)for(let y=20;y<=90;y+=15)b('#55727a',x,y,30,12,8,3,0,{roughness:.25,metalness:.18});b('#ba9c73',0,7,58,138,10,35);for(let x=-76;x<=76;x+=38)tree(g,x,-46,.58,false,item.key);item.height=116;break;
  case'millennium':pad(g,0,0,220,165,'#78a56e',item.key);for(const p of[[-70,-45],[-20,35],[55,-10],[78,54],[-76,52],[8,-55]])tree(g,p[0],p[1],.85,p[0]>50,item.key);b('#d9ceb0',0,2,0,160,2,10,.45,{shadow:false});item.height=55;break;
  case'aso':{const rock=mark(new THREE.Mesh(new THREE.DodecahedronGeometry(1,1),mat('#9a927e',{roughness:.96})),item.key);rock.scale.set(96,112,76);rock.position.y=85;rock.rotation.set(.06,.35,-.04);g.add(rock);for(const x of[-82,-52,58,89])tree(g,x,65,.7,false,item.key);item.height=205;break;}
  case'farmCity':b('#b7815f',0,19,0,145,32,78);b('#5e7b61',0,39,0,154,10,86);b('#d6b36f',-50,11,54,42,16,30);b('#6d8b70',52,11,54,42,16,30);for(const x of[-84,84])tree(g,x,-50,.72,true,item.key);item.height=64;break;
  case'jabiLake':pad(g,0,0,225,168,'#75a66c',item.key);{const lake=new THREE.Mesh(new THREE.CircleGeometry(82,48),mat('#4ea8c7',{roughness:.18,metalness:.05,transparent:true,opacity:.9}));lake.rotation.x=-Math.PI/2;lake.scale.y=.72;lake.position.y=3;lake.userData.destinationKey=item.key;lake.receiveShadow=true;g.add(lake);}for(const p of[[-88,-52],[-88,45],[91,-36],[86,53]])tree(g,p[0],p[1],.67,p[0]>0,item.key);item.height=45;break;
  case'mall':b('#e2ded3',0,27,0,160,46,92);b('#7897a1',0,31,47,120,28,3,0,{roughness:.28,metalness:.16});b('#c6a066',-56,44,47,18,12,4);b('#5b7b64',40,44,47,45,10,4);item.height=68;break;
  case'conference':b('#ded9cb',0,20,0,142,34,86);cy('#d2c6ad',0,43,0,53,18,40);torus(g,'#718c83',0,49,0,49,4,Math.PI/2,0,item.key);b('#5f7c83',0,25,45,96,24,3,0,{roughness:.25,metalness:.17});item.height=71;break;
  case'banex':for(const x of[-55,0,55]){b(x?'#d2c2a4':'#e0d5be',x,22,0,48,38,70);b('#5c7f84',x,26,36,34,20,3,0,{roughness:.27,metalness:.12});}b('#bf8b55',0,5,49,178,8,22);item.height=61;break;
  case'inec':{b('#dedfd8',0,25,0,156,42,78);b('#ebe9df',0,53,-5,58,55,44);b('#526f72',0,54,19,42,39,3,0,{roughness:.28,metalness:.15});for(const x of[-56,-28,28,56])b('#657f83',x,28,40,14,18,3);b('#2d7650',0,14,43,54,7,4);item.height=86;break;}
  case'efcc':{b('#e7e8e1',0,53,0,128,98,70);b('#edf0eb',-52,24,28,58,42,50);b('#546f79',12,57,36,62,74,3,0,{roughness:.25,metalness:.2});b('#8a4b42',-43,58,36,10,77,4);for(let y=24;y<92;y+=17)b('#ced5d1',46,y,36,22,7,3);item.height=112;break;}
  case'court':{b('#e9e7de',0,28,0,152,48,72);b('#ded8c9',0,53,-6,85,18,50);for(let x=-55;x<=55;x+=22)cy('#f1efe7',x,29,40,4,42,14);b('#b18c5b',0,7,48,165,8,28);co('#dfd9cd',0,77,-8,45,30,4);item.height=98;break;}
  default:b('#d5cbb5',0,29,0,118,52,78);b('#6f9297',0,33,40,82,22,3,0,{roughness:.3,metalness:.12});item.height=72;
 }
 tag(g,item.key);return g;}

function buildNightlifeDestination(world,item){const palette=item.id==='club-cage'?['#273945','#49d7ee','#75a6a2']:item.id==='magic-city'?['#49314a','#f47bc5','#b28bc1']:item.id==='bear-barn'?['#69503d','#e5ad5d','#c29b68']:['#343b50','#f15cab','#78849a'],g=new THREE.Group();g.position.set(item.x,0,item.z);world.add(g);pad(g,0,0,190,148,palette[2],item.key);box(g,palette[0],0,28,0,118,52,82,0,{roughness:.88},item.key);box(g,palette[0],0,57,-2,126,8,90,0,{roughness:.84},item.key);box(g,palette[1],0,42,42,72,21,4,0,{roughness:.3,metalness:.16,emissive:palette[1],emissiveIntensity:.12},item.key);for(const x of[-42,-21,21,42])box(g,palette[1],x,20,42,5,35,4,0,{roughness:.4,emissive:palette[1],emissiveIntensity:.14},item.key);for(const x of[-48,48])box(g,'#d9d2bf',x,12,47,8,22,7,0,{roughness:.72},item.key);return g;}

function createAdPlots(){return [...MAP_AD_INVENTORY,...COMPATIBILITY_MAP_AD_INVENTORY,...BILLBOARD_IDS.map(adSpaceFromId).filter(p=>p?.eligible)].map(space=>({...space,x:space.x+space.width/2,z:space.y+space.height/2,w:space.width,d:space.height,key:`ad:${space.id}`,adPlotId:space.id,height:8,category:'Advertising land',destination:{adPlotId:space.id}}));}
export function createLayout(atlas=[],venues=[],profile={}){
 const venueMap=new Map(venues.map(v=>[v.id,v])),landmarks=LANDMARKS.map(source=>{const p=toWorld(source),venue=venueMap.get(source.id);return{...source,...p,venueId:venue?.id||null,key:`landmark:${source.id}`,destination:{districtId:source.districtId,...(venue?{venueId:venue.id}:{})}};}),landmarkById=new Map(landmarks.map(v=>[v.id,v])),districts=atlas.map((place,index)=>{const anchor=place.coordinates||DISTRICT_ANCHORS[place.id],p=anchor?toWorld(anchor):fallbackPosition(place,index);return{...place,...p,key:`district:${place.id}`,priority:20,destination:{districtId:place.id}};}),districtById=new Map(districts.map(place=>[place.id,place])),nightlife=venues.filter(venue=>NIGHTLIFE_IDS.has(venue.id)).map((venue,index)=>{const districtId=venue.districts?.[0]||profile.district||'central-area',district=districtById.get(districtId),anchor=district?{x:district.x,z:district.z}:DISTRICT_ANCHORS[districtId]?toWorld(DISTRICT_ANCHORS[districtId]):fallbackPosition({id:districtId},index),angle=(hash(venue.id)%6283)/1000;return{...venue,id:venue.id,x:anchor.x+Math.cos(angle)*150,z:anchor.z+Math.sin(angle)*150,height:72,priority:92,districtId,key:`venue:${venue.id}`,destination:{districtId,venueId:venue.id}};}),adPlots=createAdPlots();
 return{width:10400,depth:7600,landmarks,landmarkById,districts,nightlife,adPlots,all:[...landmarks,...nightlife,...districts,...adPlots]};
}

function contactTexture(){const size=64,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=(x+.5-size/2)/(size/2),dy=(y+.5-size/2)/(size/2),r=Math.hypot(dx,dy),i=(y*size+x)*4,a=Math.pow(Math.max(0,1-r),1.55);data[i]=37;data[i+1]=30;data[i+2]=24;data[i+3]=Math.round(a*78);}const t=new THREE.DataTexture(data,size,size,THREE.RGBAFormat);t.needsUpdate=true;t.colorSpace=THREE.SRGBColorSpace;t.magFilter=t.minFilter=THREE.LinearFilter;return t;}
export function buildCity(layout,{now=Date.now}={}){const scene=new THREE.Scene(),world=new THREE.Group();scene.add(world);scene.background=new THREE.Color('#5f9f52');scene.fog=new THREE.Fog('#9fcf8f',9000,17000);
 // Open country continues past the mapped territory instead of ending on a floating slab.
 box(world,'#5f9f52',0,-16,0,layout.width*3,24,layout.depth*3,0,{roughness:1,shadow:false});box(world,'#73b060',0,-14,0,layout.width,24,layout.depth,0,{roughness:1,shadow:false});box(world,'#8cc671',0,-1,0,layout.width-620,5,layout.depth-620,0,{roughness:1,shadow:false});const roadNodes=new Map(abujaNavigationNodes().map(node=>[node.id,{x:node.x,z:node.y}])),mapRoads=[];for(const edge of abujaNavigationEdges()){const a=roadNodes.get(edge.a),b=roadNodes.get(edge.b);if(a&&b){road(world,a,b,mapRoadWidth(edge.roadClass));mapRoads.push({a,b,roadClass:edge.roadClass});}}
 // City detail is generated once per session and added just after the first frame,
 // so opening the Map never waits on it.
 let detail=null,detailGone=false;const detailTimer=setTimeout(()=>{if(detailGone)return;const light=MOBILE();mapDetailCache.data=mapDetailCache.light===light&&mapDetailCache.data||generateMapDetail({layout,roads:mapRoads,light});mapDetailCache.light=light;detail=buildMapDetail(THREE,world,mapDetailCache.data);world.userData.detailStats=detail.stats;world.userData.detailReady?.();},30);const districts=new Map(layout.districts.map(v=>[v.id,v])),core=['central-area','wuse-i','wuse-ii-a07','wuse-ii-a08','maitama','asokoro','jabi','utako','wuye','garki-i','garki-ii','mabushi','gwarinpa-i','lugbe','kukwaba'];for(const id of core){const p=districts.get(id);if(!p)continue;pad(world,p.x,p.z,270,198,id==='central-area'?'#a9bb99':'#9fb292');const n=hash(id),base=id==='central-area'?58:id==='maitama'||id==='asokoro'?42:31;for(let k=0;k<4;k++){const a=k*Math.PI/2+.55,h=base+((n>>(k*3))%28);box(world,k%2?'#d9cfb8':'#c7c4b1',p.x+Math.cos(a)*80,h/2+4,p.z+Math.sin(a)*60,55,h,43,a*.14,{shadow:false});}for(let k=0;k<5;k++)tree(world,p.x-108+k*54,p.z+91,.58,k%4===0);}
 for(const l of layout.landmarks)buildLandmark(world,l);for(const venue of layout.nightlife)buildNightlifeDestination(world,venue);
 // Quiet land boundaries make inventory discoverable; paid images remain separate.
 const parcels=createMapAdParcels(world,layout.adPlots.map(p=>({...p,x:p.x-p.width/2,y:p.z-p.height/2})),{now});parcels.update(globalThis.__ABJ_ADS__);
 const ads=createMapAdDisplays(world,{now});ads.update(globalThis.__ABJ_ADS__);
 const shadowTex=contactTexture(),shadowMat=new THREE.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false,toneMapped:false});for(const l of layout.landmarks){const plane=new THREE.Mesh(new THREE.PlaneGeometry(190,135),shadowMat);plane.rotation.x=-Math.PI/2;plane.position.set(l.x,4,l.z);plane.renderOrder=1;world.add(plane);}
 const carGeo=new THREE.BoxGeometry(24,10,38),carMats=['#d6a86b','#334f5b','#eee8d9','#6d7965'].map(c=>mat(c,{roughness:.42,metalness:.08})),traffic=[];for(let i=0;i<16;i++){const m=new THREE.Mesh(carGeo,carMats[i%carMats.length]);m.position.set(-2600+i*220,9,430+(i%3)*19);m.castShadow=false;m.receiveShadow=true;world.add(m);traffic.push({mesh:m,offset:i*270,speed:31+(i%4)*7});}
 const aircraft=[];const airport=layout.landmarkById.get('airport-hub');if(airport){for(let i=0;i<3;i++){const plane=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(5,52,4,10),mat('#ecebe2',{roughness:.74}));body.rotation.z=Math.PI/2;plane.add(body);const wing=new THREE.Mesh(new THREE.BoxGeometry(78,2.5,15),mat('#d4d7cf',{roughness:.8}));plane.add(wing);const tail=new THREE.Mesh(new THREE.BoxGeometry(18,18,3),mat('#58776c',{roughness:.82}));tail.position.x=-25;tail.rotation.z=.55;plane.add(tail);plane.position.set(airport.x-150+i*115,18,airport.z+108+i*18);plane.scale.setScalar(.7);world.add(plane);aircraft.push({mesh:plane,offset:i*310,speed:19+i*4});}}
 const ambient=new THREE.HemisphereLight('#fff1d7','#4f6655',1.45);scene.add(ambient);const sun=new THREE.DirectionalLight('#ffe6ba',3.05);sun.position.set(-3200,5600,2500);sun.castShadow=true;sun.shadow.mapSize.set(MOBILE()?512:1024,MOBILE()?512:1024);sun.shadow.camera.left=-5100;sun.shadow.camera.right=5100;sun.shadow.camera.top=3900;sun.shadow.camera.bottom=-3900;sun.shadow.camera.near=100;sun.shadow.camera.far=10500;sun.shadow.bias=-.0004;sun.shadow.normalBias=.85;sun.shadow.radius=3;scene.add(sun);const fill=new THREE.DirectionalLight('#d9eef1',.68);fill.position.set(2600,1700,-3000);scene.add(fill);
 return{scene,world,sun,shadowTex,traffic,ads,parcels,updateAds(state){parcels.update(state);return ads.update(state);},updateTraffic(t){for(const[i,row]of traffic.entries()){row.mesh.position.x=-3100+((row.offset+t*row.speed)%6200);row.mesh.position.z=430+(i%3)*19;}for(const row of aircraft){const airport=layout.landmarkById.get('airport-hub');if(!airport)continue;row.mesh.position.x=airport.x-230+((row.offset+t*row.speed)%460);row.mesh.position.z=airport.z+108+Math.sin((row.offset+t*row.speed)*.012)*13;}},dispose(){detailGone=true;clearTimeout(detailTimer);detail?.dispose();parcels.dispose();ads.dispose();const geos=new Set(),mats=new Set();scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])mats.add(m);});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());shadowTex.dispose();sun.shadow.map?.dispose();}};}

export function renderOutside(root,{atlas=[],venues=[],profile={},onSelect=()=>{},onHome,journey=null,serverNow,onArrive}={}){const layout=createLayout(atlas,venues,profile),all=layout.all;root.innerHTML=`<section class="outside-city outside-city-v2 outside-city-v3 outside-city-v4" aria-label="Premium 3D Abuja city"><div class="outside-stage" tabindex="0" role="application" aria-label="3D Abuja. Drag to move, pinch or scroll to zoom, tap landmarks and advertising plots."></div><div class="outside-roof-labels"></div><header class="outside-heading"><span class="outside-eyebrow">ABUJA LIFE · CITY</span><h2>Your Abuja, alive.</h2><p>Recognisable landmarks · multiplayer destinations · city stories · business displays across the map</p></header><div class="outside-tools"><button type="button" data-outside-action="overview">↗<span>Abuja</span></button><button type="button" data-outside-action="ads" aria-label="Show advertising plots" aria-pressed="false">▦<span>Advertise</span></button><button type="button" data-outside-action="mode" aria-pressed="false">↻<span>Orbit</span></button><button type="button" data-outside-action="out">−</button><button type="button" data-outside-action="in">+</button>${onHome?'<button type="button" data-outside-action="home">⌂</button>':''}</div><div class="outside-directory"><label class="outside-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Find a landmark, district or ad plot" aria-label="Search Abuja" autocomplete="off"><button type="button" data-outside-action="directory" aria-expanded="false">☷</button></label><div class="outside-results" hidden></div></div><aside class="outside-selection" hidden></aside><p class="outside-hint">Drag to explore · pinch to zoom · tap a place · Advertise to explore eligible land</p><div class="outside-status" aria-live="polite"></div></section>`;
 const shell=root.querySelector('.outside-city'),stage=root.querySelector('.outside-stage'),labelsRoot=root.querySelector('.outside-roof-labels'),input=root.querySelector('.outside-search input'),results=root.querySelector('.outside-results'),selection=root.querySelector('.outside-selection'),status=root.querySelector('.outside-status');root.dataset.outsideLandmarks=String(layout.landmarks.length);root.dataset.outsideAdPlots=String(layout.adPlots.length);root.dataset.outsideLimits=JSON.stringify({minZoom:.22,maxZoom:24,width:layout.width,depth:layout.depth});
 const startClock=Number(serverNow)||Date.now(),startPerf=performance.now(),clock=()=>startClock+performance.now()-startPerf;
 const trip=journey||null,route=trip?routeForJourney({fromDistrict:trip.fromLocation?.district||profile.district,fromVenue:trip.fromLocation?.kind==='venue'?trip.fromLocation.venue:null,toDistrict:trip.destination,toVenue:trip.venueId,returningHome:trip.returningHome,homeDistrict:profile.home?.district}):null;
 const routePoints=route?.points?.map(point=>({...point}))||[];
 const venuePosition=id=>layout.nightlife.find(place=>place.id===id)||layout.landmarks.find(place=>place.id===id);
 const origin=venuePosition(trip?.fromLocation?.venue),destination=venuePosition(trip?.venueId);
 if(origin&&routePoints.length)routePoints.unshift({x:origin.x,y:origin.z});if(destination&&routePoints.length){const last=routePoints.at(-1);if(Math.hypot(last.x-destination.x,last.y-destination.z)>1)routePoints.push({x:destination.x,y:destination.z});}
 const duration=Math.max(1,Number(trip?.seconds)||30)*1000,startsAt=Number(trip?.arrivesAt)-duration,progress=()=>trip?clamp((clock()-startsAt)/duration,0,1):0;
 let journeyModel=null,walkingModel=null,journeyAngle=0,journeyPose=null,arrivalSent=false;
 const listeners=[],listen=(t,e,f,o)=>{t.addEventListener(e,f,o);listeners.push(()=>t.removeEventListener(e,f,o));};let framed=false,renderer,model,camera,raf=0,disposed=false,last=0,elapsed=0,selected=null,directoryOpen=false,orbitMode=false,advertiseMode=false,pinchBase=null,frame=0,dragDistance=0;const home=layout.districts.find(d=>d.id===(profile.home?.district||profile.district)),view={x:home?.x||0,z:home?.z||0,zoom:.82,yaw:.42,elevation:.82},target={...view},pointers=new Map(),size={width:1,height:1};
 if(trip){const initial=sampleRoutePolyline(routePoints,progress());if(initial){view.x=target.x=initial.x;view.z=target.z=initial.y;}shell.classList.add('is-journey');root.dataset.sceneKind='transit';root.dataset.routeNodes=(route?.nodeIds||[]).join('>');status.textContent=`${trip.mode==='walk'?'Walking':'Driving'} through Abuja`;target.zoom=view.zoom=18;target.elevation=view.elevation=.7;}
 const labels=[];for(const place of all){const b=document.createElement('button');b.type='button';b.className=`outside-roof-label ${place.adPlotId?'outside-ad-label':place.venueId?'outside-venue-label':place.key.startsWith('district:')?'outside-district-label':'outside-landmark-label'}`;b.textContent=place.adPlotId?'Advertise here':(place.short||place.name);b.dataset.destinationKey=place.key;if(place.adPlotId)b.dataset.adPlotId=place.adPlotId;b.setAttribute('aria-label',`${place.name}. ${place.adPlotId?'Advertising plot. ':place.venueId?'Multiplayer destination. ':''}View destination`);labelsRoot.append(b);labels.push({place,button:b,point:new THREE.Vector3(place.x,place.adPlotId?10:Number(place.height||50)+18,place.z)});}
 const viewport=()=>{const aspect=size.width/size.height,base=Math.max(layout.width,layout.depth*aspect)*1.03;return{width:base/view.zoom,height:base/aspect/view.zoom};},constrain=()=>{target.x=clamp(target.x,-37000,37000);target.z=clamp(target.z,-37000,37000);target.elevation=clamp(target.elevation,.48,1.18);},zoom=f=>{target.zoom=clamp(target.zoom*f,.22,24);},overview=()=>{Object.assign(target,{x:-120,z:100,zoom:.59,yaw:.42,elevation:.82});selected=null;selection.hidden=true;status.textContent='Whole Abuja view';};
 const choose=(place,{focus=true}={})=>{selected=place;if(focus){target.x=place.x;target.z=place.z;const adFootprint=(place.width||place.w||320)*Math.abs(Math.cos(target.yaw))+(place.height||place.d||220)*Math.abs(Math.sin(target.yaw)),adZoom=clamp(Math.max(layout.width,layout.depth*size.width/size.height)*1.03*.78/adFootprint,8,24);target.zoom=Math.max(place.adPlotId?adZoom:4.6,target.zoom);}selection.hidden=false;const ad=!!place.adPlotId,venue=!!place.venueId,paid=place.campaign;selection.innerHTML=`<button type="button" class="outside-selection-close" data-outside-action="close" aria-label="Close">×</button><span>${ad?'ADVERTISING LAND':venue?'MULTIPLAYER DESTINATION':'ABUJA PLACE'}</span><h3>${esc(place.name)}</h3><p>${esc(paid?`Sponsored · ${paid.sponsor||paid.title}`:ad?'A seven-day business display in AbujaLife. This is advertising space in the game.':place.blurb||place.vibe||place.description||'Explore this part of Abuja.')}</p>${paid?.campaignType==='house'?`<p class="outside-house-copy">${esc(paid.body)}</p><small class="outside-house-contact">${esc(paid.domain)} · ${esc(paid.email)}</small>`:''}${paid?`<a class="outside-sponsored-link" href="${esc(paid.link)}" target="_blank" rel="noopener noreferrer sponsored">${esc(paid.cta||`Visit ${paid.title}`)} ↗</a>`:''}${venue?'<small class="outside-multiplayer-note">● Residents here share the same live destination.</small>':''}<button type="button" class="outside-travel" data-outside-action="${ad?'advertise':'travel'}">${ad?(paid?'Advertise in Abuja':'Buy / manage this space'):'Choose how to go'} <span>→</span></button>`;status.textContent=`${place.name} selected.`;if(focus){input.value='';directoryOpen=false;results.hidden=true;shell.querySelector('[data-outside-action="directory"]').setAttribute('aria-expanded','false');}};
 const renderDirectory=()=>{const q=input.value.trim().toLowerCase(),matches=all.filter(p=>`${p.name} ${p.short||''} ${p.category||''} ${p.id}`.toLowerCase().includes(q));results.hidden=!q&&!directoryOpen;results.innerHTML=matches.slice(0,90).map(p=>`<button type="button" data-outside-destination="${esc(p.key)}"><strong>${esc(p.name)}</strong><span>${esc(p.adPlotId?'Advertising land':p.venueId?'Multiplayer destination':p.category||p.vibe||'Abuja')}</span></button>`).join('')||'<p>No match. Try a landmark, district or ad plot.</p>';};listen(input,'input',renderDirectory);
 listen(shell,'click',event=>{const node=event.target.closest('button');if(!node)return;const key=node.dataset.destinationKey||node.dataset.outsideDestination;if(key){const p=all.find(v=>v.key===key);if(p){const paid=model?.ads.placements.find(v=>v.id===p.adPlotId);choose(paid?{...paid,x:paid.x+paid.width/2,z:paid.z+paid.height/2,name:paid.campaign.title,adPlotId:paid.id}:p);}return;}switch(node.dataset.outsideAction){case'ads':advertiseMode=!advertiseMode;node.setAttribute('aria-pressed',String(advertiseMode));node.setAttribute('aria-label',advertiseMode?'Hide advertising plots':'Show advertising plots');status.textContent=advertiseMode?'Tap an outlined advertising plot. Availability is checked before checkout.':'Explore Abuja and choose a destination.';break;case'overview':overview();break;case'mode':orbitMode=!orbitMode;node.setAttribute('aria-pressed',String(orbitMode));node.querySelector('span').textContent=orbitMode?'Pan':'Orbit';break;case'in':zoom(1.38);break;case'out':zoom(1/1.38);break;case'directory':directoryOpen=!directoryOpen;node.setAttribute('aria-expanded',String(directoryOpen));renderDirectory();break;case'close':selected=null;selection.hidden=true;break;case'home':onHome?.();break;case'travel':if(selected?.destination?.districtId)onSelect(selected.destination);break;case'advertise':if(selected?.adPlotId){const space=adSpaceFromId(selected.adPlotId),authored=layout.adPlots.some(p=>p.adPlotId===selected.adPlotId);onSelect({advertise:true,kind:space?.kind||'plot',adPlotId:selected.campaign?null:selected.adPlotId,adZoneId:authored&&space?.kind==='plot'?'map-parcels':space?.zoneId,page:adSpacePage(selected.adPlotId)});}break;}});
 try{renderer=new THREE.WebGLRenderer({antialias:!MOBILE(),powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,MOBILE()?1.15:1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;renderer.toneMappingExposure=1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.domElement.setAttribute('aria-hidden','true');stage.append(renderer.domElement);model=buildCity(layout,{now:clock});renderer.shadowMap.needsUpdate=true;model.world.userData.detailReady=()=>{if(renderer&&!disposed)renderer.shadowMap.needsUpdate=true;};camera=new THREE.OrthographicCamera(-1,1,1,-1,1,19000);
 if(trip){
  if(trip.mode==='walk'){walkingModel=createCharacter(profile.appearance||{});walkingModel.root.scale.setScalar(.28);model.world.add(walkingModel.root);}
  else{const vehicleId=trip.vehicleId,item=vehicleFor(vehicleId);journeyModel=buildThreeEnvironment(THREE,{scene:{width:1,height:1},depthScale:1,modelOnly:{category:'vehicle',id:vehicleId,color:trip.mode==='taxi'?'#d0b075':vehicleColorHex(profile,vehicleId),bodyStyle:trip.mode==='bus'?'bus':trip.mode==='taxi'?'taxi':item?.bodyStyle||'sedan'}});journeyModel.group.scale.setScalar(.3);model.world.add(journeyModel.group);}
  const path=new THREE.BufferGeometry().setFromPoints(routePoints.map(p=>new THREE.Vector3(p.x,8,p.y)));model.world.add(new THREE.Line(path,new THREE.LineBasicMaterial({color:'#eac36a',transparent:true,opacity:.65})));
  const end=routePoints.at(-1);if(end){const marker=new THREE.Mesh(new THREE.TorusGeometry(24,3,6,24),new THREE.MeshBasicMaterial({color:'#efc76f'}));marker.rotation.x=Math.PI/2;marker.position.set(end.x,9,end.y);model.world.add(marker);}
 }
 root.dataset.outsideRenderer='webgl-3d-v4';}catch{renderer?.dispose?.();renderer=null;labelsRoot.hidden=true;stage.innerHTML='<p class="outside-unavailable">3D is unavailable on this device. Use search to move around Abuja.</p>';directoryOpen=true;renderDirectory();}
 const pan=(dx,dy)=>{const span=viewport(),sx=-dx*span.width/size.width,sz=-dy*span.height/size.height/Math.max(.45,Math.sin(view.elevation));target.x+=sx*Math.cos(view.yaw)+sz*Math.sin(view.yaw);target.z+=-sx*Math.sin(view.yaw)+sz*Math.cos(view.yaw);constrain();},distance=pts=>Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);
 listen(stage,'pointerdown',e=>{if(e.button>0)return;dragDistance=0;stage.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY});if(pointers.size===2){dragDistance=100;pinchBase={distance:distance([...pointers.values()]),zoom:target.zoom};}});
 listen(stage,'pointermove',e=>{if(trip&&pointers.size<2)return;const p=pointers.get(e.pointerId);if(!p)return;const dx=e.clientX-p.lastX,dy=e.clientY-p.lastY;p.x=e.clientX;p.y=e.clientY;p.lastX=e.clientX;p.lastY=e.clientY;dragDistance+=Math.abs(dx)+Math.abs(dy);if(pointers.size===2){const pts=[...pointers.values()],d=distance(pts);if(pinchBase?.distance)target.zoom=clamp(pinchBase.zoom*d/pinchBase.distance,.22,24);}else if(orbitMode){target.yaw+=dx*.006;target.elevation+=dy*.004;constrain();}else pan(dx,dy);});
 const pointerUp=e=>{if(e.type==='pointercancel')dragDistance=100;pointers.delete(e.pointerId);pinchBase=null;};listen(stage,'pointerup',pointerUp);listen(stage,'pointercancel',pointerUp);listen(stage,'wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.0014));},{passive:false});
 const ray=new THREE.Raycaster(),ndc=new THREE.Vector2();listen(stage,'click',e=>{
  if(trip||dragDistance>8||!renderer||!camera)return;const rect=stage.getBoundingClientRect();ndc.set((e.clientX-rect.left)/rect.width*2-1,1-(e.clientY-rect.top)/rect.height*2);ray.setFromCamera(ndc,camera);
  const hit=ray.intersectObjects(model.world.children,true).find(h=>h.object.userData.destinationKey||h.object.userData.adParcelIds?.[h.instanceId]);if(!hit)return;
  const plotId=hit.object.userData.adParcelIds?.[hit.instanceId];
  const paid=model.ads.placements.find(p=>plotId?p.id===plotId:p.key===hit.object.userData.destinationKey);
  if(paid){choose({...paid,x:paid.x+paid.width/2,z:paid.z+paid.height/2,name:paid.campaign.title,adPlotId:paid.id});return;}
  const place=all.find(p=>plotId?p.adPlotId===plotId:p.key===hit.object.userData.destinationKey);if(place)choose(place);
 });
 listen(window,'abj:ads-updated',event=>{model?.updateAds(event.detail);if(selected?.campaign){const fresh=model?.ads.placements.find(p=>p.id===selected.id);if(fresh)choose({...fresh,x:fresh.x+fresh.width/2,z:fresh.z+fresh.height/2,name:fresh.campaign.title,adPlotId:fresh.id},{focus:false});else{selected=null;selection.hidden=true;}}});
 function resize(){const r=stage.getBoundingClientRect();if(r.width<2||r.height<2)return;size.width=Math.round(r.width);size.height=Math.round(r.height);renderer?.setSize(size.width,size.height,false);
  // Open framed on the city around the resident, about 3,600 units across, on any screen shape.
  if(!framed&&size.width>1&&size.height>1){framed=true;if(!trip){const aspect=size.width/size.height,base=Math.max(layout.width,layout.depth*aspect)*1.03;view.zoom=target.zoom=clamp(base/3600,.82,6);}}}const ro=new ResizeObserver(resize);ro.observe(stage);resize();
 let viewportSignature='',lastAdViewportAt=0;const projected=new THREE.Vector3();function cameraUpdate(){if(!camera)return;const span=viewport(),aspect=size.width/size.height;camera.left=-span.width/2;camera.right=span.width/2;camera.top=span.height/2;camera.bottom=-span.height/2;camera.near=10;camera.far=19000;const elevation=Math.max(.2,view.elevation),dist=7200;camera.position.set(view.x+Math.sin(view.yaw)*Math.cos(elevation)*dist,Math.sin(elevation)*dist,view.z+Math.cos(view.yaw)*Math.cos(elevation)*dist);camera.lookAt(view.x,0,view.z);camera.updateProjectionMatrix();camera.updateMatrixWorld();}
 let lastLabelsAt=-Infinity;
 const labelCorner=new THREE.Vector3();
 function updateLabels(){
  if(!camera||performance.now()-lastLabelsAt<100)return;
  lastLabelsAt=performance.now();
  // Include the map's own dock and quick filters, which can sit outside the
  // renderer root. World labels must yield to every fixed-control zone.
  const stageRect=stage.getBoundingClientRect(),hudRoot=shell.closest('.abj-restored-map')||shell,blocked=[...hudRoot.querySelectorAll('.outside-heading,.outside-tools,.outside-directory,.outside-quick,.outside-selection:not([hidden]),.abj-map-bottom-nav,.abj-restored-map-close')].map(el=>el.getBoundingClientRect()).filter(rect=>rect.width>0&&rect.height>0);
  const slots=new Map((globalThis.__ABJ_ADS__?.spaces||[]).map(p=>[p.id,p]));
  const paidIds=new Set(model?.ads.placements.map(p=>p.id)||[]),visible=[];
  for(const row of labels){
   const p=row.place,b=row.button,far=view.zoom<1.1;
   if(p.adPlotId){
    // Boundary boxes remain visible in ordinary exploration. Text appears only
    // when a plot has enough screen area, with a bounded label budget below.
    if(paidIds.has(p.adPlotId)){b.hidden=true;continue;}
    labelCorner.set(p.x+p.w/2,10,p.z+p.d/2).project(camera);
    projected.copy(row.point).project(camera);
    const pixels=Math.max(Math.abs(labelCorner.x-projected.x)*size.width,Math.abs(labelCorner.y-projected.y)*size.height);
    if(pixels<(advertiseMode?6:48)){b.hidden=true;continue;}
    const slot=slots.get(p.adPlotId);
    b.textContent=slot?.available===false?'Reserved ad plot':'Advertise here';
   }
   if(p.key.startsWith('district:')&&view.zoom<.66){b.hidden=true;continue;}
   if(p.venueId&&far&&p.priority<94){b.hidden=true;continue;}
   projected.copy(row.point).project(camera);
   const x=(projected.x+1)*size.width/2,y=(1-projected.y)*size.height/2;
   if(projected.z>1||x<(p.adPlotId?65:15)||x>size.width-(p.adPlotId?65:15)||y<24||y>size.height-80){b.hidden=true;continue;}
   const screenX=stageRect.left+x,screenY=stageRect.top+y;
   if(blocked.some(r=>screenX+60>r.left&&screenX-60<r.right&&screenY+24>r.top&&screenY-24<r.bottom)){b.hidden=true;continue;}
   b.hidden=false;b.style.transform=`translate3d(${Math.round(x)}px,${Math.round(y)}px,0)${p.adPlotId?' translate(-50%,-50%)':''}`;
   visible.push({b,x,y,ad:!!p.adPlotId,priority:p.priority||0,selected:selected?.key===p.key});
  }
  visible.sort((a,b)=>Number(b.selected)-Number(a.selected)||b.priority-a.priority);
  const kept=[];let adsKept=0;
  for(const row of visible){
   const collide=kept.some(k=>Math.abs(k.x-row.x)<115&&Math.abs(k.y-row.y)<48);
   if((collide&&!row.selected)||(row.ad&&adsKept>=12))row.b.hidden=true;
   else{kept.push(row);if(row.ad)adsKept++;}
  }
 }

 function tick(now){if(disposed)return;
  if(trip){const sample=sampleRoutePolyline(routePoints,progress());if(sample){const dt=Math.min(.05,(now-last||now)/1000),ease=1-Math.exp(-10*dt);if(!journeyPose)journeyPose={x:sample.x,y:sample.y};else{journeyPose.x+=(sample.x-journeyPose.x)*ease;journeyPose.y+=(sample.y-journeyPose.y)*ease;}journeyAngle+=((sample.angle-journeyAngle+540)%360-180)*(1-Math.exp(-11*dt));const body=journeyModel?.group||walkingModel?.root;if(body){body.position.set(journeyPose.x,8,journeyPose.y);body.rotation.y=-journeyAngle*Math.PI/180;}if(walkingModel)animateCharacter(walkingModel,{x:journeyPose.x,y:journeyPose.y*Math.SQRT1_2,angle:journeyAngle,moving:progress()<1,time:elapsed,phase:elapsed*6,scale:.28,elevation:8});target.x=journeyPose.x;target.z=journeyPose.y;root.dataset.routeProgress=progress().toFixed(4);root.dataset.playerX=journeyPose.x.toFixed(2);root.dataset.playerY=journeyPose.y.toFixed(2);root.dataset.driving=String(trip.mode!=='walk');root.dataset.vehicleAngle=journeyAngle.toFixed(2);root.dataset.moving=String(progress()<1);status.textContent=progress()<1?`${Math.max(0,Math.ceil((trip.arrivesAt-clock())/1000))}s · ${trip.mode==='walk'?'walking':'driving'} through Abuja`:'Confirming arrival…';if(progress()>=1&&!arrivalSent){arrivalSent=true;void Promise.resolve(onArrive?.(trip.id)).catch(()=>{});}}
  }const dt=Math.min(.05,(now-last||now)/1000);last=now;elapsed+=dt;const ease=1-Math.pow(.001,dt);for(const k of['x','z','zoom','yaw','elevation'])view[k]+=(target[k]-view[k])*ease;cameraUpdate();root.dataset.cameraX=view.x.toFixed(2);root.dataset.cameraY=view.z.toFixed(2);model?.ads.setView(camera,size);model?.parcels.setView(camera,size,{advertiseMode,selectedId:selected?.adPlotId});if(!trip&&now-lastAdViewportAt>800){const span=viewport(),bounds={x:Math.floor(view.x-span.width),y:Math.floor(view.z-span.height),width:Math.ceil(span.width*2),height:Math.ceil(span.height*2)},signature=Object.values(bounds).map(v=>Math.round(v/150)).join(':');if(signature!==viewportSignature){viewportSignature=signature;lastAdViewportAt=now;dispatchEvent(new CustomEvent('abj:ad-viewport',{detail:bounds}));}}model?.updateTraffic(elapsed);if(renderer&&model&&camera){if(frame++===0||frame%180===0)renderer.shadowMap.needsUpdate=true;renderer.render(model.scene,camera);}if(frame%2===0)updateLabels();raf=requestAnimationFrame(tick);}if(renderer||trip)raf=requestAnimationFrame(tick);
 const dispose=()=>{if(disposed)return;disposed=true;cancelAnimationFrame(raf);ro.disconnect();listeners.splice(0).forEach(fn=>fn());journeyModel?.dispose();walkingModel?.dispose?.();model?.dispose();renderer?.dispose();renderer?.domElement.remove();};dispose.focusDistrict=id=>{const p=layout.landmarks.find(v=>v.venueId===id||v.id===id)||layout.districts.find(v=>v.id===id);if(!p)return false;target.x=p.x;target.z=p.z;target.zoom=Math.max(target.zoom,3.7);if(p.key)choose(p);return true;};dispose.getMotionState=()=>({x:journeyPose?.x||view.x,y:journeyPose?.y||view.z,angle:journeyAngle,cameraX:view.x,cameraY:view.z,zoom:view.zoom,moving:!!trip&&progress()<1,driving:!!trip&&trip.mode!=='walk',routeProgress:progress(),routeNodeIds:route?.nodeIds||[],scene:trip?'transit':'public'});dispose.getAdDiagnostics=()=>({...model?.ads.diagnostics,...model?.parcels.diagnostics,visibleAdLabels:labels.filter(row=>row.place.adPlotId&&!row.button.hidden).length});dispose.getCameraState=()=>({x:view.x,y:view.z,zoom:view.zoom});dispose.updateResidents=()=>{};dispose.updateProfile=()=>{};return dispose;
}
