const IMAGE_LIMIT=512*1024;
export function safeSocialImage(value){return typeof value==='string' && /^data:image\/(png|jpeg|webp);base64,[A-Za-z\d+/=]+$/.test(value)?value:'';}
export function activeSocialStatuses(rows,now){return (Array.isArray(rows)?rows:[]).filter(row=>row.kind==='status' && Number(new Date(row.expiresAt || Number(new Date(row.createdAt))+86400000))>now);}
export function createAdvancingServerClock({getServerTime,monotonicNow=()=>performance.now(),localNow=()=>Date.now()}) {
  let anchorTime,anchorTick,serverSample;
  const now=()=>{
    const tick=monotonicNow(),value=getServerTime(),sample=typeof value==='number'?value:typeof value==='string'?Date.parse(value):NaN;
    if(Number.isFinite(sample) && sample!==serverSample){serverSample=sample;anchorTime=sample;anchorTick=tick;}
    else if(anchorTime===undefined){anchorTime=localNow();anchorTick=tick;}
    return anchorTime+Math.max(0,tick-anchorTick);
  };
  now();
  return now;
}
function imageFile(value){const safe=safeSocialImage(value);if(!safe)throw new Error('Capture or choose an image first.');const [header,encoded]=safe.split(','),bytes=Uint8Array.from(atob(encoded),c=>c.charCodeAt(0)),type=header.match(/data:([^;]+)/)[1];return new File([bytes],`abujalife-home.${type==='image/png'?'png':type==='image/webp'?'webp':'jpg'}`,{type});}
export function createPhoneSocial({getProfile,getNow,isPreview,api,navigate,render,toast,esc,icon,button,headline,portrait,dateTime,makeRequestKey}){
  let posts=[],statuses=[],cursor=null,loading=false,error='',selected=null,comments=[],commentCursor=null,statusCursor=null,commentsLoading=false,commentDraft='',text='',image='',kind='post',publishing=false,requestKey=null,owner=null,sequence=0,view='social',capturing=false,shareError='',shareCaption='',shareImage='',attachmentSequence=0,commentKey=null,commentPendingText='';
  const profile=()=>getProfile() || {};
  function reset(){owner=profile().id;posts=[];statuses=[];comments=[];cursor=null;commentCursor=null;statusCursor=null;commentDraft='';loading=false;commentsLoading=false;error='';selected=null;text='';image='';kind='post';publishing=false;requestKey=null;sequence++;attachmentSequence++;capturing=false;shareError='';shareCaption='';shareImage='';commentKey=null;commentPendingText='';}
  function capture(root){const compose=root.querySelector('#ph-socialText'),caption=root.querySelector('#ph-shareCaption'),comment=root.querySelector('#ph-socialComment');if(compose)text=compose.value;if(caption)shareCaption=caption.value;if(comment)commentDraft=comment.value;}
  const author=row=>row.resident || (row.userId===profile().id?profile():{id:row.userId,displayName:'Resident'});
  function postCard(row,detail=false){const who=author(row),mine=row.userId===profile().id,picture=safeSocialImage(row.imageDataUrl);return `<article class="ph-social-card" data-post-id="${esc(row.id)}"><header><button type="button" class="ph-social-author" data-ph-action="person" data-id="${esc(who.id || row.userId)}">${portrait(who)}<span><strong>${esc(who.displayName || who.username || 'Resident')}</strong><small>${dateTime(row.createdAt)}${row.kind==='status'?' · 24-hour status':''}</small></span></button>${mine?`<button type="button" class="ph-social-delete" data-ph-action="social-delete" data-id="${esc(row.id)}" aria-label="Delete your ${row.kind==='status'?'status':'post'}">${icon('close')}</button>`:''}</header>${picture?`<img class="ph-social-image" src="${esc(picture)}" alt="Image shared by ${esc(who.displayName || 'a resident')}" loading="lazy">`:''}<p class="ph-social-text">${esc(row.text || '')}</p><footer>${button(`${icon('heart')} ${Number(row.likes) || 0}`,'social-like',`data-id="${esc(row.id)}" aria-pressed="${!!row.likedByMe}"`,row.likedByMe?'ph-liked secondary':'subtle')}${detail?'':button(`${icon('messages')} ${Number(row.commentCount) || 0}`,'social-post',`data-id="${esc(row.id)}" aria-label="Open comments"`,'subtle')}${row.userId!==profile().id?button('Chat','dm',`data-id="${esc(row.userId)}"`,'subtle'):''}</footer></article>`;}
  function nav(){return `<nav class="ph-social-tabs" aria-label="Okrika sections">${button('Feed','app','data-app="social"',view==='social'?'':'subtle')}${button('Statuses','app','data-app="socialstatuses"',view==='socialstatuses'?'':'subtle')}${button('Chat','app','data-app="messages"','subtle')}${button('Shop','app','data-app="market"','subtle')}</nav>`;}
  const statusRows=()=>activeSocialStatuses(statuses,getNow());
  function statusStrip(){return `<div class="ph-social-status-strip"><button type="button" class="ph-status-bubble" data-ph-action="social-compose" data-kind="status"><span class="ph-status-ring">${portrait(profile())}<i>+</i></span><small>Your status</small></button>${statusRows().map(row=>`<button type="button" class="ph-status-bubble" data-ph-action="social-status" data-id="${esc(row.id)}"><span class="ph-status-ring">${portrait(author(row))}</span><small>${esc(author(row).displayName || 'Resident')}</small></button>`).join('')}</div>`;}
  function networkNote(){return isPreview()?'<p class="ph-social-local">Local preview · your posts stay on this device. Shared feeds and chats require the connected game.</p>':'';}
  function feedMarkup(){return `${headline('LIFE AROUND ABUJA','Okrika','Share your home, your day and your own view of the city.')}${nav()}${networkNote()}${statusStrip()}<div class="ph-social-tools">${button(`${icon('plus')} Share a moment`,'social-compose','data-kind="post"')}${button('Refresh','social-refresh','','subtle')}</div>${error?`<p class="ph-wallet-error" role="alert">${esc(error)}</p>`:''}${loading && !posts.length?'<p class="ph-quiet-note" role="status">Loading residents’ posts…</p>':''}<div class="ph-social-feed">${posts.map(row=>postCard(row)).join('') || (!loading?`<div class="ph-empty">${icon('friends')}<strong>Your city has room for the first story.</strong><p>Posts from real residents will appear here. Share a moment to begin.</p></div>`:'')}</div>${cursor?button(loading?'Loading…':'More moments','social-more',loading?'disabled':'','secondary wide'):''}`;}
  function statusesMarkup(){const rows=statusRows();return `${headline('HERE FOR A DAY','Statuses','Real moments disappear from the feed after 24 hours.')}${nav()}${networkNote()}${button(`${icon('plus')} Add a 24-hour status`,'social-compose','data-kind="status"','wide')}${error?`<p class="ph-wallet-error" role="alert">${esc(error)}</p>`:''}${rows.map(row=>postCard(row)).join('') || '<div class="ph-empty"><strong>No current statuses.</strong><p>Share something from your day. It will expire in 24 hours.</p></div>'}${statusCursor?button(loading?'Loading…':'More statuses','social-more-statuses',loading?'disabled':'','secondary wide'):''}`;}
  function composeMarkup(){return `${headline(kind==='status'?'A DAY IN YOUR LIFE':'YOUR CITY, YOUR STORY',kind==='status'?'New status':'Share a moment',kind==='status'?'Your status is visible for 24 hours.':'Your post appears in the resident feed.')}${networkNote()}<form class="ph-form ph-social-composer" data-ph-form="social-compose"><label class="ph-field"><span>Caption</span><textarea id="ph-socialText" name="socialText" rows="5" maxlength="4000" ${publishing?'disabled':''} placeholder="What’s happening in your Abuja?">${esc(text)}</textarea></label>${image?`<div class="ph-social-attachment"><img src="${esc(image)}" alt="Your selected image">${button('Remove image','social-remove-image','','subtle')}</div>`:''}<label class="ph-social-upload">${icon('profile')} Choose a photo<input type="file" name="socialPhoto" accept="image/png,image/jpeg,image/webp" ${publishing?'disabled':''}></label>${button('Capture my home','social-capture-home','','secondary wide')}${error?`<p class="ph-wallet-error" role="alert">${esc(error)}</p>`:''}<button type="submit" class="ph-button wide" ${publishing?'disabled':''}>${publishing?'Publishing…':kind==='status'?'Publish 24-hour status':'Publish to Okrika'}</button></form>`;}
  function detailMarkup(){const row=[...posts,...statusRows()].find(row=>row.id===selected);if(!row)return '<div class="ph-empty"><strong>This moment is no longer available.</strong></div>';return `${postCard(row,true)}${row.kind==='status'?`<p class="ph-quiet-note">Expires ${dateTime(row.expiresAt)}.</p>`:''}<h3 class="ph-section-label">Conversation</h3>${commentsLoading?'<p class="ph-quiet-note" role="status">Loading comments…</p>':''}${comments.map(comment=>`<article class="ph-social-comment">${portrait(author(comment))}<div><strong>${esc(author(comment).displayName || 'Resident')}</strong><p>${esc(comment.text)}</p><time>${dateTime(comment.createdAt)}</time></div></article>`).join('') || (!commentsLoading?'<p class="ph-quiet-note">Start the conversation.</p>':'')}${commentCursor?button('More comments','social-more-comments','','subtle wide'):''}${error?`<p class="ph-wallet-error" role="alert">${esc(error)}</p>`:''}<form class="ph-form" data-ph-form="social-comment"><label class="ph-field"><span>Your comment</span><textarea id="ph-socialComment" name="socialComment" rows="2" maxlength="1000" required placeholder="Say something kind…">${esc(commentDraft)}</textarea></label><button type="submit" class="ph-button wide" ${publishing?'disabled':''}>Send comment</button></form>`;}
  function shareMarkup(){return `${headline('YOUR HOME, YOUR STORY','Xshare','Capture your Abuja home and make the caption yours.')}${shareImage?`<img class="ph-share-preview" src="${esc(shareImage)}" alt="Screenshot of your actual AbujaLife home">`:'<div class="ph-share-empty">'+icon('property')+'<strong>A place worth sharing.</strong><p>Capture your home to preview a real screenshot here.</p></div>'}${button(capturing?'Capturing your home…':shareImage?'Capture again':'Capture my home','home-share-capture',capturing?'disabled':'','wide')}${shareImage?`<label class="ph-field"><span>Your Abuja caption</span><textarea id="ph-shareCaption" name="shareCaption" rows="4" maxlength="4000">${esc(shareCaption)}</textarea></label><div class="ph-share-actions">${button('Share image & caption','home-share-native','','wide')}${button('Download PNG','home-share-download','','secondary wide')}${button('Write on X ↗','home-share-x','','secondary wide')}${button('Post to Okrika','home-share-okrika','','subtle wide')}</div><p class="ph-quiet-note">X opens a draft with your text. Attach the downloaded image there before posting. You choose when and where to publish.</p>`:''}${shareError?`<p class="ph-wallet-error" role="alert">${esc(shareError)}</p>`:''}`;}
  function markup(next,selection){view=next;if((next==='socialpost' || next==='socialstatus') && selection && selected!==selection){selected=selection;comments=[];commentCursor=null;commentsLoading=false;commentDraft='';queueMicrotask(()=>void loadComments());}if(next==='socialcompose')return composeMarkup();if(next==='socialpost' || next==='socialstatus')return detailMarkup();if(next==='socialstatuses')return statusesMarkup();if(next==='xshare')return shareMarkup();return feedMarkup();}
  async function load({more=false}={}){if(loading)return;const mine=owner,seq=sequence;loading=true;error='';render();try{const results=await Promise.allSettled([api(`/api/social/feed${more && cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`),api('/api/social/statuses')]);if(owner!==mine || sequence!==seq)return;const [feed,status]=results;if(feed.status==='fulfilled'){const rows=Array.isArray(feed.value.posts)?feed.value.posts:[];posts=more?[...new Map([...posts,...rows].map(row=>[row.id,row])).values()]:rows;cursor=feed.value.nextCursor || null;}else error=feed.reason.message || 'The feed could not load.';if(status.status==='fulfilled'){statuses=Array.isArray(status.value.statuses)?status.value.statuses:[];statusCursor=status.value.nextCursor || null;}else error ||= status.reason.message || 'Statuses could not load.';}finally{if(owner===mine && sequence===seq){loading=false;render();}}}
  async function loadMoreStatuses(){if(loading || !statusCursor)return;const mine=owner,seq=sequence;loading=true;error='';render();try{const result=await api(`/api/social/statuses?cursor=${encodeURIComponent(statusCursor)}`);if(owner!==mine || sequence!==seq)return;statuses=[...new Map([...statuses,...(result.statuses || [])].map(row=>[row.id,row])).values()];statusCursor=result.nextCursor || null;}catch(e){if(owner===mine && sequence===seq)error=e.message;}finally{if(owner===mine && sequence===seq){loading=false;render();}}}
  async function openPost(id,status=false){selected=id;comments=[];commentsLoading=false;commentDraft='';commentCursor=null;error='';navigate(status?'socialstatus':'socialpost',id);await loadComments();}
  async function loadComments({more=false}={}){const id=selected,mine=owner,seq=sequence;if(!id || commentsLoading)return;commentsLoading=true;render();try{const result=await api(`/api/social/posts/${encodeURIComponent(id)}/comments${more && commentCursor?`?cursor=${encodeURIComponent(commentCursor)}`:''}`);if(owner!==mine || sequence!==seq || selected!==id)return;const rows=result.comments || [];comments=more?[...new Map([...comments,...rows].map(row=>[row.id,row])).values()]:rows;commentCursor=result.nextCursor || null;}catch(e){if(owner===mine && sequence===seq && selected===id)error=e.message;}finally{if(owner===mine && sequence===seq && selected===id){commentsLoading=false;render();}}}
  function replacePost(row){if(!row?.id)return;posts=posts.map(p=>p.id===row.id?row:p);statuses=statuses.map(p=>p.id===row.id?row:p);}
  async function publish(){if(publishing)return;if(!text.trim() && !image){error='Write a caption or choose a photo first.';render();return;}publishing=true;error='';requestKey ||= makeRequestKey();const mine=owner,seq=sequence,submitted={text:text.trim(),imageDataUrl:image || null,kind,idempotencyKey:requestKey};render();try{const result=await api('/api/social/posts',{method:'POST',body:submitted});if(owner!==mine || sequence!==seq)return;const input=document.querySelector('#ph-socialText');if(input)input.value='';text='';image='';requestKey=null;if(result.post?.kind==='status')statuses=[result.post,...statuses.filter(p=>p.id!==result.post.id)];else if(result.post)posts=[result.post,...posts.filter(p=>p.id!==result.post.id)];navigate(submitted.kind==='status'?'socialstatuses':'social');toast?.(submitted.kind==='status'?'Your status is live for 24 hours.':'Your moment is published.');}catch(e){if(owner===mine && sequence===seq)error=e.message || 'Your post could not publish. Your draft is saved.';}finally{if(owner===mine && sequence===seq){publishing=false;render();}}}
  async function captureHome(){if(capturing)return;capturing=true;shareError='';const mine=owner,seq=sequence;render();try{const module=await import('./home-share.js'),result=await module.captureHomeImage({profile:profile()});if(owner!==mine || sequence!==seq)return;shareImage=safeSocialImage(result);if(!shareImage)throw new Error('The home capture did not return an image.');if(!shareCaption)shareCaption=module.defaultHomeCaption(profile());}catch(e){if(owner===mine && sequence===seq)shareError=e.message || 'Your home could not be captured.';}finally{if(owner===mine && sequence===seq){capturing=false;render();}}}
  function download(){const file=imageFile(shareImage),url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function shareNative(){const file=imageFile(shareImage);if(!navigator.share || !navigator.canShare?.({files:[file]})){download();toast?.('Your image is downloaded. Use “Write on X” and attach it to your draft.');return;}try{await navigator.share({files:[file],title:'My AbujaLife home',text:shareCaption});}catch(e){if(e.name!=='AbortError')throw e;}}
  async function action(el){const action=el.dataset.phAction,id=el.dataset.id;if(!action?.startsWith('social-') && !action?.startsWith('home-share-'))return false;capture(document);try{if(action==='social-refresh')await load();if(action==='social-more')await load({more:true});if(action==='social-more-statuses')await loadMoreStatuses();if(action==='social-compose'){kind=el.dataset.kind==='status'?'status':'post';error='';navigate('socialcompose');}if(action==='social-post' || action==='social-status')await openPost(id,action==='social-status');if(action==='social-more-comments')await loadComments({more:true});if(action==='social-remove-image'){image='';requestKey=null;render();}if(action==='social-like' && !publishing){const mine=owner,seq=sequence;publishing=true;const result=await api(`/api/social/posts/${encodeURIComponent(id)}/like`,{method:'POST',body:{}});if(owner===mine && sequence===seq)replacePost(result.post);publishing=false;render();}if(action==='social-delete' && !publishing){const mine=owner,seq=sequence;publishing=true;await api(`/api/social/posts/${encodeURIComponent(id)}/delete`,{method:'POST',body:{}});if(owner===mine && sequence===seq){posts=posts.filter(row=>row.id!==id);statuses=statuses.filter(row=>row.id!==id);if(selected===id)navigate('social');}publishing=false;render();}if(action==='social-capture-home'){navigate('xshare');await captureHome();}if(action==='home-share-capture')await captureHome();if(action==='home-share-download')download();if(action==='home-share-native')await shareNative();if(action==='home-share-x'){const url=`https://x.com/intent/post?text=${encodeURIComponent(shareCaption)}`;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.click();}if(action==='home-share-okrika'){text=shareCaption;image=shareImage;kind='post';requestKey=null;navigate('socialcompose');}}catch(e){error=e.message || 'Please try again.';shareError=error;publishing=false;render();toast?.(error);}return true;}
  async function submit(form,values){if(form.dataset.phForm==='social-compose'){capture(document);await publish();return true;}if(form.dataset.phForm==='social-comment'){const content=String(values.socialComment || '').trim();if(!selected || !content || publishing)return true;publishing=true;error='';const mine=owner,seq=sequence,id=selected;commentKey=commentPendingText===content?commentKey || makeRequestKey():makeRequestKey();commentPendingText=content;try{const result=await api(`/api/social/posts/${encodeURIComponent(id)}/comments`,{method:'POST',body:{text:content,idempotencyKey:commentKey}});if(owner===mine && sequence===seq && selected===id){if(result.comment && !comments.some(c=>c.id===result.comment.id))comments.push(result.comment);const input=document.querySelector('#ph-socialComment');if(input)input.value='';commentDraft='';commentKey=null;commentPendingText='';const row=[...posts,...statuses].find(p=>p.id===id);if(row)replacePost({...row,commentCount:(Number(row.commentCount) || 0)+1});}}catch(e){if(owner===mine && sequence===seq)error=e.message;}finally{if(owner===mine && sequence===seq){publishing=false;render();}}return true;}return false;}
  async function change(el){if(el.name!=='socialPhoto')return false;const file=el.files?.[0],mine=owner,seq=++attachmentSequence;if(!file)return true;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size>10*1024*1024)throw new Error('Choose a PNG, JPEG or WebP photo smaller than 10 MB.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw new Error('Choose a photo smaller than 40 megapixels.');}const canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');context.fillStyle='#fafaf6';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let result=canvas.toDataURL('image/jpeg',.82);for(const quality of [.65,.45,.25]){if((result.length-result.indexOf(',')-1)*.75<=IMAGE_LIMIT)break;result=canvas.toDataURL('image/jpeg',quality);}if((result.length-result.indexOf(',')-1)*.75>IMAGE_LIMIT)throw new Error('This image is still too large. Choose a smaller image.');if(owner===mine && attachmentSequence===seq){image=result;requestKey=null;error='';render();}}catch(e){if(owner===mine && attachmentSequence===seq){error=e.message;render();}}return true;}
  function input(el){if(el.name==='socialText'){if(text!==el.value)requestKey=null;text=el.value;}if(el.name==='shareCaption')shareCaption=el.value;if(el.name==='socialComment')commentDraft=el.value;}
  return {markup,reset,capture,load,findResident(id){return [...posts,...statuses,...comments].find(row=>(row.resident?.id || row.userId)===id)?.resident || null;},action,submit,change,input,handleEvent(type){if(type.startsWith('social') && ['social','socialstatuses'].includes(view))void load();},expire(){if(['social','socialstatuses','socialstatus'].includes(view))render();}};
}
