import { DomainError } from './errors.js';
const json=(res,status,payload)=>{const body=JSON.stringify(payload);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','content-length':Buffer.byteLength(body)});res.end(body);};
const readJson=async req=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);if(!chunks.length)return{};const buf=Buffer.concat(chunks);if(buf.length>1_000_000)throw new DomainError('BODY_TOO_LARGE','Request body too large.',413);try{return JSON.parse(buf.toString('utf8'));}catch{throw new DomainError('INVALID_JSON','Request body must be valid JSON.');}};
export const createRouter=app=>async(req,res)=>{try{const url=new URL(req.url,'http://localhost');const path=url.pathname;let m;
if(req.method==='GET'&&path==='/health')return json(res,200,{ok:true,service:'abujalife-core',now:new Date().toISOString()});
if(req.method==='POST'&&path==='/v1/session/guest'){const body=await readJson(req);const player=app.store.createPlayer(body);app.ledger.post({playerId:player.id,amount:75000,reason:'starter_grant',idempotencyKey:`starter:${player.id}`});return json(res,201,{player,wallet:{balance:app.ledger.balance(player.id)},home:app.store.homeFor(player.id)});}
if(req.method==='GET'&&path==='/v1/world/bootstrap')return json(res,200,{districts:app.districts,landmarks:app.landmarks,roads:app.roads,events:app.events,npcArchetypes:app.npcArchetypes});
if(req.method==='GET'&&path==='/v1/world/districts')return json(res,200,{districts:app.districts});
if(req.method==='GET'&&path==='/v1/jobs')return json(res,200,{jobs:app.jobs});
if(req.method==='GET'&&path==='/v1/market/catalog')return json(res,200,{items:app.catalog});
if(req.method==='GET'&&path==='/v1/properties')return json(res,200,{properties:app.properties});
if(req.method==='GET'&&path==='/v1/vehicles')return json(res,200,{vehicles:app.vehicles});
if(req.method==='GET'&&path==='/v1/business-types')return json(res,200,{businesses:app.businesses});
if(req.method==='GET'&&path==='/v1/events')return json(res,200,{events:app.listActiveEvents({events:app.events,districtId:url.searchParams.get('district')??undefined})});
if(req.method==='GET'&&(m=path.match(/^\/v1\/players\/([^/]+)$/))){const id=m[1];return json(res,200,{player:app.store.getPlayer(id),wallet:{balance:app.ledger.balance(id)},inventory:app.store.inventoryFor(id),home:app.store.homeFor(id),vehicles:app.store.vehiclesFor(id),businesses:app.store.businessesFor(id),relationships:app.store.relationshipsFor(id)});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/life$/))){const body=await readJson(req);const p=app.store.getPlayer(m[1]);const needs=app.performLifeAction(p.needs,body.action);app.store.updatePlayer(m[1],{needs});return json(res,200,{needs});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/presence$/))){const body=await readJson(req);return json(res,200,{presence:app.heartbeatPresence({store:app.store,districts:app.districts,playerId:m[1],districtId:body.districtId,position:body.position})});}
if(req.method==='GET'&&(m=path.match(/^\/v1\/players\/([^/]+)\/nearby$/)))return json(res,200,{players:app.nearbyPlayers({store:app.store,playerId:m[1],maxDistance:Number(url.searchParams.get('radius')??100)})});
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/jobs\/([^/]+)\/complete$/))){const body=await readJson(req);return json(res,200,app.completeJobShift({store:app.store,ledger:app.ledger,jobs:app.jobs,playerId:m[1],jobId:m[2],score:body.score}));}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/market\/purchase$/))){const body=await readJson(req);return json(res,200,app.purchaseVirtualItem({store:app.store,ledger:app.ledger,catalog:app.catalog,playerId:m[1],itemId:body.itemId,quantity:body.quantity??1,requestId:body.requestId}));}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/wallet\/topup$/))){const body=await readJson(req);const entry=app.grantTopup({ledger:app.ledger,verifier:app.verifier,playerId:m[1],receipt:body.receipt});return json(res,200,{entry,balance:app.ledger.balance(m[1])});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/property$/))){const body=await readJson(req);return json(res,200,{home:app.acquireProperty({store:app.store,ledger:app.ledger,properties:app.properties,playerId:m[1],propertyId:body.propertyId,mode:body.mode,requestId:body.requestId})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/vehicles\/purchase$/))){const body=await readJson(req);return json(res,200,{vehicle:app.purchaseVehicle({store:app.store,ledger:app.ledger,vehicles:app.vehicles,playerId:m[1],vehicleId:body.vehicleId,requestId:body.requestId})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/vehicles\/([^/]+)\/drive$/))){const body=await readJson(req);return json(res,200,{vehicle:app.driveVehicle({store:app.store,playerId:m[1],vehicleId:m[2],distanceKm:body.distanceKm})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/businesses$/))){const body=await readJson(req);return json(res,201,{business:app.openBusiness({store:app.store,ledger:app.ledger,businesses:app.businesses,playerId:m[1],businessTypeId:body.businessTypeId,districtId:body.districtId,name:body.name,requestId:body.requestId})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/businesses\/([^/]+)\/cycle$/))){const body=await readJson(req);return json(res,200,{business:app.runBusinessCycle({store:app.store,ledger:app.ledger,businesses:app.businesses,playerId:m[1],businessId:m[2],quality:body.quality})});}
if(req.method==='POST'&&path==='/v1/friends/request'){const b=await readJson(req);return json(res,201,{relationship:app.requestFriend({store:app.store,from:b.from,to:b.to})});}
if(req.method==='POST'&&path==='/v1/friends/accept'){const b=await readJson(req);return json(res,200,{relationship:app.acceptFriend({store:app.store,playerId:b.playerId,otherId:b.otherId})});}
if(req.method==='POST'&&path==='/v1/players/block'){const b=await readJson(req);return json(res,200,{relationship:app.blockPlayer({store:app.store,playerId:b.playerId,otherId:b.otherId})});}
if(req.method==='POST'&&path==='/v1/messages'){const b=await readJson(req);return json(res,201,{message:app.sendMessage({store:app.store,from:b.from,to:b.to,text:b.text})});}
if(req.method==='GET'&&(m=path.match(/^\/v1\/players\/([^/]+)\/messages$/)))return json(res,200,{messages:app.store.messagesFor(m[1])});
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/events\/([^/]+)\/join$/)))return json(res,200,{join:app.joinEvent({store:app.store,events:app.events,playerId:m[1],eventId:m[2]})});
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/mayor\/nominate$/))){const b=await readJson(req);return json(res,201,{candidate:app.nominateMayor({store:app.store,playerId:m[1],manifesto:b.manifesto})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/mayor\/vote$/))){const b=await readJson(req);return json(res,200,{vote:app.voteMayor({store:app.store,voterId:m[1],candidateId:b.candidateId})});}
if(req.method==='POST'&&(m=path.match(/^\/v1\/players\/([^/]+)\/ads$/))){const b=await readJson(req);return json(res,201,{ad:app.bookCityAd({store:app.store,ledger:app.ledger,playerId:m[1],districtId:b.districtId,title:b.title,targetUrl:b.targetUrl,days:b.days,requestId:b.requestId})});}
if(req.method==='GET'&&(m=path.match(/^\/v1\/players\/([^/]+)\/okrika$/))){const p=app.store.getPlayer(m[1]);return json(res,200,app.okrikaHandoff({baseUrl:app.okrikaBaseUrl,playerId:p.id,districtId:p.districtId,query:url.searchParams.get('q')??''}));}
return json(res,404,{error:{code:'NOT_FOUND',message:'Route not found.'}});
}catch(error){const status=error.status??(error instanceof DomainError?error.status:500);return json(res,status,{error:{code:error.code??'INTERNAL_ERROR',message:status>=500?'Internal server error.':error.message}});}};
